import {
  AssessmentStage,
  MetricGauge,
  TelemetryItem,
  TenantHealthData,
  SecurityCoverageData,
  GroupLifecycleData,
  LicenseOptimizationData,
  CopilotReadinessData,
} from '../types';

export const initialAssessmentStages: AssessmentStage[] = [
  {
    id: 'stage-1',
    title: 'M365 Security Baseline',
    status: 'done',
    completedAt: '12 mins ago',
    description: 'Evaluated Conditional Access policies, MFA enrollment, and Admin role distribution.',
    documentData: {
      severity: 'red',
      omgHeroTitle: 'CRITICAL SECURITY BREACH SURFACE EXPOSED',
      omgHeroStat: '84 UNPROTECTED USERS & 11 PERMANENT GLOBAL ADMINS',
      omgHeroHighlight: 'OMG PANIC ALERT: 12% of user logins pass through unprotected endpoints with legacy authentication allowed! 11 accounts possess permanent Global Admin rights with zero PIM approval requirements, creating extreme lateral attack surface.',
      omgHeroBadge: 'CRITICAL RISK - IMMEDIATE REMEDIATION REQUIRED',
      executiveSummaryText: 'Comprehensive Security Audit conducted across Entra ID tenant policies. While core identity infrastructure is functional, significant policy gaps leave high-privilege access exposed to credential theft and password spraying.',
      annualWasteCost: '$42,000 Estimated Cyber Insurance Penalty',
      affectedItemsCount: 95,
      keyFindings: [
        {
          title: 'Unenforced Multi-Factor Authentication',
          riskLevel: 'CRITICAL',
          detail: '84 active user accounts lack Conditional Access policy enforcement for MFA.',
          impact: 'High probability of password spray compromise on remote logins.',
        },
        {
          title: 'Global Administrator Over-Provisioning',
          riskLevel: 'CRITICAL',
          detail: '11 accounts hold permanent Global Admin bindings without PIM activation controls.',
          impact: 'Single compromised account can result in full tenant takeover.',
        },
        {
          title: 'Legacy Auth Protocols Active',
          riskLevel: 'WARNING',
          detail: '14 service mailboxes accept POP3/IMAP connections bypassing MFA checks.',
          impact: 'Brute force attempts bypass conditional access rules.',
        },
      ],
      recommendedActions: [
        'Deploy Conditional Access Policy #CA-004 to enforce MFA for all non-service accounts.',
        'Convert 6 Global Admin permanent assignments to Eligible PIM roles with Manager approval.',
        'Block Legacy Authentication protocols tenant-wide in Entra ID Security Defaults.',
      ],
      powershellSnippet: '# Enforce CA Policy and PIM Role Conversion\nNew-MgPolicyConditionalAccessPolicy -DisplayName "Enforce CA-004 MFA" -State "Enabled"\nSet-MgUserAuthenticationMethod -UserId "admin@tenant.com" -MfaRequired $true',
    },
  },
  {
    id: 'stage-2',
    title: 'Governance & Sensitivity Labels',
    status: 'done',
    completedAt: '8 mins ago',
    description: 'Audited SharePoint guest access, Teams file sharing, and auto-labeling rules.',
    documentData: {
      severity: 'yellow',
      omgHeroTitle: 'WARNING: SENSITIVE FINANCIAL DATA ACCESSIBLE VIA COPILOT',
      omgHeroStat: '28 EXECUTIVE SITES PUBLICLY INDEXED TO INTERNAL STAFF',
      omgHeroHighlight: 'OMG CAUTION ALERT: 28 high-sensitivity SharePoint repositories (including Payroll, Executive HR, and M&A folders) grant default internal read access. Once Copilot is activated, any internal employee could discover executive compensation metrics!',
      omgHeroBadge: 'MODERATE RISK - COPILOT INDEXING EXPOSURE',
      executiveSummaryText: 'Data governance audit reveals over-sharing across internal Microsoft Teams and SharePoint sites. Sensitivity labels are applied inconsistently, permitting internal search crawlers to index confidential records.',
      annualWasteCost: '$28,000 Potential Regulatory Non-Compliance Exposure',
      affectedItemsCount: 28,
      keyFindings: [
        {
          title: 'SharePoint Finance Site Over-Shared',
          riskLevel: 'WARNING',
          detail: '"Everyone except external users" possesses default edit permissions on Financial Forecasts.',
          impact: 'Data leakage through Microsoft Graph search and Copilot summaries.',
        },
        {
          title: 'Unlabeled Sensitive Document Libraries',
          riskLevel: 'WARNING',
          detail: '64% of SharePoint document libraries have no auto-labeling rules configured.',
          impact: 'Unencrypted files can be exported outside tenant boundaries.',
        },
        {
          title: 'Stale Guest Sharing Links',
          riskLevel: 'INFO',
          detail: '182 external guest sharing links remain active beyond 90-day recommended lifecycle.',
          impact: 'Former vendor partners maintain passive file access.',
        },
      ],
      recommendedActions: [
        'Apply Restricted Access Control (RAC) on Executive & Finance SharePoint sites.',
        'Publish mandatory Auto-Labeling Policy for Confidential & Highly Confidential data.',
        'Run Automated Guest Access review and revoke links idle for >60 days.',
      ],
      powershellSnippet: '# Enable Restricted Access Control on Sensitive Sites\nSet-SPOSite -Identity "https://tenant.sharepoint.com/sites/Finance" -RestrictedAccessControl $true\nSet-[#Enable-SensitivityLabeling]',
    },
  },
  {
    id: 'stage-3',
    title: 'License Optimization Analytics',
    status: 'done',
    completedAt: '3 mins ago',
    description: 'Identified unassigned E5/E3 licenses, inactive mailboxes, and redundant add-ons.',
    documentData: {
      severity: 'red',
      omgHeroTitle: 'OMG ENTITLEMENT LEAKAGE: SEVERE ANNUAL BUDGET DRAIN CALCULATED',
      omgHeroStat: '$184,800 / YEAR LICENSE WASTE DETECTED',
      omgHeroHighlight: 'OMG PANIC ALERT: Your tenant is actively wasting $15,400 EVERY SINGLE MONTH on 142 unassigned M365 E5/E3 licenses and 44 unutilized Visio Plan 2 add-ons assigned to departed or inactive users! Reclaim this capital immediately.',
      omgHeroBadge: 'CRITICAL COST WASTE - $184,800/YR LEAKAGE',
      executiveSummaryText: 'Financial license utilization audit analyzing SKU entitlements against Microsoft Graph login activity over the last 90 days. Major capital recovery opportunities identified across top-tier subscription tiers.',
      annualWasteCost: '$184,800 / yr',
      monthlyWasteCost: '$15,400 / mo',
      affectedItemsCount: 186,
      keyFindings: [
        {
          title: 'Unassigned Microsoft 365 E5 Licenses',
          riskLevel: 'CRITICAL',
          detail: '98 unassigned E5 licenses idle in tenant pool ($55/user/mo = $64,680/year waste).',
          impact: 'Immediate cash flow leakage with zero business utility.',
        },
        {
          title: 'Licenses Allocated to Blocked Accounts',
          riskLevel: 'CRITICAL',
          detail: '44 disabled user accounts retain active E3/E5 subscription assignments ($19,008/year waste).',
          impact: 'Unnecessary subscription fee payments for departed employees.',
        },
        {
          title: 'Inactive Mailboxes Holding Subscriptions',
          riskLevel: 'WARNING',
          detail: '89 mailboxes with 0 logins in 120 days holding full Microsoft 365 licenses ($85,608/year).',
          impact: 'Mailboxes should be converted to free Shared Mailboxes.',
        },
      ],
      recommendedActions: [
        'Deprovision and reclaim 98 unassigned E5 licenses back into enterprise pool.',
        'Strip subscription SKUs from 44 blocked user accounts via automated PowerShell script.',
        'Convert 89 inactive mailboxes to free Shared Mailboxes and remove license bindings.',
      ],
      powershellSnippet: '# Reclaim Unassigned & Blocked User Licenses\n$blocked = Get-MgUser -Filter "accountEnabled eq false"\nforeach ($u in $blocked) { Set-MgUserLicense -UserId $u.Id -RemoveLicenses @("SPE_E5","SPE_E3") }\nWrite-Host "Successfully reclaimed $15,400/mo in license entitlements."',
    },
  },
  {
    id: 'stage-4',
    title: 'Copilot Readiness Analysis',
    status: 'in_progress',
    description: 'Analyzing Microsoft Graph data permissions, document classification, and user licensing.',
    documentData: {
      severity: 'green',
      omgHeroTitle: 'OPTIMAL READINESS: COPILOT ROLLOUT VERIFIED & APPROVED',
      omgHeroStat: '412 USERS QUALIFIED & SECURITY FENCED',
      omgHeroHighlight: 'OMG SUCCESS ALERT: Tenant infrastructure satisfies 94% of Microsoft Graph indexing requirements! Automated Data Loss Prevention (DLP) boundaries are confirmed and 412 target users are fully qualified for immediate Copilot deployment.',
      omgHeroBadge: 'LOW RISK - READY FOR DEPLOYMENT',
      executiveSummaryText: 'Readiness evaluation for Microsoft Copilot for Microsoft 365. All technical prerequisites, license alignment, and Graph semantic search permissions have passed automated verification.',
      annualWasteCost: '$0 Waste / Estimated +24% Productivity Surge',
      affectedItemsCount: 412,
      keyFindings: [
        {
          title: 'Microsoft Graph Indexing Ready',
          riskLevel: 'INFO',
          detail: 'Graph Search semantic index is 100% synced for 412 qualified users.',
          impact: 'Instant AI response times with zero indexing lag.',
        },
        {
          title: 'DLP Fencing Enforced',
          riskLevel: 'INFO',
          detail: 'DLP rules successfully guard PII across Exchange, OneDrive, and Teams.',
          impact: 'Guaranteed compliance during AI response generation.',
        },
        {
          title: 'Base Prerequisites Aligned',
          riskLevel: 'INFO',
          detail: 'Prerequisite E5/E3 base licenses matched to Copilot seat allocation.',
          impact: 'Seamless license activation without additional base SKU purchases.',
        },
      ],
      recommendedActions: [
        'Authorize Copilot seat deployment for 412 qualified enterprise users.',
        'Activate Copilot Usage & Adoption Telemetry dashboard in M365 Admin Center.',
        'Distribute Copilot Prompt Engineering playbook to executive leadership.',
      ],
      powershellSnippet: '# Assign Copilot Licenses to Qualified User Batch\n$users = Get-Content -Path ".\\CopilotReadyUsers.txt"\nforeach ($u in $users) { Set-MgUserLicense -UserId $u -AddLicenses @{SkuId="COPILOT_M365"} }\nWrite-Host "Assigned Copilot seats to 412 users."',
    },
  },
];

export const initialGauges: MetricGauge[] = [
  {
    id: 'sec-score',
    title: 'Security Score',
    score: 72,
    scanDelay: '0s',
    description: 'Overall tenant hardening posture compared to Microsoft Benchmark (68%).',
    benchmark: '+4% vs Industry Average',
    trend: 'up',
    trendValue: '+3.2% this month',
  },
  {
    id: 'compliance',
    title: 'Governance',
    score: 85,
    scanDelay: '0.5s',
    description: 'SharePoint guest access, Teams file sharing, and sensitivity labeling coverage.',
    benchmark: 'Governance & Labels Enforced',
    trend: 'up',
    trendValue: '+1.5% this month',
  },
  {
    id: 'identity-health',
    title: 'Compliance',
    score: 94,
    scanDelay: '1s',
    description: 'Data Loss Prevention (DLP) policies, HIPAA, and SOC2 compliance alignment.',
    benchmark: 'SOC2 & HIPAA Compliant',
    trend: 'neutral',
    trendValue: 'Stable',
  },
  {
    id: 'license-roi',
    title: 'Copilot Readiness',
    score: 68,
    scanDelay: '1.5s',
    description: 'License assignment, Microsoft Graph permissions, and document classification readiness.',
    benchmark: '412 Users Ready for Copilot',
    trend: 'up',
    trendValue: '+18 users ready this week',
  },
];

export const initialTelemetryItems: TelemetryItem[] = [
  {
    id: 'tel-1',
    type: 'security',
    title: 'Security Coverage Gap',
    description: 'Analysis of authentication telemetry shows 12% of accounts lacking MFA enforcement.',
    icon: 'security',
    iconColor: 'green',
    architectSays: 'Optimal MFA coverage verified across core executive departments.',
    architectStatus: 'success',
    affectedCount: 84,
    remediationStep: 'Require MFA for all standard user logins via Conditional Access Policy #CA-004.',
    powershellSnippet: 'Set-MgUserAuthenticationMethod -UserId "user@tenant.com" -MfaRequired $true',
  },
  {
    id: 'tel-2',
    type: 'groups',
    title: 'Stale Groups Detected',
    description: 'Over 45% of M365 Groups have seen no activity in the past 90 days.',
    icon: 'hub',
    iconColor: 'amber',
    architectSays: 'Consider implementing a group expiration policy to reduce sprawl and surface area.',
    architectStatus: 'warning',
    affectedCount: 168,
    remediationStep: 'Enable Microsoft 365 Group lifecycle policy with 180-day automatic renewal prompt.',
    powershellSnippet: 'Set-AzureADMSGroupLifecyclePolicy -GroupLifetimeInDays 180 -ManagedGroupTypes "All"',
  },
  {
    id: 'tel-3',
    type: 'licenses',
    title: 'Unassigned Licenses',
    description: 'Found 142 premium licenses currently unassigned or assigned to blocked users.',
    icon: 'payments',
    iconColor: 'red',
    architectSays: 'Critical entitlement leakage detected. $14,200 annual budget waste.',
    architectStatus: 'error',
    affectedCount: 142,
    remediationStep: 'Reclaim 98 unassigned E5 licenses and 44 Visio Plan 2 entitlements.',
    powershellSnippet: 'Set-MgUserLicense -UserId $blockedUser.Id -RemoveLicenses @("SPE_E5")',
  },
  {
    id: 'tel-4',
    type: 'copilot',
    title: 'Over-Shared SharePoint Sites',
    description: '28 high-sensitivity sites allow "Everyone except external users" edit permissions.',
    icon: 'auto_awesome',
    iconColor: 'blue',
    architectSays: 'Copilot indexing will surface sensitive financial files to unauthorized internal staff.',
    architectStatus: 'info',
    affectedCount: 28,
    remediationStep: 'Restricted Access Control (RAC) enforcement on sensitive sites.',
    powershellSnippet: 'Set-SPOSite -Identity "https://tenant.sharepoint.com/sites/Finance" -RestrictedAccessControl $true',
  },
  {
    id: 'tel-5',
    type: 'security',
    title: 'Legacy Auth Protocols Enabled',
    description: 'IMAP and POP3 basic auth connection attempts detected from 14 service mailboxes.',
    icon: 'key_off',
    iconColor: 'red',
    architectSays: 'Basic auth bypasses MFA. Immediate security threat level elevated.',
    architectStatus: 'error',
    affectedCount: 14,
    remediationStep: 'Block legacy authentication in Conditional Access and transition scripts to Graph API.',
    powershellSnippet: 'New-MgPolicyConditionalAccessPolicy -DisplayName "Block Legacy Auth"',
  },
  {
    id: 'tel-6',
    type: 'identity',
    title: 'Global Admin Over-provisioning',
    description: '11 accounts currently possess permanent Global Administrator role bindings.',
    icon: 'manage_accounts',
    iconColor: 'amber',
    architectSays: 'Exceeds Microsoft recommended ceiling of 5 Global Admins. Enforce PIM.',
    architectStatus: 'warning',
    affectedCount: 11,
    remediationStep: 'Migrate 6 admins to eligible PIM assignments with approval workflows.',
    powershellSnippet: 'Open Entra ID -> Privileged Identity Management -> Roles -> Assign Eligible',
  },
];

export const mockTenantHealth: TenantHealthData = {
  unifiedScore: 77,
  metrics: [
    { subject: 'Security', score: 72, fullMark: 100 },
    { subject: 'Governance', score: 85, fullMark: 100 },
    { subject: 'Compliance', score: 85, fullMark: 100 },
    { subject: 'Copilot Readiness', score: 65, fullMark: 100 },
  ],
};

export const mockSecurityCoverage: SecurityCoverageData = {
  mfaActivePercentage: 88,
  conditionalAccessEnforced: 92,
  legacyAuthBlocked: 96,
  totalUsers: 636,
};

export const mockGroupLifecycle: GroupLifecycleData = {
  activeCount: 198,
  staleCount: 168,
  orphanCount: 42,
  totalGroups: 408,
};

export const mockLicenseOptimization: LicenseOptimizationData = {
  potentialMonthlySavings: 4250,
  unassignedCount: 142,
  idleSKUs: 3,
  topSavingsProduct: 'Microsoft 365 E5 ($38/mo x 98)',
};

export const mockCopilotReadiness: CopilotReadinessData = {
  readyUsers: 412,
  needsActionUsers: 224,
  totalEligible: 636,
  topBlocker: 'Sensitivity label missing on 1,420 OneDrive documents',
};
