import { Persona, StoryBeat, WhiteboardNode, WhiteboardLink, DocumentPreviewData } from '../types';

export const INITIAL_PERSONAS: Persona[] = [
  {
    id: 'user',
    name: 'You (Enterprise Lead)',
    role: 'The Customer',
    title: 'VP of Technology & Business Transformation',
    department: 'Enterprise IT & Digital Workplace',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
    accentColor: 'border-emerald-400 text-emerald-400 shadow-emerald-500/50',
    glowHex: '#10b981',
    secondaryHex: '#047857',
    position: 'bottom-center',
    activeInBeats: [1, 2, 3, 4],
    idlePulseDuration: 3,
    bio: 'Executive lead guiding the organization through Microsoft 365 Copilot evaluation, ensuring productivity gains are balanced with rigorous data security, PCI compliance, and ROI.',
    priorities: [
      'Maximize Copilot adoption & time-to-value across 1,500 target seats',
      'Ensure zero data exposure risks across retail PCI & employee PII',
      'Align cross-functional leaders on governance and remediation budget',
    ],
    keyQuote: 'We want maximum AI productivity for our teams, but not at the expense of customer trust or compliance leaks.',
  },
  {
    id: 'shane',
    name: 'Shane',
    role: 'Lead Consultant',
    title: 'Principal M365 Copilot Architect',
    department: 'Microsoft Digital Practice',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    accentColor: 'border-cyan-400 text-cyan-300 shadow-cyan-500/50',
    glowHex: '#06b6d4',
    secondaryHex: '#0891b2',
    position: 'head',
    activeInBeats: [1, 2, 3, 4],
    idlePulseDuration: 2.5,
    bio: 'Senior Microsoft Partner Advisory lead with over 15 years of enterprise transformation experience, specializing in Microsoft 365 Copilot readiness, Microsoft Graph architecture, and executive alignment.',
    priorities: [
      'Facilitate structured Copilot assessment & remediation roadmap',
      'Help customer remediate oversharing & DLP gaps before license rollouts',
      'Deliver measurable 300%+ ROI across modern workplace workflows',
    ],
    keyQuote: 'Copilot is only as good as the data boundary it grounds on. Fix permissions first, and productivity skyrockets safely.',
  },
  {
    id: 'jane',
    name: 'Jane',
    role: 'Mission Specialist',
    title: 'Director of AI Strategy & Productivity',
    department: 'Business Transformation Office',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
    accentColor: 'border-purple-400 text-purple-300 shadow-purple-500/50',
    glowHex: '#a855f7',
    secondaryHex: '#7e22ce',
    position: 'left-top',
    activeInBeats: [1, 2, 3, 4],
    idlePulseDuration: 3.2,
    bio: 'Specialist in enterprise AI adoption metrics and change enablement, focusing on high-impact use cases in executive communications, sales enablement, and customer support.',
    priorities: [
      'Track hours saved per employee across pilot groups',
      'Build internal champion networks for Copilot prompts & workflows',
      'Establish governance guardrails for prompt engineering',
    ],
    keyQuote: 'Our goal is saving 5.2 hours per employee every week through smart prompt enablement.',
  },
  {
    id: 'marcus',
    name: 'Marcus',
    role: 'Engineering Lead',
    title: 'Chief Enterprise Systems Architect',
    department: 'Cloud Infrastructure & Engineering',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    accentColor: 'border-amber-400 text-amber-300 shadow-amber-500/50',
    glowHex: '#f59e0b',
    secondaryHex: '#b45309',
    position: 'left-bottom',
    activeInBeats: [1, 2, 3, 4],
    idlePulseDuration: 2.8,
    bio: 'Hands-on engineering lead managing tenant architecture, Microsoft Graph API connectors, SharePoint index hygiene, and identity provisioning.',
    priorities: [
      'Audit 8.4M indexed items across Exchange, Teams & OneDrive',
      'Automate permission remediation scripts across 312 EEEU sites',
      'Maintain sub-second Copilot query grounding performance',
    ],
    keyQuote: 'The tech is ready. We just need to clean up legacy access control lists so the Graph index stays clean.',
  },
  {
    id: 'priya',
    name: 'Priya',
    role: 'Operations Lead',
    title: 'Head of Global IT Service Operations',
    department: 'IT Operations & Service Desk',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    accentColor: 'border-blue-400 text-blue-300 shadow-blue-500/50',
    glowHex: '#3b82f6',
    secondaryHex: '#1d4ed8',
    position: 'right-top',
    activeInBeats: [1, 2, 3, 4],
    idlePulseDuration: 3.5,
    bio: 'Operations director responsible for IT service desk ticketing, retail store system integration, and end-user support readiness during software deployments.',
    priorities: [
      'Prevent support reps from accidentally emailing credit card numbers or PII',
      'Train support desk agents on safe Copilot prompt usage',
      'Minimize IT support ticket surges during pilot license rollouts',
    ],
    keyQuote: 'Our support reps handle thousands of customer queries daily. We need automated DLP safeguards to prevent accidental data leaks.',
  },
  {
    id: 'kirk',
    name: 'Kirk',
    role: 'Security Expert',
    title: 'Chief Information Security Officer (CISO)',
    department: 'Information Security & Data Protection',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=256&q=80',
    accentColor: 'border-rose-500 text-rose-300 shadow-rose-600/60',
    glowHex: '#f43f5e',
    secondaryHex: '#be123c',
    position: 'right-center',
    isConditional: true,
    activeInBeats: [2, 3, 4],
    idlePulseDuration: 1.8,
    bio: 'CISO leading enterprise threat protection and Microsoft Purview governance. Expert in sensitivity labeling, tenant isolation, and audit readiness.',
    priorities: [
      'Remediate 312 SharePoint sites overshared with "Everyone Except External Users"',
      'Enforce mandatory Microsoft Purview Sensitivity Labels across financial & M&A assets',
      'Verify strict boundary isolation before authorizing Copilot deployment',
    ],
    keyQuote: 'EEEU permissions mean anyone can prompt Copilot to summarize executive salary files. We must lock down site ACLs immediately.',
  },
  {
    id: 'beth',
    name: 'Beth',
    role: 'Legal & Risk Advisor',
    title: 'General Counsel & Corporate Risk Officer',
    department: 'Legal, Compliance & Regulatory Risk',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=256&q=80',
    accentColor: 'border-red-400 text-red-300 shadow-red-500/60',
    glowHex: '#ef4444',
    secondaryHex: '#991b1b',
    position: 'right-bottom',
    isConditional: true,
    activeInBeats: [2, 3, 4],
    idlePulseDuration: 2.1,
    bio: 'Corporate counsel specializing in PCI-DSS, GDPR, HR data privacy laws, and regulatory liability in retail enterprise environments.',
    priorities: [
      'Protect HR Social Security Numbers and employee salary records from AI indexing',
      'Mitigate PCI-DSS financial liability regarding retail credit card data exposure',
      'Ensure AI output meets strict regulatory and legal discovery standards',
    ],
    keyQuote: 'As a retail enterprise with no DLP, an accidental email containing credit card numbers or SSNs could trigger massive regulatory fines.',
  },
];

export const INITIAL_WHITEBOARD_NODES: WhiteboardNode[] = [
  {
    id: 'dlp',
    label: 'Purview DLP Gap',
    category: 'security',
    status: 'danger',
    x: 18,
    y: 28,
    value: '42% Unenforced',
    metricLabel: 'Sensitivity Labels Missing',
    details: '1,240 SharePoint sites contain confidential financial docs without DLP restriction rules.',
    plainSummary: 'Data Loss Prevention (DLP) policies are currently disabled or unconfigured across 42% of your Microsoft 365 environment. This means files containing sensitive customer credit card numbers (PCI) and employee Social Security numbers (SSN) do not have security tags or protection rules attached.',
    businessImpact: 'If an employee prompts Copilot or emails a document containing customer credit card numbers or employee SSNs, there are no DLP guardrails to block or encrypt the message. This exposes the company to severe regulatory fines and PCI compliance violations.',
    recommendedActions: [
      'Enable Microsoft Purview auto-labeling rules for credit cards, SSNs, and executive financial reports.',
      'Configure DLP policy rules to block unencrypted external sharing of PCI data.',
      'Deploy Purview Information Protection to automatically encrypt classified files.',
    ],
    suggestedQuestion: 'How can we quickly deploy Microsoft Purview DLP policies to protect PCI credit card data and employee PII?',
  },
  {
    id: 'oversharing',
    label: 'SharePoint Oversharing',
    category: 'security',
    status: 'danger',
    x: 48,
    y: 22,
    value: '1,240 Sites Exposed',
    metricLabel: 'Wide "Everyone" Permissions',
    details: 'Broad search permissions allow Copilot to summarize sensitive salary and strategic audit files.',
    plainSummary: '312 core SharePoint site collections currently grant broad read permissions to the "Everyone Except External Users" (EEEU) group. Copilot respects user permissions—meaning if any employee asks Copilot "What are executive salaries?" or "Show me M&A plans", Copilot will locate and summarize those files because everyone technically has access.',
    businessImpact: 'Internal oversharing is the #1 risk when deploying Microsoft 365 Copilot. Any staff member can accidentally discover confidential compensation data, unannounced reorganization plans, or internal performance reviews through simple conversational search.',
    recommendedActions: [
      'Run an automated permission scan to identify all sites using "Everyone Except External Users" (EEEU).',
      'Replace broad EEEU access groups with explicit role-based department permissions.',
      'Apply Restricted SharePoint Search (RSS) to exclude unindexed legacy repositories during Copilot pilot testing.',
    ],
    suggestedQuestion: 'What steps are needed to revoke EEEU permissions across our 312 overshared SharePoint sites?',
  },
  {
    id: 'sprawl',
    label: 'Teams Channel Sprawl',
    category: 'governance',
    status: 'warning',
    x: 78,
    y: 32,
    value: '312 Unmanaged Channels',
    metricLabel: 'Orphaned Guests',
    details: 'Unmonitored external guest access in core project teams could leak AI-synthesized summaries.',
    plainSummary: 'Over 300 Microsoft Teams channels have been created without central lifecycle management, and 142 external guest accounts remain active long after their projects ended. Copilot indexes chat history and shared files across all accessible channels.',
    businessImpact: 'Active external guests or contractors in unmonitored channels could gain access to Copilot-generated summaries containing confidential internal roadmap discussions.',
    recommendedActions: [
      'Enforce automated Teams channel expiration & guest access recertification reviews every 90 days.',
      'Require Conditional Access and Multi-Factor Authentication (MFA) step-up for external guest users.',
      'Archive orphaned project teams and remove inactive guest memberships.',
    ],
    suggestedQuestion: 'How do we remediate guest access and channel sprawl before launching Copilot?',
  },
  {
    id: 'graph',
    label: 'Microsoft Graph Index',
    category: 'copilot',
    status: 'active',
    x: 32,
    y: 68,
    value: '8.4M Documents',
    metricLabel: 'Indexed Semantic Fabric',
    details: 'M365 Copilot grounding engine ready across Exchange, OneDrive, and Teams data.',
    plainSummary: 'The Microsoft Graph semantic index is the underlying search fabric that powers Copilot. It continuously indexes 8.4 million documents, emails, Teams chats, and calendar events across your tenant to provide instant, context-aware AI answers.',
    businessImpact: 'The Graph index is fully operational and healthy. Because Copilot draws answers directly from this index, cleaning up permission boundaries immediately makes Copilot responses safer and more accurate.',
    recommendedActions: [
      'Verify Graph connector health and indexing status across SharePoint and OneDrive.',
      'Monitor semantic search latency to ensure sub-second response times for Copilot users.',
      'Maintain clean directory metadata for optimal organizational context grounding.',
    ],
    suggestedQuestion: 'Can you explain how Microsoft Graph grounds Copilot responses in our enterprise data?',
  },
  {
    id: 'readiness',
    label: 'Copilot License Readiness',
    category: 'adoption',
    status: 'warning',
    x: 68,
    y: 72,
    value: '42% Target',
    metricLabel: 'Technical Eligibility',
    details: 'Requires DLP remediation & Sensitivity Label baseline to proceed to pilot deployment.',
    plainSummary: 'Currently, 250 out of 1,500 target user seats are technically qualified for Copilot deployment. Complete readiness requires completing the Purview DLP policy setup and SharePoint oversharing cleanup.',
    businessImpact: 'Deploying Copilot to all 1,500 target seats immediately after remediation will unlock an estimated 5.2 hours saved per employee per week, yielding a projected 340% 12-month ROI.',
    recommendedActions: [
      'Complete Phase 1 security remediation (DLP + EEEU site cleanup).',
      'Deploy 250 pilot licenses to executive champion groups for immediate workflow testing.',
      'Scale adoption to the full 1,500 seat baseline with automated training and prompt playbooks.',
    ],
    suggestedQuestion: 'What is our timeline to get from 42% readiness to 100% full deployment?',
  },
];

export const INITIAL_WHITEBOARD_LINKS: WhiteboardLink[] = [
  { fromId: 'dlp', toId: 'oversharing', status: 'risk', label: 'Data Exposure' },
  { fromId: 'oversharing', toId: 'readiness', status: 'risk', label: '$ Financial & Regulatory Risk' },
  { fromId: 'sprawl', toId: 'dlp', status: 'risk', label: 'Guest Access Deficit' },
  { fromId: 'graph', toId: 'readiness', status: 'active', label: 'Semantic Grounding' },
];

export const STORY_BEATS: StoryBeat[] = [
  {
    id: 1,
    title: '1. Strategy Briefing & Persona Introductions',
    shortTitle: 'Introductions',
    subtitle: 'Shane sets the Copilot assessment framework while project leads align on productivity targets.',
    atmosphereTheme: 'calm',
    ambientGlowColor: 'radial-gradient(ellipse at 50% 30%, rgba(30, 27, 75, 0.8) 0%, rgba(15, 23, 42, 0.95) 70%)',
    activePersonaIds: ['user', 'shane', 'jane', 'marcus', 'priya'],
    speakerHighlightId: 'shane',
    readinessScore: 42,
    riskLevel: 'Medium',
    dlpCoverage: 35,
    oversharingSites: 1240,
    copilotLicensesReady: 250,
    summary: 'The briefing room opens. Shane introduces the Microsoft 365 Copilot Readiness framework.',
    messages: [
      {
        id: 'm1-1',
        speakerId: 'shane',
        speakerName: 'Shane — Lead Consultant',
        text: 'Welcome to your Microsoft 365 Copilot Readiness Briefing! Today we evaluate your enterprise data grounding, governance posture, and adoption readiness.',
        timestamp: '10:00 AM',
        beatIndex: 1,
        anchors: [
          {
            id: 'a-value',
            type: 'value',
            label: 'Copilot Value Matrix',
            iconName: 'Zap',
            description: 'Simulate productivity gains across M365 apps.',
          },
        ],
      },
      {
        id: 'm1-2',
        speakerId: 'jane',
        speakerName: 'Jane — Mission Specialist',
        text: 'Our business units are eager to launch Copilot across 1,500 priority seats! Email synthesis and document generation are estimated to save 5+ hours per employee weekly.',
        timestamp: '10:01 AM',
        beatIndex: 1,
        anchors: [
          {
            id: 'a-sprawl',
            type: 'sprawl',
            label: 'Teams Sprawl Analysis',
            iconName: 'Users',
            description: 'Inspect 312 unmanaged Teams channels.',
          },
        ],
      },
      {
        id: 'm1-3',
        speakerId: 'marcus',
        speakerName: 'Marcus — Engineering Lead',
        text: 'Microsoft Graph indexing is active across 8.4M enterprise items. Our tenant speed looks solid, but we must verify permissions before opening semantic search.',
        timestamp: '10:02 AM',
        beatIndex: 1,
      },
      {
        id: 'm1-4',
        speakerId: 'priya',
        speakerName: 'Priya — Operations Lead',
        text: 'Operational workflows depend heavily on shared SharePoint libraries. We need to ensure Copilot honors our exact access control lists.',
        timestamp: '10:02 AM',
        beatIndex: 1,
      },
    ],
  },
  {
    id: 2,
    title: '2. The Security Twist (Kirk & Beth Interject)',
    shortTitle: 'Security Twist',
    subtitle: 'Kirk & Beth enter with urgent security metrics: oversharing and un-enforced Purview DLP policies detected!',
    atmosphereTheme: 'twist',
    ambientGlowColor: 'radial-gradient(ellipse at 50% 30%, rgba(88, 28, 135, 0.85) 0%, rgba(15, 23, 42, 0.98) 75%)',
    activePersonaIds: ['user', 'shane', 'jane', 'marcus', 'priya', 'kirk', 'beth'],
    speakerHighlightId: 'kirk',
    readinessScore: 38,
    riskLevel: 'Critical',
    dlpCoverage: 28,
    oversharingSites: 1240,
    copilotLicensesReady: 100,
    summary: 'Kirk (Security) and Beth (Legal) interrupt with critical oversharing audit findings across 1,240 sites.',
    messages: [
      {
        id: 'm2-1',
        speakerId: 'kirk',
        speakerName: 'Kirk — Security Expert',
        text: 'HOLD ON! Our automated Purview security scan just flagged 1,240 SharePoint sites with "Everyone except external users" broad read permissions!',
        timestamp: '10:03 AM',
        beatIndex: 2,
        anchors: [
          {
            id: 'a-oversharing',
            type: 'oversharing',
            label: 'Oversharing Exposure Breakdown',
            iconName: 'AlertTriangle',
            description: 'Inspect 1,240 overshared SharePoint locations.',
          },
          {
            id: 'a-dlp',
            type: 'dlp',
            label: 'DLP Gap Details',
            iconName: 'ShieldAlert',
            description: 'View missing Sensitivity Labels and financial risk.',
          },
        ],
        docId: 'doc-security-audit',
      },
      {
        id: 'm2-2',
        speakerId: 'beth',
        speakerName: 'Beth — Legal & Risk Advisor',
        text: 'If Copilot is deployed today, any employee can ask "What are the unannounced executive compensation packages?" and Copilot will happily summarize the unencrypted documents!',
        timestamp: '10:04 AM',
        beatIndex: 2,
        docId: 'doc-exposure-report',
      },
      {
        id: 'm2-3',
        speakerId: 'shane',
        speakerName: 'Shane — Lead Consultant',
        text: 'This is the classic Copilot Readiness Paradox: Copilot respects permissions perfectly — but if your permissions are overshared, Copilot accelerates data exposure!',
        timestamp: '10:05 AM',
        beatIndex: 2,
      },
    ],
    handOffCards: [
      {
        id: 'card-eeeu',
        title: 'SharePoint EEEU Oversharing Risk',
        question: 'What do you think about 312 SharePoint sites shared with Everyone Except External Users (EEEU)?',
        scenarioContext: 'Because Copilot respects user ACLs, any document accessible by "Everyone Except External Users" becomes instantly searchable and summarizable across the enterprise.',
        issuedBy: 'kirk',
        status: 'pending',
        suggestedPrompts: [
          {
            id: 'p1-1',
            label: 'Ask Room: What happens to Copilot search results with 312 sites open to EEEU?',
            messageText: 'What happens to our Copilot search results if 312 SharePoint sites remain shared with Everyone Except External Users?',
          },
          {
            id: 'p1-2',
            label: 'Ask Room: How do we restrict EEEU access and enforce Purview Sensitivity Labels?',
            messageText: 'How do we restrict EEEU permissions across those 312 sites and enforce Purview Sensitivity Labels automatically?',
          },
          {
            id: 'p1-3',
            label: 'Ask Room: Kirk, which executive compensation files are exposed right now?',
            messageText: 'Kirk, can you identify which specific executive compensation or HR folders are exposed under EEEU permissions today?',
          },
        ],
        impact: {
          readinessDelta: 22,
          description: 'Restricts Copilot indexing to verified sensitivity-labeled documents only.',
        },
      },
      {
        id: 'card-retail-dlp',
        title: 'Retail DLP Deficit: Support PCI & HR PII Leaks',
        question: 'We are a retail company with no DLP — what if a support rep emails a credit card number, or HR sends off a SSN on accident?',
        scenarioContext: 'Without Purview Data Loss Prevention (DLP) policies, Copilot can index unencrypted credit card numbers, customer PII, and employee SSNs in open chat prompts.',
        issuedBy: 'beth',
        status: 'pending',
        suggestedPrompts: [
          {
            id: 'p2-1',
            label: 'Ask Room: How can Purview DLP prevent support reps from emailing credit cards or HR from sending SSNs?',
            messageText: 'We are a retail company with no DLP. How can Purview DLP prevent a support rep from emailing a credit card number or HR from sending an SSN by accident?',
          },
          {
            id: 'p2-2',
            label: 'Ask Room: Beth, what are our PCI-DSS and GDPR legal liabilities if Copilot indexes unencrypted PII?',
            messageText: 'Beth, what are our regulatory PCI-DSS and GDPR legal liabilities if Copilot indexes unencrypted customer credit cards or employee SSNs?',
          },
          {
            id: 'p2-3',
            label: 'Ask Room: Let\'s enforce mandatory Purview Auto-Labeling for PCI & PII data now.',
            messageText: 'Let\'s enforce mandatory Purview Auto-Labeling for PCI credit card numbers and HR SSN data across our entire tenant right away.',
          },
        ],
        impact: {
          readinessDelta: 18,
          description: 'Prevents accidental PII & credit card data exposure in Copilot grounding.',
        },
      },
    ],
  },
  {
    id: 3,
    title: '3. Interactive Remediation & Hand-Off Cards',
    shortTitle: 'Remediation',
    subtitle: 'The customer interacts directly with floating hand-off cards to apply security controls and re-link whiteboard nodes.',
    atmosphereTheme: 'remediation',
    ambientGlowColor: 'radial-gradient(ellipse at 50% 30%, rgba(15, 118, 110, 0.75) 0%, rgba(15, 23, 42, 0.98) 75%)',
    activePersonaIds: ['user', 'shane', 'jane', 'marcus', 'priya', 'kirk', 'beth'],
    speakerHighlightId: 'user',
    readinessScore: 78,
    riskLevel: 'Medium',
    dlpCoverage: 88,
    oversharingSites: 120,
    copilotLicensesReady: 1200,
    summary: 'The human user resolves DLP policies and restricts oversharing using floating hand-off cards.',
    messages: [
      {
        id: 'm3-1',
        speakerId: 'shane',
        speakerName: 'Shane — Lead Consultant',
        text: 'Outstanding decision! We are handing you the Governance Remediation controls. Adjust the DLP slider and apply the Conditional Access policies on the floating cards.',
        timestamp: '10:06 AM',
        beatIndex: 3,
      },
      {
        id: 'm3-2',
        speakerId: 'kirk',
        speakerName: 'Kirk — Security Expert',
        text: 'Purview auto-labeling rules are compiling! Sensitivity labels now shield corporate M&A, HR, and payroll folders from broad Copilot query results.',
        timestamp: '10:07 AM',
        beatIndex: 3,
      },
      {
        id: 'm3-3',
        speakerId: 'marcus',
        speakerName: 'Marcus — Engineering Lead',
        text: 'The Graph index has re-aligned! Restricted ACLs updated across 1,240 sites in under 3 minutes.',
        timestamp: '10:08 AM',
        beatIndex: 3,
      },
    ],
    handOffCards: [
      {
        id: 'card-3',
        title: 'Apply Conditional Access & MFA Policy for Copilot',
        subtitle: 'Require Device Compliance & Step-Up Auth for mobile Copilot access.',
        issuedBy: 'kirk',
        type: 'button',
        status: 'pending',
        impact: {
          readinessDelta: 16,
          riskDelta: 'low',
          nodeResolved: 'sprawl',
          description: 'Secures guest access endpoints across 312 Teams channels.',
        },
      },
    ],
  },
  {
    id: 4,
    title: '4. Executive Briefing Resolution & Roadmap',
    shortTitle: 'Resolution',
    subtitle: 'Shane presents the final Copilot Pilot Roadmap with 94% Readiness Score and full compliance green light!',
    atmosphereTheme: 'resolution',
    ambientGlowColor: 'radial-gradient(ellipse at 50% 30%, rgba(30, 58, 138, 0.8) 0%, rgba(15, 23, 42, 0.98) 75%)',
    activePersonaIds: ['user', 'shane', 'jane', 'marcus', 'priya', 'kirk', 'beth'],
    speakerHighlightId: 'shane',
    readinessScore: 94,
    riskLevel: 'Low',
    dlpCoverage: 98,
    oversharingSites: 12,
    copilotLicensesReady: 1500,
    summary: 'The assessment reaches 94% Copilot Readiness. Shane delivers the official rollout deployment roadmap.',
    messages: [
      {
        id: 'm4-1',
        speakerId: 'shane',
        speakerName: 'Shane — Lead Consultant',
        text: 'Congratulations! Your Copilot Readiness Score has surged to 94%! All security vectors are fortified, Purview DLP is active, and license allocation is approved for 1,500 seats.',
        timestamp: '10:09 AM',
        beatIndex: 4,
        docId: 'doc-copilot-spec',
      },
      {
        id: 'm4-2',
        speakerId: 'jane',
        speakerName: 'Jane — Mission Specialist',
        text: 'This is a massive win! Our business units can now launch Copilot securely with maximum productivity gains and zero oversharing risk.',
        timestamp: '10:10 AM',
        beatIndex: 4,
      },
      {
        id: 'm4-3',
        speakerId: 'beth',
        speakerName: 'Beth — Legal & Risk Advisor',
        text: 'Legal gives full approval for Phase 1 Copilot rollout. Audit trails and compliance boundary checks are green across the tenant.',
        timestamp: '10:10 AM',
        beatIndex: 4,
      },
    ],
  },
];

export const MOCK_DOCUMENTS: Record<string, DocumentPreviewData> = {
  'doc-security-audit': {
    id: 'doc-security-audit',
    title: 'M365 Purview Security Audit & Sensitivity Label Gap Analysis',
    type: 'security_audit',
    classification: 'CONFIDENTIAL',
    author: 'Kirk — Cyber Security Governance',
    date: '2026-07-31',
    summary: 'Automated tenant-wide scan of 8.4M Graph objects reveals un-enforced sensitivity labels across 1,240 financial and executive SharePoint site collections.',
    findings: [
      {
        severity: 'High',
        topic: 'Broad "Everyone" ACL Exposure',
        detail: '1,240 SharePoint libraries inherit "Everyone except external users" read permissions.',
        status: 'Critical Risk for Copilot Index',
      },
      {
        severity: 'High',
        topic: 'Missing Auto-Labeling Rules',
        detail: 'Financial spreadsheets lack Purview "Confidential - Financial" encryption labels.',
        status: 'Action Required',
      },
      {
        severity: 'Medium',
        topic: 'Orphaned Guest Access in Teams',
        detail: '312 legacy channels hold active guest accounts with broad file access.',
        status: 'Review In Progress',
      },
    ],
    stats: {
      'Total Sites Scanned': '4,850',
      'Unprotected Sites': '1,240',
      'Exposed Financial Files': '18,420',
      'Purview Policy Status': '35% Enforced',
    },
  },
  'doc-exposure-report': {
    id: 'doc-exposure-report',
    title: 'Copilot Semantic Search Data Exposure Risk Matrix',
    type: 'data_exposure',
    classification: 'RESTRICTED',
    author: 'Beth — Corporate Legal & Regulatory Risk',
    date: '2026-07-31',
    summary: 'Simulation of Copilot natural language queries demonstrating unauthorized data synthesis across un-segmented internal repositories.',
    findings: [
      {
        severity: 'High',
        topic: 'M&A Strategy Document Synthesis',
        detail: 'Query "Summarize current acquisition targets" returned un-redacted negotiation briefs.',
        status: 'High Liability',
      },
      {
        severity: 'High',
        topic: 'Payroll & Compensation Queries',
        detail: 'Query "Show executive bonus structure for Q3" retrieved executive comp spreadsheets.',
        status: 'High Privacy Risk',
      },
    ],
    stats: {
      'Potential Financial Exposure': '$14.2M Risk',
      'Regulatory Standards Impacted': 'GDPR, SEC, HIPAA',
      'Calculated Blast Radius': 'Entire Enterprise (6,200 Users)',
    },
  },
  'doc-copilot-spec': {
    id: 'doc-copilot-spec',
    title: 'Microsoft 365 Copilot Enterprise Deployment Architecture & Roadmap',
    type: 'copilot_spec',
    classification: 'INTERNAL',
    author: 'Shane — Lead AI Readiness Consultant',
    date: '2026-07-31',
    summary: 'Approved enterprise rollout specification for 1,500 Copilot licenses across Phase 1 business units with active Purview guardrails.',
    findings: [
      {
        severity: 'Low',
        topic: 'Phase 1 License Distribution',
        detail: '1,500 seats assigned to Executive, Sales, and R&D champions.',
        status: 'Approved',
      },
      {
        severity: 'Low',
        topic: 'Governance Boundary Active',
        detail: 'Purview auto-labeling and restricted search boundary fully functional.',
        status: 'Verified Green',
      },
    ],
    stats: {
      'Readiness Score': '94% Excellent',
      'Target Pilot Seats': '1,500 Users',
      'Estimated Weekly Hours Saved': '7,500 Hours / Wk',
      'Projected ROI': '340% 12-Mo Return',
    },
  },
};
