import React, { useState } from 'react';
import {
  ShieldAlert,
  Zap,
  ShieldCheck,
  AlertTriangle,
  Sparkles,
  X,
  ChevronRight,
  BookOpen,
  DollarSign,
  TrendingUp,
  Clock,
  CheckCircle2,
  Lock,
  ArrowRight,
  FileText,
  SlidersHorizontal,
  Code,
  Shield,
  Layers,
  Send,
  Eye,
  Check,
  UserCheck,
  CheckSquare,
  ListTodo,
  MessageSquare,
  Building2,
  Award,
  Target,
  Plus
} from 'lucide-react';
import { cn } from '../../lib/utils';
import { RbdAcceptanceAndRuleLinker } from './RbdAcceptanceAndRuleLinker';

export interface AlertWizardPayload {
  id: string;
  code: string;
  title: string;
  tenantId: string;
  tenantName: string;
  category: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  targetResource: string;
  description: string;
  detectedAt?: string;
  riskNotificationType?: string;
  matchedSopCode?: string;
  isOutOfScope?: boolean;
  outOfScopeReason?: string;
  upgradeEstimate?: string;
  rootCauseAnalysis?: string;
  currentConfigJson?: Record<string, any>;
  targetConfigJson?: Record<string, any>;
  graphEndpoint?: string;

  // Operator Task Specific Fields
  taskSource?: 'alert' | 'sop' | 'scheduled' | 'psa';
  executionType?: 'automated' | 'manual' | 'gated';
  assignedTo?: string | null;
  psaTicketId?: string;
  checklists?: { id: string; label: string; done: boolean }[];
  activityTrail?: { id: string; timestamp: string; actor: string; note: string }[];
  remainingSeconds?: number;

  // SLA Dashboard Specific Fields
  slaTier?: string;
  monthlyAttainment?: number;
  targetAttainment?: number;
  mttdMinutes?: number;
  mttrMinutes?: number;
  activeBreaches?: number;
  autoHealedIncidents?: number;
  status?: 'healthy' | 'at_risk' | 'breached';
  primaryDomain?: string;
}

export interface AlertResolutionWizardModalProps {
  isOpen: boolean;
  alert: AlertWizardPayload | null;
  wizardMode?: 'alert' | 'operator_task' | 'sla_dashboard';
  onClose: () => void;
  onRemediateSuccess: (alertId: string, executionDetails: any) => void;
  onAcceptRbdSuccess: (alertId: string, rbdRecord: any) => void;
  onSendQuoteSuccess?: (alertId: string, quoteDetails: any) => void;
  onMicroTxSuccess?: (alertId: string, amount: number) => void;
  onToggleChecklist?: (alertId: string, checklistId: string) => void;
  onAddWorkNote?: (alertId: string, noteText: string) => void;
  onReassignTask?: (alertId: string, newAssignee: string) => void;
  onIssueSlaCredit?: (alertId: string, creditAmount: number) => void;
  className?: string;
}

export const AlertResolutionWizardModal: React.FC<AlertResolutionWizardModalProps> = ({
  isOpen,
  alert,
  wizardMode = 'alert',
  onClose,
  onRemediateSuccess,
  onAcceptRbdSuccess,
  onSendQuoteSuccess,
  onMicroTxSuccess,
  onToggleChecklist,
  onAddWorkNote,
  onReassignTask,
  onIssueSlaCredit,
  className,
}) => {
  const [showSopPreviewDialog, setShowSopPreviewDialog] = useState(false);
  const [showRbdModal, setShowRbdModal] = useState(false);
  const [isExecutingSop, setIsExecutingSop] = useState(false);
  const [isSendingQuote, setIsSendingQuote] = useState(false);
  const [quoteSent, setQuoteSent] = useState(false);
  const [microTxBilled, setMicroTxBilled] = useState(false);
  const [workNoteInput, setWorkNoteInput] = useState('');
  const [creditIssued, setCreditIssued] = useState(false);

  if (!isOpen || !alert) return null;

  const rootCause = alert.rootCauseAnalysis || (
    wizardMode === 'operator_task'
      ? `Task generated by ${alert.taskSource?.toUpperCase() || 'SOP DETECTOR'} for target ${alert.targetResource}. Execution type: ${alert.executionType || 'Automated'}. Graph API payload pending operator review.`
      : wizardMode === 'sla_dashboard'
      ? `Tenant ${alert.tenantName} current attainment at ${alert.monthlyAttainment || 92.4}% is below contracted ${alert.targetAttainment || 95.0}% threshold due to ${alert.activeBreaches || 2} active policy drift events.`
      : `Manual Conditional Access exclusion added for ${alert.targetResource} via Azure Portal by global admin at ${alert.detectedAt || '12:45 UTC'}. Exemption overrides tenant MFA enforcement policy.`
  );

  const currentConfig = alert.currentConfigJson || (
    wizardMode === 'operator_task'
      ? {
          taskId: alert.id,
          taskCode: alert.code,
          assignedTo: alert.assignedTo || "Unassigned",
          executionType: alert.executionType || "manual",
          psaTicket: alert.psaTicketId || "CW-89102",
          checklistProgress: `${alert.checklists?.filter(c => c.done).length || 0}/${alert.checklists?.length || 3} Completed`,
          taskStatus: "IN_PROGRESS"
        }
      : wizardMode === 'sla_dashboard'
      ? {
          tenantId: alert.tenantId,
          slaTier: alert.slaTier || "Gold",
          currentAttainment: `${alert.monthlyAttainment || 92.4}%`,
          contractualGoal: `${alert.targetAttainment || 95.0}%`,
          mttdAverage: `${alert.mttdMinutes || 3.2} min`,
          mttrAverage: `${alert.mttrMinutes || 12.8} min`,
          slaComplianceStatus: alert.status === 'breached' ? "CONTRACT_BREACH" : "AT_RISK_WARNING"
        }
      : {
          policyName: "CA001-RequireMFA-ExecutiveTier",
          state: "enabled",
          userExclusions: [alert.targetResource],
          enforceMfa: false,
          sessionControlHours: null,
          complianceStatus: "NON_COMPLIANT_DRIFT"
        }
  );

  const targetConfig = alert.targetConfigJson || (
    wizardMode === 'operator_task'
      ? {
          taskId: alert.id,
          taskCode: alert.code,
          assignedTo: alert.assignedTo || "Shane McCaw (Lead Tech)",
          executionType: "automated_graph_dispatched",
          psaTicket: `${alert.psaTicketId || 'CW-89102'} (Synced & Resolved)`,
          checklistProgress: "All Checklists Completed (100%)",
          taskStatus: "COMPLETED"
        }
      : wizardMode === 'sla_dashboard'
      ? {
          tenantId: alert.tenantId,
          slaTier: alert.slaTier || "Gold",
          restoredAttainment: "99.8%",
          contractualGoal: `${alert.targetAttainment || 95.0}%`,
          mttdAverage: "< 2.0 min",
          mttrAverage: "< 5.0 min",
          slaComplianceStatus: "HEALTHY_CONTRACT_COMPLIANT"
        }
      : {
          policyName: "CA001-RequireMFA-ExecutiveTier",
          state: "enabled",
          userExclusions: [],
          enforceMfa: true,
          sessionControlHours: 12,
          complianceStatus: "ENFORCED_BASELINE"
        }
  );

  const sopCode = alert.matchedSopCode || (
    wizardMode === 'operator_task' ? `SOP-TASK-${alert.code}` :
    wizardMode === 'sla_dashboard' ? `SOP-SLA-RESERVE-${alert.tenantId}` :
    `SOP-${(alert.category || 'IAM').toUpperCase().slice(0, 3)}-04`
  );

  const isOutOfScope = alert.isOutOfScope ?? (
    wizardMode === 'alert' ? (alert.severity === 'critical' || alert.category === 'Identity' || alert.category === 'IAM') : false
  );

  const handleExecuteSopFinal = () => {
    setIsExecutingSop(true);
    setTimeout(() => {
      setIsExecutingSop(false);
      setShowSopPreviewDialog(false);
      onRemediateSuccess(alert.id, {
        remediatedAt: new Date().toISOString(),
        sopCode,
        graphEndpoint: alert.graphEndpoint || `/tenants/${alert.tenantId}/remediate`
      });
      onClose();
    }, 1200);
  };

  const handleSendQuote = () => {
    setIsSendingQuote(true);
    setTimeout(() => {
      setIsSendingQuote(false);
      setQuoteSent(true);
      if (onSendQuoteSuccess) {
        onSendQuoteSuccess(alert.id, {
          amount: 250,
          quoteType: wizardMode === 'sla_dashboard' ? 'Platinum SLA Tier Upgrade' : 'Gold Tier Upgrade Proposal',
          sentTo: `ciso@${alert.tenantId.toLowerCase().replace('ten-', '')}.com`
        });
      }
    }, 800);
  };

  const handleBillMicroTx = () => {
    setMicroTxBilled(true);
    if (onMicroTxSuccess) {
      onMicroTxSuccess(alert.id, 250);
    }
  };

  const handleAddNote = () => {
    if (!workNoteInput.trim()) return;
    onAddWorkNote?.(alert.id, workNoteInput.trim());
    setWorkNoteInput('');
  };

  const handleIssueCredit = () => {
    setCreditIssued(true);
    onIssueSlaCredit?.(alert.tenantId, 250);
  };

  return (
    <div className={cn("fixed inset-0 z-50 flex items-center justify-center bg-[#06080d]/90 backdrop-blur-md p-4 lg:p-6 animate-in fade-in duration-200", className)}>
      <div className="w-full max-w-7xl h-[92vh] rounded-3xl border border-[#23314a] bg-[#0d121a] shadow-2xl flex flex-col text-slate-100 font-sans overflow-hidden">
        
        {/* WIZARD TOP HEADER */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#202b3c] bg-[#111722]/80">
          <div className="flex items-center gap-3">
            <div className={cn(
              "p-2.5 rounded-2xl border",
              wizardMode === 'operator_task' ? "bg-amber-500/10 border-amber-500/30 text-amber-400" :
              wizardMode === 'sla_dashboard' ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-400" :
              "bg-red-500/10 border-red-500/30 text-red-400"
            )}>
              {wizardMode === 'operator_task' ? <ListTodo className="w-6 h-6" /> :
               wizardMode === 'sla_dashboard' ? <Award className="w-6 h-6" /> :
               <ShieldAlert className="w-6 h-6" />}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className={cn(
                  "text-xs font-mono font-bold px-2.5 py-0.5 rounded-full border uppercase",
                  wizardMode === 'operator_task' ? "bg-amber-500/20 text-amber-300 border-amber-500/40" :
                  wizardMode === 'sla_dashboard' ? "bg-emerald-500/20 text-emerald-300 border-emerald-500/40" :
                  "bg-red-500/20 text-red-300 border-red-500/40"
                )}>
                  {wizardMode === 'operator_task' ? 'OPERATOR TASK CONSOLE' :
                   wizardMode === 'sla_dashboard' ? 'MSP SLA REMEDIATION' :
                   `${alert.severity} THREAT`}
                </span>
                <h2 className="text-base font-extrabold text-white tracking-tight">{alert.title}</h2>
                <span className="text-xs font-mono text-cyan-400 bg-cyan-950/60 px-2 py-0.5 rounded border border-cyan-800">
                  {alert.code}
                </span>
              </div>
              <p className="text-xs text-slate-400 mt-0.5">
                Tenant: <strong className="text-white">{alert.tenantName}</strong> ({alert.tenantId}) | Target: <code className="text-amber-300 font-mono">{alert.targetResource}</code>
                {wizardMode === 'operator_task' && alert.psaTicketId && (
                  <span className="ml-2 text-cyan-300 font-mono">| PSA: <strong>{alert.psaTicketId}</strong></span>
                )}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 bg-[#080b10] border border-[#202b3c] px-3.5 py-1.5 rounded-xl text-xs font-mono">
              <Clock className="w-3.5 h-3.5 text-amber-400 animate-pulse" />
              <span>SLA Target: <strong className="text-amber-400">{wizardMode === 'sla_dashboard' ? `${alert.monthlyAttainment || 92.4}% Attainment` : '11m 42s Remaining'}</strong></span>
            </div>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-white rounded-xl hover:bg-slate-800 transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* TOP SECTION: THREAT & DRIFT ROOT CAUSE ANALYSIS + CONFIG COMPARISON */}
        <div className="p-6 border-b border-[#1f2a3c] bg-[#090d14] space-y-4">
          <div className={cn(
            "flex items-start gap-3 p-3.5 rounded-2xl border",
            wizardMode === 'operator_task' ? "bg-amber-950/20 border-amber-500/30" :
            wizardMode === 'sla_dashboard' ? "bg-emerald-950/20 border-emerald-500/30" :
            "bg-red-950/20 border-red-500/30"
          )}>
            <AlertTriangle className={cn(
              "w-5 h-5 shrink-0 mt-0.5",
              wizardMode === 'operator_task' ? "text-amber-400" :
              wizardMode === 'sla_dashboard' ? "text-emerald-400" :
              "text-red-400"
            )} />
            <div className="space-y-1">
              <h4 className={cn(
                "text-xs font-bold uppercase tracking-wider font-mono",
                wizardMode === 'operator_task' ? "text-amber-300" :
                wizardMode === 'sla_dashboard' ? "text-emerald-300" :
                "text-red-300"
              )}>
                {wizardMode === 'operator_task' ? 'Operator Task Objective & Diagnostic Overview' :
                 wizardMode === 'sla_dashboard' ? 'Contractual SLA Performance & Breach Root Cause' :
                 'Threat & Drift Root Cause Analysis'}
              </h4>
              <p className="text-xs text-slate-300 leading-relaxed">
                {rootCause}
              </p>
            </div>
          </div>

          {/* CONFIGURATION DRIFT COMPARISON (BEFORE VS REQUIRED AFTER) */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* CURRENT NON-COMPLIANT CONFIG */}
            <div className="p-3.5 rounded-2xl bg-red-950/15 border border-red-500/30 space-y-2">
              <div className="flex items-center justify-between text-xs font-bold text-red-300">
                <span className="flex items-center gap-1.5 font-mono">
                  <X className="w-4 h-4 text-red-400" />
                  {wizardMode === 'operator_task' ? 'CURRENT UNRESOLVED TASK STATE' :
                   wizardMode === 'sla_dashboard' ? 'CURRENT DEGRADED SLA ATTAINMENT STATE' :
                   'CURRENT NON-COMPLIANT DRIFT STATE'}
                </span>
                <span className="text-[10px] bg-red-500/20 px-2 py-0.5 rounded text-red-300 border border-red-500/30 font-mono">
                  {wizardMode === 'sla_dashboard' ? 'SLA DEFICIT' : 'ACTIVE DRIFT'}
                </span>
              </div>
              <pre className="p-3 rounded-xl bg-[#06080e] border border-red-950 text-[11px] font-mono text-red-300 overflow-x-auto leading-relaxed">
                {JSON.stringify(currentConfig, null, 2)}
              </pre>
            </div>

            {/* REQUIRED COMPLIANT BASELINE CONFIG */}
            <div className="p-3.5 rounded-2xl bg-emerald-950/15 border border-emerald-500/30 space-y-2">
              <div className="flex items-center justify-between text-xs font-bold text-emerald-300">
                <span className="flex items-center gap-1.5 font-mono">
                  <Check className="w-4 h-4 text-emerald-400" />
                  {wizardMode === 'operator_task' ? 'TARGET COMPLETED TASK STATE' :
                   wizardMode === 'sla_dashboard' ? 'RESTORED CONTRACT COMPLIANT SLA STATE' :
                   'REQUIRED COMPLIANT BASELINE STATE'}
                </span>
                <span className="text-[10px] bg-emerald-500/20 px-2 py-0.5 rounded text-emerald-300 border border-emerald-500/30 font-mono">
                  ENFORCED TARGET
                </span>
              </div>
              <pre className="p-3 rounded-xl bg-[#06080e] border border-emerald-950 text-[11px] font-mono text-emerald-300 overflow-x-auto leading-relaxed">
                {JSON.stringify(targetConfig, null, 2)}
              </pre>
            </div>
          </div>
        </div>

        {/* 3-PANEL WIZARD LAYOUT */}
        <div className="flex-1 grid grid-cols-12 gap-5 p-6 overflow-y-auto custom-scrollbar">
          
          {/* PANEL 1: CONTEXT & ASSIGNMENT / TELEMETRY */}
          <div className="col-span-12 lg:col-span-4 rounded-2xl border border-[#202b3c] bg-[#111722]/60 p-4 space-y-4">
            <div className="flex items-center gap-2 border-b border-[#1f2a3c] pb-2.5">
              <Sparkles className="w-4 h-4 text-[#38BDF8]" />
              <h3 className="text-xs font-bold text-white uppercase tracking-wider font-mono">
                {wizardMode === 'operator_task' ? 'Panel 1: Operator Task & Assignment' :
                 wizardMode === 'sla_dashboard' ? 'Panel 1: Tenant SLA Telemetry' :
                 'Panel 1: AI Threat Recommendation'}
              </h3>
            </div>

            {wizardMode === 'operator_task' ? (
              <div className="space-y-3 text-xs">
                <div className="p-3 rounded-xl bg-[#080b10] border border-[#202b3c] space-y-2">
                  <div className="text-slate-400 font-mono font-bold">Assigned Technician:</div>
                  <select
                    value={alert.assignedTo || 'Unassigned'}
                    onChange={(e) => onReassignTask?.(alert.id, e.target.value)}
                    className="w-full bg-[#181c22] border border-[#404752] rounded p-2 text-white font-mono"
                  >
                    <option value="Unassigned">Unassigned (Queue Pool)</option>
                    <option value="Shane McCaw (Lead Tech)">Shane McCaw (Lead Tech)</option>
                    <option value="Alex Rivera (L2 Engineer)">Alex Rivera (L2 Engineer)</option>
                    <option value="Sarah Lin (Security Specialist)">Sarah Lin (Security Specialist)</option>
                    <option value="Devon Vance (Service Desk)">Devon Vance (Service Desk)</option>
                  </select>
                </div>

                <div className="p-3 rounded-xl bg-[#080b10] border border-[#202b3c] space-y-1.5 font-mono">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Source:</span>
                    <strong className="text-cyan-300 uppercase">{alert.taskSource || 'SOP'}</strong>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Execution Type:</span>
                    <strong className="text-amber-300 uppercase">{alert.executionType || 'Automated'}</strong>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Target Resource:</span>
                    <strong className="text-white">{alert.targetResource}</strong>
                  </div>
                </div>

                <div className="p-3 rounded-xl bg-cyan-950/20 border border-cyan-500/30 text-xs space-y-1 text-cyan-200 font-mono">
                  <div className="font-bold flex items-center gap-1.5">
                    <Code className="w-3.5 h-3.5 text-cyan-400" />
                    Graph Endpoint:
                  </div>
                  <code className="block text-[11px] text-cyan-300 bg-[#06080e] p-2 rounded border border-cyan-900 truncate">
                    {alert.graphEndpoint || `/tenants/${alert.tenantId}/tasks/${alert.code}`}
                  </code>
                </div>
              </div>
            ) : wizardMode === 'sla_dashboard' ? (
              <div className="space-y-3 text-xs">
                <div className="p-3 rounded-xl bg-[#080b10] border border-[#202b3c] space-y-2 font-mono">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Contract Tier:</span>
                    <span className="font-bold text-amber-400">{alert.slaTier || 'Gold Tier'}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Monthly Attainment:</span>
                    <span className="font-bold text-emerald-400">{alert.monthlyAttainment || 92.4}%</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Target Goal:</span>
                    <span className="font-bold text-white">{alert.targetAttainment || 95.0}%</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">MTTD / MTTR:</span>
                    <span className="font-bold text-cyan-300">{alert.mttdMinutes || 3.2}m / {alert.mttrMinutes || 12.8}m</span>
                  </div>
                </div>

                <div className="p-3 rounded-xl bg-emerald-950/20 border border-emerald-500/30 text-xs space-y-1 text-emerald-200">
                  <div className="font-bold flex items-center gap-1.5 font-mono">
                    <Target className="w-3.5 h-3.5 text-emerald-400" />
                    Auto-Healed Incidents Ratio:
                  </div>
                  <div className="text-lg font-mono font-bold text-emerald-300">
                    {alert.autoHealedIncidents || 18} Automated Fixes ({((alert.autoHealedIncidents || 18) / ((alert.autoHealedIncidents || 18) + (alert.activeBreaches || 2)) * 100).toFixed(0)}%)
                  </div>
                </div>
              </div>
            ) : (
              <div className="space-y-3 text-xs">
                <div className="p-3 rounded-xl bg-[#080b10] border border-[#202b3c] space-y-2">
                  <div className="text-xs font-bold text-cyan-300">AI Threat Vector Assessment:</div>
                  <p className="text-xs text-slate-300 leading-relaxed">
                    {alert.description} Exemption leaves account vulnerable to credential stuffing attacks across external endpoints.
                  </p>
                </div>

                <div className="space-y-2">
                  <div className="text-[11px] font-bold text-slate-400 uppercase font-mono">Security Blast Radius Impact:</div>
                  <div className="p-3 rounded-xl bg-[#080b10] border border-[#202b3c] space-y-1.5 text-xs">
                    <div className="flex justify-between">
                      <span className="text-slate-400">Breach Probability Increase:</span>
                      <strong className="text-red-400">+42%</strong>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-400">Compliance Standard Gap:</span>
                      <strong className="text-amber-300">CIS 1.1 Non-Compliance</strong>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-400">Target Resource:</span>
                      <code className="text-cyan-300 font-mono">{alert.targetResource}</code>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* PANEL 2: MATCHING SOP RUNBOOK & CHECKLIST / EXECUTION */}
          <div className="col-span-12 lg:col-span-4 rounded-2xl border border-[#202b3c] bg-[#111722]/60 p-4 space-y-4">
            <div className="flex items-center justify-between border-b border-[#1f2a3c] pb-2.5">
              <div className="flex items-center gap-2">
                <BookOpen className="w-4 h-4 text-[#38BDF8]" />
                <h3 className="text-xs font-bold text-white uppercase tracking-wider font-mono">
                  {wizardMode === 'operator_task' ? 'Panel 2: Interactive Task Checklists' : 'Panel 2: Matching SOP Runbook'}
                </h3>
              </div>
              <span className="text-[10px] font-mono font-bold bg-[#0078d4]/20 text-[#38BDF8] border border-[#0078d4]/40 px-2 py-0.5 rounded">
                {sopCode}
              </span>
            </div>

            {wizardMode === 'operator_task' && alert.checklists && alert.checklists.length > 0 ? (
              <div className="space-y-2">
                <div className="text-[11px] font-mono font-bold text-slate-400 uppercase">Interactive Step Checklists:</div>
                <div className="space-y-1.5">
                  {alert.checklists.map((chk) => (
                    <label
                      key={chk.id}
                      className={cn(
                        "flex items-center gap-2.5 p-2.5 rounded-xl border text-xs cursor-pointer transition-colors",
                        chk.done ? "bg-emerald-950/20 border-emerald-500/40 text-emerald-300" : "bg-[#080b10] border-[#202b3c] text-slate-200 hover:border-[#0078d4]"
                      )}
                    >
                      <input
                        type="checkbox"
                        checked={chk.done}
                        onChange={() => onToggleChecklist?.(alert.id, chk.id)}
                        className="rounded bg-[#06080e]"
                      />
                      <span className={cn(chk.done && "line-through opacity-80")}>{chk.label}</span>
                    </label>
                  ))}
                </div>
              </div>
            ) : (
              <div className="space-y-2">
                <div className="p-2.5 rounded-xl bg-emerald-950/20 border border-emerald-500/30 text-xs text-emerald-300 flex items-center justify-between">
                  <span className="font-bold">Step 1: Revoke Active Sign-In Sessions</span>
                  <span className="font-mono text-[10px]">~120ms</span>
                </div>

                <div className="p-2.5 rounded-xl bg-emerald-950/20 border border-emerald-500/30 text-xs text-emerald-300 flex items-center justify-between">
                  <span className="font-bold">Step 2: Re-enforce Baseline Policy Drift</span>
                  <span className="font-mono text-[10px]">~340ms</span>
                </div>

                <div className="p-2.5 rounded-xl bg-emerald-950/20 border border-emerald-500/30 text-xs text-emerald-300 flex items-center justify-between">
                  <span className="font-bold">Step 3: Update Graph Telemetry & Clear Alert</span>
                  <span className="font-mono text-[10px]">~210ms</span>
                </div>
              </div>
            )}

            <div className="p-3 rounded-xl bg-[#080b10] border border-[#202b3c] space-y-2 text-xs">
              <div className="text-slate-400">Execution Safety Preview:</div>
              <p className="text-slate-300 leading-normal">
                Clicking <strong>Preview Auto-Heal Execution</strong> opens side-by-side Before/After state comparison before committing changes to Microsoft Graph.
              </p>
            </div>
          </div>

          {/* PANEL 3: WORK NOTES / SCOPE & COMMERCIAL REMEDIES */}
          <div className="col-span-12 lg:col-span-4 rounded-2xl border border-amber-500/40 bg-amber-950/10 p-4 space-y-4">
            <div className="flex items-center justify-between border-b border-amber-500/30 pb-2.5">
              <div className="flex items-center gap-2">
                <SlidersHorizontal className="w-4 h-4 text-amber-400" />
                <h3 className="text-xs font-bold text-amber-300 uppercase tracking-wider font-mono">
                  {wizardMode === 'operator_task' ? 'Panel 3: Technician Notes & PSA Sync' :
                   wizardMode === 'sla_dashboard' ? 'Panel 3: SLA Remedies & Commercials' :
                   'Panel 3: Scope Creep & Commercials'}
                </h3>
              </div>
              <span className="text-[10px] font-mono font-bold bg-amber-500/20 text-amber-300 border border-amber-500/40 px-2 py-0.5 rounded">
                {wizardMode === 'sla_dashboard' ? 'CONTRACT REMEDY' : 'GOVERNANCE'}
              </span>
            </div>

            {wizardMode === 'operator_task' ? (
              <div className="space-y-3 text-xs">
                <div>
                  <label className="block text-slate-300 mb-1 font-bold">Log Technician Activity Note:</label>
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={workNoteInput}
                      onChange={(e) => setWorkNoteInput(e.target.value)}
                      placeholder="Add investigation step / notes..."
                      className="flex-1 bg-[#080b10] border border-[#404752] rounded p-2 text-white text-xs outline-none focus:border-[#0078d4]"
                    />
                    <button
                      onClick={handleAddNote}
                      className="bg-[#0078d4] hover:bg-[#0060ab] text-white px-3 py-2 rounded font-mono font-bold cursor-pointer"
                    >
                      Post Note
                    </button>
                  </div>
                </div>

                {alert.activityTrail && alert.activityTrail.length > 0 && (
                  <div className="p-3 rounded-xl bg-[#080b10] border border-[#202b3c] space-y-2 max-h-32 overflow-y-auto">
                    <div className="text-[10px] text-slate-400 font-mono font-bold uppercase">Recent Activity Trail:</div>
                    {alert.activityTrail.slice(-3).map((note) => (
                      <div key={note.id} className="text-[11px] border-b border-[#202b3c] pb-1.5">
                        <div className="text-cyan-300 font-mono font-bold">{note.actor} ({note.timestamp}):</div>
                        <p className="text-slate-300">{note.note}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ) : wizardMode === 'sla_dashboard' ? (
              <div className="space-y-3 text-xs">
                <p className="text-amber-200/90 leading-relaxed">
                  Remediate tenant SLA deficit via automated policy realignment or issue SLA Service Credit note.
                </p>

                <div className="space-y-2">
                  <button
                    onClick={handleIssueCredit}
                    disabled={creditIssued}
                    className="w-full text-xs font-bold bg-amber-500/20 hover:bg-amber-500/30 text-amber-200 border border-amber-500/40 p-2.5 rounded-xl transition-all flex items-center justify-center gap-2 cursor-pointer"
                  >
                    <DollarSign className="w-4 h-4 text-amber-300" />
                    <span>{creditIssued ? '✅ $250 SLA Credit Issued to Ledger' : 'Post $250.00 SLA Service Credit Note'}</span>
                  </button>

                  <button
                    onClick={handleSendQuote}
                    disabled={isSendingQuote || quoteSent}
                    className="w-full text-xs font-bold bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 disabled:opacity-50 text-slate-950 p-2.5 rounded-xl transition-all shadow-md flex items-center justify-center gap-2 cursor-pointer"
                  >
                    <Send className="w-4 h-4" />
                    <span>{isSendingQuote ? 'Dispatching Proposal...' : quoteSent ? '✅ Platinum Upgrade Quote Dispatched' : 'Push Platinum SLA Upgrade Proposal (+ $4/seat)'}</span>
                  </button>
                </div>
              </div>
            ) : isOutOfScope ? (
              <div className="space-y-3">
                <p className="text-xs text-amber-200/90 leading-relaxed">
                  {alert.outOfScopeReason || 'Remediation for this alert falls outside standard contracted SLA tier.'}
                </p>

                <div className="p-3 rounded-xl bg-amber-950/40 border border-amber-500/30 text-xs font-mono text-amber-300">
                  Estimated Financial Impact: <strong>$250.00 Ad-Hoc Fee OR +$4.00/seat Gold Upgrade</strong>
                </div>

                <div className="space-y-2">
                  <button
                    onClick={handleSendQuote}
                    disabled={isSendingQuote || quoteSent}
                    className="w-full text-xs font-bold bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 disabled:opacity-50 text-slate-950 p-2.5 rounded-xl transition-all shadow-md flex items-center justify-center gap-2 cursor-pointer"
                  >
                    <Send className="w-4 h-4" />
                    <span>{isSendingQuote ? 'Dispatching Gold Quote...' : quoteSent ? '✅ Gold Upgrade Quote Dispatched' : 'Push Gold Upgrade Quote to Client'}</span>
                  </button>

                  <button
                    onClick={handleBillMicroTx}
                    disabled={microTxBilled}
                    className="w-full text-xs font-bold bg-amber-500/20 hover:bg-amber-500/30 text-amber-200 border border-amber-500/40 p-2.5 rounded-xl transition-all flex items-center justify-center gap-2 cursor-pointer"
                  >
                    <DollarSign className="w-4 h-4 text-amber-300" />
                    <span>{microTxBilled ? '✅ $250 Micro-Tx Billed to Ledger' : 'Post $250.00 Micro-Transaction Fee'}</span>
                  </button>
                </div>
              </div>
            ) : (
              <div className="p-4 text-center text-xs text-slate-400 italic">
                This item remediation is covered under active client contract baseline.
              </div>
            )}
          </div>

        </div>

        {/* BOTTOM DECISION GATE / ACTION BAR */}
        <div className="px-6 py-4 border-t border-[#202b3c] bg-[#111722] flex items-center justify-between">
          <div className="text-xs text-slate-400 font-mono">
            Decision Gate Status: <strong className="text-cyan-400">Awaiting Operator Path Selection</strong>
          </div>

          <div className="flex items-center gap-3">
            {/* PATH A: FIX / EXECUTE SOP */}
            <button
              onClick={() => setShowSopPreviewDialog(true)}
              className="text-xs font-bold bg-gradient-to-r from-emerald-600 to-cyan-600 hover:from-emerald-500 hover:to-cyan-500 text-white px-5 py-2.5 rounded-xl transition-all shadow-lg flex items-center gap-2 cursor-pointer"
            >
              <Zap className="w-4 h-4 text-yellow-300" />
              <span>
                {wizardMode === 'operator_task' ? '▶️ Execute Task & Dispatch Graph Auto-Heal' :
                 wizardMode === 'sla_dashboard' ? '▶️ Execute SLA Auto-Heal & Restore Attainment' :
                 '▶️ Fix Risk / Preview SOP Auto-Heal'}
              </span>
            </button>

            {/* PATH B: ACCEPT RISK / REQUIRE RBD */}
            <button
              onClick={() => setShowRbdModal(true)}
              className="text-xs font-bold bg-gradient-to-r from-red-600 to-amber-600 hover:from-red-500 hover:to-amber-500 text-white px-5 py-2.5 rounded-xl transition-all shadow-lg flex items-center gap-2 cursor-pointer"
            >
              <ShieldAlert className="w-4 h-4" />
              <span>
                {wizardMode === 'sla_dashboard' ? '🛡️ Log Contract Waiver / SLA Exemption' :
                 '🛡️ Accept Risk & Require RBD Waiver'}
              </span>
            </button>
          </div>
        </div>

      </div>

      {/* BEFORE / AFTER SOP EXECUTION PREVIEW DIALOG */}
      {showSopPreviewDialog && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#06080d]/90 backdrop-blur-md p-4 animate-in fade-in duration-150">
          <div className="w-full max-w-2xl rounded-2xl border border-emerald-500/40 bg-[#0d121a] p-6 shadow-2xl space-y-5 text-slate-100 font-sans">
            
            <div className="flex items-start justify-between border-b border-[#202b3c] pb-4">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400">
                  <Zap className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-white flex items-center gap-2">
                    <span>
                      {wizardMode === 'operator_task' ? 'Operator Task Graph Auto-Heal Execution' :
                       wizardMode === 'sla_dashboard' ? 'SLA Attainment Restoration Execution' :
                       'SOP Remediation Execution Preview'}
                    </span>
                    <span className="text-[10px] font-mono font-extrabold uppercase px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                      BEFORE / AFTER
                    </span>
                  </h3>
                  <p className="text-xs text-slate-400 mt-0.5">
                    Review side-by-side state transformation before dispatching Graph API payload.
                  </p>
                </div>
              </div>
              <button onClick={() => setShowSopPreviewDialog(false)} className="text-slate-400 hover:text-white">
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* BEFORE VS AFTER COMPARISON */}
            <div className="grid grid-cols-2 gap-4">
              <div className="p-3.5 rounded-xl bg-red-950/20 border border-red-500/30 space-y-1.5 text-xs">
                <div className="font-bold text-red-400 flex items-center gap-1 font-mono">
                  <X className="w-3.5 h-3.5" />
                  BEFORE (Current State):
                </div>
                <div className="font-mono text-[11px] text-slate-300 space-y-1 bg-[#06080e] p-2.5 rounded border border-red-950">
                  <div>Resource: <span className="text-red-400 font-bold">{alert.targetResource}</span></div>
                  <div>Status: <span className="text-red-400 font-bold">{wizardMode === 'sla_dashboard' ? `${alert.monthlyAttainment || 92.4}% ATTAINMENT` : 'DRIFTED / PENDING'}</span></div>
                </div>
              </div>

              <div className="p-3.5 rounded-xl bg-emerald-950/20 border border-emerald-500/30 space-y-1.5 text-xs">
                <div className="font-bold text-emerald-400 flex items-center gap-1 font-mono">
                  <Check className="w-3.5 h-3.5" />
                  AFTER (Remediated Target):
                </div>
                <div className="font-mono text-[11px] text-slate-300 space-y-1 bg-[#06080e] p-2.5 rounded border border-emerald-950">
                  <div>Resource: <span className="text-emerald-400 font-bold">{alert.targetResource}</span></div>
                  <div>Status: <span className="text-emerald-400 font-bold">{wizardMode === 'sla_dashboard' ? '99.8% RESTORED SLA' : 'ENFORCED BASELINE'}</span></div>
                </div>
              </div>
            </div>

            <div className="p-3 rounded-xl bg-[#080b10] border border-[#202b3c] text-xs font-mono text-cyan-300">
              Dispatches: <code className="text-white">{alert.graphEndpoint || `/tenants/${alert.tenantId}/remediate`}</code>
            </div>

            <div className="flex items-center justify-end gap-3 pt-3 border-t border-[#202b3c]">
              <button
                onClick={() => setShowSopPreviewDialog(false)}
                className="text-xs font-semibold text-slate-400 hover:text-white px-4 py-2"
              >
                Cancel
              </button>
              <button
                onClick={handleExecuteSopFinal}
                disabled={isExecutingSop}
                className="text-xs font-bold bg-gradient-to-r from-emerald-600 to-cyan-600 hover:from-emerald-500 hover:to-cyan-500 text-white px-5 py-2.5 rounded-xl transition-all shadow-lg flex items-center gap-2 cursor-pointer"
              >
                <Zap className="w-4 h-4 text-yellow-300" />
                <span>{isExecutingSop ? 'Executing Graph Auto-Heal...' : '🔥 Execute Graph API Auto-Heal Now'}</span>
              </button>
            </div>

          </div>
        </div>
      )}

      {/* RBD ACCEPTANCE & RULE LINKING MODAL */}
      <RbdAcceptanceAndRuleLinker
        isOpen={showRbdModal}
        alertPayload={{
          alertId: alert.id,
          tenantId: alert.tenantId,
          tenantName: alert.tenantName,
          riskNotificationType: alert.riskNotificationType || `${alert.category.toUpperCase()}_MFA_EXEMPTION`,
          targetResource: alert.targetResource,
          severity: alert.severity,
          title: alert.title,
        }}
        onClose={() => setShowRbdModal(false)}
        onConfirmRbd={(record) => {
          setShowRbdModal(false);
          onAcceptRbdSuccess(alert.id, record);
          onClose();
        }}
      />

    </div>
  );
};
