import {
  PillarData,
  IntelligenceSignal,
  RiskHeatmapCell,
  CostBreakdownItem,
  SecurityTrendPoint,
  AdoptionMetricItem,
} from '../types';

export const INITIAL_PILLARS: PillarData[] = [
  {
    id: 'security',
    name: 'Security',
    shortCode: 'SEC',
    score: 91,
    change: 12,
    trend: 'up',
    icon: 'Shield',
    color: '#a0c9ff',
    bars: [2, 4, 3, 6],
    targetScore: 95,
    description: 'Zero Trust architecture posture, identity security & threat protection.',
    subMetrics: [
      { name: 'MFA Coverage', value: '98.4%', status: 'good' },
      { name: 'Conditional Access Policy', value: 'Compliant', status: 'good' },
      { name: 'Risky User Count', value: 3, status: 'warning' },
    ],
    recommendations: [
      'Enforce FIDO2 security keys for all high-privilege administrators.',
      'Disable legacy basic auth across secondary tenant endpoints.',
    ],
  },
  {
    id: 'governance',
    name: 'Governance',
    shortCode: 'GOV',
    score: 74,
    change: -2,
    trend: 'down',
    icon: 'Gavel',
    color: '#dab9ff',
    bars: [4, 3, 5, 4],
    targetScore: 85,
    description: 'Data classification, sensitivity labeling, lifecycle and retention controls.',
    subMetrics: [
      { name: 'Labeled Documents', value: '78%', status: 'warning' },
      { name: 'Unused Guest Accounts', value: 142, status: 'critical' },
      { name: 'Retention Policies Active', value: '12 / 14', status: 'good' },
    ],
    recommendations: [
      'Automate monthly access reviews for guest access in HR & Legal sites.',
      'Apply auto-labeling policies to financial statement repositories.',
    ],
  },
  {
    id: 'compliance',
    name: 'Compliance',
    shortCode: 'COMP',
    score: 88,
    change: 5,
    trend: 'up',
    icon: 'ShieldCheck',
    color: '#c8c6c5',
    bars: [3, 5, 6, 4],
    targetScore: 90,
    description: 'Regulatory posture (ISO 27001, HIPAA, GDPR, SOC2) and auditing controls.',
    subMetrics: [
      { name: 'Regulatory Score', value: '88%', status: 'good' },
      { name: 'Audit Log Retention', value: '365 days', status: 'good' },
      { name: 'DLP Overrides (24h)', value: 14, status: 'warning' },
    ],
    recommendations: [
      'Review low-severity DLP override exceptions in Teams attachments.',
      'Finalize quarterly audit evidence package for SOC2 Type II.',
    ],
  },
  {
    id: 'adoption',
    name: 'Adoption',
    shortCode: 'ADOP',
    score: 62,
    change: 18,
    trend: 'up',
    icon: 'Users',
    color: '#479ef5',
    bars: [2, 3, 4, 5],
    targetScore: 80,
    description: 'Active usage metrics, workspace engagement, collaboration density.',
    subMetrics: [
      { name: 'Monthly Active Users', value: '1,420', status: 'good' },
      { name: 'Collab Density', value: '64%', status: 'warning' },
      { name: 'Inactive Mailboxes (>90d)', value: 89, status: 'warning' },
    ],
    recommendations: [
      'Conduct department enablement sessions for Microsoft 365 Copilot feature adoption.',
      'Reclaim inactive licenses from unengaged accounts.',
    ],
  },
  {
    id: 'copilot',
    name: 'Copilot',
    shortCode: 'COPILOT',
    score: 71,
    change: 34,
    trend: 'up',
    icon: 'Bot',
    color: '#a0c9ff',
    bars: [1, 3, 5, 8],
    targetScore: 85,
    description: 'Generative AI deployment readiness, permissions hygiene & prompt governance.',
    subMetrics: [
      { name: 'Copilot Seats Assigned', value: '450', status: 'good' },
      { name: 'Over-exposed Documents', value: 340, status: 'critical' },
      { name: 'Weekly Prompt Activity', value: '12.4k', status: 'good' },
    ],
    recommendations: [
      'Restrict "Everyone" sharing links on root SharePoint finance sites before expanding seats.',
      'Enable Copilot audit logging in Microsoft Purview.',
    ],
  },
  {
    id: 'architecture',
    name: 'Architecture',
    shortCode: 'ARCH',
    score: 85,
    change: 0,
    trend: 'stable',
    icon: 'Network',
    color: '#8a919d',
    bars: [5, 5, 5, 5],
    targetScore: 90,
    description: 'Tenant layout, hybrid identity sync, network topology & domain alignment.',
    subMetrics: [
      { name: 'DirSync Status', value: 'Healthy', status: 'good' },
      { name: 'Legacy Auth Traffic', value: '12%', status: 'warning' },
      { name: 'Domain Health', value: '100%', status: 'good' },
    ],
    recommendations: [
      'Block legacy authentication protocols across all tenant conditional access rules.',
      'Migrate remaining Exchange hybrid endpoints to cloud native routing.',
    ],
  },
  {
    id: 'licensing',
    name: 'Licensing',
    shortCode: 'LIC',
    score: 94,
    change: -8,
    trend: 'down',
    icon: 'Receipt',
    color: '#d2e4ff',
    bars: [8, 7, 8, 6],
    targetScore: 98,
    description: 'SKU optimization, license utilization efficiency & waste reduction.',
    subMetrics: [
      { name: 'License Waste Value', value: '$42,000/yr', status: 'warning' },
      { name: 'E5/G5 Utilization Rate', value: '86%', status: 'good' },
      { name: 'Auto-Cleanup Potential', value: '$14,541/mo', status: 'good' },
    ],
    recommendations: [
      'Downgrade 45 underutilized E5 licenses to E3 with add-ons.',
      'Implement automated workflow for removing licenses from terminated employees.',
    ],
  },
];

export const INITIAL_SIGNALS: IntelligenceSignal[] = [
  {
    id: 'sig-1',
    pillar: 'Security',
    iconName: 'Shield',
    title: 'Security: High-risk identity detection',
    description: 'Multiple MFA failures detected from unexpected geolocation (US-West-2).',
    severity: 'Critical',
    timestamp: '4m ago',
    acknowledged: false,
    remediated: false,
  },
  {
    id: 'sig-2',
    pillar: 'Governance',
    iconName: 'Gavel',
    title: 'Governance: Policy drift in HR Site',
    description: 'Sensitivity labels removed from 12 restricted documents in the past 24h.',
    severity: 'Warning',
    timestamp: '18m ago',
    acknowledged: false,
    remediated: false,
  },
  {
    id: 'sig-3',
    pillar: 'Copilot',
    iconName: 'Bot',
    title: 'Copilot: Permissions hygiene gap',
    description: '340 files accessible via \'Everyone\' links found in sensitive financial folders.',
    severity: 'Critical',
    timestamp: '1h ago',
    acknowledged: false,
    remediated: false,
  },
  {
    id: 'sig-4',
    pillar: 'Licensing',
    iconName: 'Receipt',
    title: 'Licensing: Over-licensed SKUs detected',
    description: '45 users assigned E5 licenses with zero usage of advanced features for 90 days.',
    severity: 'Optimization',
    timestamp: '2h ago',
    acknowledged: false,
    remediated: false,
  },
  {
    id: 'sig-5',
    pillar: 'Architecture',
    iconName: 'Network',
    title: 'Architecture: CA misalignment',
    description: 'Legacy authentication protocols still active for 12% of total tenant sign-ins.',
    severity: 'Warning',
    timestamp: '3h ago',
    acknowledged: false,
    remediated: false,
  },
];

export const RISK_HEATMAP_GRID: RiskHeatmapCell[] = [
  // Row 1: IDENTITY
  { id: 'cell-1', rowCategory: 'IDENTITY', colIndex: 0, severityColor: 'bg-[#ffb4ab]', label: 'Privileged Elevation Drift', riskScore: 88, affectedCount: 14 },
  { id: 'cell-2', rowCategory: 'IDENTITY', colIndex: 1, severityColor: 'bg-[#a0c9ff]', label: 'Stale Admin Credentials', riskScore: 42, affectedCount: 8 },
  { id: 'cell-3', rowCategory: 'IDENTITY', colIndex: 2, severityColor: 'bg-[#9c9a9a]', label: 'Unverified Guest Domain', riskScore: 50, affectedCount: 23 },
  { id: 'cell-4', rowCategory: 'IDENTITY', colIndex: 3, severityColor: 'bg-[#93000a]', label: 'Anomalous Token Lifetimes', riskScore: 92, affectedCount: 5 },
  { id: 'cell-5', rowCategory: 'IDENTITY', colIndex: 4, severityColor: 'bg-[#5a3289]', label: 'Service Principal Over-Permission', riskScore: 65, affectedCount: 19 },
  { id: 'cell-6', rowCategory: 'IDENTITY', colIndex: 5, severityColor: 'bg-[#479ef5]', label: 'Legacy MFA Bypass Rules', riskScore: 78, affectedCount: 11 },

  // Row 2: POLICIES
  { id: 'cell-7', rowCategory: 'POLICIES', colIndex: 0, severityColor: 'bg-[#479ef5]', label: 'DLP Override Exceptions', riskScore: 35, affectedCount: 30 },
  { id: 'cell-8', rowCategory: 'POLICIES', colIndex: 1, severityColor: 'bg-[#ffb4ab]', label: 'Expired Conditional Access', riskScore: 82, affectedCount: 4 },
  { id: 'cell-9', rowCategory: 'POLICIES', colIndex: 2, severityColor: 'bg-[#a0c9ff]', label: 'Unenforced Device Compliance', riskScore: 58, affectedCount: 47 },
  { id: 'cell-10', rowCategory: 'POLICIES', colIndex: 3, severityColor: 'bg-[#5a3289]', label: 'Missing Sensitivity Policies', riskScore: 68, affectedCount: 112 },
  { id: 'cell-11', rowCategory: 'POLICIES', colIndex: 4, severityColor: 'bg-[#c8c6c5]', label: 'Unsynchronized Retention Rules', riskScore: 29, affectedCount: 15 },
  { id: 'cell-12', rowCategory: 'POLICIES', colIndex: 5, severityColor: 'bg-[#93000a]', label: 'Global Anonymous Sharing', riskScore: 89, affectedCount: 2 },

  // Row 3: DRIFT
  { id: 'cell-13', rowCategory: 'DRIFT', colIndex: 0, severityColor: 'bg-[#dab9ff]', label: 'Unlabeled SharePoint Repos', riskScore: 61, affectedCount: 88 },
  { id: 'cell-14', rowCategory: 'DRIFT', colIndex: 1, severityColor: 'bg-[#a0c9ff]', label: 'Orphaned Power Automate Flows', riskScore: 40, affectedCount: 34 },
  { id: 'cell-15', rowCategory: 'DRIFT', colIndex: 2, severityColor: 'bg-[#ffb4ab]', label: 'Copilot Vector Exposure', riskScore: 85, affectedCount: 340 },
  { id: 'cell-16', rowCategory: 'DRIFT', colIndex: 3, severityColor: 'bg-[#479ef5]', label: 'Tenant Configuration Drift', riskScore: 49, affectedCount: 7 },
  { id: 'cell-17', rowCategory: 'DRIFT', colIndex: 4, severityColor: 'bg-[#8a919d]', label: 'Outdated Hybrid Connectors', riskScore: 32, affectedCount: 3 },
  { id: 'cell-18', rowCategory: 'DRIFT', colIndex: 5, severityColor: 'bg-[#93000a]', label: 'Unused Security Group Nesting', riskScore: 76, affectedCount: 62 },
];

export const COST_EFFICIENCY_ITEMS: CostBreakdownItem[] = [
  { label: 'Licensing Waste', amount: 42000, percentage: 75, color: '#a0c9ff' },
  { label: 'Automation Savings', amount: 12000, percentage: 45, color: '#dab9ff' },
  { label: 'Risk Avoidance', amount: 88000, percentage: 90, color: '#c8c6c5' },
];

export const SECURITY_TRENDS: SecurityTrendPoint[] = [
  { label: 'Mon', alerts: 40, riskyUsers: 25, privSignIns: 15 },
  { label: 'Tue', alerts: 60, riskyUsers: 30, privSignIns: 20 },
  { label: 'Wed', alerts: 35, riskyUsers: 20, privSignIns: 18 },
  { label: 'Thu', alerts: 70, riskyUsers: 45, privSignIns: 25 },
  { label: 'Fri', alerts: 45, riskyUsers: 28, privSignIns: 19 },
  { label: 'Sat', alerts: 80, riskyUsers: 50, privSignIns: 32 },
  { label: 'Sun', alerts: 55, riskyUsers: 35, privSignIns: 22 },
  { label: 'Today', alerts: 90, riskyUsers: 58, privSignIns: 38 },
];

export const ADOPTION_METRICS: AdoptionMetricItem[] = [
  { id: 'teams', name: 'Teams Engagement', percentage: 92, icon: 'MessageSquare', color: '#479ef5' },
  { id: 'collab', name: 'Collab Density', percentage: 64, icon: 'Share2', color: '#dab9ff' },
  { id: 'copilot', name: 'Copilot Usage', percentage: 41, icon: 'Rocket', color: '#a0c9ff' },
];
