import type { MetricDef, SmartBands } from "./types";

/**
 * Metric registry — one entry per real data source in the platform, sourced
 * from `full-data-catalog-chart-mapping.md` at the repo root. Every catalog row
 * that maps to a real, definable metric is encoded here.
 *
 * Namespacing: `key` is prefixed by the catalog's domain grouping
 * (identity, governance, security, compliance, collaboration, licensing,
 * intune, drift, dynamics, powerPlatform, copilot, usage, platform, workflow,
 * engine, alerts, health, projects, sla, financial, offers, packages, ai,
 * portalWf, diagnostics, benchmark, serviceHealth).
 *
 * `[BOTH]` catalog rows are encoded as `scope: "customer"` per the task spec —
 * the MSP aggregate is a rollup computed later, not a separate metric.
 *
 * Smart eligibility: set true only for metrics with a clear "better direction"
 * and a sensible target — security/compliance coverage metrics. Raw counts,
 * revenue, and inventory are not smart-eligible.
 *
 * ── `sourceKey` IS A CLAIM ABOUT THE LIVE `monitor_checks` TABLE ─────────────
 * A `monitor_profile` metric's `sourceKey` names a real row in `monitor_checks`.
 * That table is DATA, not code (see monitor-check-endpoints-are-data), so a
 * sourceKey written here is a hand-made assertion that rots silently: a key that
 * names no catalog row resolves to `unknown_check_key`, which every consumer
 * renders as an empty cell — indistinguishable from a tenant that simply has not
 * collected the check. Two audits have now found phantom keys this way
 * (`identity:high-risk-signins` and `cost:license-waste-estimate`, 2026-07-26),
 * and the third (2026-08-05, #441) found an entire phantom DOMAIN: `usage:*`.
 *
 * `usage:` is not a real check-key domain. It never was. Fourteen entries below
 * named twelve `usage:*` keys, and the customer-facing Copilot Readiness Report
 * printed four of them verbatim to a paying customer as "not wired to a check in
 * the catalogue". The real per-workload activity checks in the catalog are
 * `adoption:teams-activity-trend`, `adoption:sharepoint-onedrive-trend`,
 * `adoption:email-activity-trend` and `adoption:overall-active-rate` — but every
 * one of them is a per-USER (or per-SITE) Graph usage-report detail endpoint, so
 * re-pointing these metrics at them would take `_itemCount` and render the whole
 * licensed-user roster under a caption that says "active users". That is the
 * exact #333 trap, and it is why the entries below were retired to the
 * `not_collected:` sentinel rather than repointed: the platform genuinely does
 * not collect a per-workload active-user COUNT today, and saying so is honest
 * where a near-miss key would not be. Producing one is a check + mapping change
 * (DB-resident), not a registry edit.
 *
 * Guarded from here on by `registry-source-key-contract.test.ts` in api-server,
 * which fails on any sourceKey outside the real domain vocabulary or on the
 * dated list of keys a live audit has confirmed absent.
 */

/** Coverage metrics we want at/above the target (e.g. 100% MFA). */
const COVERAGE_UP_BANDS: SmartBands = {
  critical: 50,
  needsImprovement: 80,
  acceptable: 95,
};

/**
 * Risk-count metrics where lower is better and the target is 0. Bands are
 * expressed as counts: at/below `acceptable` is good, above `critical` is bad.
 */
const RISK_COUNT_BANDS: SmartBands = {
  critical: 10,
  needsImprovement: 5,
  acceptable: 1,
};

export const DASHBOARD_METRICS: MetricDef[] = [
  // =========================================================================
  // PART 1 — M365 Monitor Check Catalog (per-tenant Graph data, sourceType: monitor_profile)
  // =========================================================================

  // ---- Identity & Access -------------------------------------------------
  {
    key: "identity.mfaRegisteredCount",
    label: "MFA Registered Users",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:mfa-registration",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "identity.legacyAuthCount",
    label: "Legacy Auth Usage",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "identity:legacy-auth-usage",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "identity.passwordlessUserCount",
    label: "Passwordless Adoption",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:passwordless-adoption",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "identity.disabledAccountCount",
    label: "Disabled Accounts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:disabled-accounts",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "identity.staleAccountCount",
    label: "Stale Accounts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:stale-accounts",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "identity.failedSigninCount",
    label: "Failed Sign-ins",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    // Git #1110: `identity:failed-signins` names no row in the live
    // monitor_checks catalog (confirmed 2026-08-17 via a live query of all
    // check keys — only `identity:risky-signins` and `identity:signin-risk-
    // policy` exist under `identity:*signin*`). No dedicated failed-signin-
    // count check exists today, and `identity:risky-signins` is a distinct
    // already-curated metric (identity.highRiskSigninCount), so not a
    // genuine match. Same phantom-sourceKey class as #1103; retired to the
    // honest not_collected: sentinel rather than guessed at a near-miss key.
    sourceKey: "not_collected:failed-signins",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "identity.impossibleTravelCount",
    label: "Impossible Travel Events",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    // #1103: `identity:impossible-travel` names no row in the live monitor_checks
    // catalog (confirmed 2026-08-17) — no impossible-travel detection check
    // exists at all today. Retired to the honest not_collected: sentinel rather
    // than guessed at a near-miss key.
    sourceKey: "not_collected:impossible-travel",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    // Global Admin sprawl — the identity:global-admin-count check counts real
    // Global Administrator role holders. Not smart-eligible: the healthy target
    // is a small non-zero band (2–4 with break-glass), not 0, so the shared
    // RISK_COUNT_BANDS "target 0" semantics would mis-grade it.
    key: "identity.globalAdminCount",
    label: "Global Administrators",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:global-admin-count",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    // Standing (permanent, non-PIM-eligible) privileged role assignments from
    // the identity:pim-permanent-roles check. NOTE: this check currently needs
    // a Graph scope the multi-tenant app doesn't have yet (known, backlogged) —
    // until then it resolves not_available/no_data, which consumers must
    // surface honestly rather than fabricate around.
    key: "identity.pimPermanentRoleCount",
    label: "Standing Privileged Roles",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:pim-permanent-roles",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "identity.riskyUserCount",
    label: "Risky Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "identity:risky-users",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "identity.highRiskSigninCount",
    label: "High-Risk Sign-ins",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    // The real catalog check is `identity:risky-signins` — it is the key
    // curated into core:security-baseline (2026-07-21-repopulate-monitoring-
    // package-checks.sql, whose keys were each verified present + active in the
    // live monitor_checks catalog). `identity:high-risk-signins` appeared
    // nowhere else in the repo — no migration ever created it — so this metric
    // could never resolve. A phantom sourceKey now reports `unknown_check_key`
    // rather than looking like an empty tenant (see dashboard-resolvers.ts).
    sourceKey: "identity:risky-signins",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "identity.signinActivity",
    label: "Sign-in Activity (day × hour)",
    valueType: "time-series",
    shape: "heatmap",
    sourceType: "monitor_profile",
    sourceKey: "audit:signins",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "identity.caFailureCount",
    label: "Conditional Access Failures",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    // #1103: `security:conditional-access-failures` names no row in the live
    // monitor_checks catalog (confirmed 2026-08-17). The real CA checks
    // (identity:ca-report-only, identity:ca-policy-count, identity:ca-legacy-
    // auth-block, identity:ca-mfa-coverage, identity:ca-device-compliance) are
    // policy-state snapshots, not a "failures" count — no genuine match.
    sourceKey: "not_collected:conditional-access-failures",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "identity.provisioningEventCount",
    label: "Provisioning Events",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "audit:provisioning",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "identity.privilegedRoleChangeCount",
    label: "Privileged Role Changes",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    // #1103: `audit:directory-role-changes` names no row in the live
    // monitor_checks catalog (confirmed 2026-08-17) — `audit:` is not a real
    // check-key domain at all. `identity:pim-permanent-roles` is a point-in-time
    // count of permanent role assignments, not a role-CHANGE event list, so it
    // is not a genuine match either.
    sourceKey: "not_collected:privileged-role-changes",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "identity.changeEventCount",
    label: "Directory Change Events",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "audit:directory-audits",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Identity Governance ----------------------------------------------
  {
    // #1119: real, catalogued scoring signal (signal.governance.ownerless-groups
    // in docs/signals.json) that had never been registered as a dashboard
    // metric, hence the raw ownerlessGroupCount property name being visible
    // wherever Shane was seeing it.
    key: "governance.ownerlessGroupCount",
    label: "Ownerless Groups",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "governance:ownerless-groups",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1117: genuinely new check -- governance:public-groups-discoverable
    // ships alongside this entry (2026-08-17-governance-public-groups-1117.sql).
    key: "governance.publicGroupCount",
    label: "Public Groups",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "governance:public-groups-discoverable",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    // #1117: check itself shipped by #396 (2026-08-12-public-teams-
    // discoverability-396.sql) but was deliberately left unwired to the
    // metric registry as that migration's own follow-up scope -- this is
    // that follow-up.
    key: "governance.publicTeamCount",
    label: "Public Teams",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "governance:public-teams-discoverable",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    // #1123 -- `governance:access-review-drift` names no row in the live
    // monitor_checks catalog (confirmed 2026-08-18): 13 real `governance:*`
    // keys exist, none matching. Nearest real key is
    // `governance:access-review-completion` ("Access Review Completion
    // Rate"), a different concept, not a genuine match. Same phantom-
    // sourceKey class as #1103/#1110; retired to the honest not_collected:
    // sentinel rather than repointed at a near-miss key.
    key: "governance.accessReviewDriftCount",
    label: "Access Review Drift",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:access-review-drift",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "governance.overdueAccessReviewCount",
    label: "Overdue Access Reviews",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "governance:overdue-access-reviews",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1122 -- appgov:cert-secret-expiration (fixed by #541) already fires
    // live warnings but had no dashboard-registry metric at all. Metric key
    // leaf mirrors the check's own mapping targetField
    // (expiredPasswordCredentialCount) exactly, so pickMappedValueField's
    // token-overlap match (dashboard-resolvers.ts) picks it unambiguously
    // over the check's other three targetFields (passwordCredentialCount,
    // keyCredentialCount, expiredKeyCredentialCount).
    key: "governance.expiredPasswordCredentialCount",
    label: "Expired App Secrets",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "appgov:cert-secret-expiration",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1122 -- same check as governance.expiredPasswordCredentialCount above,
    // the certificate (keyCredentials) half of the same live-firing check.
    key: "governance.expiredKeyCredentialCount",
    label: "Expired App Certificates",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "appgov:cert-secret-expiration",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1122 -- appgov:stale-app-registrations (age-based per #551) had no
    // dashboard-registry metric either. Key mirrors the check's real
    // targetField exactly (appRegistrationsOver180dCount) for the same
    // unambiguous-match reason as the two credential metrics above.
    key: "governance.appRegistrationsOver180dCount",
    label: "App Registrations Over 180 Days",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "appgov:stale-app-registrations",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1122 -- same check as governance.appRegistrationsOver180dCount above,
    // the over-365-day (critical) band of the same age-based check.
    key: "governance.appRegistrationsOver365dCount",
    label: "App Registrations Over 365 Days",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "appgov:stale-app-registrations",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // Git #1233 -- portal-v2 Security's "OAuth Apps & Consent Grants" evidence
    // drill-down (`secEvidenceData.ts`) hardcoded its "Enterprise apps" stat
    // card at 148. appgov:enterprise-app-count is a real, live check --
    // confirmed against monitor_checks (endpoint /servicePrincipals, mapping
    // `count` on `id` -> enterpriseAppCount) -- and had no dashboard-registry
    // metric either, same gap class as #1122's three appgov checks above.
    key: "governance.enterpriseAppCount",
    label: "Enterprise Apps",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "appgov:enterprise-app-count",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    // Git #1233 -- same drill-down's "Tenant-wide consent" stat card
    // (hardcoded 9). appgov:risky-permission-grants' riskyPermissionGrantCount
    // targetField is a real, confirmed-correct split on oauth2PermissionGrants'
    // consentType == 'AllPrincipals' (see #551 Phase 3 migration,
    // 2026-08-08-unreviewed-consents-risky-grants-consenttype-551.sql) -- not
    // the same bare item-count bug #551 fixed on this check.
    key: "governance.riskyPermissionGrantCount",
    label: "Tenant-Wide OAuth Consent Grants",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "appgov:risky-permission-grants",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1260 -- governance:empty-security-groups' emptySecurityGroupCount
    // targetField. countEmptyArray on GET /groups?$expand=members(...),
    // filtered to securityEnabled/not-mailEnabled so this counts pure
    // security groups only.
    key: "governance.emptySecurityGroupCount",
    label: "Empty Security Groups",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "governance:empty-security-groups",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1260 -- appgov:dormant-service-principals' dormantServicePrincipalCount
    // targetField. NOT a sign-in-activity signal -- servicePrincipal has none
    // in v1.0 (no signInActivity, no createdDateTime either). countEmptyArray
    // on $expand=appRoleAssignedTo: a service principal nothing is provisioned
    // to use. See the migration file's own HONESTY NOTE
    // (2026-08-24-health-object-inventory-4-missing-checks-1260.sql) before
    // wiring this to any "no sign-in" UI copy.
    key: "governance.dormantServicePrincipalCount",
    label: "Service Principals With No Assigned Access",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "appgov:dormant-service-principals",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  // ---- Security & Defender ----------------------------------------------
  {
    key: "security.activeAlertCount",
    label: "Active Alerts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:active-alerts",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "security.highSeverityAlertCount",
    label: "High-Severity Alerts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:high-severity-alerts",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "security.malwareAlertCount",
    label: "Malware Alerts",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "security:malware-alerts",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "security.phishingAlertCount",
    label: "Phishing Alerts",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "security:phishing-alerts",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "security.insiderRiskAlertCount",
    label: "Insider Risk Management Alerts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:insider-risk-alerts",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "security.alertsBySeverity",
    label: "Alerts by Severity",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "security:active-alerts",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "security.riskDetectionCount",
    label: "Risk Detections by Type",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "security:risk-detections",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "security.failedSimulationCount",
    label: "Failed Attack Simulations",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:attack-simulation",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "security.secureScore",
    label: "Secure Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:secure-score",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "security.secureScoreControls",
    label: "Secure Score by Control Category",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "security:secure-score-controls",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "security.secureScoreDriftCount",
    label: "Secure Score Drift",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:secure-score-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "security.lowScoreControlCount",
    label: "Low-Score Controls",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    // #1103: `security:low-score-controls` names no row in the live
    // monitor_checks catalog (confirmed 2026-08-17). `security:secure-score-by-
    // category` is the nearest real check, but it returns a per-category
    // breakdown distribution (secureScoreByCategory), not a pre-computed COUNT
    // of controls below a threshold — deriving that count would be a new
    // aggregation, not a rename, so not repointed on a guess.
    sourceKey: "not_collected:low-score-controls",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    // Git #1258 -- exchange:dkim-spf-dmarc-status is a real, live DNS check
    // (`runDnsCheck`, 2026-08-06-dns-executor-dkim-spf-dmarc-496.sql) but its
    // mapping carries three booleans (spfConfigured/dmarcConfigured/
    // dkimConfiguredAtDefaultSelectors) plus record strings -- no numeric
    // targetField for pickMappedValueField to pick, so this can't resolve as a
    // plain scalar the way #1117's governance checks do. `needs_aggregation`
    // + a resolveMonitorAggregation case (dashboard-resolvers.ts) counts how
    // many of the three protocols are NOT configured -- exactly the "N open
    // findings" claim the Security page's Email Security card already makes.
    key: "security.emailAuthFindingCount",
    label: "Email Authentication Findings",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "exchange:dkim-spf-dmarc-status",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },

  // ---- Compliance & Governance ------------------------------------------
  {
    key: "compliance.dlpIncidentCount",
    label: "DLP Incidents",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "compliance:dlp-incidents",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.weakDlpPolicyCount",
    label: "Weak DLP Policies",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:weak-dlp-policies",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.activeEdiscoveryCount",
    label: "Active eDiscovery Cases",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:active-ediscovery",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.labelErrorCount",
    label: "Sensitivity Label Errors",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:label-errors",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.labelPolicyDriftCount",
    label: "Label Policy Drift",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    // #1103: `compliance:label-policy-drift` names no row in the live
    // monitor_checks catalog (confirmed 2026-08-17). `compliance:label-errors`
    // is a distinct real check already curated onto compliance.labelErrorCount
    // above — it counts label DISTRIBUTION failures, not policy drift — so it
    // is not a genuine match for this metric.
    sourceKey: "not_collected:label-policy-drift",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "compliance.retentionDriftCount",
    label: "Retention Policy Drift",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    // #1103: `compliance:retention-drift` names no row in the live
    // monitor_checks catalog (confirmed 2026-08-17). `governance:retention-
    // policy-coverage` is the nearest real check, but it reports workload
    // COVERAGE percentage, not policy drift/changes — not a genuine match.
    sourceKey: "not_collected:retention-drift",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "compliance.missingRetentionTagCount",
    label: "Missing Retention Tags",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:missing-retention-tags",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.missingLabelCount",
    label: "Missing Sensitivity Labels",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:missing-labels",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.guestUserCount",
    label: "Guest Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "compliance:guest-users",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.externalInviteCount",
    label: "External Invites",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "compliance:external-invites",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.orphanedSiteCount",
    label: "Orphaned SharePoint Sites",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:orphaned-sites",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.orphanedTeamCount",
    label: "Orphaned Teams",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:orphaned-teams",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.sharePointSiteCount",
    label: "SharePoint Sites",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:sharepoint-sites",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.oversharedSiteCount",
    label: "Overshared Sites",
    valueType: "count",
    shape: "scalar",
    denominatorMetric: "compliance.sharePointSiteCount",
    sourceType: "monitor_profile",
    sourceKey: "compliance:overshared-sites",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1117: check itself shipped by #357 (2026-08-03-sharepoint-per-site-
    // eeeu-enumeration-357.sql) but that migration's own FOLLOW-UP section
    // explicitly deferred "a metric-registry entry pointing a metric at
    // sourceKey compliance:eeeu-site-sharing" as separate scope -- this is
    // that follow-up. Note compliance.oversharedSiteCount above is UNCHANGED
    // and still points at the older tenant-aggregate compliance:overshared-
    // sites check, per #357's explicit "not a rewrite" decision.
    key: "compliance.eeeuSiteCount",
    label: "SharePoint EEEU Sharing",
    valueType: "count",
    shape: "scalar",
    denominatorMetric: "compliance.sharePointSiteCount",
    sourceType: "monitor_profile",
    sourceKey: "compliance:eeeu-site-sharing",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.publicChannelCount",
    label: "Public Channels",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:public-channels",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.oneDriveExternalCount",
    label: "OneDrive External Shares",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "compliance:onedrive-external",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Collaboration & Exchange -----------------------------------------
  {
    key: "collaboration.mailboxCount",
    label: "Mailboxes",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:mailboxes",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.forwardingMailboxCount",
    label: "External Auto-Forwarding Mailboxes",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:forwarding-mailboxes",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "collaboration.inboxRuleCount",
    label: "Inbox Rules",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:inbox-rules",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.delegationGrantCount",
    label: "Mailbox Delegation Grants",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:delegation-grants",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.sharedMailboxSigninEnabledCount",
    label: "Shared Mailboxes with Sign-in Enabled",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:shared-mailbox-signin",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "collaboration.teamsChannelCount",
    label: "Teams Channels",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:teams-channels",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  // The six entries below named `usage:*` keys that do not exist in
  // monitor_checks (#441 — see the header). Retired to the `not_collected:`
  // sentinel, which is the registry's own existing idiom for "no producer
  // exists yet", rather than repointed at a near-miss `adoption:*` check whose
  // item count means something else entirely.
  {
    key: "collaboration.fileActivity",
    label: "File Activity (day × hour)",
    valueType: "time-series",
    shape: "heatmap",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:onedrive-file-activity",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "collaboration.activeEmailUserCount",
    label: "Active Email Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:active-email-users",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "collaboration.activeTeamsUserCount",
    label: "Active Teams Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:active-teams-users",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "collaboration.activeSharePointUserCount",
    label: "Active SharePoint Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:active-sharepoint-users",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "collaboration.activeOneDriveUserCount",
    label: "Active OneDrive Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:active-onedrive-users",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "collaboration.meetingsOrganized",
    label: "Meetings Organized",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:meetings-organized",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },

  // ---- Licensing & Cost -------------------------------------------------
  {
    key: "licensing.skuBreakdown",
    label: "License SKU Breakdown",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "licensing:sku-utilization",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "licensing.wasteEstimateBreakdown",
    label: "License Waste by SKU ($/mo)",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "cost:license-waste-estimate",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "licensing.duplicateLicenseCount",
    label: "Duplicate Licenses",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "licensing:duplicate-assignments",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "licensing.inactiveLicenseCount",
    label: "Inactive Licenses",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "licensing:inactive-user-licenses",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "licensing.copilotLicenseBreakdown",
    label: "Copilot License Breakdown",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "copilot:license-readiness",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "licensing.costTrend",
    label: "License Cost & Waste ($)",
    valueType: "currency",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "not_collected:license-cost",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },

  // ---- Intune & Devices -------------------------------------------------
  {
    key: "intune.nonCompliantDeviceCount",
    label: "Non-Compliant Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:non-compliant-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.configDriftCount",
    label: "Device Config Drift",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:config-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "intune.unencryptedDeviceCount",
    label: "Unencrypted Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:unencrypted-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.unenrolledDeviceCount",
    label: "Unenrolled Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:unenrolled-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.jailbrokenDeviceCount",
    label: "Jailbroken Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:jailbroken-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.rootedDeviceCount",
    label: "Rooted Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:rooted-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.highThreatDeviceCount",
    label: "High-Threat Devices",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "intune:high-threat-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.outdatedDeviceCount",
    label: "Outdated OS Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:outdated-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1260 -- devices:stale-duplicate-records' staleDeviceRecordCount
    // targetField. GET /devices' own approximateLastSignInDateTime (a real
    // v1.0 property, unlike application) null-or-90-days-old.
    key: "intune.staleDeviceRecordCount",
    label: "Stale Device Records",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "devices:stale-duplicate-records",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1260 -- same check as intune.staleDeviceRecordCount above, the
    // duplicate-hardware-ID half (countDuplicates on deviceId).
    key: "intune.duplicateDeviceRecordCount",
    label: "Duplicate Device Records",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "devices:stale-duplicate-records",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    // #1260 -- devices:unassigned-intune-profiles' unassignedIntuneProfileCount
    // targetField. countEmptyArray on $expand=assignments -- a profile that
    // targets no device or group.
    key: "intune.unassignedProfileCount",
    label: "Unassigned Intune Profiles",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "devices:unassigned-intune-profiles",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },

  // ---- Configuration Drift (dedicated engine) ---------------------------
  {
    key: "drift.caPolicyDriftCount",
    label: "CA Policy Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:ca-policy",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.directorySettingsDriftCount",
    label: "Directory Settings Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:directory-settings",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.licenseAssignmentDriftCount",
    label: "License Assignment Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:license-assignment",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.mailboxConfigDriftCount",
    label: "Mailbox Config Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:mailbox-config",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.roleAssignmentDriftCount",
    label: "Role Assignment Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:role-assignment",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.securityDefaultsDriftCount",
    label: "Security Defaults Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:security-defaults",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.sharePointAdminDriftCount",
    label: "SharePoint Admin Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:sharepoint-admin",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.teamsPolicyDriftCount",
    label: "Teams Policy Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:teams-policy",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.appConfigDriftCount",
    label: "App Registration Config Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:app-config",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.redirectUriDriftCount",
    label: "Redirect URI Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:redirect-uri",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.secretDriftCount",
    label: "App Secret Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:secret",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.certificateDriftCount",
    label: "Certificate Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:certificate",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.permissionDriftCount",
    label: "Graph Permission Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:permission",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.tenantConfigDriftCount",
    label: "Tenant Baseline Config Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:tenant-config",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Dynamics 365 -----------------------------------------------------
  {
    key: "dynamics.appPermissionCount",
    label: "Dynamics App Permissions",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:app-permissions",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.roleAssignmentCount",
    label: "Dynamics Role Assignments",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:role-assignments",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.permissionGrantCount",
    label: "Dynamics Permission Grants",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:permission-grants",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.appRoleDriftCount",
    label: "Dynamics App Role Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:app-role-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.spDriftCount",
    label: "Dynamics Service Principal Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:sp-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.consentChangeCount",
    label: "Dynamics Consent Changes",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:consent-changes",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.orphanedSpCount",
    label: "Dynamics Orphaned Service Principals",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:orphaned-sps",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },

  // ---- Power Platform ---------------------------------------------------
  {
    key: "powerPlatform.appCount",
    label: "Power Platform Apps",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "power-platform:app-inventory",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "powerPlatform.flowCount",
    label: "Power Platform Flows",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "power-platform:flow-inventory",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Copilot ----------------------------------------------------------
  {
    key: "copilot.overshareExposureCount",
    label: "Copilot Oversharing Exposure",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "copilot:overshare-exposure",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "copilot.usagePerUser",
    label: "Copilot Prompt/Usage per User",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:copilot-usage",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },

  // ---- Usage & Adoption -------------------------------------------------
  // Same retirement as the six `collaboration.*` activity entries above (#441).
  // All eight named `usage:*` keys; the domain does not exist in monitor_checks.
  {
    key: "usage.exchangeUsageCount",
    label: "Exchange Adoption Score",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:exchange-adoption-score",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "usage.sharePointUsageCount",
    label: "SharePoint Adoption Score",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:sharepoint-adoption-score",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "usage.oneDriveUsageCount",
    label: "OneDrive Adoption Score",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:onedrive-adoption-score",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    key: "usage.teamsUsageCount",
    label: "Teams Adoption Score",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:teams-adoption-score",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
  {
    // #1105: `adoption:email-activity-trend` (GET /reports/getEmailActivityUserDetail)
    // was already collecting for every tenant, but its mapping's sourceField
    // ("lastActivityDate") never matched the CSV's real literal header
    // ("Last Activity Date"), so it silently produced 0 on every run since
    // 2026-07-19. Fixed in 2026-08-17-adoption-active-user-counts-1105.sql,
    // which also replaces the blank/non-blank predicate with a real
    // `newerThanDays 7` check (Last Activity Date is NOT period-bounded on
    // these reports, confirmed live). Live-verified non-zero via
    // shaneapp://executeScan against the testbed tenant same session.
    key: "usage.exchangeActiveCount",
    label: "Exchange Active Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "adoption:email-activity-trend",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    // #1105: `adoption:sharepoint-onedrive-trend` (GET /reports/getSharePointSiteUsageDetail)
    // — same mapping-correctness fix as usage.exchangeActiveCount above. Honest
    // caveat kept in the label's real meaning even though not in the string:
    // this endpoint is PER-SITE, not per-user (the check's own name is a
    // misnomer — it has never queried OneDrive), so the number is really
    // "sites with a recently active owner", a proxy for SharePoint adoption
    // rather than a deduplicated user count. Left on this check rather than
    // repointed at the real per-user getSharePointActivityUserDetail endpoint
    // because this check's storage/file-count columns are also consumed by
    // cost tracking elsewhere — see the migration's own header for the full
    // reasoning.
    key: "usage.sharePointActiveCount",
    label: "SharePoint Active Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "adoption:sharepoint-onedrive-trend",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    // #1105: brand-new check (no prior OneDrive active-user coverage existed
    // at all) — `onedrive:active-users`, GET /reports/getOneDriveUsageAccountDetail
    // (period='D7'), countWhere Last Activity Date newerThanDays 7 && not
    // deleted. Distinct from #753's onedrive:sync-errors (same endpoint,
    // period='D30', staleness proxy — different purpose, different check).
    key: "usage.oneDriveActiveCount",
    label: "OneDrive Active Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "onedrive:active-users",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    // #1105: `adoption:teams-activity-trend` (GET /reports/getTeamsUserActivityUserDetail)
    // — same mapping-correctness fix as the siblings above.
    key: "usage.teamsActiveCount",
    label: "Teams Active Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "adoption:teams-activity-trend",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    // #1252: the denominator siblings alongside the 4 active-count metrics
    // above — same checks, same `pickMappedValueField` token-overlap
    // disambiguation (each metric key's own tokens steer it to its matching
    // targetField on a shared check). Lets the Adoption pillar page render a
    // real "N of M" population line instead of a fixture percentage.
    key: "usage.teamsLicensedUserCount",
    label: "Teams Licensed Users Scanned",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "adoption:teams-activity-trend",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "usage.exchangeLicensedUserCount",
    label: "Exchange Licensed Users Scanned",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "adoption:email-activity-trend",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    // Per-SITE, not per-user — same honest caveat as usage.sharePointActiveCount
    // above; this is "sites scanned", not a licensed-user count.
    key: "usage.sharePointSitesScannedCount",
    label: "SharePoint Sites Scanned",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "adoption:sharepoint-onedrive-trend",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "usage.oneDriveAccountsScannedCount",
    label: "OneDrive Accounts Scanned",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "onedrive:active-users",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    // #753/#1114: the stale-sync proxy check — see that migration's own header
    // for why this counts accounts with a blank-or-30+-day-stale "Last Activity
    // Date" as a client-side sync-health PROXY, not a literal sync-error read.
    // Registered here for the first time (#1252) — #753 deliberately left the
    // metric-registry entry as a follow-up, done now.
    key: "usage.oneDriveSyncErrorCount",
    label: "OneDrive Stale Sync Accounts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "onedrive:sync-errors",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Platform/Custom (platform's own health, ops-facing) --------------
  {
    key: "platform.failedEndpointCount",
    label: "Graph API Failed Endpoints",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:graph-failed-endpoints",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.rateLimitEventCount",
    label: "Graph API Rate-Limit Events",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:graph-rate-limits",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.expiringTokenCount",
    label: "Expiring Tokens",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:expiring-tokens",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.dbFailureCount",
    label: "DB Failures",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:db-failures",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.queueDepthCount",
    label: "Queue Depth",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:queue-depth",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.schedulerDelayCount",
    label: "Scheduler Delays",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:scheduler-delays",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.failedServiceCount",
    label: "Failed Services",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:failed-services",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // ---- Workflow Engine (ops/admin) --------------------------------------
  {
    key: "workflow.workflowFailureCount",
    label: "Workflow Failures",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:failures",
    scope: "msp",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "workflow.unhealthyNodeCount",
    label: "Unhealthy Workflow Nodes",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:unhealthy-nodes",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "workflow.highLatencyNodeCount",
    label: "High-Latency Nodes",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:high-latency-nodes",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "workflow.invalidSchemaNodeCount",
    label: "Invalid-Schema Nodes",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:invalid-schema-nodes",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "workflow.nodeTimeoutCount",
    label: "Node Timeouts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:node-timeouts",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "workflow.dependencyFailureCount",
    label: "Dependency Failures",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:dependency-failures",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "workflow.queueBacklogCount",
    label: "Workflow Queue Backlog",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:queue-backlog",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // =========================================================================
  // PART 2 — Platform / Business Data (platform tables + engine snapshots)
  // =========================================================================

  // ---- Engine Scores (tenant_engine_snapshots) --------------------------
  {
    key: "engine.healthScore",
    label: "Health Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "health",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.driftScore",
    label: "Drift Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "drift",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.priorityScore",
    label: "Priority Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "priority",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.forecastingScore",
    label: "Forecasting Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "forecasting",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.securityScore",
    label: "Security Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "security",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.complianceScore",
    label: "Compliance Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "compliance",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.governanceScore",
    label: "Governance Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "governance",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.adoptionScore",
    label: "Adoption Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "adoption",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.copilotScore",
    label: "Copilot Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "copilot",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.crmScore",
    label: "CRM Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "crm",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.mspIntelligenceScore",
    label: "MSP Intelligence Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "msp-intelligence",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.pillarSnapshot",
    label: "Engine Pillar Snapshot",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "engine_snapshot",
    sourceKey: "tenant_engine_snapshots",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "engine.scoreTrend",
    label: "Engine Score Trend",
    valueType: "time-series",
    shape: "trend",
    sourceType: "engine_snapshot",
    sourceKey: "tenant_engine_snapshots",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Alerts (msp_alert_events, msp_alert_rules) -----------------------
  {
    key: "alerts.recentAlerts",
    label: "Recent Alerts",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "platform_table",
    sourceKey: "msp_alert_events",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "alerts.alertVolume",
    label: "Alert Volume Over Time",
    valueType: "time-series",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "msp_alert_events",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "alerts.ruleCoverage",
    label: "Alert Rule Coverage",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "msp_alert_rules",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // ---- Client Health (client_health_history, msp_score_history) ---------
  {
    key: "health.clientHealthHistory",
    label: "Client Health Score History",
    valueType: "time-series",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "client_health_history",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "health.clientHealthHeatmap",
    label: "Client Health Heatmap",
    valueType: "time-series",
    shape: "heatmap",
    sourceType: "platform_table",
    sourceKey: "msp_score_history",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // ---- Projects & Delivery (projects, kanban_tasks, client_services) ----
  {
    key: "projects.activeProjectCount",
    label: "Active Projects",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "projects",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "projects.openTaskCount",
    label: "Open Tasks",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "kanban_tasks",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "projects.projectVelocity",
    label: "Project Velocity",
    valueType: "time-series",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "kanban_tasks",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "projects.tasksByColumn",
    label: "Tasks by Kanban Column",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "kanban_tasks",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- SLA & Scope Creep ------------------------------------------------
  {
    key: "sla.compliancePercent",
    label: "SLA Compliance %",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "sla",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "sla.activeBreachCount",
    label: "Active SLA Breaches",
    valueType: "count",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "sla",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "sla.scopeCreepStatus",
    label: "Scope Creep Status",
    valueType: "categorical",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "scope-creep",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Financial (msp_charges, msp_subscriptions, invoices, msp_sows) ---
  {
    key: "financial.totalRevenue",
    label: "Total Revenue / MRR / ARR",
    valueType: "currency",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "msp_charges",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "financial.outstandingRevenue",
    label: "Outstanding Revenue",
    valueType: "currency",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "invoices",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "financial.revenueByServiceType",
    label: "Revenue by Service Type",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "msp_charges",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "financial.revenueTrend",
    label: "Revenue Trend",
    valueType: "time-series",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "msp_charges",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "financial.pipelineValue",
    label: "Pipeline Value",
    valueType: "currency",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "opportunities",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // ---- Sales Offers (sales_offers, sales_offer_events, msp_sales_offers) -
  {
    key: "offers.activeOfferCount",
    label: "Active Offers",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "sales_offers",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "offers.offerFunnel",
    label: "Offer Funnel (triggered → viewed → accepted)",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "sales_offer_events",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "offers.remediationOffers",
    label: "Remediation Offers",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "platform_table",
    sourceKey: "msp_sales_offers",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Monitoring Packages (monitoring_packages, msp_customers) ---------
  {
    key: "packages.activePackageCount",
    label: "Active Monitoring Packages",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "monitoring_packages",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "packages.packageCoverage",
    label: "Package Coverage Across Book",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "monitoring_packages",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "packages.assessmentCoverage",
    label: "Assessment Coverage",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "msp_customers",
    scope: "msp",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },

  // ---- AI Usage (ai_usage_events, ai_balance_ledger, msp_ai_purchases) --
  {
    key: "ai.tokenBurn",
    label: "AI Token Burn",
    valueType: "time-series",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "ai_usage_events",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "ai.currentBalance",
    label: "AI Balance Remaining",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "ai_balance_ledger",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "ai.costByFeature",
    label: "AI Cost by Feature",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "ai_usage_events",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // ---- Workflow Runs (portal_wf_runs, portal_wf_operator_tasks) ---------
  {
    key: "portalWf.failedWorkflowCount",
    label: "Failed Workflows (recent)",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "portal_wf_runs",
    scope: "msp",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "portalWf.approvalsWaiting",
    label: "Approvals Waiting",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "portal_wf_operator_tasks",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "portalWf.jobQueueDepth",
    label: "Background Job Queue Depth",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "msp_job_queue",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "portalWf.successRate",
    label: "Workflow Success Rate",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "portal_wf_runs",
    scope: "msp",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },

  // ---- Diagnostics (msp_diagnostic_runs, msp_diagnostic_findings) -------
  {
    key: "diagnostics.recentScans",
    label: "Recent Tenant Scans",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "platform_table",
    sourceKey: "msp_diagnostic_runs",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "diagnostics.findingsBySeverity",
    label: "Findings by Severity",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "msp_diagnostic_findings",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Benchmarking (industry_benchmark_reference) ----------------------
  {
    key: "benchmark.scoreVsIndustry",
    label: "Client Score vs. Industry Benchmark",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "industry_benchmark_reference",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },

  // ---- Microsoft Service Health (net-new, not yet collected) ------------
  {
    key: "serviceHealth.uptimeStatus",
    label: "M365 Service Uptime Status",
    valueType: "categorical",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:service-health-overview",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
];
