import type { MetricDef, SmartBands } from "./types";

/**
 * Metric registry — one entry per real data source in the platform, sourced
 * from `full-data-catalog-chart-mapping.md` at the repo root. Every catalog row
 * that maps to a real, definable metric is encoded here.
 *
 * Namespacing: `key` is prefixed by the catalog's domain grouping
 * (identity, governance, security, compliance, collaboration, licensing,
 * intune, drift, dynamics, powerPlatform, copilot, usage, platform, workflow,
 * engine, alerts, health, projects, sla, financial, offers, packages, ai,
 * portalWf, diagnostics, benchmark, serviceHealth).
 *
 * `[BOTH]` catalog rows are encoded as `scope: "customer"` per the task spec —
 * the MSP aggregate is a rollup computed later, not a separate metric.
 *
 * Smart eligibility: set true only for metrics with a clear "better direction"
 * and a sensible target — security/compliance coverage metrics. Raw counts,
 * revenue, and inventory are not smart-eligible.
 */

/** Coverage metrics we want at/above the target (e.g. 100% MFA). */
const COVERAGE_UP_BANDS: SmartBands = {
  critical: 50,
  needsImprovement: 80,
  acceptable: 95,
};

/**
 * Risk-count metrics where lower is better and the target is 0. Bands are
 * expressed as counts: at/below `acceptable` is good, above `critical` is bad.
 */
const RISK_COUNT_BANDS: SmartBands = {
  critical: 10,
  needsImprovement: 5,
  acceptable: 1,
};

export const DASHBOARD_METRICS: MetricDef[] = [
  // =========================================================================
  // PART 1 — M365 Monitor Check Catalog (per-tenant Graph data, sourceType: monitor_profile)
  // =========================================================================

  // ---- Identity & Access -------------------------------------------------
  {
    key: "identity.mfaRegisteredCount",
    label: "MFA Registered Users",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:mfa-registration",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "identity.legacyAuthCount",
    label: "Legacy Auth Usage",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "identity:legacy-auth-usage",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "identity.passwordlessUserCount",
    label: "Passwordless Adoption",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:passwordless-adoption",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "identity.disabledAccountCount",
    label: "Disabled Accounts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:disabled-accounts",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "identity.staleAccountCount",
    label: "Stale Accounts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:stale-accounts",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "identity.failedSigninCount",
    label: "Failed Sign-ins",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "identity:failed-signins",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "identity.impossibleTravelCount",
    label: "Impossible Travel Events",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "identity:impossible-travel",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "identity.riskyUserCount",
    label: "Risky Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "identity:risky-users",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "identity.highRiskSigninCount",
    label: "High-Risk Sign-ins",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "identity:high-risk-signins",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "identity.signinActivity",
    label: "Sign-in Activity (day × hour)",
    valueType: "time-series",
    shape: "heatmap",
    sourceType: "monitor_profile",
    sourceKey: "audit:signins",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "identity.caFailureCount",
    label: "Conditional Access Failures",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "security:conditional-access-failures",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "identity.provisioningEventCount",
    label: "Provisioning Events",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "audit:provisioning",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "identity.privilegedRoleChangeCount",
    label: "Privileged Role Changes",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "audit:directory-role-changes",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "identity.changeEventCount",
    label: "Directory Change Events",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "audit:directory-audits",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Identity Governance ----------------------------------------------
  {
    key: "governance.orphanedAccessPackageCount",
    label: "Orphaned Access Packages",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "governance:orphaned-access-packages",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "governance.accessReviewDriftCount",
    label: "Access Review Drift",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "governance:access-review-drift",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "governance.overdueAccessReviewCount",
    label: "Overdue Access Reviews",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "governance:overdue-access-reviews",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "governance.activeEntitlementAssignmentCount",
    label: "Active Entitlement Assignments",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "governance:active-entitlement-assignments",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "governance.entitlementPolicyDriftCount",
    label: "Entitlement Policy Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "governance:entitlement-policy-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "governance.workflowDriftCount",
    label: "Lifecycle Workflow Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "governance:lifecycle-workflow-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "governance.workflowFailureCount",
    label: "Lifecycle Workflow Failures",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "governance:lifecycle-workflow-failures",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },

  // ---- Security & Defender ----------------------------------------------
  {
    key: "security.activeAlertCount",
    label: "Active Alerts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:active-alerts",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "security.highSeverityAlertCount",
    label: "High-Severity Alerts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:high-severity-alerts",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "security.malwareAlertCount",
    label: "Malware Alerts",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "security:malware-alerts",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "security.phishingAlertCount",
    label: "Phishing Alerts",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "security:phishing-alerts",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "security.insiderRiskAlertCount",
    label: "Insider Risk Management Alerts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:insider-risk-alerts",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "security.alertsBySeverity",
    label: "Alerts by Severity",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "security:active-alerts",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "security.riskDetectionCount",
    label: "Risk Detections by Type",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "security:risk-detections",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "security.failedSimulationCount",
    label: "Failed Attack Simulations",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:attack-simulation",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "security.secureScore",
    label: "Secure Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:secure-score",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "security.secureScoreControls",
    label: "Secure Score by Control Category",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "security:secure-score-controls",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "security.secureScoreDriftCount",
    label: "Secure Score Drift",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:secure-score-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "security.lowScoreControlCount",
    label: "Low-Score Controls",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "security:low-score-controls",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },

  // ---- Compliance & Governance ------------------------------------------
  {
    key: "compliance.dlpIncidentCount",
    label: "DLP Incidents",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "compliance:dlp-incidents",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.weakDlpPolicyCount",
    label: "Weak DLP Policies",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:weak-dlp-policies",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.activeEdiscoveryCount",
    label: "Active eDiscovery Cases",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:active-ediscovery",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.labelErrorCount",
    label: "Sensitivity Label Errors",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:label-errors",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.labelPolicyDriftCount",
    label: "Label Policy Drift",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:label-policy-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.retentionDriftCount",
    label: "Retention Policy Drift",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:retention-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.missingRetentionTagCount",
    label: "Missing Retention Tags",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:missing-retention-tags",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.missingLabelCount",
    label: "Missing Sensitivity Labels",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:missing-labels",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.guestUserCount",
    label: "Guest Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "compliance:guest-users",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.externalInviteCount",
    label: "External Invites",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "compliance:external-invites",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.orphanedSiteCount",
    label: "Orphaned SharePoint Sites",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:orphaned-sites",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.orphanedTeamCount",
    label: "Orphaned Teams",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:orphaned-teams",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.sharePointSiteCount",
    label: "SharePoint Sites",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:sharepoint-sites",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.oversharedSiteCount",
    label: "Overshared Sites",
    valueType: "count",
    shape: "scalar",
    denominatorMetric: "compliance.sharePointSiteCount",
    sourceType: "monitor_profile",
    sourceKey: "compliance:overshared-sites",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "compliance.publicChannelCount",
    label: "Public Channels",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "compliance:public-channels",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "compliance.oneDriveExternalCount",
    label: "OneDrive External Shares",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "compliance:onedrive-external",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Collaboration & Exchange -----------------------------------------
  {
    key: "collaboration.mailboxCount",
    label: "Mailboxes",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:mailboxes",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.forwardingMailboxCount",
    label: "External Auto-Forwarding Mailboxes",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:forwarding-mailboxes",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "collaboration.inboxRuleCount",
    label: "Inbox Rules",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:inbox-rules",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.delegationGrantCount",
    label: "Mailbox Delegation Grants",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:delegation-grants",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.sharedMailboxSigninEnabledCount",
    label: "Shared Mailboxes with Sign-in Enabled",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:shared-mailbox-signin",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "collaboration.teamsChannelCount",
    label: "Teams Channels",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "collaboration:teams-channels",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.fileActivity",
    label: "File Activity (day × hour)",
    valueType: "time-series",
    shape: "heatmap",
    sourceType: "monitor_profile",
    sourceKey: "usage:onedrive-activity",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "collaboration.activeEmailUserCount",
    label: "Active Email Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:email-activity",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.activeTeamsUserCount",
    label: "Active Teams Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:teams-activity",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.activeSharePointUserCount",
    label: "Active SharePoint Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:sharepoint-activity",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.activeOneDriveUserCount",
    label: "Active OneDrive Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:onedrive-activity",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "collaboration.meetingsOrganized",
    label: "Meetings Organized",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:teams-activity",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },

  // ---- Licensing & Cost -------------------------------------------------
  {
    key: "licensing.skuBreakdown",
    label: "License SKU Breakdown",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "licensing:sku-utilization",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "licensing.wasteEstimateBreakdown",
    label: "License Waste by SKU ($/mo)",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "cost:license-waste-estimate",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },
  {
    key: "licensing.duplicateLicenseCount",
    label: "Duplicate Licenses",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "licensing:duplicate-assignments",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "licensing.inactiveLicenseCount",
    label: "Inactive Licenses",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "licensing:inactive-user-licenses",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "licensing.copilotLicenseBreakdown",
    label: "Copilot License Breakdown",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "monitor_profile",
    sourceKey: "copilot:license-readiness",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "licensing.costTrend",
    label: "License Cost & Waste ($)",
    valueType: "currency",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "not_collected:license-cost",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },

  // ---- Intune & Devices -------------------------------------------------
  {
    key: "intune.nonCompliantDeviceCount",
    label: "Non-Compliant Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:non-compliant-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.configDriftCount",
    label: "Device Config Drift",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:config-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "intune.unencryptedDeviceCount",
    label: "Unencrypted Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:unencrypted-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.unenrolledDeviceCount",
    label: "Unenrolled Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:unenrolled-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.jailbrokenDeviceCount",
    label: "Jailbroken Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:jailbroken-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.rootedDeviceCount",
    label: "Rooted Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:rooted-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.highThreatDeviceCount",
    label: "High-Threat Devices",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "intune:high-threat-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "intune.outdatedDeviceCount",
    label: "Outdated OS Devices",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "intune:outdated-devices",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },

  // ---- Configuration Drift (dedicated engine) ---------------------------
  {
    key: "drift.caPolicyDriftCount",
    label: "CA Policy Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:ca-policy",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.directorySettingsDriftCount",
    label: "Directory Settings Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:directory-settings",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.licenseAssignmentDriftCount",
    label: "License Assignment Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:license-assignment",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.mailboxConfigDriftCount",
    label: "Mailbox Config Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:mailbox-config",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.roleAssignmentDriftCount",
    label: "Role Assignment Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:role-assignment",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.securityDefaultsDriftCount",
    label: "Security Defaults Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:security-defaults",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.sharePointAdminDriftCount",
    label: "SharePoint Admin Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:sharepoint-admin",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.teamsPolicyDriftCount",
    label: "Teams Policy Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:teams-policy",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.appConfigDriftCount",
    label: "App Registration Config Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:app-config",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.redirectUriDriftCount",
    label: "Redirect URI Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:redirect-uri",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.secretDriftCount",
    label: "App Secret Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:secret",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.certificateDriftCount",
    label: "Certificate Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:certificate",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.permissionDriftCount",
    label: "Graph Permission Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:permission",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "drift.tenantConfigDriftCount",
    label: "Tenant Baseline Config Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "drift:tenant-config",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Dynamics 365 -----------------------------------------------------
  {
    key: "dynamics.appPermissionCount",
    label: "Dynamics App Permissions",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:app-permissions",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.roleAssignmentCount",
    label: "Dynamics Role Assignments",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:role-assignments",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.permissionGrantCount",
    label: "Dynamics Permission Grants",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:permission-grants",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.appRoleDriftCount",
    label: "Dynamics App Role Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:app-role-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.spDriftCount",
    label: "Dynamics Service Principal Drift",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:sp-drift",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.consentChangeCount",
    label: "Dynamics Consent Changes",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:consent-changes",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "dynamics.orphanedSpCount",
    label: "Dynamics Orphaned Service Principals",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "dynamics:orphaned-sps",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },

  // ---- Power Platform ---------------------------------------------------
  {
    key: "powerPlatform.appCount",
    label: "Power Platform Apps",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "power-platform:app-inventory",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "powerPlatform.flowCount",
    label: "Power Platform Flows",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "power-platform:flow-inventory",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Copilot ----------------------------------------------------------
  {
    key: "copilot.overshareExposureCount",
    label: "Copilot Oversharing Exposure",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "copilot:overshare-exposure",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "copilot.usagePerUser",
    label: "Copilot Prompt/Usage per User",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:copilot-usage",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },

  // ---- Usage & Adoption -------------------------------------------------
  {
    key: "usage.exchangeUsageCount",
    label: "Exchange Adoption Score",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:exchange-adoption",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "usage.sharePointUsageCount",
    label: "SharePoint Adoption Score",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:sharepoint-adoption",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "usage.oneDriveUsageCount",
    label: "OneDrive Adoption Score",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:onedrive-adoption",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "usage.teamsUsageCount",
    label: "Teams Adoption Score",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:teams-adoption",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "usage.exchangeActiveCount",
    label: "Exchange Active Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:exchange-active",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "usage.sharePointActiveCount",
    label: "SharePoint Active Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:sharepoint-active",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "usage.oneDriveActiveCount",
    label: "OneDrive Active Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:onedrive-active",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "usage.teamsActiveCount",
    label: "Teams Active Users",
    valueType: "count",
    shape: "trend",
    sourceType: "monitor_profile",
    sourceKey: "usage:teams-active",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Platform/Custom (platform's own health, ops-facing) --------------
  {
    key: "platform.failedEndpointCount",
    label: "Graph API Failed Endpoints",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:graph-failed-endpoints",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.rateLimitEventCount",
    label: "Graph API Rate-Limit Events",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:graph-rate-limits",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.expiringTokenCount",
    label: "Expiring Tokens",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:expiring-tokens",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.dbFailureCount",
    label: "DB Failures",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:db-failures",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.queueDepthCount",
    label: "Queue Depth",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:queue-depth",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.schedulerDelayCount",
    label: "Scheduler Delays",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:scheduler-delays",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "platform.failedServiceCount",
    label: "Failed Services",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "platform:failed-services",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // ---- Workflow Engine (ops/admin) --------------------------------------
  {
    key: "workflow.workflowFailureCount",
    label: "Workflow Failures",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:failures",
    scope: "msp",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "workflow.unhealthyNodeCount",
    label: "Unhealthy Workflow Nodes",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:unhealthy-nodes",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "workflow.highLatencyNodeCount",
    label: "High-Latency Nodes",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:high-latency-nodes",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "workflow.invalidSchemaNodeCount",
    label: "Invalid-Schema Nodes",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:invalid-schema-nodes",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "workflow.nodeTimeoutCount",
    label: "Node Timeouts",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:node-timeouts",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "workflow.dependencyFailureCount",
    label: "Dependency Failures",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:dependency-failures",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "workflow.queueBacklogCount",
    label: "Workflow Queue Backlog",
    valueType: "count",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "workflow:queue-backlog",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // =========================================================================
  // PART 2 — Platform / Business Data (platform tables + engine snapshots)
  // =========================================================================

  // ---- Engine Scores (tenant_engine_snapshots) --------------------------
  {
    key: "engine.healthScore",
    label: "Health Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "health",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.driftScore",
    label: "Drift Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "drift",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.priorityScore",
    label: "Priority Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "priority",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.forecastingScore",
    label: "Forecasting Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "forecasting",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.securityScore",
    label: "Security Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "security",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.complianceScore",
    label: "Compliance Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "compliance",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.governanceScore",
    label: "Governance Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "governance",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.adoptionScore",
    label: "Adoption Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "adoption",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.copilotScore",
    label: "Copilot Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "copilot",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.crmScore",
    label: "CRM Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "crm",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.mspIntelligenceScore",
    label: "MSP Intelligence Engine Score",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "msp-intelligence",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "engine.pillarSnapshot",
    label: "Engine Pillar Snapshot",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "engine_snapshot",
    sourceKey: "tenant_engine_snapshots",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "engine.scoreTrend",
    label: "Engine Score Trend",
    valueType: "time-series",
    shape: "trend",
    sourceType: "engine_snapshot",
    sourceKey: "tenant_engine_snapshots",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Alerts (msp_alert_events, msp_alert_rules) -----------------------
  {
    key: "alerts.recentAlerts",
    label: "Recent Alerts",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "platform_table",
    sourceKey: "msp_alert_events",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "alerts.alertVolume",
    label: "Alert Volume Over Time",
    valueType: "time-series",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "msp_alert_events",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "alerts.ruleCoverage",
    label: "Alert Rule Coverage",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "msp_alert_rules",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // ---- Client Health (client_health_history, msp_score_history) ---------
  {
    key: "health.clientHealthHistory",
    label: "Client Health Score History",
    valueType: "time-series",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "client_health_history",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "health.clientHealthHeatmap",
    label: "Client Health Heatmap",
    valueType: "time-series",
    shape: "heatmap",
    sourceType: "platform_table",
    sourceKey: "msp_score_history",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // ---- Projects & Delivery (projects, kanban_tasks, client_services) ----
  {
    key: "projects.activeProjectCount",
    label: "Active Projects",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "projects",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "projects.openTaskCount",
    label: "Open Tasks",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "kanban_tasks",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "projects.projectVelocity",
    label: "Project Velocity",
    valueType: "time-series",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "kanban_tasks",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "projects.tasksByColumn",
    label: "Tasks by Kanban Column",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "kanban_tasks",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- SLA & Scope Creep ------------------------------------------------
  {
    key: "sla.compliancePercent",
    label: "SLA Compliance %",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "sla",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },
  {
    key: "sla.activeBreachCount",
    label: "Active SLA Breaches",
    valueType: "count",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "sla",
    scope: "customer",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "sla.scopeCreepStatus",
    label: "Scope Creep Status",
    valueType: "categorical",
    shape: "scalar",
    sourceType: "engine_snapshot",
    sourceKey: "scope-creep",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Financial (msp_charges, msp_subscriptions, invoices, msp_sows) ---
  {
    key: "financial.totalRevenue",
    label: "Total Revenue / MRR / ARR",
    valueType: "currency",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "msp_charges",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "financial.outstandingRevenue",
    label: "Outstanding Revenue",
    valueType: "currency",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "invoices",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "financial.revenueByServiceType",
    label: "Revenue by Service Type",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "msp_charges",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "financial.revenueTrend",
    label: "Revenue Trend",
    valueType: "time-series",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "msp_charges",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "financial.pipelineValue",
    label: "Pipeline Value",
    valueType: "currency",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "opportunities",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // ---- Sales Offers (sales_offers, sales_offer_events, msp_sales_offers) -
  {
    key: "offers.activeOfferCount",
    label: "Active Offers",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "sales_offers",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "offers.offerFunnel",
    label: "Offer Funnel (triggered → viewed → accepted)",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "sales_offer_events",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "offers.remediationOffers",
    label: "Remediation Offers",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "platform_table",
    sourceKey: "msp_sales_offers",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Monitoring Packages (monitoring_packages, msp_customers) ---------
  {
    key: "packages.activePackageCount",
    label: "Active Monitoring Packages",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "monitoring_packages",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "packages.packageCoverage",
    label: "Package Coverage Across Book",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "monitoring_packages",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "packages.assessmentCoverage",
    label: "Assessment Coverage",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "msp_customers",
    scope: "msp",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },

  // ---- AI Usage (ai_usage_events, ai_balance_ledger, msp_ai_purchases) --
  {
    key: "ai.tokenBurn",
    label: "AI Token Burn",
    valueType: "time-series",
    shape: "trend",
    sourceType: "platform_table",
    sourceKey: "ai_usage_events",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "ai.currentBalance",
    label: "AI Balance Remaining",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "ai_balance_ledger",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "ai.costByFeature",
    label: "AI Cost by Feature",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "ai_usage_events",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },

  // ---- Workflow Runs (portal_wf_runs, portal_wf_operator_tasks) ---------
  {
    key: "portalWf.failedWorkflowCount",
    label: "Failed Workflows (recent)",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "portal_wf_runs",
    scope: "msp",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 0,
    smartBands: RISK_COUNT_BANDS,
  },
  {
    key: "portalWf.approvalsWaiting",
    label: "Approvals Waiting",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "portal_wf_operator_tasks",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "portalWf.jobQueueDepth",
    label: "Background Job Queue Depth",
    valueType: "count",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "msp_job_queue",
    scope: "msp",
    status: "available",
    smartEligible: false,
  },
  {
    key: "portalWf.successRate",
    label: "Workflow Success Rate",
    valueType: "percentage-eligible",
    shape: "scalar",
    sourceType: "platform_table",
    sourceKey: "portal_wf_runs",
    scope: "msp",
    status: "available",
    smartEligible: true,
    smartDefaultTarget: 100,
    smartBands: COVERAGE_UP_BANDS,
  },

  // ---- Diagnostics (msp_diagnostic_runs, msp_diagnostic_findings) -------
  {
    key: "diagnostics.recentScans",
    label: "Recent Tenant Scans",
    valueType: "event-list",
    shape: "timeline",
    sourceType: "platform_table",
    sourceKey: "msp_diagnostic_runs",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },
  {
    key: "diagnostics.findingsBySeverity",
    label: "Findings by Severity",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "msp_diagnostic_findings",
    scope: "customer",
    status: "available",
    smartEligible: false,
  },

  // ---- Benchmarking (industry_benchmark_reference) ----------------------
  {
    key: "benchmark.scoreVsIndustry",
    label: "Client Score vs. Industry Benchmark",
    valueType: "categorical",
    shape: "distribution",
    sourceType: "platform_table",
    sourceKey: "industry_benchmark_reference",
    scope: "customer",
    status: "needs_aggregation",
    smartEligible: false,
  },

  // ---- Microsoft Service Health (net-new, not yet collected) ------------
  {
    key: "serviceHealth.uptimeStatus",
    label: "M365 Service Uptime Status",
    valueType: "categorical",
    shape: "scalar",
    sourceType: "monitor_profile",
    sourceKey: "not_collected:service-health-overview",
    scope: "customer",
    status: "not_collected",
    smartEligible: false,
  },
];
