export type SafetyLevel = 'safe' | 'gated' | 'blocked';

export type M365DomainCategory =
  | 'App Registrations'
  | 'Auth & MFA'
  | 'Conditional Access'
  | 'Devices & Intune'
  | 'Exchange & Mailbox'
  | 'Groups & Distribution'
  | 'Licensing & Billing'
  | 'PIM & Privileged Roles'
  | 'Security & Defender'
  | 'SharePoint & OneDrive'
  | 'Teams & Collaboration'
  | 'Tenant & GDAP'
  | 'Users & Provisioning';

export interface M365ActionItem {
  id: string;
  name: string;
  category: M365DomainCategory;
  description: string;
  safetyLevel: SafetyLevel;
  minTier: 'Business Basic' | 'Business Premium' | 'E3' | 'E5' | 'P2';
  apiEndpoint: string;
  impactAnalysis: string;
  defaultPayloadParams?: Record<string, string>;
  history: {
    executedBy: string;
    timestamp: string;
    ticketId: string;
    status: 'Success' | 'Failed' | 'Pending Approval';
  }[];
}

export const M365_ACTION_REGISTRY: M365ActionItem[] = [
  // 1. App Registrations (6)
  {
    id: 'app-01',
    name: 'Rotate Azure AD Service Principal Secret',
    category: 'App Registrations',
    description: 'Generates new 24-month client secret and soft-deletes expired credentials for MSP automation.',
    safetyLevel: 'gated',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/applications/{id}/addPassword',
    impactAnalysis: 'Automation scripts using old secret will fail until updated with new credential value.',
    history: [
      { executedBy: 'm.vance@msp.com', timestamp: '2 days ago', ticketId: 'INC-8821', status: 'Success' },
      { executedBy: 'secops@msp.com', timestamp: '3 weeks ago', ticketId: 'CHG-4012', status: 'Success' },
    ],
  },
  {
    id: 'app-02',
    name: 'Revoke High-Risk OAuth Application Permissions',
    category: 'App Registrations',
    description: 'Terminates consent grants for unverified 3rd-party OAuth apps requesting offline_access.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/oauth2PermissionGrants/{id}',
    impactAnalysis: 'Users will be required to re-authenticate and request admin consent on next app launch.',
    history: [{ executedBy: 'auto-policy@msp.com', timestamp: '1 day ago', ticketId: 'AUT-102', status: 'Success' }],
  },
  {
    id: 'app-03',
    name: 'Enforce Admin Consent Workflow for API Permissions',
    category: 'App Registrations',
    description: 'Requires Global Admin sign-off for any non-admin requesting tenant-wide Graph API access.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/policies/adminConsentRequestPolicy',
    impactAnalysis: 'End-users can no longer self-consent to 3rd party applications.',
    history: [],
  },
  {
    id: 'app-04',
    name: 'Purge Stale Service Principals (>180 Days Unused)',
    category: 'App Registrations',
    description: 'Deletes enterprise applications with no token issuing activity in the last 180 days.',
    safetyLevel: 'gated',
    minTier: 'E3',
    apiEndpoint: '/v1.0/servicePrincipals/{id}',
    impactAnalysis: 'Permanent removal of enterprise application registrations.',
    history: [],
  },
  {
    id: 'app-05',
    name: 'Configure SAML Single Sign-On Endpoint',
    category: 'App Registrations',
    description: 'Pushes enterprise SSO configuration and X.509 certificate for custom SaaS integration.',
    safetyLevel: 'gated',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/servicePrincipals/{id}/synchronization/jobs',
    impactAnalysis: 'Updates federation metadata for all signed-in users on target enterprise app.',
    history: [{ executedBy: 'b.smith@msp.com', timestamp: '5 days ago', ticketId: 'INC-9012', status: 'Success' }],
  },
  {
    id: 'app-06',
    name: 'Lock Certificate Self-Signing for Non-Admins',
    category: 'App Registrations',
    description: 'Restricts non-administrative users from uploading self-signed certificates to app registrations.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/policies/authorizationPolicy',
    impactAnalysis: 'Prevents non-admin developers from granting certificates to apps.',
    history: [],
  },

  // 2. Auth & MFA (7)
  {
    id: 'auth-01',
    name: 'Enforce FIDO2 / Passkey Authentication Policy',
    category: 'Auth & MFA',
    description: 'Pushes strict FIDO2 security key registration requirement for privileged admin roles.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/fido2',
    impactAnalysis: 'Admins without hardware keys must register passkeys on next login.',
    history: [{ executedBy: 'm.vance@msp.com', timestamp: '12 hours ago', ticketId: 'SEC-9921', status: 'Success' }],
  },
  {
    id: 'auth-02',
    name: 'Revoke All Refresh Tokens & Active User Sessions',
    category: 'Auth & MFA',
    description: 'Invalidates active OAuth refresh tokens instantly across all devices for compromised account.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}/revokeSignInSessions',
    impactAnalysis: 'User will be immediately kicked out of Outlook, Teams, OneDrive, and web apps.',
    history: [{ executedBy: 'secops@msp.com', timestamp: '3 hours ago', ticketId: 'INC-9988', status: 'Success' }],
  },
  {
    id: 'auth-03',
    name: 'Disable Legacy SMS / Voice Call MFA Fallback',
    category: 'Auth & MFA',
    description: 'Blocks SIM-swappable SMS and voice call verification, forcing Microsoft Authenticator / FIDO2.',
    safetyLevel: 'gated',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/policies/authenticationMethodsPolicy',
    impactAnalysis: 'Users relying solely on SMS for MFA will fail login until configuring Authenticator app.',
    history: [],
  },
  {
    id: 'auth-04',
    name: 'Enable Number Matching for Authenticator Push Prompts',
    category: 'Auth & MFA',
    description: 'Prevents MFA fatigue attacks by requiring users to enter displayed 2-digit number in app.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/microsoftAuthenticator',
    impactAnalysis: 'Adds number matching requirement to all push notifications.',
    history: [{ executedBy: 'auto-policy@msp.com', timestamp: '1 month ago', ticketId: 'AUT-002', status: 'Success' }],
  },
  {
    id: 'auth-05',
    name: 'Reset MFA Registration for User Account',
    category: 'Auth & MFA',
    description: 'Clears registered authentication methods, allowing user to re-enroll MFA devices.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}/authentication/methods',
    impactAnalysis: 'User must complete initial MFA enrollment on next sign-in.',
    history: [],
  },
  {
    id: 'auth-06',
    name: 'Enable Certificate-Based Authentication (CBA)',
    category: 'Auth & MFA',
    description: 'Configures X.509 smart card / hardware certificate authentication for high-security tenants.',
    safetyLevel: 'gated',
    minTier: 'E5',
    apiEndpoint: '/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/x509Certificate',
    impactAnalysis: 'Requires active PKI infrastructure and smart card readers.',
    history: [],
  },
  {
    id: 'auth-07',
    name: 'Block Password spray Risk Accounts',
    category: 'Auth & MFA',
    description: 'Automatically triggers force-password-reset on users flagged with high risk sign-in activity.',
    safetyLevel: 'safe',
    minTier: 'P2',
    apiEndpoint: '/v1.0/identityProtection/riskyUsers/dismiss',
    impactAnalysis: 'Forces user to change password at next login.',
    history: [],
  },

  // 3. Conditional Access (6)
  {
    id: 'ca-01',
    name: 'Deploy MSP Baseline Conditional Access Policy Set',
    category: 'Conditional Access',
    description: 'Installs 5 core CA policies: Require MFA, Block Legacy Auth, Require Compliant Device, Risk-Based Challenge.',
    safetyLevel: 'gated',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/identity/conditionalAccess/policies',
    impactAnalysis: 'Applies tenant-wide sign-in restrictions. Emergency break-glass accounts auto-excluded.',
    history: [{ executedBy: 'm.vance@msp.com', timestamp: '4 days ago', ticketId: 'BASE-101', status: 'Success' }],
  },
  {
    id: 'ca-02',
    name: 'Toggle Conditional Access Policy State (Report-Only / Enforced)',
    category: 'Conditional Access',
    description: 'Switches policy enforcement mode between Report-Only monitoring and active Enforced state.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/identity/conditionalAccess/policies/{id}',
    impactAnalysis: 'Immediate change to sign-in access evaluation rules.',
    history: [],
  },
  {
    id: 'ca-03',
    name: 'Add Break-Glass Admin Exclusion Group to All CA Policies',
    category: 'Conditional Access',
    description: 'Ensures designated emergency administrator accounts are exempted from lockouts.',
    safetyLevel: 'gated',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/identity/conditionalAccess/policies/{id}',
    impactAnalysis: 'Exempts break-glass account from strict MFA and device compliance checks.',
    history: [{ executedBy: 'secops@msp.com', timestamp: '1 week ago', ticketId: 'SEC-8820', status: 'Success' }],
  },
  {
    id: 'ca-04',
    name: 'Block Non-Compliant Unmanaged Device Access',
    category: 'Conditional Access',
    description: 'Denies access to Exchange & SharePoint from personal or non-Intune enrolled endpoints.',
    safetyLevel: 'gated',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/identity/conditionalAccess/policies',
    impactAnalysis: 'Users on personal BYOD PCs will be blocked from web/desktop client access.',
    history: [],
  },
  {
    id: 'ca-05',
    name: 'Enforce Geo-Blocking Location Restrictions',
    category: 'Conditional Access',
    description: 'Blocks authentication requests originating outside designated approved country subnets.',
    safetyLevel: 'gated',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/identity/conditionalAccess/namedLocations',
    impactAnalysis: 'Travelling employees outside approved countries will be blocked unless exception added.',
    history: [],
  },
  {
    id: 'ca-06',
    name: 'Require Session Sign-In Frequency Controls (8-Hour Max)',
    category: 'Conditional Access',
    description: 'Forces full re-authentication and MFA re-challenge every 8 hours for web apps.',
    safetyLevel: 'safe',
    minTier: 'P2',
    apiEndpoint: '/v1.0/identity/conditionalAccess/policies',
    impactAnalysis: 'Web session tokens will expire after 8 hours.',
    history: [],
  },

  // 4. Devices & Intune (6)
  {
    id: 'dev-01',
    name: 'Push BitLocker Disk Encryption Baseline Profile',
    category: 'Devices & Intune',
    description: 'Enforces XTS-AES 256-bit BitLocker encryption on all Windows 10/11 endpoints with TPM 2.0.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/deviceManagement/deviceConfigurations',
    impactAnalysis: 'Unencrypted endpoints will begin silent drive encryption on next reboot.',
    history: [{ executedBy: 'auto-intune@msp.com', timestamp: '2 days ago', ticketId: 'POL-302', status: 'Success' }],
  },
  {
    id: 'dev-02',
    name: 'Trigger Remote Wipe / Corporate Data Sync Wiping',
    category: 'Devices & Intune',
    description: 'Wipes company data from compromised or lost mobile device without affecting personal files.',
    safetyLevel: 'blocked',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/deviceManagement/managedDevices/{id}/wipe',
    impactAnalysis: 'IRREVERSIBLE DATA REMOVAL: Removes all enterprise apps, profiles, and data from endpoint.',
    history: [{ executedBy: 'secops@msp.com', timestamp: '1 month ago', ticketId: 'INC-7012', status: 'Success' }],
  },
  {
    id: 'dev-03',
    name: 'Force Intune Endpoint Sync & Policy Evaluation',
    category: 'Devices & Intune',
    description: 'Sends real-time MDM check-in signal to all registered Windows, macOS, and mobile devices.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/deviceManagement/managedDevices/{id}/syncDevice',
    impactAnalysis: 'Forces device agent check-in without interrupting user session.',
    history: [],
  },
  {
    id: 'dev-04',
    name: 'Backup BitLocker Recovery Keys to Entra ID',
    category: 'Devices & Intune',
    description: 'Escrow missing drive recovery passwords to cloud tenant directory for emergency recovery.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/informationProtection/bitlocker/recoveryKeys',
    impactAnalysis: 'Saves recovery key payload to cloud tenant database.',
    history: [],
  },
  {
    id: 'dev-05',
    name: 'Deploy Microsoft Defender for Endpoint Sensor Baseline',
    category: 'Devices & Intune',
    description: 'Pushes Defender EDR onboarding script to all Windows & macOS Intune managed devices.',
    safetyLevel: 'safe',
    minTier: 'E5',
    apiEndpoint: '/v1.0/deviceManagement/deviceConfigurations',
    impactAnalysis: 'Installs and starts Defender EDR service on endpoints.',
    history: [{ executedBy: 'm.vance@msp.com', timestamp: '3 days ago', ticketId: 'SEC-401', status: 'Success' }],
  },
  {
    id: 'dev-06',
    name: 'Block Non-Compliant Endpoint Sync Access',
    category: 'Devices & Intune',
    description: 'Restricts sync services on endpoints failing OS patch level or antivirus baseline rules.',
    safetyLevel: 'gated',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/deviceManagement/deviceCompliancePolicySettingStateSummaries',
    impactAnalysis: 'Non-compliant laptops will lose access to local OneDrive sync.',
    history: [],
  },

  // 5. Exchange & Mailbox (7)
  {
    id: 'ex-01',
    name: 'Disable POP3 / IMAP4 / Basic Auth Protocols Tenant-Wide',
    category: 'Exchange & Mailbox',
    description: 'Blocks legacy clear-text email protocols across all Exchange Online mailboxes.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}/mailboxSettings',
    impactAnalysis: 'Legacy mail clients (e.g. Outlook 2010, old printer scanners) using POP3/IMAP will fail.',
    history: [{ executedBy: 'm.vance@msp.com', timestamp: 'Yesterday', ticketId: 'EXC-102', status: 'Success' }],
  },
  {
    id: 'ex-02',
    name: 'Audit & Remove External Mail Forwarding Rules',
    category: 'Exchange & Mailbox',
    description: 'Scans all inbox rules and auto-deletes rules directing internal mail to external domains.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}/mailFolders/inbox/messageRules',
    impactAnalysis: 'Removes exfiltration forwarding rules.',
    history: [{ executedBy: 'secops@msp.com', timestamp: '4 hours ago', ticketId: 'INC-9912', status: 'Success' }],
  },
  {
    id: 'ex-03',
    name: 'Convert User Mailbox to Shared Mailbox (50GB Free)',
    category: 'Exchange & Mailbox',
    description: 'Converts departed employee mailbox to shared type, releasing paid M365 license seat.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}',
    impactAnalysis: 'Preserves mailbox data while removing assigned paid license.',
    history: [{ executedBy: 'support@msp.com', timestamp: '2 days ago', ticketId: 'OFF-4091', status: 'Success' }],
  },
  {
    id: 'ex-04',
    name: 'Enable Litigation Hold (10-Year Data Retention)',
    category: 'Exchange & Mailbox',
    description: 'Applies immutable litigation hold on mailbox items, preventing permanent deletion by user.',
    safetyLevel: 'gated',
    minTier: 'E3',
    apiEndpoint: '/v1.0/users/{id}/mailboxSettings',
    impactAnalysis: 'Mailbox items deleted by user are retained in Recoverable Items store for eDiscovery.',
    history: [],
  },
  {
    id: 'ex-05',
    name: 'Purge Phishing Email Message Across All Mailboxes (Search & Purge)',
    category: 'Exchange & Mailbox',
    description: 'Executes Tenant-wide soft/hard delete of malicious email payload by Network Message ID.',
    safetyLevel: 'blocked',
    minTier: 'E5',
    apiEndpoint: '/v1.0/security/threatIntelligence/emailPurge',
    impactAnalysis: 'REMOVES TARGETED EMAIL FROM ALL USER INBOXES PERMANENTLY.',
    history: [{ executedBy: 'secops@msp.com', timestamp: '2 weeks ago', ticketId: 'INC-2041', status: 'Success' }],
  },
  {
    id: 'ex-06',
    name: 'Set Auto-Reply Out-Of-Office Notice for Separated Staff',
    category: 'Exchange & Mailbox',
    description: 'Configures external bounce message directing senders to supervisor.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}/mailboxSettings/automaticRepliesSetting',
    impactAnalysis: 'External senders receive auto-responder.',
    history: [],
  },
  {
    id: 'ex-07',
    name: 'Grant Full Access / Send-As Mailbox Permission',
    category: 'Exchange & Mailbox',
    description: 'Grants delegation access on shared or executive mailbox to authorized technician/manager.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}/mailboxSettings',
    impactAnalysis: 'Delegate can open and send email from target mailbox.',
    history: [],
  },

  // 6. Groups & Distribution (6)
  {
    id: 'grp-01',
    name: 'Convert Distribution List to Unified M365 Group',
    category: 'Groups & Distribution',
    description: 'Upgrades legacy DL to modern Microsoft 365 Group with shared mailbox, calendar, and Teams integration.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/groups',
    impactAnalysis: 'Group gains Teams & SharePoint site backing.',
    history: [],
  },
  {
    id: 'grp-02',
    name: 'Block External Email Delivery to Internal Security Groups',
    category: 'Groups & Distribution',
    description: 'Restricts mail delivery on internal admin and security groups to authenticated internal senders.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/groups/{id}',
    impactAnalysis: 'External spammers cannot send email directly to internal security distribution groups.',
    history: [{ executedBy: 'auto-policy@msp.com', timestamp: '1 month ago', ticketId: 'AUT-09', status: 'Success' }],
  },
  {
    id: 'grp-03',
    name: 'Purge Orphaned Groups Without Active Owners',
    category: 'Groups & Distribution',
    description: 'Identifies and re-assigns or deletes Microsoft 365 Groups where all owners have been deleted.',
    safetyLevel: 'gated',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/groups/{id}/owners',
    impactAnalysis: 'Assigns fallback MSP admin owner or soft-deletes orphaned groups.',
    history: [],
  },
  {
    id: 'grp-04',
    name: 'Enable Dynamic User Membership Rules for Security Groups',
    category: 'Groups & Distribution',
    description: 'Configures automated membership rules based on user department, country, or title attribute.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/groups/{id}',
    impactAnalysis: 'Group membership auto-populates based on Entra ID user attributes.',
    history: [],
  },
  {
    id: 'grp-05',
    name: 'Restrict Group Creation Permissions to MSP Admins Only',
    category: 'Groups & Distribution',
    description: 'Prevents end-users from spawning unmanaged M365 Groups and Teams channels.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/directory/directorySettingTemplates',
    impactAnalysis: 'Only designated admin group members can create new Teams or Groups.',
    history: [{ executedBy: 'm.vance@msp.com', timestamp: '2 months ago', ticketId: 'GOV-01', status: 'Success' }],
  },
  {
    id: 'grp-06',
    name: 'Trigger Expiration Policy Review for M365 Groups',
    category: 'Groups & Distribution',
    description: 'Sends access review notifications to group owners for groups inactive over 180 days.',
    safetyLevel: 'safe',
    minTier: 'P2',
    apiEndpoint: '/v1.0/groupLifecyclePolicies',
    impactAnalysis: 'Inactive groups will be flagged for owner renewal or auto-deletion.',
    history: [],
  },

  // 7. Licensing & Billing (6)
  {
    id: 'lic-01',
    name: 'Bulk License Reallocator & Unassigned Waste Optimizer',
    category: 'Licensing & Billing',
    description: 'Scans for unassigned paid E3/E5 licenses and revokes idle seats sitting unallocated over 30 days.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}/assignLicense',
    impactAnalysis: 'Reclaims unused licenses back to tenant pool.',
    history: [{ executedBy: 'b.smith@msp.com', timestamp: '3 days ago', ticketId: 'OPT-8812', status: 'Success' }],
  },
  {
    id: 'lic-02',
    name: 'Assign Group-Based Licensing Baseline (GBL)',
    category: 'Licensing & Billing',
    description: 'Automates license provisioning by binding SKU allocations to Entra ID security groups.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/groups/{id}/assignLicense',
    impactAnalysis: 'Users added to security group automatically receive assigned license SKU.',
    history: [{ executedBy: 'm.vance@msp.com', timestamp: '1 week ago', ticketId: 'LIC-002', status: 'Success' }],
  },
  {
    id: 'lic-03',
    name: 'Downgrade Unused E5 Seats to Business Premium',
    category: 'Licensing & Billing',
    description: 'Swaps expensive E5 licenses for Business Premium on non-executive accounts.',
    safetyLevel: 'gated',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/users/{id}/assignLicense',
    impactAnalysis: 'Changes license entitlement and saves ~$18/user/month.',
    history: [],
  },
  {
    id: 'lic-04',
    name: 'Revoke License Entitlements for Terminated Staff',
    category: 'Licensing & Billing',
    description: 'Removes assigned SKU licenses from disabled user accounts to stop recurring bill.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}/assignLicense',
    impactAnalysis: 'Frees license seat for re-assignment.',
    history: [{ executedBy: 'support@msp.com', timestamp: '5 days ago', ticketId: 'OFF-109', status: 'Success' }],
  },
  {
    id: 'lic-05',
    name: 'Enable Defender for Endpoint Add-on License Trial',
    category: 'Licensing & Billing',
    description: 'Triggers 30-day evaluation trial for Defender P2 threat protection across 250 seats.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/subscribedSkus',
    impactAnalysis: 'Activates trial licenses in tenant.',
    history: [],
  },
  {
    id: 'lic-06',
    name: 'Generate Monthly License Consumption & Wastage Audit Report',
    category: 'Licensing & Billing',
    description: 'Outputs CSV breakdown of total licenses, assigned seats, and monthly MRR wastage.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/reports/getM365AppUserDetail',
    impactAnalysis: 'Generates report artifact.',
    history: [],
  },

  // 8. PIM & Privileged Roles (6)
  {
    id: 'pim-01',
    name: 'Convert Permanent Global Admins to Time-Bound PIM Activation',
    category: 'PIM & Privileged Roles',
    description: 'Removes standing Global Admin rights and enforces Privileged Identity Management time-bound activation.',
    safetyLevel: 'gated',
    minTier: 'P2',
    apiEndpoint: '/v1.0/roleManagement/directory/roleAssignments',
    impactAnalysis: 'Admins must request 1-8 hour role activation with ticket justification before accessing admin controls.',
    history: [{ executedBy: 'secops@msp.com', timestamp: 'Yesterday', ticketId: 'PIM-901', status: 'Success' }],
  },
  {
    id: 'pim-02',
    name: 'Trigger Emergency Technician PIM Role Elevation (8-Hour GA)',
    category: 'PIM & Privileged Roles',
    description: 'Grants temporary 8-hour Global Admin role to designated MSP technician with ticket justification.',
    safetyLevel: 'gated',
    minTier: 'P2',
    apiEndpoint: '/v1.0/roleManagement/directory/roleAssignmentRequests',
    impactAnalysis: 'Technician receives temporary Global Admin rights. Auto-revokes in 8 hours.',
    history: [{ executedBy: 'm.vance@msp.com', timestamp: '6 hours ago', ticketId: 'INC-9911', status: 'Success' }],
  },
  {
    id: 'pim-03',
    name: 'Require Multi-Stage Approval for Global Admin Role Activation',
    category: 'PIM & Privileged Roles',
    description: 'Configures PIM workflow requiring SecOps lead approval before Global Admin role activates.',
    safetyLevel: 'safe',
    minTier: 'P2',
    apiEndpoint: '/v1.0/roleManagement/directory/roleEligibilityScheduleRequests',
    impactAnalysis: 'PIM activations will pause for manager approval.',
    history: [],
  },
  {
    id: 'pim-04',
    name: 'Audit Standing Admin Privileges Across All Directory Roles',
    category: 'PIM & Privileged Roles',
    description: 'Generates real-time report of all users assigned standing Exchange, Global, or User Admin roles.',
    safetyLevel: 'safe',
    minTier: 'P2',
    apiEndpoint: '/v1.0/roleManagement/directory/roleAssignments',
    impactAnalysis: 'Generates compliance audit payload.',
    history: [],
  },
  {
    id: 'pim-05',
    name: 'Enforce Ticket Number Requirement on PIM Activation',
    category: 'PIM & Privileged Roles',
    description: 'Forces technicians to enter valid ConnectWise/Autotask ticket ID during PIM request.',
    safetyLevel: 'safe',
    minTier: 'P2',
    apiEndpoint: '/v1.0/roleManagement/directory/roleDefinitions',
    impactAnalysis: 'PIM prompt includes mandatory ticket ID field.',
    history: [{ executedBy: 'auto-policy@msp.com', timestamp: '3 weeks ago', ticketId: 'AUT-88', status: 'Success' }],
  },
  {
    id: 'pim-06',
    name: 'Revoke Active Emergency GA Elevation Instantly',
    category: 'PIM & Privileged Roles',
    description: 'Terminates active PIM role elevation before the 8-hour expiry window.',
    safetyLevel: 'safe',
    minTier: 'P2',
    apiEndpoint: '/v1.0/roleManagement/directory/roleAssignmentRequests/{id}',
    impactAnalysis: 'Immediately drops elevated admin rights.',
    history: [],
  },

  // 9. Security & Defender (6)
  {
    id: 'sec-01',
    name: 'Deploy Safe Links & Safe Attachments Anti-Phishing Baseline',
    category: 'Security & Defender',
    description: 'Pushes Defender for Office 365 Plan 2 time-of-click URL detonation and attachment sandboxing.',
    safetyLevel: 'safe',
    minTier: 'E5',
    apiEndpoint: '/v1.0/security/threatIntelligence',
    impactAnalysis: 'All incoming emails with links/attachments undergo real-time sandbox analysis.',
    history: [{ executedBy: 'm.vance@msp.com', timestamp: '4 days ago', ticketId: 'DEF-102', status: 'Success' }],
  },
  {
    id: 'sec-02',
    name: 'Isolate Compromised Endpoint via Defender EDR',
    category: 'Security & Defender',
    description: 'Cuts network connectivity to infected PC while maintaining Defender cloud channel for remediation.',
    safetyLevel: 'blocked',
    minTier: 'E5',
    apiEndpoint: '/v1.0/security/alerts_v2/{id}',
    impactAnalysis: 'BLOCKS ALL NETWORK TRAFFIC TO/FROM ENDPOINT EXCEPT DEFENDER CLOUD CHANNEL.',
    history: [{ executedBy: 'secops@msp.com', timestamp: '1 month ago', ticketId: 'INC-6012', status: 'Success' }],
  },
  {
    id: 'sec-03',
    name: 'Enable Automated Incident Investigation & Response (AIR)',
    category: 'Security & Defender',
    description: 'Configures Defender XDR to auto-remediate malware and malicious inbox rules without human delay.',
    safetyLevel: 'safe',
    minTier: 'E5',
    apiEndpoint: '/v1.0/security/incidents',
    impactAnalysis: 'Defender will automatically quarantine threats.',
    history: [],
  },
  {
    id: 'sec-04',
    name: 'Trigger Real-Time Threat Hunting KQL Query Sweep',
    category: 'Security & Defender',
    description: 'Runs custom KQL query across tenant endpoints searching for IOC hashes and suspicious PowerShell.',
    safetyLevel: 'safe',
    minTier: 'E5',
    apiEndpoint: '/v1.0/security/runHuntingQuery',
    impactAnalysis: 'Queries Defender XDR telemetry lake.',
    history: [{ executedBy: 'secops@msp.com', timestamp: '1 day ago', ticketId: 'HUNT-901', status: 'Success' }],
  },
  {
    id: 'sec-05',
    name: 'Block Malicious Sender Domain / IP Tenant-Wide',
    category: 'Security & Defender',
    description: 'Adds sender domain or IP subnet to Defender Tenant Allow/Block List (TABL).',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/security/labels/m365',
    impactAnalysis: 'Blocks all incoming mail from target domain/IP across all user mailboxes.',
    history: [],
  },
  {
    id: 'sec-06',
    name: 'Purge Quarantined Phishing Messages (>30 Days Old)',
    category: 'Security & Defender',
    description: 'Permanently deletes expired spam and phishing messages held in security quarantine.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/security/threatIntelligence/vulnerabilities',
    impactAnalysis: 'Frees quarantine storage.',
    history: [],
  },

  // 10. SharePoint & OneDrive (6)
  {
    id: 'spo-01',
    name: 'Restrict External File Sharing to Specific Whitelisted Domains',
    category: 'SharePoint & OneDrive',
    description: 'Limits SharePoint and OneDrive anonymous and guest link sharing strictly to approved partner domains.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/sites',
    impactAnalysis: 'Users cannot share file links with domains outside the approved partner list.',
    history: [{ executedBy: 'auto-policy@msp.com', timestamp: '2 weeks ago', ticketId: 'AUT-201', status: 'Success' }],
  },
  {
    id: 'spo-02',
    name: 'Block Unauthenticated "Anyone with the Link" Anonymous Sharing',
    category: 'SharePoint & OneDrive',
    description: 'Disables anonymous shareable links, requiring recipient email verification for external links.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/admin/sharepoint/settings',
    impactAnalysis: 'Existing "Anyone" links will expire.',
    history: [{ executedBy: 'm.vance@msp.com', timestamp: '1 month ago', ticketId: 'SEC-301', status: 'Success' }],
  },
  {
    id: 'spo-03',
    name: 'Reassign Departed User OneDrive Storage to Manager',
    category: 'SharePoint & OneDrive',
    description: 'Grants supervisor 30-day delegate access to separated employee OneDrive document store.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}/drive',
    impactAnalysis: 'Manager receives access link to separated user documents.',
    history: [{ executedBy: 'support@msp.com', timestamp: '3 days ago', ticketId: 'OFF-8821', status: 'Success' }],
  },
  {
    id: 'spo-04',
    name: 'Enforce Idle Session Timeout for Unattended Web Clients (15 Mins)',
    category: 'SharePoint & OneDrive',
    description: 'Logs users out of web-based SharePoint/OneDrive if inactive for 15 minutes.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/admin/sharepoint/settings',
    impactAnalysis: 'Inactive browser tabs will prompt for sign-in.',
    history: [],
  },
  {
    id: 'spo-05',
    name: 'Set Site Collection Quota Storage Limits (1TB Max)',
    category: 'SharePoint & OneDrive',
    description: 'Caps individual SharePoint team site storage to prevent runaway cloud consumption.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/sites/{id}',
    impactAnalysis: 'Sites reaching 1TB will enter read-only mode until quota expanded.',
    history: [],
  },
  {
    id: 'spo-06',
    name: 'Purge External B2B Guest Access Links Across SharePoint',
    category: 'SharePoint & OneDrive',
    description: 'Scans site collections and revokes external share links older than 90 days.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/sites/{id}/permissions',
    impactAnalysis: 'Expired guest links will no longer function.',
    history: [],
  },

  // 11. Teams & Collaboration (6)
  {
    id: 'teams-01',
    name: 'Disable Unverified External Guest Chat in Teams Channels',
    category: 'Teams & Collaboration',
    description: 'Restricts Teams guest access policies to prevent unverified federated guest messaging.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/teamsSettings',
    impactAnalysis: 'Guests must be explicitly added to team before starting 1-on-1 chat.',
    history: [{ executedBy: 'auto-policy@msp.com', timestamp: '3 weeks ago', ticketId: 'AUT-021', status: 'Success' }],
  },
  {
    id: 'teams-02',
    name: 'Block App Installation from Unofficial Teams App Store',
    category: 'Teams & Collaboration',
    description: 'Restricts Teams app catalog to Microsoft native and MSP-approved line-of-business applications.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/appCatalogs/teamsApps',
    impactAnalysis: 'Users cannot install unapproved third-party Teams bots or tabs.',
    history: [],
  },
  {
    id: 'teams-03',
    name: 'Enforce Meeting Watermarking & Recording Safeguards',
    category: 'Teams & Collaboration',
    description: 'Pushes sensitivity label policy applying attendee email watermarks on confidential video calls.',
    safetyLevel: 'safe',
    minTier: 'E5',
    apiEndpoint: '/v1.0/me/onlineMeetings',
    impactAnalysis: 'Confidential Teams meetings display user email watermark overlay.',
    history: [],
  },
  {
    id: 'teams-04',
    name: 'Force Archive Inactive Teams Channels (>180 Days Inactive)',
    category: 'Teams & Collaboration',
    description: 'Sets inactive Teams channels to read-only state while retaining chat and file archives.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/teams/{id}/archive',
    impactAnalysis: 'Channel becomes read-only.',
    history: [],
  },
  {
    id: 'teams-05',
    name: 'Disable File Transfers in External Teams Meetings',
    category: 'Teams & Collaboration',
    description: 'Prevents meeting attendees from uploading or downloading files during external Teams calls.',
    safetyLevel: 'safe',
    minTier: 'Business Premium',
    apiEndpoint: '/v1.0/teamsSettings',
    impactAnalysis: 'Blocks in-meeting chat file attachments for guests.',
    history: [],
  },
  {
    id: 'teams-06',
    name: 'Audit All Teams Private Channels & External Guest Roster',
    category: 'Teams & Collaboration',
    description: 'Generates report listing all private Teams channels and their associated external guest members.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/teams/{id}/channels',
    impactAnalysis: 'Generates audit payload.',
    history: [],
  },

  // 12. Tenant & GDAP (6)
  {
    id: 'ten-01',
    name: 'Request 180-Day GDAP Delegation Access Extension',
    category: 'Tenant & GDAP',
    description: 'Generates Partner Center Granular Delegated Admin Privileges (GDAP) invitation link for client approval.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/tenantRelationships/delegatedAdminRelationships',
    impactAnalysis: 'Sends invitation to client global admin to renew MSP management delegation.',
    history: [{ executedBy: 'm.vance@msp.com', timestamp: '5 days ago', ticketId: 'GDAP-102', status: 'Success' }],
  },
  {
    id: 'ten-02',
    name: 'Enable Microsoft Graph Delta Sync Webhooks',
    category: 'Tenant & GDAP',
    description: 'Configures real-time Azure Event Grid subscription for instant user and security policy change notifications.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/subscriptions',
    impactAnalysis: 'Subscribes MSP engine to tenant Graph event notifications.',
    history: [],
  },
  {
    id: 'ten-03',
    name: 'Enforce Security Defaults (Fallback when no CA policies exist)',
    category: 'Tenant & GDAP',
    description: 'Enables Microsoft Security Defaults baseline enforcing MFA for all users and admins.',
    safetyLevel: 'gated',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/policies/identitySecurityDefaultsEnforcementPolicy',
    impactAnalysis: 'CANNOT BE COMBINED WITH CUSTOM CONDITIONAL ACCESS POLICIES. Enforces basic MFA.',
    history: [],
  },
  {
    id: 'ten-04',
    name: 'Configure Custom Branding & Logo for Tenant Sign-In Page',
    category: 'Tenant & GDAP',
    description: 'Pushes company logo, custom background, and helpdesk contact link to Entra sign-in screen.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/organization/{id}/branding',
    impactAnalysis: 'Updates public sign-in page design.',
    history: [],
  },
  {
    id: 'ten-05',
    name: 'Lock Out Deprecated Partner Admin Relationships (DAP to GDAP Migration)',
    category: 'Tenant & GDAP',
    description: 'Terminates legacy high-privilege DAP relationship, ensuring strict GDAP role separation.',
    safetyLevel: 'gated',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/tenantRelationships/delegatedAdminRelationships',
    impactAnalysis: 'Removes legacy full DAP access.',
    history: [{ executedBy: 'secops@msp.com', timestamp: '2 months ago', ticketId: 'MIG-001', status: 'Success' }],
  },
  {
    id: 'ten-06',
    name: 'Generate Tenant Security & Compliance Certification Export',
    category: 'Tenant & GDAP',
    description: 'Exports comprehensive SOC2 / ISO27001 proof artifact showing all M365 security baselines.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/reports/getSecurityComplianceSummary',
    impactAnalysis: 'Generates compliance PDF/JSON artifact.',
    history: [],
  },

  // 13. Users & Provisioning (6)
  {
    id: 'usr-01',
    name: 'Execute Standard Offboarding Workflow (Revoke, Convert, Archive)',
    category: 'Users & Provisioning',
    description: '1-Click Offboarding: Revokes sessions, resets password, converts mailbox, revokes licenses, transfers OneDrive.',
    safetyLevel: 'gated',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}',
    impactAnalysis: 'COMPLETE USER DEPROVISIONING: Revokes access, converts mailbox, and archives user data.',
    history: [{ executedBy: 'support@msp.com', timestamp: 'Yesterday', ticketId: 'OFF-9012', status: 'Success' }],
  },
  {
    id: 'usr-02',
    name: 'Trigger Force Password Reset on Next Sign-In',
    category: 'Users & Provisioning',
    description: 'Sets user password profile to require immediate change upon next authentication.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}',
    impactAnalysis: 'User must change password on next login attempt.',
    history: [],
  },
  {
    id: 'usr-03',
    name: 'Block Account Sign-In / Lock Account Instantly',
    category: 'Users & Provisioning',
    description: 'Sets accountEnabled = false in Entra ID, blocking all cloud sign-in attempts.',
    safetyLevel: 'gated',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}',
    impactAnalysis: 'User cannot authenticate to any Microsoft service.',
    history: [{ executedBy: 'secops@msp.com', timestamp: '3 hours ago', ticketId: 'INC-9988', status: 'Success' }],
  },
  {
    id: 'usr-04',
    name: 'Bulk Provision New Employee User Account',
    category: 'Users & Provisioning',
    description: 'Creates user account, sets temporary strong password, assigns license, and adds to baseline groups.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users',
    impactAnalysis: 'Creates new directory user object.',
    history: [{ executedBy: 'support@msp.com', timestamp: '2 days ago', ticketId: 'ONB-1092', status: 'Success' }],
  },
  {
    id: 'usr-05',
    name: 'Purge Dormant External Guest Accounts (>90 Days Inactive)',
    category: 'Users & Provisioning',
    description: 'Deletes B2B guest user accounts that have not signed in for over 90 days.',
    safetyLevel: 'gated',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}',
    impactAnalysis: 'Deletes guest accounts from directory.',
    history: [{ executedBy: 'auto-policy@msp.com', timestamp: '1 week ago', ticketId: 'AUT-301', status: 'Success' }],
  },
  {
    id: 'usr-06',
    name: 'Update Department, Job Title & Manager Attributes',
    category: 'Users & Provisioning',
    description: 'Pushes organizational attribute updates to sync dynamic group memberships.',
    safetyLevel: 'safe',
    minTier: 'Business Basic',
    apiEndpoint: '/v1.0/users/{id}',
    impactAnalysis: 'Updates user directory profile attributes.',
    history: [],
  },
];
