import { Tenant, ThreatFeedItem, PendingRemediation, AuditLogItem } from '../types';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 't-contoso',
    name: 'Contoso Ltd',
    code: 'CO',
    primaryDomain: 'contoso.com',
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    licenseUsage: { assigned: 425, total: 500, tier: 'E5' },
    mfaPercentage: 98,
    secureScore: 82.1,
    maxSecureScore: 92.0,
    syncStatus: 'Healthy',
    lastSyncTimestamp: '2 mins ago',
    activeAlertsCount: 0,
    adminCount: 4,
    userCount: 480,
    globalAdminUPNs: ['admin@contoso.com', 'm.vance@contoso.com'],
    conditionalAccessPoliciesCount: 12,
    pimEnabled: true,
    securityDefaults: false,
  },
  {
    id: 't-fabrikam',
    name: 'Fabrikam Inc',
    code: 'FA',
    primaryDomain: 'fabrikam.com',
    tenantId: 'e294b2a1-0984-46c8-9042-[#d28a113919e]',
    licenseUsage: { assigned: 190, total: 200, tier: 'Business Premium' },
    mfaPercentage: 45,
    secureScore: 42.8,
    maxSecureScore: 88.0,
    syncStatus: 'Warning',
    lastSyncTimestamp: '14 mins ago',
    activeAlertsCount: 3,
    adminCount: 6,
    userCount: 195,
    globalAdminUPNs: ['admin@fabrikam.com', 'it-sec@fabrikam.com', 'j.doe@fabrikam.com'],
    conditionalAccessPoliciesCount: 4,
    pimEnabled: false,
    securityDefaults: true,
  },
  {
    id: 't-northwind',
    name: 'Northwind Traders',
    code: 'NW',
    primaryDomain: 'northwindtraders.com',
    tenantId: '33a921d0-32b0-45e0-8339-444ffb88109a',
    licenseUsage: { assigned: 60, total: 100, tier: 'E3' },
    mfaPercentage: 100,
    secureScore: 79.5,
    maxSecureScore: 89.0,
    syncStatus: 'Sync Failed',
    lastSyncTimestamp: '3 hours ago (Graph Timeout)',
    activeAlertsCount: 1,
    adminCount: 2,
    userCount: 64,
    globalAdminUPNs: ['sysadmin@northwindtraders.com'],
    conditionalAccessPoliciesCount: 8,
    pimEnabled: true,
    securityDefaults: false,
  },
  {
    id: 't-adventure',
    name: 'Adventure Works',
    code: 'AW',
    primaryDomain: 'adventure-works.com',
    tenantId: '991024bc-512a-431f-b3a1-129a0088cb11',
    licenseUsage: { assigned: 750, total: 1000, tier: 'E5' },
    mfaPercentage: 99,
    secureScore: 88.2,
    maxSecureScore: 95.0,
    syncStatus: 'Healthy',
    lastSyncTimestamp: 'Just now',
    activeAlertsCount: 0,
    adminCount: 5,
    userCount: 810,
    globalAdminUPNs: ['secops@adventure-works.com', 'cloudadmin@adventure-works.com'],
    conditionalAccessPoliciesCount: 18,
    pimEnabled: true,
    securityDefaults: false,
  },
  {
    id: 't-woodgrove',
    name: 'Woodgrove Bank',
    code: 'WB',
    primaryDomain: 'woodgrovebank.com',
    tenantId: '448d120a-88bc-4991-aa02-8802dff3311a',
    licenseUsage: { assigned: 310, total: 350, tier: 'E5' },
    mfaPercentage: 96,
    secureScore: 84.5,
    maxSecureScore: 94.0,
    syncStatus: 'Healthy',
    lastSyncTimestamp: '5 mins ago',
    activeAlertsCount: 1,
    adminCount: 3,
    userCount: 320,
    globalAdminUPNs: ['compliance@woodgrovebank.com'],
    conditionalAccessPoliciesCount: 15,
    pimEnabled: true,
    securityDefaults: false,
  },
  {
    id: 't-trey',
    name: 'Trey Research',
    code: 'TR',
    primaryDomain: 'treyresearch.net',
    tenantId: '110293aa-99bb-411a-8822-440192830192',
    licenseUsage: { assigned: 145, total: 150, tier: 'Business Premium' },
    mfaPercentage: 82,
    secureScore: 71.0,
    maxSecureScore: 88.0,
    syncStatus: 'Healthy',
    lastSyncTimestamp: '12 mins ago',
    activeAlertsCount: 2,
    adminCount: 3,
    userCount: 148,
    globalAdminUPNs: ['admin@treyresearch.net'],
    conditionalAccessPoliciesCount: 6,
    pimEnabled: false,
    securityDefaults: true,
  },
  {
    id: 't-tailspin',
    name: 'Tailspin Toys',
    code: 'TT',
    primaryDomain: 'tailspintoys.com',
    tenantId: '55112233-4455-6677-8899-aabbccddeeff',
    licenseUsage: { assigned: 88, total: 100, tier: 'Business Premium' },
    mfaPercentage: 58,
    secureScore: 54.2,
    maxSecureScore: 85.0,
    syncStatus: 'Warning',
    lastSyncTimestamp: '25 mins ago',
    activeAlertsCount: 2,
    adminCount: 4,
    userCount: 92,
    globalAdminUPNs: ['owner@tailspintoys.com'],
    conditionalAccessPoliciesCount: 3,
    pimEnabled: false,
    securityDefaults: false,
  },
  {
    id: 't-litware',
    name: 'Litware Inc',
    code: 'LW',
    primaryDomain: 'litwareinc.com',
    tenantId: '88223344-5566-7788-9900-112233445566',
    licenseUsage: { assigned: 510, total: 600, tier: 'E3' },
    mfaPercentage: 94,
    secureScore: 76.8,
    maxSecureScore: 90.0,
    syncStatus: 'Healthy',
    lastSyncTimestamp: '1 min ago',
    activeAlertsCount: 0,
    adminCount: 5,
    userCount: 530,
    globalAdminUPNs: ['secadmin@litwareinc.com'],
    conditionalAccessPoliciesCount: 10,
    pimEnabled: true,
    securityDefaults: false,
  },
];

export const INITIAL_THREAT_FEED: ThreatFeedItem[] = [
  {
    id: 'tf-1',
    tenantId: 't-contoso',
    tenantName: 'Contoso Ltd',
    severity: 'HIGH',
    timestamp: '2m ago',
    title: 'MFA disabled for admin@contoso.com',
    sourceModule: 'Azure AD',
    description: 'Admin account admin@contoso.com excluded from Conditional Access MFA Policy CA001.',
    targetUPN: 'admin@contoso.com',
    actionRequired: 'Re-enforce Conditional Access Policy CA001 and trigger authentication challenge.',
    actionType: 'FIX_NOW',
    status: 'OPEN',
  },
  {
    id: 'tf-2',
    tenantId: 't-fabrikam',
    tenantName: 'Fabrikam Inc',
    severity: 'MED',
    timestamp: '15m ago',
    title: 'Global Admin role assigned in Fabrikam',
    sourceModule: 'PIM',
    description: 'Permanent Global Admin role assigned to user j.doe@fabrikam.com without approval ticket.',
    targetUPN: 'j.doe@fabrikam.com',
    actionRequired: 'Convert permanent assignment to Privileged Identity Management (PIM) eligible assignment.',
    actionType: 'REVIEW',
    status: 'OPEN',
  },
  {
    id: 'tf-3',
    tenantId: 't-northwind',
    tenantName: 'Northwind Traders',
    severity: 'LOW',
    timestamp: '45m ago',
    title: 'New external guest added in Northwind',
    sourceModule: 'Teams',
    description: 'External guest external.vendor@partner.com granted access to Executive Strategy team.',
    targetUPN: 'external.vendor@partner.com',
    actionRequired: 'Acknowledge guest access addition and verify B2B domain whitelist compliance.',
    actionType: 'ACKNOWLEDGE',
    status: 'OPEN',
  },
  {
    id: 'tf-4',
    tenantId: 't-adventure',
    tenantName: 'Adventure Works',
    severity: 'LOW',
    timestamp: '1h ago',
    title: 'Conditional Access Policy Modified',
    sourceModule: 'Conditional Access',
    description: 'Policy [CA-005] Device Compliance Enforced updated by secops@adventure-works.com.',
    actionRequired: 'Review policy difference against baseline MSP Security Template v4.2.',
    actionType: 'VIEW_DIFF',
    status: 'OPEN',
  },
  {
    id: 'tf-5',
    tenantId: 't-tailspin',
    tenantName: 'Tailspin Toys',
    severity: 'HIGH',
    timestamp: '1h 20m ago',
    title: 'Impossible Travel Suspicious Sign-in',
    sourceModule: 'Defender',
    description: 'Sign-in from Lagos, NG detected 10 minutes after successful sign-in from Chicago, US.',
    targetUPN: 'owner@tailspintoys.com',
    actionRequired: 'Revoke active refresh tokens, force password reset, and enable risk-based CA.',
    actionType: 'REVOKE_SESSIONS',
    status: 'OPEN',
  },
];

export const INITIAL_PENDING_REMEDIATIONS: PendingRemediation[] = [
  {
    id: 'pr-1',
    tenantName: 'Fabrikam Inc',
    tenantId: 't-fabrikam',
    title: 'Enforce MFA for 105 Unprotected Users',
    category: 'Identity',
    severity: 'HIGH',
    affectedTarget: '105 Users',
    createdTime: '1 hour ago',
    suggestedAction: 'Apply Security Defaults / Enable Conditional Access Policy CA-MFA-ALL',
  },
  {
    id: 'pr-2',
    tenantName: 'Northwind Traders',
    tenantId: 't-northwind',
    title: 'Repair Directory Sync Agent Connection',
    category: 'Policy Drift',
    severity: 'HIGH',
    affectedTarget: 'Entra Connect Sync',
    createdTime: '3 hours ago',
    suggestedAction: 'Re-authenticate Entra Connect Sync Service Account & trigger delta sync',
  },
  {
    id: 'pr-3',
    tenantName: 'Tailspin Toys',
    tenantId: 't-tailspin',
    title: 'Reclaim 12 Unused Business Premium Licenses',
    category: 'License',
    severity: 'MED',
    affectedTarget: '12 Unassigned Seats',
    createdTime: '1 day ago',
    suggestedAction: 'Deprovision inactive seats to save $264/mo',
  },
  {
    id: 'pr-4',
    tenantName: 'Trey Research',
    tenantId: 't-trey',
    title: 'Disable Legacy Basic Authentication Protocols',
    category: 'Security',
    severity: 'HIGH',
    affectedTarget: 'Exchange Online POP3/IMAP4',
    createdTime: '2 days ago',
    suggestedAction: 'Enforce Modern Authentication across Exchange Online tenant',
  },
  {
    id: 'pr-5',
    tenantName: 'Contoso Ltd',
    tenantId: 't-contoso',
    title: 'Rotate Expiring Azure AD App Registration Secret',
    category: 'Security',
    severity: 'MED',
    affectedTarget: 'MSP-Automation-App-01',
    createdTime: '2 days ago',
    suggestedAction: 'Generate new client secret and update MSP Vault key',
  },
  {
    id: 'pr-6',
    tenantName: 'Woodgrove Bank',
    tenantId: 't-woodgrove',
    title: 'Enable PIM for 2 Global Administrator Accounts',
    category: 'Identity',
    severity: 'HIGH',
    affectedTarget: '2 Global Admins',
    createdTime: '3 days ago',
    suggestedAction: 'Convert permanent Global Admin roles to PIM time-bound activation',
  },
  {
    id: 'pr-7',
    tenantName: 'Litware Inc',
    tenantId: 't-litware',
    title: 'Audit Inactive External B2B Guests (>90 Days)',
    category: 'Identity',
    severity: 'LOW',
    affectedTarget: '28 Guest Users',
    createdTime: '4 days ago',
    suggestedAction: 'Run Microsoft Graph Access Review sweep to disable dormant guest accounts',
  },
  {
    id: 'pr-8',
    tenantName: 'Adventure Works',
    tenantId: 't-adventure',
    title: 'Enable Defender for Office 365 Safe Attachments',
    category: 'Security',
    severity: 'MED',
    affectedTarget: 'Exchange Mailboxes',
    createdTime: '5 days ago',
    suggestedAction: 'Deploy baseline Anti-Phishing & Safe Links security policies',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log-1',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    tenantName: 'Fabrikam Inc',
    initiatedBy: 'Global Admin (m.vance@msp.com)',
    action: 'Graph API: Enforce Security Defaults',
    status: 'SUCCESS',
    details: 'Security Defaults policy applied. MFA registration prompt enforced for all users.',
  },
  {
    id: 'log-2',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    tenantName: 'Tailspin Toys',
    initiatedBy: 'Auto-Remediation Bot',
    action: 'Revoke User Refresh Tokens',
    status: 'SUCCESS',
    details: 'Revoked all active OAuth refresh tokens for user owner@tailspintoys.com.',
  },
  {
    id: 'log-3',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    tenantName: 'Northwind Traders',
    initiatedBy: 'System Health Checker',
    action: 'Trigger Instant Graph Sync',
    status: 'FAILED',
    details: 'Graph API endpoint returned HTTP 504 Gateway Timeout. Scheduled retry in 15 mins.',
  },
  {
    id: 'log-4',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    tenantName: 'Contoso Ltd',
    initiatedBy: 'Global Admin (m.vance@msp.com)',
    action: 'CA Policy Update: Block Legacy Auth',
    status: 'SUCCESS',
    details: 'Policy CA009 updated to block legacy authentication protocols across all clients.',
  },
];
