import React, { useState } from "react";
import type { AncestorGroup } from "./ancestorOutputs";

// ── VariableChipPanel ─────────────────────────────────────────────────────────
//
// Persistent "Available Variables" panel shown in the node config panel.
// Renders a grouped, scrollable chip list of every token in scope for the
// currently-selected node.  ForEach loop-variable groups float to the top
// and receive a teal highlight.
//
// Chips:
//  - primary text  = human-readable label
//  - secondary badge = monospace {{path}}
//  - click calls onInsert(tokenPath) — the parent inserts at cursor
//
// Collapse preference is persisted in localStorage under "wf_var_panel_open".

const LS_KEY = "wf_var_panel_open";

function readOpen(): boolean {
  try {
    const v = localStorage.getItem(LS_KEY);
    return v !== "false";
  } catch {
    return true;
  }
}

function writeOpen(v: boolean): void {
  try {
    localStorage.setItem(LS_KEY, v ? "true" : "false");
  } catch {
    // ignore
  }
}

/**
 * True when the group carries loop-body variables.
 * Detects groups by explicit loop sentinel keys (`item`, `itemIndex`, `itemsTotal`,
 * `collectedResults`) or by `item.*` sub-field expansions generated by
 * `resolveItemSubfields`.  Alias sub-fields (`alias.*`) always co-exist with the
 * sentinel keys in the same group, so the sentinel check is sufficient.
 */
const LOOP_SENTINELS = new Set(["item", "itemIndex", "itemsTotal", "collectedResults"]);

function isForeachGroup(g: AncestorGroup): boolean {
  return g.outputs.some(o => LOOP_SENTINELS.has(o.key) || o.key.startsWith("item."));
}

export interface VariableChipPanelProps {
  ancestorOutputs: AncestorGroup[];
  /** Called with the raw token path (no {{ }}). */
  onInsert: (tokenPath: string) => void;
  /**
   * When true, a brief hint is shown telling the user to click a text field
   * before clicking a chip (shown when no field has been focused yet).
   */
  noTargetHint?: boolean;
}

export function VariableChipPanel({ ancestorOutputs, onInsert, noTargetHint }: VariableChipPanelProps) {
  const [open, setOpen] = useState<boolean>(readOpen);

  function toggle() {
    const next = !open;
    setOpen(next);
    writeOpen(next);
  }

  // Sort: foreach groups first (by original order within each bucket)
  const sorted = [...ancestorOutputs].sort((a, b) => {
    const af = isForeachGroup(a) ? 0 : 1;
    const bf = isForeachGroup(b) ? 0 : 1;
    return af - bf;
  });

  // Exclude "sample unavailable" sentinels from the chip count badge
  const totalChips = sorted.reduce(
    (n, g) => n + g.outputs.filter(o => o.key !== "__sample_unavailable__").length,
    0,
  );

  if (totalChips === 0 && sorted.every(g => g.outputs.every(o => o.key === "__sample_unavailable__"))) {
    // All groups contain only sentinels — still render so the user sees the message
  } else if (totalChips === 0) {
    return null;
  }

  return (
    <div className="rounded-lg border border-[#30363D] bg-[#0D1117] overflow-hidden">
      {/* Header / toggle row */}
      <button
        type="button"
        onMouseDown={e => e.preventDefault()}
        onClick={toggle}
        className="w-full flex items-center justify-between px-3 py-2 text-left hover:bg-[#161B22] transition-colors"
      >
        <div className="flex items-center gap-2">
          <svg className="w-3 h-3 text-[#484F58] flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
          <span className="text-[10px] font-semibold uppercase tracking-wider text-[#7D8590]">
            Available Variables
          </span>
          <span className="text-[9px] bg-[#1C2128] border border-[#30363D] text-[#484F58] rounded-full px-1.5 py-0.5 leading-none">
            {totalChips}
          </span>
        </div>
        <svg
          className={`w-3 h-3 text-[#484F58] transition-transform duration-150 flex-shrink-0 ${open ? "" : "-rotate-90"}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>

      {/* No-target hint — shown briefly when user clicks a chip before focusing any field */}
      {noTargetHint && (
        <div className="px-3 py-1.5 bg-amber-950/40 border-t border-amber-700/30 flex items-center gap-1.5">
          <svg className="w-3 h-3 text-amber-400 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span className="text-[10px] text-amber-300">Click a text field below first, then click a chip to insert it.</span>
        </div>
      )}

      {open && (
        <div className="max-h-64 overflow-y-auto border-t border-[#30363D] px-2.5 py-2.5 space-y-3">
          {sorted.map(group => {
            const isForeach = isForeachGroup(group);
            return (
              <div key={group.nodeId}>
                {/* Group header */}
                <div className="flex items-center gap-1.5 mb-1.5">
                  <span
                    className={`text-[9px] font-semibold uppercase tracking-wider truncate max-w-[160px] ${
                      isForeach ? "text-teal-400" : "text-[#484F58]"
                    }`}
                  >
                    {group.nodeName}
                  </span>
                  {isForeach && (
                    <span className="flex-shrink-0 text-[8px] bg-teal-950/60 border border-teal-700/40 text-teal-300 rounded px-1 py-0.5 leading-none">
                      loop
                    </span>
                  )}
                </div>

                {/* Chips */}
                <div className="flex flex-wrap gap-1">
                  {group.outputs.map(o => {
                    // Special sentinel — dynamic node with no captured sample yet
                    if (o.key === "__sample_unavailable__") {
                      return (
                        <div
                          key="__sample_unavailable__"
                          className="w-full flex items-center gap-1.5 rounded px-2 py-1.5 bg-amber-950/30 border border-amber-700/25"
                        >
                          <svg className="w-3 h-3 text-amber-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                          </svg>
                          <span className="text-[10px] text-amber-300/80 leading-snug">
                            Run a Test Run to populate sample data
                          </span>
                        </div>
                      );
                    }

                    const tokenPath = group.isStartNode
                      ? o.key
                      : `steps.${group.nodeId}.${o.key}`;
                    return (
                      <button
                        key={o.key}
                        type="button"
                        title={`${o.label}\n{{${tokenPath}}}`}
                        onMouseDown={e => e.preventDefault()}
                        onClick={() => onInsert(tokenPath)}
                        className={`inline-flex flex-col items-start rounded px-1.5 py-1 text-left transition-colors border ${
                          isForeach
                            ? "bg-teal-950/40 border-teal-700/30 hover:bg-teal-900/50 hover:border-teal-600/50"
                            : "bg-[#161B22] border-[#30363D] hover:bg-[#1C2128] hover:border-[#444C56]"
                        }`}
                      >
                        <span
                          className={`text-[10px] font-medium leading-tight ${
                            isForeach ? "text-teal-200" : "text-[#C9D1D9]"
                          }`}
                        >
                          {o.label.length > 30 ? o.label.slice(0, 28) + "…" : o.label}
                        </span>
                        <span
                          className={`font-mono text-[9px] leading-tight mt-0.5 ${
                            isForeach ? "text-teal-400/80" : "text-[#2E9EFF]/80"
                          }`}
                        >
                          {`{{${tokenPath}}}`}
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
