using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;

namespace BuildConsole.Services
{
    /// <summary>
    /// The BuildConsole version scheme: <c>v{Major}.{Minor}.{build}</c>.
    ///
    /// Major/Minor are simple hardcoded constants, bumped by hand (start v1.0).
    /// {build} is the git commit count for this app's own folder
    /// (<c>git rev-list --count HEAD -- desktop/BuildConsole</c>), so it
    /// advances automatically with every commit that actually touches
    /// BuildConsole and never needs manual bumping.
    ///
    /// Two distinct numbers matter, and the gap between them is the whole point:
    ///   • <see cref="RunningBuild"/> — baked into THIS assembly at compile time
    ///     (the <c>GeneratedBuildInfo.BuildNumber</c> constant the csproj's
    ///     GenerateBuildInfo target writes from the same git command). A running
    ///     instance therefore knows the exact build it was compiled from, even
    ///     after the local repo has moved on underneath it.
    ///   • <see cref="GetCurrentBuild"/> — computed live against the current
    ///     local repo the same way. When it's ahead of RunningBuild, the running
    ///     copy is stale (BuildConsole has been committed to since it was built)
    ///     and there's a newer build available to deploy.
    /// </summary>
    public static class VersionInfo
    {
        // Major.Minor — simple hardcoded constants, bumped by hand. Start v1.0.
        public const int Major = 1;
        public const int Minor = 0;

        /// <summary>The build number embedded into this assembly at compile time (see <c>GeneratedBuildInfo</c>, generated by the csproj's GenerateBuildInfo target). This is what the actually-running instance was built from.</summary>
        public static int RunningBuild => GeneratedBuildInfo.BuildNumber;

        /// <summary>e.g. <c>v1.0.155</c> — the version of the actually-running instance.</summary>
        public static string RunningVersion => Format(RunningBuild);

        public static string Format(int build) => $"v{Major}.{Minor}.{build}";

        /// <summary>
        /// The build number the current local repo state WOULD produce
        /// (<c>git rev-list --count HEAD -- desktop/BuildConsole</c>), or null if
        /// it can't be determined (git missing, not a repo, etc). Runs git
        /// synchronously and briefly — call it off the UI thread (Task.Run) from
        /// pollers so a git hiccup can never hang the app.
        /// </summary>
        public static int? GetCurrentBuild()
        {
            var repoRoot = FindRepoRoot();
            if (repoRoot == null) return null;
            // Git #2539 — through SubprocessRunner so an aborted/crashed git (the real ancient-git
            // crash class this issue traced) is retried with backoff rather than silently yielding
            // an empty stdout that parses to null. On a genuine failure this still returns null.
            // Same pathspec used at build time (see BuildConsole.csproj's GenerateBuildInfo target).
            var res = SubprocessRunner.Run("git", "rev-list --count HEAD -- desktop/BuildConsole",
                repoRoot, TimeSpan.FromSeconds(5), "version");
            if (!res.Ok) return null;
            return int.TryParse(res.StdOut.Trim(), out int n) ? n : (int?)null;
        }

        /// <summary>
        /// The real first-line commit titles for the BuildConsole commits that landed
        /// AFTER build <paramref name="sinceBuild"/> and up to and including the
        /// currently-running build (<see cref="RunningBuild"/>), newest first — the raw
        /// material for the Home screen's "What's New" patch-notes list. Reuses the same
        /// <c>desktop/BuildConsole</c> pathspec the build number itself is derived from,
        /// so "one build number = one commit touching BuildConsole" holds exactly: the
        /// count of titles returned equals <c>RunningBuild - sinceBuild</c> (barring the
        /// safety cap below).
        ///
        /// Because the local repo may have moved ON PAST the running build (Shane keeps
        /// committing after launching a build), we anchor to the running build, not the
        /// live repo head: skip the commits newer than RunningBuild, then take the
        /// RunningBuild→sinceBuild window. <c>%s</c> is git's subject (first line only),
        /// never the body. Returns an empty list on any failure (git missing, not a
        /// repo, nothing new) so the caller can treat "no titles" and "couldn't tell"
        /// identically — the section just doesn't show. Runs git synchronously and
        /// briefly; call it off the UI thread (Task.Run) like <see cref="GetCurrentBuild"/>.
        /// </summary>
        /// <param name="max">Hard cap on how many titles to return — a light patch-notes
        /// list, not a full changelog dump. If more than this landed, the newest
        /// <paramref name="max"/> are returned and the caller can note the remainder.</param>
        public static List<string> GetNewCommitTitles(int sinceBuild, int max = 15)
        {
            var result = new List<string>();
            int current = RunningBuild;
            int take = current - sinceBuild;
            if (take <= 0) return result;                 // nothing new (or clock went backwards)
            if (take > max) take = max;                   // cap — keep the list quick to scan

            var repoRoot = FindRepoRoot();
            if (repoRoot == null) return result;

            // How far the LIVE repo is ahead of the build we're actually running — those
            // newer-than-us commits must be skipped so we show the window that ended at
            // this running build, not the repo's current head. Clamp at 0 (never negative).
            int liveBuild = GetCurrentBuild() ?? current;
            int skip = liveBuild - current;
            if (skip < 0) skip = 0;

            // Git #2539 — via SubprocessRunner (crash-retry + honest exit check). %s = subject
            // (first line only). Same pathspec as the build number. On any non-success, return an
            // empty list so the caller treats "no titles" and "couldn't tell" identically.
            var res = SubprocessRunner.Run("git",
                $"log --skip={skip} --max-count={take} --format=%s HEAD -- desktop/BuildConsole",
                repoRoot, TimeSpan.FromSeconds(5), "version");
            if (!res.Ok) return new List<string>();
            foreach (var line in res.StdOut.Split('\n'))
            {
                var t = line.Trim();
                if (t.Length > 0 && !IsBookendCommitTitle(t)) result.Add(t);
            }
            return result;
        }

        /// <summary>
        /// Gets a range of commit titles (subjects) starting from a specific offset (skip)
        /// and taking a maximum count, filtering out session-bookend commits.
        /// </summary>
        public static List<string> GetCommitsRange(int skip, int take)
        {
            var result = new List<string>();
            var repoRoot = FindRepoRoot();
            if (repoRoot == null) return result;

            // Git #2539 — via SubprocessRunner (crash-retry + honest exit check).
            var res = SubprocessRunner.Run("git",
                $"log --skip={skip} --max-count={take} --format=%s HEAD -- desktop/BuildConsole",
                repoRoot, TimeSpan.FromSeconds(5), "version");
            if (!res.Ok) return new List<string>();
            foreach (var line in res.StdOut.Split('\n'))
            {
                var t = line.Trim();
                if (t.Length > 0 && !IsBookendCommitTitle(t)) result.Add(t);
            }
            return result;
        }

        // Matches the session-bookend commit conventions from CLAUDE.md's "Mandatory
        // session bookends" section (BUILD_LOG.md / PLATFORM_BUILD.md IN FLIGHT/DONE
        // rows), plus the looser "Bookend:"/bare "IN FLIGHT:" phrasings seen in real
        // history — these are process/tracking commits, not human-readable feature
        // descriptions, so What's New should never show them alongside the real
        // commit for the same change.
        private static readonly Regex BookendTitlePattern = new Regex(
            @"^(?:BuildConsole\s+)?(?:BUILD_LOG|PLATFORM_BUILD)\b|^Bookend\s*:|^(?:DONE|IN\s+FLIGHT)\s*[:-]",
            RegexOptions.IgnoreCase);

        /// <summary>True if <paramref name="title"/> is a pure session-bookend/tracking
        /// commit (see <see cref="BookendTitlePattern"/>) rather than a real feature commit.</summary>
        public static bool IsBookendCommitTitle(string title) =>
            !string.IsNullOrEmpty(title) && BookendTitlePattern.IsMatch(title);

        /// <summary>
        /// Repo root = the nearest ancestor of the running exe that contains a
        /// <c>.git</c> entry (a directory in a normal clone, a file in a
        /// worktree). Preferred over <see cref="BuildTrackerConfig.FindRepoRoot"/>
        /// here because it doesn't depend on
        /// scripts/build-queue-watcher.config.json being present; falls back to
        /// that config-based lookup only if the <c>.git</c> walk comes up empty.
        /// </summary>
        public static string? FindRepoRoot()
        {
            try
            {
                var dir = new DirectoryInfo(AppContext.BaseDirectory);
                while (dir != null)
                {
                    if (Directory.Exists(Path.Combine(dir.FullName, ".git")) ||
                        File.Exists(Path.Combine(dir.FullName, ".git")))
                        return dir.FullName;
                    dir = dir.Parent;
                }
            }
            catch { /* fall through to the config-based lookup */ }
            return BuildTrackerConfig.FindRepoRoot();
        }
    }
}
