using System;
using System.Diagnostics;
using System.IO;

namespace BuildConsole.Services
{
    /// <summary>
    /// The BuildConsole version scheme: <c>v{Major}.{Minor}.{build}</c>.
    ///
    /// Major/Minor are simple hardcoded constants, bumped by hand (start v1.0).
    /// {build} is the git commit count for this app's own folder
    /// (<c>git rev-list --count HEAD -- desktop/BuildConsole</c>), so it
    /// advances automatically with every commit that actually touches
    /// BuildConsole and never needs manual bumping.
    ///
    /// Two distinct numbers matter, and the gap between them is the whole point:
    ///   • <see cref="RunningBuild"/> — baked into THIS assembly at compile time
    ///     (the <c>GeneratedBuildInfo.BuildNumber</c> constant the csproj's
    ///     GenerateBuildInfo target writes from the same git command). A running
    ///     instance therefore knows the exact build it was compiled from, even
    ///     after the local repo has moved on underneath it.
    ///   • <see cref="GetCurrentBuild"/> — computed live against the current
    ///     local repo the same way. When it's ahead of RunningBuild, the running
    ///     copy is stale (BuildConsole has been committed to since it was built)
    ///     and there's a newer build available to deploy.
    /// </summary>
    public static class VersionInfo
    {
        // Major.Minor — simple hardcoded constants, bumped by hand. Start v1.0.
        public const int Major = 1;
        public const int Minor = 0;

        /// <summary>The build number embedded into this assembly at compile time (see <c>GeneratedBuildInfo</c>, generated by the csproj's GenerateBuildInfo target). This is what the actually-running instance was built from.</summary>
        public static int RunningBuild => GeneratedBuildInfo.BuildNumber;

        /// <summary>e.g. <c>v1.0.155</c> — the version of the actually-running instance.</summary>
        public static string RunningVersion => Format(RunningBuild);

        public static string Format(int build) => $"v{Major}.{Minor}.{build}";

        /// <summary>
        /// The build number the current local repo state WOULD produce
        /// (<c>git rev-list --count HEAD -- desktop/BuildConsole</c>), or null if
        /// it can't be determined (git missing, not a repo, etc). Runs git
        /// synchronously and briefly — call it off the UI thread (Task.Run) from
        /// pollers so a git hiccup can never hang the app.
        /// </summary>
        public static int? GetCurrentBuild()
        {
            var repoRoot = FindRepoRoot();
            if (repoRoot == null) return null;
            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "git",
                    // Same pathspec used at build time (see BuildConsole.csproj's
                    // GenerateBuildInfo target) — relative to the repo root we run in.
                    Arguments = "rev-list --count HEAD -- desktop/BuildConsole",
                    WorkingDirectory = repoRoot,
                    RedirectStandardOutput = true,
                    UseShellExecute = false,
                    CreateNoWindow = true,
                };
                using var proc = Process.Start(psi);
                if (proc == null) return null;
                // --count writes a single integer line to stdout; nothing to stderr
                // on success, so redirecting stdout only avoids the unread-pipe
                // deadlock class entirely.
                string stdout = proc.StandardOutput.ReadToEnd();
                proc.WaitForExit(5000);
                return int.TryParse(stdout.Trim(), out int n) ? n : (int?)null;
            }
            catch
            {
                return null;
            }
        }

        /// <summary>
        /// Repo root = the nearest ancestor of the running exe that contains a
        /// <c>.git</c> entry (a directory in a normal clone, a file in a
        /// worktree). Preferred over <see cref="BuildTrackerConfig.FindRepoRoot"/>
        /// here because it doesn't depend on
        /// scripts/build-queue-watcher.config.json being present; falls back to
        /// that config-based lookup only if the <c>.git</c> walk comes up empty.
        /// </summary>
        public static string? FindRepoRoot()
        {
            try
            {
                var dir = new DirectoryInfo(AppContext.BaseDirectory);
                while (dir != null)
                {
                    if (Directory.Exists(Path.Combine(dir.FullName, ".git")) ||
                        File.Exists(Path.Combine(dir.FullName, ".git")))
                        return dir.FullName;
                    dir = dir.Parent;
                }
            }
            catch { /* fall through to the config-based lookup */ }
            return BuildTrackerConfig.FindRepoRoot();
        }
    }
}
