export type ProductTypeKey = "credit_pack" | "assessment" | "project" | "retainer" | "monitoring_tier";

export const COMMON_IMPORT_FIELDS = new Set([
  "slug", "name", "description", "category", "categoryPath", "tagline", "serviceType",
  "billingType", "visibility", "isPublic", "isActive", "label",
  "tier", "highlighted", "badge", "iconName", "sortOrder", "tags", "isFreeOffering",
  "serviceClass", "deliveryType",
]);

export const PRODUCT_TYPE_IMPORT_FIELDS: Record<ProductTypeKey, Set<string>> = {
  credit_pack: new Set([
    ...COMMON_IMPORT_FIELDS,
    "price", "deliverables", "inclusions", "features", "targetAudience",
  ]),
  assessment: new Set([
    ...COMMON_IMPORT_FIELDS,
    "basePrice", "maxPrice", "durationDays", "deliverables", "inclusions", "features",
    "requiredAppPermissions", "fulfillmentTypeKey", "triggeringSignalKeys",
    "customerAgreementTemplate", "workflowTemplateId", "targetAudience", "hoursPerMonth",
  ]),
  project: new Set([
    ...COMMON_IMPORT_FIELDS,
    "price", "basePrice", "maxPrice", "durationDays", "turnaround", "deliverables",
    "inclusions", "features", "requiredAppPermissions", "fulfillmentTypeKey",
    "triggeringSignalKeys", "customerAgreementTemplate", "workflowTemplateId",
    "targetAudience", "hoursPerMonth",
  ]),
  retainer: new Set([
    ...COMMON_IMPORT_FIELDS,
    "price", "hoursPerMonth", "deliverables", "inclusions", "features",
    "requiredAppPermissions", "fulfillmentTypeKey", "triggeringSignalKeys",
    "customerAgreementTemplate", "workflowTemplateId", "targetAudience",
  ]),
  monitoring_tier: new Set([
    ...COMMON_IMPORT_FIELDS,
    "tenantTierLabel", "seatMin", "seatMax", "includedEngines", "includedFeatures",
    "pricePerUserMonth", "seatCountFloor", "minMspPlanTier",
  ]),
};

export function detectProductType(
  serviceClass: string | null | undefined,
  deliveryType: string | null | undefined,
): ProductTypeKey {
  if (serviceClass === "subscription" && deliveryType === "bundle_subscription") return "monitoring_tier";
  if (serviceClass === "add_on" && deliveryType === "none") return "credit_pack";
  if (deliveryType === "assessment") return "assessment";
  if (deliveryType === "retainer") return "retainer";
  if (serviceClass === "project") return "project";
  return "project";
}

export const PRODUCT_TYPE_EXPORT_FIELDS: Record<ProductTypeKey, string[]> = {
  credit_pack: [
    "slug", "name", "description", "category", "categoryPath", "tagline", "serviceType",
    "billingType", "price", "visibility", "isPublic", "tier", "highlighted", "badge",
    "iconName", "sortOrder", "tags", "isFreeOffering", "serviceClass", "deliveryType",
    "deliverables", "inclusions", "features", "targetAudience",
  ],
  assessment: [
    "slug", "name", "description", "category", "categoryPath", "tagline", "serviceType",
    "billingType", "basePrice", "maxPrice", "durationDays", "visibility", "isPublic",
    "tier", "highlighted", "badge", "iconName", "sortOrder", "tags", "isFreeOffering",
    "serviceClass", "deliveryType", "deliverables", "inclusions", "features", "targetAudience",
    "hoursPerMonth", "requiredAppPermissions", "fulfillmentTypeKey", "triggeringSignalKeys",
    "customerAgreementTemplate", "workflowTemplateId",
  ],
  project: [
    "slug", "name", "description", "category", "categoryPath", "tagline", "serviceType",
    "billingType", "price", "basePrice", "maxPrice", "durationDays", "turnaround",
    "visibility", "isPublic", "tier", "highlighted", "badge", "iconName", "hoursPerMonth",
    "sortOrder", "tags", "isFreeOffering", "serviceClass", "deliveryType", "deliverables",
    "inclusions", "features", "targetAudience", "requiredAppPermissions", "fulfillmentTypeKey",
    "triggeringSignalKeys", "customerAgreementTemplate", "workflowTemplateId",
  ],
  retainer: [
    "slug", "name", "description", "category", "categoryPath", "tagline", "serviceType",
    "billingType", "price", "visibility", "isPublic", "tier", "highlighted", "badge",
    "iconName", "hoursPerMonth", "sortOrder", "tags", "isFreeOffering", "serviceClass",
    "deliveryType", "deliverables", "inclusions", "features", "targetAudience",
    "requiredAppPermissions", "fulfillmentTypeKey", "triggeringSignalKeys",
    "customerAgreementTemplate", "workflowTemplateId",
  ],
  monitoring_tier: [
    "slug", "name", "description", "category", "categoryPath", "tagline", "serviceType",
    "billingType", "visibility", "isPublic", "tier", "highlighted", "badge", "iconName",
    "sortOrder", "tags", "isFreeOffering", "serviceClass", "deliveryType",
    "tenantTierLabel", "seatMin", "seatMax", "includedEngines", "includedFeatures",
    "pricePerUserMonth", "seatCountFloor", "minMspPlanTier",
  ],
};

export const PRODUCT_TYPE_TEMPLATES: Record<ProductTypeKey, Record<string, unknown>> = {
  credit_pack: {
    serviceClass: "add_on",
    deliveryType: "none",
    billingType: "one_time",
    slug: "example-credit-pack",
    name: "Example Credit Pack",
    description: "A bundle of AI credits redeemable across any tenant.",
    category: "Add-ons",
    categoryPath: "Add-ons",
    price: 299,
    visibility: "private",
    isPublic: false,
    isFreeOffering: false,
    sortOrder: 0,
    tags: ["credits", "add-on"],
    deliverables: ["Credit bundle applied to tenant account"],
    inclusions: ["Immediate activation"],
    features: ["AI credit top-up", "No expiry"],
    targetAudience: "MSPs who need additional AI credits",
  },
  assessment: {
    serviceClass: null,
    deliveryType: "assessment",
    billingType: "one_time",
    slug: "example-assessment",
    name: "Example Assessment",
    description: "A one-time diagnostic review with a detailed findings report.",
    category: "Assessments",
    categoryPath: "Assessments",
    basePrice: 1500,
    maxPrice: 3000,
    durationDays: 14,
    visibility: "private",
    isPublic: false,
    isFreeOffering: false,
    sortOrder: 0,
    tags: ["assessment", "diagnostic"],
    deliverables: ["Written findings report", "Remediation roadmap"],
    inclusions: ["Two stakeholder interviews", "Tenant health scan"],
    features: ["Actionable recommendations", "Executive summary"],
    targetAudience: "IT leaders evaluating their M365 posture",
    requiredAppPermissions: [
      { scope: "User.Read.All", reason: "Enumerate licensed users" }
    ],
    fulfillmentTypeKey: null,
    triggeringSignalKeys: [],
    customerAgreementTemplate: null,
    workflowTemplateId: null,
    hoursPerMonth: null,
  },
  project: {
    serviceClass: "project",
    deliveryType: null,
    billingType: "fixed",
    slug: "example-project",
    name: "Example Project",
    description: "A scoped implementation project requiring a signed SOW.",
    category: "Projects",
    categoryPath: "Projects",
    price: 5000,
    basePrice: 4000,
    maxPrice: 8000,
    durationDays: 30,
    turnaround: "4 weeks",
    visibility: "private",
    isPublic: false,
    isFreeOffering: false,
    sortOrder: 0,
    tags: ["project", "implementation"],
    deliverables: ["Configured environment", "Training session", "Handover documentation"],
    inclusions: ["Project kickoff", "Weekly status calls", "Post-launch support (14 days)"],
    features: ["Dedicated PM", "Change management guidance"],
    targetAudience: "Organisations migrating to M365",
    requiredAppPermissions: [],
    fulfillmentTypeKey: null,
    triggeringSignalKeys: [],
    customerAgreementTemplate: null,
    workflowTemplateId: null,
    hoursPerMonth: null,
  },
  retainer: {
    serviceClass: null,
    deliveryType: "retainer",
    billingType: "recurring_monthly",
    slug: "example-retainer",
    name: "Example Retainer",
    description: "An ongoing monthly engagement billed at a fixed rate.",
    category: "Retainers",
    categoryPath: "Retainers",
    price: 1200,
    visibility: "private",
    isPublic: false,
    isFreeOffering: false,
    sortOrder: 0,
    tags: ["retainer", "ongoing"],
    deliverables: ["Monthly status report"],
    inclusions: ["On-call advisory (business hours)", "Quarterly review call"],
    features: ["Flexible scope", "Priority response"],
    targetAudience: "Clients needing ongoing M365 advisory",
    hoursPerMonth: "10 hours",
    requiredAppPermissions: [],
    fulfillmentTypeKey: null,
    triggeringSignalKeys: [],
    customerAgreementTemplate: null,
    workflowTemplateId: null,
  },
  monitoring_tier: {
    serviceClass: "subscription",
    deliveryType: "bundle_subscription",
    billingType: "recurring_monthly",
    slug: "example-monitoring-tier",
    name: "Example Monitoring Tier",
    description: "An MSP platform subscription tier with per-seat pricing.",
    category: "Monitoring",
    categoryPath: "Monitoring",
    visibility: "private",
    isPublic: false,
    isFreeOffering: false,
    sortOrder: 0,
    tags: ["monitoring", "msp"],
    tenantTierLabel: "Core",
    seatMin: 1,
    seatMax: 50,
    includedEngines: ["priority", "health", "drift"],
    includedFeatures: ["advanced_signals", "custom_workflows"],
    pricePerUserMonth: 8.00,
    seatCountFloor: 5,
    minMspPlanTier: "starter",
  },
};
