import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminArticlesRouter from "./admin-articles";
import adminServicesRouter from "./admin-services";
import adminWorkflowTemplatesRouter from "./admin-workflow-templates";
import adminProjectTemplatesRouter from "./admin-project-templates";
import adminContractTemplatesRouter from "./admin-contract-templates";
import sharesRouter from "./shares";
import authRouter from "./auth";
import leadsRouter from "./leads";
import downloadsRouter from "./downloads";
import portalRouter from "./portal";
import publicServicesRouter from "./public-services";
import publicEngagementProjectsRouter from "./public-engagement-projects";
import adminEngagementProjectsRouter from "./admin-engagement-projects";
import adminAiDraftRouter from "./admin-ai-draft";
import adminOverviewRouter from "./admin-overview";
import adminMobileRouter from "./admin-mobile";
import adminEmailsRouter from "./admin-emails";
import graphWebhookRouter from "./graph-webhook";
import auditLogsRouter from "./audit-logs";
import adminSharepointRouter from "./admin-sharepoint";
import adminAssetLibraryRouter from "./admin-asset-library";
import quizRouter from "./quiz";
import adminQuizLeadsRouter from "./admin-quiz-leads";
import contactChatRouter from "./contact-chat";
import analyticsRouter from "./analytics";
import adminGenerateArtifactsRouter from "./admin-generate-artifacts";
import adminEmailTemplatesRouter from "./admin-email-templates";
import adminCouponsRouter from "./admin-coupons";
import quizQuickWinRouter from "./quiz-quick-win";
import quizSelectorRouter from "./quiz-selector";
import adminServicePageTriggersRouter from "./admin-service-page-triggers";
import publicServicePageTriggersRouter from "./public-service-page-triggers";
import adminAzureCredentialsRouter from "./admin-azure-credentials";
import adminScriptRunnerRouter from "./admin-script-runner";
import bookingRouter from "./booking";
import mfaRouter from "./mfa";

const router: IRouter = Router();

router.use(healthRouter);
router.use(adminArticlesRouter);
router.use(adminServicesRouter);
router.use(adminWorkflowTemplatesRouter);
router.use(adminProjectTemplatesRouter);
router.use(adminContractTemplatesRouter);
router.use(adminEngagementProjectsRouter);
router.use(adminAiDraftRouter);
router.use(adminOverviewRouter);
router.use(adminMobileRouter);
router.use(adminEmailsRouter);
router.use(graphWebhookRouter);
router.use(sharesRouter);
router.use(authRouter);
router.use(leadsRouter);
router.use(downloadsRouter);
router.use(publicServicesRouter);
router.use(publicEngagementProjectsRouter);
router.use(publicServicePageTriggersRouter);
router.use(portalRouter);
router.use(auditLogsRouter);
router.use(adminSharepointRouter);
router.use(adminAssetLibraryRouter);
router.use(quizRouter);
router.use(adminQuizLeadsRouter);
router.use(contactChatRouter);
router.use(analyticsRouter);
router.use(adminGenerateArtifactsRouter);
router.use(adminEmailTemplatesRouter);
router.use(adminCouponsRouter);
router.use(quizQuickWinRouter);
router.use(quizSelectorRouter);
router.use(adminServicePageTriggersRouter);
router.use(adminAzureCredentialsRouter);
router.use(adminScriptRunnerRouter);
router.use(bookingRouter);
router.use(mfaRouter);

export default router;
