import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminArticlesRouter from "./admin-articles";
import adminServicesRouter from "./admin-services";
import adminWorkflowTemplatesRouter from "./admin-workflow-templates";
import adminProjectTemplatesRouter from "./admin-project-templates";
import adminContractTemplatesRouter from "./admin-contract-templates";
import sharesRouter from "./shares";
import authRouter from "./auth";
import leadsRouter from "./leads";
import downloadsRouter from "./downloads";
import portalRouter from "./portal";
import publicServicesRouter from "./public-services";
import publicStatusRouter from "./public-status";
import publicEngagementProjectsRouter from "./public-engagement-projects";
import adminEngagementProjectsRouter from "./admin-engagement-projects";
import adminAiDraftRouter from "./admin-ai-draft";
import adminOverviewRouter from "./admin-overview";
import adminMobileRouter from "./admin-mobile";
import adminEmailsRouter from "./admin-emails";
import graphWebhookRouter from "./graph-webhook";
import auditLogsRouter from "./audit-logs";
import adminSharepointRouter from "./admin-sharepoint";
import adminAssetLibraryRouter from "./admin-asset-library";
import quizRouter from "./quiz";
import adminQuizLeadsRouter from "./admin-quiz-leads";
import contactChatRouter from "./contact-chat";
import analyticsRouter from "./analytics";
import adminGenerateArtifactsRouter from "./admin-generate-artifacts";
import adminEmailTemplatesRouter from "./admin-email-templates";
import adminCouponsRouter from "./admin-coupons";
import quizQuickWinRouter from "./quiz-quick-win";
import quizSelectorRouter from "./quiz-selector";
import adminServicePageTriggersRouter from "./admin-service-page-triggers";
import publicServicePageTriggersRouter from "./public-service-page-triggers";
import publicHeroRouter from "./public-hero";
import publicPersonalizationRouter from "./public-personalization";
import adminAzureCredentialsRouter from "./admin-azure-credentials";
import adminScriptRunnerRouter from "./admin-script-runner";
import scriptIngestionRouter from "./script-ingestion";
import portalScriptLibraryRouter from "./portal-script-library";
import adminClientDocumentsRouter from "./admin-client-documents";
import bookingRouter from "./booking";
import mfaRouter from "./mfa";
import opportunitiesRouter from "./opportunities";
import adminDbStatusRouter from "./admin-db-status";
import adminClientsRouter from "./admin-clients";
import inboxRouter from "./inbox";
import adminQuizPainConfigRouter from "./admin-quiz-pain-config";
import aiNextBestActionsRouter from "./ai-next-best-actions";
import analyticsForecastRouter from "./analytics-forecast";
import clientHealthTrendsRouter from "./client-health-trends";
import adminFinanceRouter from "./admin-finance";
import adminMarketingRouter from "./admin-marketing";
import adminM365ScriptsRouter from "./admin-m365-scripts";
import adminM365RunRouter from "./admin-m365-run";
import adminPsScriptsRouter from "./admin-ps-scripts";
import adminKanbanEscalationRouter from "./admin-kanban-escalation";
import adminAiPromptsRouter from "./admin-ai-prompts";
import notificationsRouter from "./notifications";
import notificationPreferencesRouter from "./notification-preferences";
import pushRouter from "./push";
import adminCallbackTokensRouter from "./admin-callback-tokens";
import adminInsightsRouter from "./admin-insights";
import portalQuickWinScoringRouter from "./portal-quick-win-scoring";
import adminWorkflowsRouter from "./admin-workflows";
import adminStalledScriptsRouter from "./admin-stalled-scripts";
import adminGeneratedImagesRouter from "./admin-generated-images";
import adminMediaLibraryRouter from "./admin-media-library";
import presentationsRouter from "./presentations";
import adminSignalRulesRouter from "./admin-signal-rules";
import adminEnginesRouter from "./admin-engines";
import adminOverlordRouter from "./admin-overlord";
import crmPreviewStatsRouter from "./crm-preview-stats";
import adminSowDebugRouter from "./admin-sow-debug";
import consentRouter from "./consent";
import mspPortalRouter from "./msp-portal";
import mspV1Router from "./msp-v1";
import adminSlaRouter from "./admin-sla";
import adminScopeCreepRouter from "./admin-scope-creep";
import mspScopeCreepRouter from "./msp-scope-creep";
import mspSlaRouter from "./msp-sla";
import mspEnginesRouter from "./msp-engines";
import webhooksRouter from "./webhooks";
import mspOnboardingRouter from "./msp-onboarding";
import breakGlassVerificationRouter from "./break-glass-verification";
import platformAgreementsRouter from "./platform-agreements";
import mspSignupRouter from "./msp-signup";
import mspBillingWebhookRouter from "./msp-billing-webhook";
import portalCustomerEnginesRouter from "./portal-customer-engines";
import portalCustomerTimelineRouter from "./portal-customer-timeline";
import portalCustomerSearchRouter from "./portal-customer-search";
import dashboardDataRouter from "./dashboard-data";
import dashboardTemplatesRouter from "./dashboard-templates";
import dashboardOverridesRouter from "./dashboard-overrides";
import dashboardExecutiveSummaryRouter from "./dashboard-executive-summary";
import dashboardExportRouter from "./dashboard-export";
import adminFulfillmentTypesRouter from "./admin-fulfillment-types";
import adminDocumentTypesRouter from "./admin-document-types";
import mspDocumentsRouter from "./msp-documents";
import mspDocumentsHubRouter from "./msp-documents-hub";
import mspAdminSettingsRouter from "./msp-admin-settings";
import mspSettingsRouter from "./msp-settings";
import mspPlanManagementRouter from "./msp-plan-management";
import mspPlanSelfServiceRouter from "./msp-plan-self-service";
import mspPartnerRevenueRouter from "./msp-partner-revenue";
import mspAuditLogRouter from "./msp-audit-log";
import portalThemePreferenceRouter from "./portal-theme-preference";
import supportChatRouter from "./support-chat";
import adminMonitorChecksRouter from "./admin-monitor-checks";
import adminBaselineTemplatesRouter from "./admin-baseline-templates";
import adminConfigPackRunRouter from "./admin-config-pack-run";
import mspReportsRouter from "./msp-reports";
import mspAlertsRouter from "./msp-alerts";
import mspExecutiveRouter from "./msp-executive";
import mspCustomerTimelineRouter from "./msp-customer-timeline";
import mspDataRightsRouter from "./msp-data-rights";
import mspStaffSearchRouter from "./msp-staff-search";
import mspMessageCenterRouter from "./msp-message-center";
import mspM365SlaRouter from "./msp-m365-sla";
import portalM365SlaRouter from "./portal-m365-sla";
import mspCustomDomainRouter from "./msp-custom-domain";
import mspSalesBundlesRouter from "./msp-sales-bundles";
import salesOffersRouter from "./sales-offers";
import mspSalesOffersRouter from "./msp-sales-offers";
import portalOffersRouter from "./portal-offers";
import portalMarketplaceRouter from "./portal-marketplace";
import mspMarketplacePurchaseRouter from "./msp-marketplace-purchase";
import portalMissionControlRouter from "./portal-mission-control";
import portalAssessmentRouter from "./portal-assessment";
import portalFirstLoginRouter from "./portal-first-login";
import mspDiagnosticsRouter from "./msp-diagnostics";
import portalDeliveryKanbanRouter from "./portal-delivery-kanban";
import adminLiveMonitorRouter from "./admin-live-monitor";
import mspSowRouter from "./msp-sow";
import adminObservabilityRouter from "./admin-observability";
import adminIncidentsRouter from "./admin-incidents";
import adminExceptionsRouter from "./admin-exceptions";
import adminLiveStreamRouter from "./admin-live-stream";
import adminTestSuitesRouter from "./admin-test-suites";
import adminEventsRouter from "./admin-events";
import portalCheckoutRouter from "./portal-checkout";
import portalRetainerBillingRouter from "./portal-retainer-billing";
import clientEventsRouter from "./client-events";
import portal404EventsRouter from "./portal-404-events";
import adminAnalyticsSessionReplayRouter from "./admin-analytics-session-replay";
import adminAnalyticsHeatmapRouter from "./admin-analytics-heatmap";
import adminAnalyticsAttributionRouter from "./admin-analytics-attribution";

import pccRouter from "./pcc.js";

const router: IRouter = Router();

// Dev-only seed endpoint — registered at runtime, not imported at module level,
// so the conditional stays out of the production bundle entirely.
if (process.env.NODE_ENV !== "production") {
  void import("./admin-dev-seed").then(m => {
    router.use(m.default);
  });
}

router.use(healthRouter);
router.use(adminArticlesRouter);
router.use(adminServicesRouter);
router.use(adminWorkflowTemplatesRouter);
router.use(adminProjectTemplatesRouter);
router.use(adminContractTemplatesRouter);
router.use(adminEngagementProjectsRouter);
router.use(adminAiDraftRouter);
router.use(adminOverviewRouter);
router.use(adminMobileRouter);
router.use(adminEmailsRouter);
router.use(graphWebhookRouter);
router.use(sharesRouter);
router.use(authRouter);
router.use(leadsRouter);
router.use(downloadsRouter);
router.use(publicServicesRouter);
router.use(publicStatusRouter);
router.use(publicEngagementProjectsRouter);
router.use(publicServicePageTriggersRouter);
router.use(publicHeroRouter);
router.use(publicPersonalizationRouter);
router.use(adminClientsRouter);
router.use(portalCustomerEnginesRouter);
router.use(portalCustomerTimelineRouter);
router.use(portalCustomerSearchRouter);
router.use(dashboardDataRouter);
router.use(dashboardTemplatesRouter);
router.use(dashboardOverridesRouter);
router.use(dashboardExecutiveSummaryRouter);
router.use(dashboardExportRouter);
router.use(portalRouter);
router.use(auditLogsRouter);
router.use(adminSharepointRouter);
router.use(adminAssetLibraryRouter);
router.use(quizRouter);
router.use(adminQuizLeadsRouter);
router.use(contactChatRouter);
router.use(analyticsRouter);
router.use(adminGenerateArtifactsRouter);
router.use(adminEmailTemplatesRouter);
router.use(adminCouponsRouter);
router.use(quizQuickWinRouter);
router.use(quizSelectorRouter);
router.use(adminServicePageTriggersRouter);
router.use(adminAzureCredentialsRouter);
router.use(adminScriptRunnerRouter);
router.use(adminClientDocumentsRouter);
router.use(bookingRouter);
router.use(mfaRouter);
router.use(opportunitiesRouter);
router.use(adminDbStatusRouter);
router.use(inboxRouter);
router.use(adminQuizPainConfigRouter);
router.use(aiNextBestActionsRouter);
router.use(analyticsForecastRouter);
router.use(clientHealthTrendsRouter);
router.use(adminFinanceRouter);
router.use(adminMarketingRouter);
router.use(adminM365ScriptsRouter);
router.use(adminM365RunRouter);
router.use(adminPsScriptsRouter);
router.use(adminKanbanEscalationRouter);
router.use(adminAiPromptsRouter);
router.use(notificationsRouter);
router.use(notificationPreferencesRouter);
router.use(pushRouter);
router.use(adminCallbackTokensRouter);
router.use(adminInsightsRouter);
router.use(portalQuickWinScoringRouter);
router.use(adminWorkflowsRouter);
router.use(adminStalledScriptsRouter);
router.use(adminGeneratedImagesRouter);
router.use(adminMediaLibraryRouter);
router.use(presentationsRouter);
router.use(adminSignalRulesRouter);
router.use(adminEnginesRouter);
router.use(adminOverlordRouter);
router.use(crmPreviewStatsRouter);
router.use(adminSowDebugRouter);
router.use(consentRouter);
router.use(mspPortalRouter);
router.use(platformAgreementsRouter);
router.use(adminFulfillmentTypesRouter);
router.use(adminDocumentTypesRouter);
router.use(adminSlaRouter);
router.use(adminScopeCreepRouter);
router.use(mspScopeCreepRouter);
router.use(mspSlaRouter);
router.use(mspEnginesRouter);
router.use(webhooksRouter);
router.use(mspOnboardingRouter);
router.use(breakGlassVerificationRouter);
router.use(mspSignupRouter);
router.use(mspBillingWebhookRouter);
router.use(portalCustomerEnginesRouter);
router.use(scriptIngestionRouter);
router.use(portalScriptLibraryRouter);
router.use(mspDocumentsRouter);
router.use(mspDocumentsHubRouter);
router.use(mspAdminSettingsRouter);
router.use(mspSettingsRouter);
router.use(mspPlanManagementRouter);
router.use(mspPlanSelfServiceRouter);
router.use(mspPartnerRevenueRouter);
router.use(mspAuditLogRouter);
router.use(portalThemePreferenceRouter);
router.use(supportChatRouter);
router.use(adminMonitorChecksRouter);
router.use(adminBaselineTemplatesRouter);
router.use(adminConfigPackRunRouter);
router.use(mspReportsRouter);
router.use(mspAlertsRouter);
router.use(mspExecutiveRouter);
router.use(mspCustomerTimelineRouter);
router.use(mspDataRightsRouter);
router.use(mspStaffSearchRouter);
router.use(mspMessageCenterRouter);
router.use(mspM365SlaRouter);
router.use(portalM365SlaRouter);
router.use(mspCustomDomainRouter);
router.use(mspSalesBundlesRouter);
router.use(salesOffersRouter);
router.use(mspSalesOffersRouter);
router.use(portalOffersRouter);
router.use(portalMarketplaceRouter);
router.use(mspMarketplacePurchaseRouter);
router.use(portalMissionControlRouter);
router.use(portalAssessmentRouter);
router.use(portalFirstLoginRouter);
router.use(mspDiagnosticsRouter);
router.use(portalDeliveryKanbanRouter);
router.use(adminLiveMonitorRouter);
router.use(mspSowRouter);
router.use(adminObservabilityRouter);
router.use(adminIncidentsRouter);
router.use(adminAnalyticsSessionReplayRouter);
router.use(adminAnalyticsAttributionRouter);
router.use(adminExceptionsRouter);
router.use(adminLiveStreamRouter);
router.use(adminTestSuitesRouter);
router.use(adminEventsRouter);
router.use(portalCheckoutRouter);
router.use(portalRetainerBillingRouter);
router.use(clientEventsRouter);
router.use(portal404EventsRouter);
router.use(adminAnalyticsHeatmapRouter);

// MSP platform API — versioned surface
router.use("/msp/v1", mspV1Router);

// Platform Command Center (PCC) API Router
router.use("/pcc", pccRouter);

export default router;
