import { Router, type IRouter } from "express";
import healthRouter from "./health.ts";
import versionRouter from "./version.ts";
import adminArticlesRouter from "./admin-articles.ts";
import adminServicesRouter from "./admin-services.ts";
import adminWorkflowTemplatesRouter from "./admin-workflow-templates.ts";
import adminProjectTemplatesRouter from "./admin-project-templates.ts";
import adminContractTemplatesRouter from "./admin-contract-templates.ts";
import sharesRouter from "./shares.ts";
import authRouter from "./auth.ts";
import authSessionContextRouter from "./auth-session-context.ts";
import leadsRouter from "./leads.ts";
import downloadsRouter from "./downloads.ts";
import portalTeamRouter from "./portal-team.ts";
import portalProfileRouter from "./portal-profile.ts";
import portalOnboardingRouter from "./portal-onboarding.ts";
import portalProjectsRouter from "./portal-projects.ts";
import portalDocumentsRouter from "./portal-documents.ts";
import liveDocumentPdfRouter from "./live-document-pdf.ts";
import liveDocumentSharesRouter from "./live-document-shares.ts";
import portalBillingRouter from "./portal-billing.ts";
import portalPresentationsRouter from "./portal-presentations.ts";
import portalCheckoutFreeRouter from "./portal-checkout-free.ts";
import portalCheckoutDirectRouter from "./portal-checkout-direct.ts";
import portalPrivacyRouter from "./portal-privacy.ts";
import portalRetentionGateRouter from "./portal-retention-gate.ts";
import mspStaffRouter from "./msp-staff.ts";
import adminImpersonationRouter from "./admin-impersonation.ts";
import adminProjectsRouter from "./admin-projects.ts";
import adminReportsRouter from "./admin-reports.ts";
import adminInvoicesRouter from "./admin-invoices.ts";
import adminPurchasesRouter from "./admin-purchases.ts";
import adminPresentationsRouter from "./admin-presentations.ts";
import adminQuickWinRouter from "./admin-quick-win.ts";
import adminFulfillmentRouter from "./admin-fulfillment.ts";
import adminTestimonialsRouter from "./admin-testimonials.ts";
import publicServicesRouter from "./public-services.ts";
import publicStatusRouter from "./public-status.ts";
import publicBrokenLinkReportRouter from "./public-broken-link-report.ts";
import publicSignalChecksRouter from "./public-signal-checks.ts";
import publicEngagementProjectsRouter from "./public-engagement-projects.ts";
import adminEngagementProjectsRouter from "./admin-engagement-projects.ts";
import adminAiDraftRouter from "./admin-ai-draft.ts";
import adminOverviewRouter from "./admin-overview.ts";
import adminMobileRouter from "./admin-mobile.ts";
import adminEmailsRouter from "./admin-emails.ts";
import graphWebhookRouter from "./graph-webhook.ts";
import auditLogsRouter from "./audit-logs.ts";
import adminSharepointRouter from "./admin-sharepoint.ts";
import adminAssetLibraryRouter from "./admin-asset-library.ts";
import quizRouter from "./quiz.ts";
import publicChatRouter from "./public-chat.ts";
import adminPublicChatRouter from "./admin-public-chat.ts";
import adminGenerateArtifactsRouter from "./admin-generate-artifacts.ts";
import adminEmailTemplatesRouter from "./admin-email-templates.ts";
import adminCouponsRouter from "./admin-coupons.ts";
import quizQuickWinRouter from "./quiz-quick-win.ts";
import quizSelectorRouter from "./quiz-selector.ts";
import publicHeroRouter from "./public-hero.ts";
import publicConsentScopesRouter from "./public-consent-scopes.ts";
import publicAssessmentPaymentRouter from "./public-assessment-payment.ts";
import publicAssessmentAccountRouter from "./public-assessment-account.ts";
import publicPurchaseAccountRouter from "./public-purchase-account.ts";
import publicPurchasePaymentRouter from "./public-purchase-payment.ts";
import publicPurchasePacksRouter from "./public-purchase-packs.ts";
import publicPersonalizationRouter from "./public-personalization.ts";
import adminAzureCredentialsRouter from "./admin-azure-credentials.ts";
import adminAzureLighthouseRouter from "./admin-azure-lighthouse.ts";
import adminScriptRunnerRouter from "./admin-script-runner.ts";
import scriptIngestionRouter from "./script-ingestion.ts";
import portalScriptLibraryRouter from "./portal-script-library.ts";
import bookingRouter from "./booking.ts";
import mfaRouter from "./mfa.ts";
import opportunitiesRouter from "./opportunities.ts";
import adminDbStatusRouter from "./admin-db-status.ts";
import adminDeployConsoleRouter from "./admin-deploy-console.ts";
import adminTestTriggerRouter from "./admin-test-trigger.ts";
import adminRunHistoryRouter from "./admin-run-history.ts";
import adminMoneyRouter from "./admin-money.ts";
import adminClientsRouter from "./admin-clients.ts";
import inboxRouter from "./inbox.ts";
import adminQuizPainConfigRouter from "./admin-quiz-pain-config.ts";
import aiNextBestActionsRouter from "./ai-next-best-actions.ts";
import analyticsForecastRouter from "./analytics-forecast.ts";
import analyticsRouter from "./analytics.ts";
import clientHealthTrendsRouter from "./client-health-trends.ts";
import adminFinanceRouter from "./admin-finance.ts";
import adminMarketingRouter from "./admin-marketing.ts";
import adminContentStudioRouter from "./admin-content-studio.ts";
import adminRetainerRouter from "./admin-retainer.ts";
import adminRbdRouter from "./admin-rbd.ts";
import adminAutomationRegistryRouter from "./admin-automation-registry.ts";
import adminM365InterpretationsRouter from "./admin-m365-interpretations.ts";
import portalRetainerRouter from "./portal-retainer.ts";
import adminM365ScriptsRouter from "./admin-m365-scripts.ts";
import adminM365RunRouter from "./admin-m365-run.ts";
import adminPsScriptsRouter from "./admin-ps-scripts.ts";
import adminAiPromptsRouter from "./admin-ai-prompts.ts";
import notificationsRouter from "./notifications.ts";
import notificationPreferencesRouter from "./notification-preferences.ts";
import portalAlertPreferencesRouter from "./portal-alert-preferences.ts";
import pushRouter from "./push.ts";
import adminCallbackTokensRouter from "./admin-callback-tokens.ts";
import adminDocumentDownloadsRouter from "./admin-document-downloads.ts";
import portalQuickWinScoringRouter from "./portal-quick-win-scoring.ts";
import adminWorkflowsRouter from "./admin-workflows.ts";
import adminGeneratedImagesRouter from "./admin-generated-images.ts";
import adminMediaLibraryRouter from "./admin-media-library.ts";
import presentationsRouter from "./presentations.ts";
import adminSignalRulesRouter from "./admin-signal-rules.ts";
import adminEnginesRouter from "./admin-engines.ts";
import adminOverlordRouter from "./admin-overlord.ts";
import crmPreviewStatsRouter from "./crm-preview-stats.ts";
import consentRouter from "./consent.ts";
import mspPortalRouter from "./msp-portal.ts";
import mspV1Router from "./msp-v1.ts";
import adminSlaRouter from "./admin-sla.ts";
import adminScopeCreepRouter from "./admin-scope-creep.ts";
import mspScopeCreepRouter from "./msp-scope-creep.ts";
import mspSlaRouter from "./msp-sla.ts";
import mspEnginesRouter from "./msp-engines.ts";
import mspEngineHistoryRouter from "./msp-engine-history.ts";
import mspCustomerScoresRouter from "./msp-customer-scores.ts";
import webhooksRouter from "./webhooks.ts";
import mspConsoleWebhooksRouter from "./msp-console-webhooks.ts";
import mspOnboardingRouter from "./msp-onboarding.ts";
import mspConsentRouter from "./msp-consent.ts";
import breakGlassVerificationRouter from "./break-glass-verification.ts";
import mspBreakGlassRouter from "./msp-break-glass.ts";
import mspStatusReportsRouter from "./msp-status-reports.ts";
import mspKanbanRouter from "./msp-kanban.ts";
import mspCommunicationsPushRouter from "./msp-communications-push.ts";
import mspTrainingSessionsRouter from "./msp-training-sessions.ts";
import mspSignupRouter from "./msp-signup.ts";
import mspBillingWebhookRouter from "./msp-billing-webhook.ts";
import portalCustomerEnginesRouter from "./portal-customer-engines.ts";
import portalCustomerRequestsRouter from "./portal-customer-requests.ts";
import portalCustomerTimelineRouter from "./portal-customer-timeline.ts";
import portalCustomerSearchRouter from "./portal-customer-search.ts";
import dashboardDataRouter from "./dashboard-data.ts";
import dashboardTemplatesRouter from "./dashboard-templates.ts";
import dashboardOverridesRouter from "./dashboard-overrides.ts";
import dashboardExecutiveSummaryRouter from "./dashboard-executive-summary.ts";
import dashboardExportRouter from "./dashboard-export.ts";
import adminFulfillmentTypesRouter from "./admin-fulfillment-types.ts";
import adminDocumentTypesRouter from "./admin-document-types.ts";
import adminDocumentGeneratorRouter from "./admin-document-generator.ts";
import adminResultsTemplatesRouter from "./admin-results-templates.ts";
import mspDocumentsRouter from "./msp-documents.ts";
import mspDocumentsHubRouter from "./msp-documents-hub.ts";
import mspAdminSettingsRouter from "./msp-admin-settings.ts";
import mspSettingsRouter from "./msp-settings.ts";
import mspPlanManagementRouter from "./msp-plan-management.ts";
import mspPlanSelfServiceRouter from "./msp-plan-self-service.ts";
import mspPartnerRevenueRouter from "./msp-partner-revenue.ts";
import mspAuditLogRouter from "./msp-audit-log.ts";
import portalThemePreferenceRouter from "./portal-theme-preference.ts";
import portalRemediationTrackerRouter from "./portal-remediation-tracker.ts";
import portalRemediationTrackerExportRouter from "./portal-remediation-tracker-export.ts";
import portalRemediationTrackerScoresRouter from "./portal-remediation-tracker-scores.ts";
import portalRemediationFixRoutesRouter from "./portal-remediation-fix-routes.ts";
import portalRemediationChecklistRouter from "./portal-remediation-checklist.ts";
import portalRemediationRevealRouter from "./portal-remediation-reveal.ts";
import portalRemediationBypassResolutionsRouter from "./portal-remediation-bypass-resolutions.ts";
import mspRemediationTrackerRouter from "./msp-remediation-tracker.ts";
import mspRemediationTrackerExportRouter from "./msp-remediation-tracker-export.ts";
import mspRemediationTrackerScoresRouter from "./msp-remediation-tracker-scores.ts";
import mspRemediationChecklistRouter from "./msp-remediation-checklist.ts";
import mspRemediationFixRoutesRouter from "./msp-remediation-fix-routes.ts";
import mspRemediationRevealRouter from "./msp-remediation-reveal.ts";
import mspRemediationBypassResolutionsRouter from "./msp-remediation-bypass-resolutions.ts";
import portalTenantCheckItemsRouter from "./portal-tenant-check-items.ts";
import portalAccountSecurityGraphRouter from "./portal-account-security-graph.ts";
import portalChangeControlRouter from "./portal-change-control.ts";
import portalChangeCatalogRouter from "./portal-change-catalog.ts";
import portalMessageCenterRouter from "./portal-message-center.ts";
import portalRiskRegisterRouter from "./portal-risk-register.ts";
import portalPoamsRouter from "./portal-poams.ts";
import portalActiveDirectoryRouter from "./portal-active-directory.ts";
import portalRbdDocumentRouter from "./portal-rbd-document.ts";
import publicRbdDocumentRouter from "./public-rbd-document.ts";
import portalPolicyDecisionsRouter from "./portal-policy-decisions.ts";
import portalComplianceObligationsRouter from "./portal-compliance-obligations.ts";
import portalOversharingItemsRouter from "./portal-oversharing-items.ts";
import portalOversharingSitesRouter from "./portal-oversharing-sites.ts";
import portalGovernanceAreasRouter from "./portal-governance-areas.ts";
import portalPiiGovernanceRouter from "./portal-pii-governance.ts";
import portalSignInHelpRouter from "./portal-sign-in-help.ts";
import portalOwnershipRouter from "./portal-ownership.ts";
import portalSettingsOwnershipRouter from "./portal-settings-ownership.ts";
import portalSettingsChangeControlRouter from "./portal-settings-change-control.ts";
import portalSettingsDepartmentsRouter from "./portal-settings-departments.ts";
import portalSecurityPlanRouter from "./portal-security-plan.ts";
import portalSecurityPlanDocumentRouter from "./portal-security-plan-document.ts";
import portalRunbooksRouter from "./portal-runbooks.ts";
import portalSopsRouter from "./portal-sops.ts";
import portalEmailAuthStatusRouter from "./portal-email-auth-status.ts";
import supportChatRouter from "./support-chat.ts";
import adminMonitorChecksRouter from "./admin-monitor-checks.ts";
import adminMonitorCheckRunsRouter from "./admin-monitor-check-runs.ts";
import adminSimulatorAssessmentsRouter from "./admin-simulator-assessments.ts";
import adminActiveDirectoryRouter from "./admin-active-directory.ts";
import adminRbacRouter from "./admin-rbac.ts";
import adminDlpProvisioningRouter from "./admin-dlp-provisioning.ts";
import adminGlobalReaderProvisioningRouter from "./admin-global-reader-provisioning.ts";
import zohoAuthRouter from "./zoho-auth.ts";
import zohoWebhookRouter from "./zoho-webhook.ts";
import zohoCrmRouter from "./zoho-crm.ts";
import zohoBooksRouter from "./zoho-books.ts";
import engagebayRouter from "./engagebay.ts";
import engagebayWebhookRouter from "./engagebay-webhook.ts";
import engagebayCrmRouter from "./engagebay-crm.ts";
import engagebayTagsRouter from "./engagebay-tags.ts";
import engagebayActivityRouter from "./engagebay-activity.ts";
import adminAiBillingRouter from "./admin-ai-billing.ts";
import adminBaselineTemplatesRouter from "./admin-baseline-templates.ts";
import adminWriteActionsRouter from "./admin-write-actions.ts";
import adminTestbedRouter from "./admin-testbed.ts";
import adminConfigPackRunRouter from "./admin-config-pack-run.ts";
import adminRemediationCatalogRouter from "./admin-remediation-catalog.ts";
import adminWritePermissionsRouter from "./admin-write-permissions.ts";
import adminExecuteActionRouter from "./admin-execute-action.ts";
import mspReportsRouter from "./msp-reports.ts";
import mspAlertsRouter from "./msp-alerts.ts";
import mspRetentionQueueRouter from "./msp-retention-queue.ts";
import mspExecutiveRouter from "./msp-executive.ts";
import mspOwnershipRouter from "./msp-ownership.ts";
import mspCustomerTimelineRouter from "./msp-customer-timeline.ts";
import mspLaunchControlRouter from "./msp-launch-control.ts";
import mspDataRightsRouter from "./msp-data-rights.ts";
import mspStaffSearchRouter from "./msp-staff-search.ts";
import mspMessageCenterRouter from "./msp-message-center.ts";
import mspSupportRouter from "./msp-support.ts";
import mspM365SlaRouter from "./msp-m365-sla.ts";
import portalM365SlaRouter from "./portal-m365-sla.ts";
import mspCustomDomainRouter from "./msp-custom-domain.ts";
import mspSalesBundlesRouter from "./msp-sales-bundles.ts";
import salesOffersRouter from "./sales-offers.ts";
import mspSalesOffersRouter from "./msp-sales-offers.ts";
import portalOffersRouter from "./portal-offers.ts";
import portalMarketplaceRouter from "./portal-marketplace.ts";
import mspMarketplacePurchaseRouter from "./msp-marketplace-purchase.ts";
import portalMissionControlRouter from "./portal-mission-control.ts";
import portalEngineHistoryRouter from "./portal-engine-history.ts";
import portalAssessmentRouter from "./portal-assessment.ts";
import copilotAssessmentPersonasRouter from "./copilot-assessment-personas.ts";
import copilotAssessmentFinalReportRouter from "./copilot-assessment-final-report.ts";
import copilotAssessmentCheckoutRouter from "./copilot-assessment-checkout.ts";
import copilotAssessmentRemediationRouter from "./copilot-assessment-remediation.ts";
import copilotAssessmentQuizProfileRouter from "./copilot-assessment-quiz-profile.ts";
import copilotAssessmentQuizCatalogRouter from "./copilot-assessment-quiz-catalog.ts";
import portalFirstLoginRouter from "./portal-first-login.ts";
import mspDiagnosticsRouter from "./msp-diagnostics.ts";
import portalDeliveryKanbanRouter from "./portal-delivery-kanban.ts";
import adminLiveMonitorRouter from "./admin-live-monitor.ts";
import mspSowRouter from "./msp-sow.ts";
import adminObservabilityRouter from "./admin-observability.ts";
import adminCustomerAlertRulesRouter from "./admin-customer-alert-rules.ts";
import adminIncidentsRouter from "./admin-incidents.ts";
import adminExceptionsRouter from "./admin-exceptions.ts";
import adminDlqRouter from "./admin-dlq.ts";
import adminLiveStreamRouter from "./admin-live-stream.ts";
import adminTestSuitesRouter from "./admin-test-suites.ts";
import adminEventsRouter from "./admin-events.ts";
import portalCheckoutRouter from "./portal-checkout.ts";
import portalRetainerBillingRouter from "./portal-retainer-billing.ts";
import clientEventsRouter from "./client-events.ts";
import portal404EventsRouter from "./portal-404-events.ts";
import mspChangesRouter from "./msp-changes.ts";
import mspChangeCatalogRouter from "./msp-change-catalog.ts";
import mspStandingPoliciesRouter from "./msp-standing-policies.ts";
import mspPolicyDecisionsRouter from "./msp-policy-decisions.ts";
import mspActiveDirectoryRouter from "./msp-active-directory.ts";
import mspTeamRouter from "./msp-team.ts";
import mspPolicyEngineSettingsRouter from "./msp-policy-engine-settings.ts";
import mspVipClassificationsRouter from "./msp-vip-classifications.ts";
import mspRunbooksRouter from "./msp-runbooks.ts";
import mspChangeFreezeWindowsRouter from "./msp-change-freeze-windows.ts";
import mspChangeMaintenanceWindowsRouter from "./msp-change-maintenance-windows.ts";
import mspChangeDependenciesRouter from "./msp-change-dependencies.ts";
import mspChangeControlCabRouter from "./msp-change-control-cab.ts";
import mspChangeExecutionsRouter from "./msp-change-executions.ts";
import mspEvidenceAttachmentsRouter from "./msp-evidence-attachments.ts";
import mspChangePirRouter from "./msp-change-pir.ts";
import mspSopsRouter from "./msp-sops.ts";
import mspDlqRouter from "./msp-dlq.ts";
import mspRbdRouter from "./msp-rbd.ts";
import mspPoamsRouter from "./msp-poams.ts";
import mspRbdVersionsRouter from "./msp-rbd-versions.ts";
import mspSecurityPlanRouter from "./msp-security-plan.ts";
import mspRbdInstancesRouter from "./msp-rbd-instances.ts";
import mspComplianceFrameworksRouter from "./msp-compliance-frameworks.ts";
import adminDriftRouter from "./admin-drift.ts";
import adminConfigResourcesRouter from "./admin-config-resources.ts";
import adminConfigDiffsRouter from "./admin-config-diffs.ts";
import adminConfigSnapshotsRouter from "./admin-config-snapshots.ts";
// Git #1843 — the customer and MSP operator surfaces over configuration state.
// Deliberately separate routers from the two admin ones above: the endpoint prefix IS
// the audience, and mixing audiences in one artifact is the confusion at the root of
// the five failed portal attempts.
import portalConfigStateRouter from "./portal-config-state.ts";
import mspConfigStateRouter from "./msp-config-state.ts";
import mspConfigStateDiffsRouter from "./msp-config-state-diffs.ts";
import adminNavPinsRouter from "./admin-nav-pins.ts";
import adminBuildTrackerRouter from "./admin-build-tracker.ts";

import pccRouter from "./pcc.ts";

const router: IRouter = Router();

// Dev-only seed endpoint — registered at runtime, not imported at module level,
// so the conditional stays out of the production bundle entirely.
if (process.env.NODE_ENV !== "production") {
  void import("./admin-dev-seed.ts").then(m => {
    router.use(m.default);
  });
}

router.use(healthRouter);
router.use(versionRouter);
router.use(adminBuildTrackerRouter);
router.use(adminArticlesRouter);
router.use(adminServicesRouter);
router.use(adminWorkflowTemplatesRouter);
router.use(adminProjectTemplatesRouter);
router.use(adminContractTemplatesRouter);
router.use(adminEngagementProjectsRouter);
router.use(adminAiDraftRouter);
router.use(adminOverviewRouter);
router.use(adminMobileRouter);
router.use(adminEmailsRouter);
router.use(graphWebhookRouter);
router.use(sharesRouter);
router.use(authRouter);
router.use(authSessionContextRouter);
router.use(leadsRouter);
router.use(downloadsRouter);
router.use(publicServicesRouter);
router.use(publicStatusRouter);
router.use(publicBrokenLinkReportRouter);
router.use(publicSignalChecksRouter);
router.use(publicEngagementProjectsRouter);
router.use(publicHeroRouter);
router.use(publicConsentScopesRouter);
router.use(publicAssessmentPaymentRouter);
router.use(publicAssessmentAccountRouter);
router.use(publicPurchaseAccountRouter);
router.use(publicPurchasePaymentRouter);
router.use(publicPurchasePacksRouter);
router.use(publicPersonalizationRouter);
router.use(adminClientsRouter);
router.use(portalCustomerEnginesRouter);
router.use(portalCustomerRequestsRouter);
router.use(portalCustomerTimelineRouter);
router.use(portalCustomerSearchRouter);
router.use(dashboardDataRouter);
router.use(dashboardTemplatesRouter);
router.use(dashboardOverridesRouter);
router.use(dashboardExecutiveSummaryRouter);
router.use(dashboardExportRouter);
router.use(portalTeamRouter);
router.use(portalProfileRouter);
router.use(portalOnboardingRouter);
// portalDashboardRouter was mounted here until #327. It registered a second
// GET /portal/dashboard, which portalCustomerEnginesRouter (mounted above)
// always won on registration order, so it never served a request. Its payload
// was a strict subset of the surviving handler's — see the note on that route.
router.use(portalProjectsRouter);
router.use(portalDocumentsRouter);
router.use(liveDocumentPdfRouter);
router.use(liveDocumentSharesRouter);
router.use(portalBillingRouter);
router.use(portalPresentationsRouter);
router.use(portalCheckoutFreeRouter);
router.use(portalCheckoutDirectRouter);
router.use(portalPrivacyRouter);
router.use(portalRetentionGateRouter);
router.use(mspStaffRouter);
router.use(adminImpersonationRouter);
router.use(adminProjectsRouter);
router.use(adminReportsRouter);
router.use(adminInvoicesRouter);
router.use(adminPurchasesRouter);
router.use(adminPresentationsRouter);
router.use(adminQuickWinRouter);
router.use(adminFulfillmentRouter);
router.use(adminTestimonialsRouter);
router.use(auditLogsRouter);
router.use(adminSharepointRouter);
router.use(adminAssetLibraryRouter);
router.use(quizRouter);
router.use(publicChatRouter);
router.use(adminPublicChatRouter);
router.use(adminGenerateArtifactsRouter);
router.use(adminEmailTemplatesRouter);
router.use(adminCouponsRouter);
router.use(quizQuickWinRouter);
router.use(quizSelectorRouter);
router.use(adminAzureCredentialsRouter);
router.use(adminAzureLighthouseRouter);
router.use(adminScriptRunnerRouter);
router.use(bookingRouter);
router.use(mfaRouter);
router.use(opportunitiesRouter);
router.use(adminDbStatusRouter);
router.use(adminDeployConsoleRouter);
router.use(adminTestTriggerRouter);
router.use(adminRunHistoryRouter);
router.use(adminMoneyRouter);
router.use(inboxRouter);
router.use(adminQuizPainConfigRouter);
router.use(aiNextBestActionsRouter);
router.use(analyticsForecastRouter);
router.use(analyticsRouter);
router.use(clientHealthTrendsRouter);
router.use(adminFinanceRouter);
router.use(adminMarketingRouter);
router.use(adminContentStudioRouter);
router.use(adminRetainerRouter);
router.use(adminRbdRouter);
router.use(adminAutomationRegistryRouter);
router.use(adminM365InterpretationsRouter);
router.use(portalRetainerRouter);
router.use(adminM365ScriptsRouter);
router.use(adminM365RunRouter);
router.use(adminPsScriptsRouter);
router.use(adminAiPromptsRouter);
router.use(notificationsRouter);
router.use(notificationPreferencesRouter);
router.use(portalAlertPreferencesRouter);
router.use(pushRouter);
router.use(adminCallbackTokensRouter);
// Rehomed from admin-insights.ts (Git #3478) — admin-insights.ts and
// insight-pdf.ts were deleted outright once these three still-live GET routes
// (and the generic HTML→PDF helpers other features depend on) were moved out.
router.use(adminDocumentDownloadsRouter);
router.use(portalQuickWinScoringRouter);
router.use(adminWorkflowsRouter);
router.use(adminGeneratedImagesRouter);
router.use(adminMediaLibraryRouter);
router.use(presentationsRouter);
router.use(adminSignalRulesRouter);
router.use(adminEnginesRouter);
router.use(adminOverlordRouter);
router.use(crmPreviewStatsRouter);
router.use(consentRouter);
router.use(mspPortalRouter);
router.use(adminFulfillmentTypesRouter);
router.use(adminDocumentTypesRouter);
router.use(adminDocumentGeneratorRouter);
router.use(adminResultsTemplatesRouter);
router.use(adminSlaRouter);
router.use(adminScopeCreepRouter);
router.use(mspScopeCreepRouter);
router.use(mspSlaRouter);
router.use(mspEnginesRouter);
router.use(mspEngineHistoryRouter);
router.use(mspCustomerScoresRouter);
router.use(webhooksRouter);
router.use(mspConsoleWebhooksRouter);
router.use(mspOnboardingRouter);
router.use(mspConsentRouter);
router.use(breakGlassVerificationRouter);
router.use(mspBreakGlassRouter);
router.use(mspStatusReportsRouter);
router.use(mspKanbanRouter);
router.use(mspCommunicationsPushRouter);
router.use(mspTrainingSessionsRouter);
router.use(mspSignupRouter);
router.use(mspBillingWebhookRouter);
router.use(portalCustomerEnginesRouter);
router.use(scriptIngestionRouter);
router.use(portalScriptLibraryRouter);
router.use(mspDocumentsRouter);
router.use(mspDocumentsHubRouter);
router.use(mspAdminSettingsRouter);
router.use(mspSettingsRouter);
router.use(mspPlanManagementRouter);
router.use(mspPlanSelfServiceRouter);
router.use(mspPartnerRevenueRouter);
router.use(mspAuditLogRouter);
router.use(portalThemePreferenceRouter);
router.use(portalRemediationTrackerRouter);
router.use(portalRemediationTrackerExportRouter);
router.use(portalRemediationTrackerScoresRouter);
router.use(portalRemediationFixRoutesRouter);
router.use(portalRemediationChecklistRouter);
router.use(portalRemediationRevealRouter);
router.use(portalRemediationBypassResolutionsRouter);
router.use(mspRemediationTrackerRouter);
router.use(mspRemediationTrackerExportRouter);
router.use(mspRemediationTrackerScoresRouter);
router.use(mspRemediationChecklistRouter);
router.use(mspRemediationFixRoutesRouter);
router.use(mspRemediationRevealRouter);
router.use(mspRemediationBypassResolutionsRouter);
router.use(portalTenantCheckItemsRouter);
router.use(portalAccountSecurityGraphRouter);
router.use(portalChangeControlRouter);
router.use(portalChangeCatalogRouter);
router.use(portalMessageCenterRouter);
router.use(portalRiskRegisterRouter);
router.use(portalPoamsRouter);
router.use(portalActiveDirectoryRouter);
router.use(portalRbdDocumentRouter);
router.use(publicRbdDocumentRouter);
router.use(portalPolicyDecisionsRouter);
router.use(portalComplianceObligationsRouter);
router.use(portalOversharingItemsRouter);
router.use(portalOversharingSitesRouter);
router.use(portalGovernanceAreasRouter);
router.use(portalPiiGovernanceRouter);
router.use(portalSignInHelpRouter);
router.use(portalOwnershipRouter);
router.use(portalSettingsOwnershipRouter);
router.use(portalSettingsChangeControlRouter);
router.use(portalSettingsDepartmentsRouter);
router.use(portalSecurityPlanRouter);
router.use(portalSecurityPlanDocumentRouter);
router.use(portalRunbooksRouter);
router.use(portalSopsRouter);
router.use(portalEmailAuthStatusRouter);
router.use(adminNavPinsRouter);
router.use(supportChatRouter);
// Mounted before adminMonitorChecksRouter so the single-endpoint execution
// routes (.../:key/run) are matched on their own terms rather than depending on
// the CRUD router's :key patterns not shadowing them.
router.use(adminMonitorCheckRunsRouter);
router.use(adminMonitorChecksRouter);
router.use(adminSimulatorAssessmentsRouter);
router.use(adminActiveDirectoryRouter);
router.use(adminRbacRouter);
router.use(adminDlpProvisioningRouter);
router.use(adminGlobalReaderProvisioningRouter);
router.use(zohoAuthRouter);
router.use(zohoWebhookRouter);
router.use(zohoCrmRouter);
router.use(zohoBooksRouter);
router.use(engagebayRouter);
router.use(engagebayWebhookRouter);
router.use(engagebayCrmRouter);
router.use(engagebayTagsRouter);
router.use(engagebayActivityRouter);
router.use(adminAiBillingRouter);
router.use(adminBaselineTemplatesRouter);
router.use(adminWriteActionsRouter);
router.use(adminTestbedRouter);
router.use(adminConfigPackRunRouter);
router.use(adminRemediationCatalogRouter);
router.use(adminWritePermissionsRouter);
router.use(adminExecuteActionRouter);
router.use(mspReportsRouter);
router.use(mspAlertsRouter);
router.use(mspRetentionQueueRouter);
router.use(mspChangesRouter);
router.use(mspChangeCatalogRouter);
router.use(mspStandingPoliciesRouter);
router.use(mspPolicyDecisionsRouter);
router.use(mspActiveDirectoryRouter);
router.use(mspTeamRouter);
router.use(mspPolicyEngineSettingsRouter);
router.use(mspVipClassificationsRouter);
router.use(mspRunbooksRouter);
router.use(mspChangeFreezeWindowsRouter);
router.use(mspChangeMaintenanceWindowsRouter);
router.use(mspChangeDependenciesRouter);
router.use(mspChangeControlCabRouter);
router.use(mspChangeExecutionsRouter);
router.use(mspEvidenceAttachmentsRouter);
router.use(mspChangePirRouter);
router.use(mspSopsRouter);
router.use(mspDlqRouter);
router.use(mspRbdRouter);
router.use(mspPoamsRouter);
router.use(mspRbdVersionsRouter);
router.use(mspSecurityPlanRouter);
router.use(mspRbdInstancesRouter);
router.use(mspComplianceFrameworksRouter);
router.use(adminDriftRouter);
router.use(adminConfigResourcesRouter);
router.use(adminConfigDiffsRouter);
router.use(adminConfigSnapshotsRouter);
router.use(portalConfigStateRouter);
router.use(mspConfigStateRouter);
router.use(mspConfigStateDiffsRouter);
router.use(mspExecutiveRouter);
router.use(mspOwnershipRouter);
router.use(mspCustomerTimelineRouter);
router.use(mspLaunchControlRouter);
router.use(mspDataRightsRouter);
router.use(mspStaffSearchRouter);
router.use(mspMessageCenterRouter);
router.use(mspSupportRouter);
router.use(mspM365SlaRouter);
router.use(portalM365SlaRouter);
router.use(mspCustomDomainRouter);
router.use(mspSalesBundlesRouter);
router.use(salesOffersRouter);
router.use(mspSalesOffersRouter);
router.use(portalOffersRouter);
router.use(portalMarketplaceRouter);
router.use(mspMarketplacePurchaseRouter);
router.use(portalMissionControlRouter);
router.use(portalEngineHistoryRouter);
router.use(portalAssessmentRouter);
router.use(copilotAssessmentPersonasRouter);
router.use(copilotAssessmentFinalReportRouter);
router.use(copilotAssessmentCheckoutRouter);
router.use(copilotAssessmentRemediationRouter);
router.use(copilotAssessmentQuizProfileRouter);
router.use(copilotAssessmentQuizCatalogRouter);
router.use(portalFirstLoginRouter);
router.use(mspDiagnosticsRouter);
router.use(portalDeliveryKanbanRouter);
router.use(adminLiveMonitorRouter);
router.use(mspSowRouter);
router.use(adminObservabilityRouter);
router.use(adminCustomerAlertRulesRouter);
router.use(adminIncidentsRouter);
router.use(adminExceptionsRouter);
router.use(adminDlqRouter);
router.use(adminLiveStreamRouter);
router.use(adminTestSuitesRouter);
router.use(adminEventsRouter);
router.use(portalCheckoutRouter);
router.use(portalRetainerBillingRouter);
router.use(clientEventsRouter);
router.use(portal404EventsRouter);

// MSP platform API — versioned surface
router.use("/msp/v1", mspV1Router);

// Platform Command Center (PCC) API Router
router.use("/pcc", pccRouter);

export default router;
