/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Log in to the MSP portal
 */



export const MspAuthLoginBody = zod.object({
  "email": zod.string().email(),
  "password": zod.string().min(1),
  "slug": zod.string().describe('The MSP\'s portal slug'),
  "totpCode": zod.string().optional().describe('TOTP code for MFA-enabled accounts')
})

export const MspAuthLoginResponse = zod.object({
  "accessToken": zod.string(),
  "user": zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "name": zod.string().nullish(),
  "role": zod.enum(['admin', 'user']),
  "mspRole": zod.enum(['PlatformAdmin', 'MSPAdmin', 'MSPOperator', 'CustomerUser', 'ServiceAccount', 'Free']).nullish(),
  "mspId": zod.number().nullish(),
  "mspSlug": zod.string().nullish(),
  "customerId": zod.number().nullish()
})
})


/**
 * @summary Refresh MSP access token using httpOnly cookie
 */
export const MspAuthRefreshResponse = zod.object({
  "accessToken": zod.string(),
  "user": zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "name": zod.string().nullish(),
  "role": zod.enum(['admin', 'user']),
  "mspRole": zod.enum(['PlatformAdmin', 'MSPAdmin', 'MSPOperator', 'CustomerUser', 'ServiceAccount', 'Free']).nullish(),
  "mspId": zod.number().nullish(),
  "mspSlug": zod.string().nullish(),
  "customerId": zod.number().nullish()
})
})


/**
 * @summary Log out and clear the refresh token cookie
 */
export const MspAuthLogoutResponse = zod.object({
  "ok": zod.boolean().optional()
})


/**
 * @summary Return the currently authenticated user's profile
 */
export const MspAuthMeResponse = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "name": zod.string().nullish(),
  "role": zod.enum(['admin', 'user']),
  "mspRole": zod.enum(['PlatformAdmin', 'MSPAdmin', 'MSPOperator', 'CustomerUser', 'ServiceAccount', 'Free']).nullish(),
  "mspId": zod.number().nullish(),
  "mspSlug": zod.string().nullish(),
  "customerId": zod.number().nullish()
})


/**
 * @summary Resolve a tenant slug to its MSP record (used for portal branding)
 */
export const GetPortalTenantParams = zod.object({
  "slug": zod.coerce.string().describe('The MSP\'s URL slug')
})

export const GetPortalTenantResponse = zod.object({
  "id": zod.number(),
  "slug": zod.string(),
  "name": zod.string(),
  "logoUrl": zod.string().nullish(),
  "primaryColor": zod.string().nullish(),
  "status": zod.string().optional()
})


/**
 * @summary Return MSP KPI dashboard metrics
 */
export const GetMspDashboardResponse = zod.object({
  "msp": zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "status": zod.string().optional(),
  "offboardingState": zod.string().nullish()
}).nullish(),
  "customers": zod.object({
  "total": zod.number().optional(),
  "active": zod.number().optional(),
  "inactive": zod.number().optional(),
  "suspended": zod.number().optional()
}).optional(),
  "signals": zod.object({
  "firedThisMonth": zod.number().optional()
}).optional(),
  "offers": zod.object({
  "sentThisMonth": zod.number().optional(),
  "acceptedThisMonth": zod.number().optional(),
  "acceptanceRate": zod.number().optional(),
  "unacceptedCount": zod.number().optional()
}).optional(),
  "revenue": zod.object({
  "totalThisMonthCents": zod.number().optional()
}).optional(),
  "ai": zod.object({
  "creditsRemaining": zod.number().nullish(),
  "creditLimit": zod.number().nullish()
}).optional()
})


/**
 * @summary List customers for the authenticated MSP
 */
export const listMspCustomersQueryPageDefault = 1;

export const listMspCustomersQueryLimitDefault = 50;
export const listMspCustomersQueryLimitMax = 200;

export const listMspCustomersQueryStatusDefault = `all`;

export const ListMspCustomersQueryParams = zod.object({
  "page": zod.coerce.number().min(1).default(listMspCustomersQueryPageDefault),
  "limit": zod.coerce.number().min(1).max(listMspCustomersQueryLimitMax).default(listMspCustomersQueryLimitDefault),
  "search": zod.coerce.string().optional().describe('Filter by company name or domain'),
  "status": zod.enum(['active', 'inactive', 'all']).default(listMspCustomersQueryStatusDefault)
})

export const ListMspCustomersResponse = zod.object({
  "customers": zod.array(zod.object({
  "id": zod.number(),
  "mspId": zod.number().optional(),
  "companyName": zod.string(),
  "domain": zod.string().nullish(),
  "status": zod.enum(['active', 'inactive', 'suspended', 'offboarding']),
  "contactName": zod.string().nullish(),
  "contactEmail": zod.string().nullish(),
  "tenantId": zod.string().nullish(),
  "createdAt": zod.coerce.date().optional()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number()
})


/**
 * @summary Create a new customer under the authenticated MSP
 */



export const CreateMspCustomerBody = zod.object({
  "companyName": zod.string().min(1),
  "domain": zod.string().optional(),
  "contactName": zod.string().optional(),
  "contactEmail": zod.string().email().optional(),
  "tenantId": zod.string().optional()
})


/**
 * @summary Get a single customer record
 */
export const GetMspCustomerParams = zod.object({
  "id": zod.coerce.number()
})

export const GetMspCustomerResponse = zod.object({
  "id": zod.number(),
  "mspId": zod.number().optional(),
  "companyName": zod.string(),
  "domain": zod.string().nullish(),
  "status": zod.enum(['active', 'inactive', 'suspended', 'offboarding']),
  "contactName": zod.string().nullish(),
  "contactEmail": zod.string().nullish(),
  "tenantId": zod.string().nullish(),
  "createdAt": zod.coerce.date().optional()
})


/**
 * @summary Update a customer record
 */
export const UpdateMspCustomerParams = zod.object({
  "id": zod.coerce.number()
})




export const UpdateMspCustomerBody = zod.object({
  "companyName": zod.string().min(1).optional(),
  "domain": zod.string().optional(),
  "contactName": zod.string().optional(),
  "contactEmail": zod.string().email().optional(),
  "status": zod.enum(['active', 'inactive', 'suspended']).optional()
})

export const UpdateMspCustomerResponse = zod.object({
  "id": zod.number(),
  "mspId": zod.number().optional(),
  "companyName": zod.string(),
  "domain": zod.string().nullish(),
  "status": zod.enum(['active', 'inactive', 'suspended', 'offboarding']),
  "contactName": zod.string().nullish(),
  "contactEmail": zod.string().nullish(),
  "tenantId": zod.string().nullish(),
  "createdAt": zod.coerce.date().optional()
})


/**
 * @summary List available MSP subscription tiers
 */
export const ListMspSignupTiersResponse = zod.object({
  "tiers": zod.array(zod.object({
  "id": zod.number(),
  "slug": zod.string().nullish(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "tagline": zod.string().nullish(),
  "price": zod.string().nullish(),
  "tenantAllowance": zod.number().nullish(),
  "aiCreditAllowance": zod.number().nullish(),
  "overageRateCents": zod.number().nullish(),
  "features": zod.array(zod.string()).nullish(),
  "badge": zod.string().nullish(),
  "highlighted": zod.boolean().optional()
}))
})


/**
 * @summary Return MSP organisation settings
 */
export const GetMspSettingsResponse = zod.object({
  "companyName": zod.string().nullish(),
  "domain": zod.string().nullish(),
  "logoUrl": zod.string().nullish(),
  "primaryColor": zod.string().nullish(),
  "supportEmail": zod.string().nullish(),
  "timezone": zod.string().nullish()
})


/**
 * @summary Update MSP organisation settings
 */
export const UpdateMspSettingsBody = zod.object({
  "companyName": zod.string().optional(),
  "domain": zod.string().optional(),
  "logoUrl": zod.string().optional(),
  "primaryColor": zod.string().optional(),
  "supportEmail": zod.string().optional(),
  "timezone": zod.string().optional()
})

export const UpdateMspSettingsResponse = zod.object({
  "companyName": zod.string().nullish(),
  "domain": zod.string().nullish(),
  "logoUrl": zod.string().nullish(),
  "primaryColor": zod.string().nullish(),
  "supportEmail": zod.string().nullish(),
  "timezone": zod.string().nullish()
})


/**
 * @summary Generate a single-use Microsoft admin-consent invite link
 */
export const createConsentInviteLinkBodyTtlHoursDefault = 72;
export const createConsentInviteLinkBodyTtlHoursMax = 168;



export const CreateConsentInviteLinkBody = zod.object({
  "tenantId": zod.string().optional().describe('Azure AD tenant ID hint (use \"common\" to allow any tenant)'),
  "customerId": zod.number().optional(),
  "clientUserId": zod.number().optional(),
  "ttlHours": zod.number().min(1).max(createConsentInviteLinkBodyTtlHoursMax).default(createConsentInviteLinkBodyTtlHoursDefault)
})

export const CreateConsentInviteLinkResponse = zod.object({
  "consentUrl": zod.string().url(),
  "token": zod.string(),
  "expiresAt": zod.coerce.date(),
  "scopes": zod.array(zod.string())
})


