import { Tenant, IntentFeedItem } from '@/components/msp-tenants/types';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'T-0001-AV',
    name: 'Stark Industries',
    shortLetter: 'S',
    status: 'critical',
    secureScore: 41,
    securePtsDelta: -4,
    secureSparkline: [4, 6, 3, 2],
    complianceScore: 52,
    compliancePtsDelta: 0,
    complianceSparkline: [5, 5, 5],
    baselineAlignment: 32,
    gdap: {
      text: '2d 04h left',
      daysLeft: 2,
      percent: 10,
      isCritical: true,
    },
    automation: {
      text: '3 Failed Workflows',
      count: 3,
      isFailed: true,
    },
    incidentsCount: 8,
    hasWarning: true,
    hasLockReset: false,
    hasSyncIssue: false,
    region: 'us-east-1',
    licenseCount: 1450,
    usersCount: 1280,
    mfaEnforcedPercent: 44,
    conditionalAccessRules: 12,
    primaryDomain: 'starkindustries.com',
    failedWorkflowsDetails: [
      'Conditional Access Policy Sync - AccessDenied to Graph Endpoint',
      'MFA Enforce Script - Failed on 42 newly provisioned accounts',
      'Intune Device Compliance Wipe - Timed out after 300s'
    ],
    notes: 'High-priority VIP tenant requiring immediate GDAP session extension and Conditional Access remediation.'
  },
  {
    id: 'T-4829-XJ',
    name: 'Contoso Corp',
    shortLetter: 'C',
    status: 'healthy',
    secureScore: 94,
    securePtsDelta: 12,
    secureSparkline: [8, 10, 14, 16],
    complianceScore: 88,
    compliancePtsDelta: 3,
    complianceSparkline: [6, 9, 11],
    baselineAlignment: 98,
    gdap: {
      text: '182d left',
      daysLeft: 182,
      percent: 80,
    },
    automation: {
      text: '122 Healthy',
      count: 122,
    },
    incidentsCount: 0,
    hasWarning: false,
    hasLockReset: true,
    hasSyncIssue: true,
    region: 'us-central-1',
    licenseCount: 3200,
    usersCount: 2980,
    mfaEnforcedPercent: 99,
    conditionalAccessRules: 28,
    primaryDomain: 'contoso.com',
    failedWorkflowsDetails: [],
    notes: 'Gold standard baseline alignment. Entra ID P2 adoption increased significantly.'
  },
  {
    id: 'T-1100-AB',
    name: 'Hooli Data Systems',
    shortLetter: 'H',
    status: 'expired',
    secureScore: 88,
    securePtsDelta: 0,
    secureSparkline: [12, 12, 12],
    complianceScore: 91,
    compliancePtsDelta: 8,
    complianceSparkline: [4, 8, 14],
    baselineAlignment: 84,
    gdap: {
      text: 'Expired',
      daysLeft: 0,
      percent: 0,
      isExpired: true,
    },
    automation: {
      text: 'Idle',
      isIdle: true,
    },
    incidentsCount: 2,
    hasWarning: false,
    hasLockReset: true,
    hasSyncIssue: false,
    region: 'us-west-2',
    licenseCount: 890,
    usersCount: 810,
    mfaEnforcedPercent: 88,
    conditionalAccessRules: 18,
    primaryDomain: 'hooli.xyz',
    failedWorkflowsDetails: [],
    notes: 'GDAP relationship expired 3 days ago. Re-authorization email sent to tenant admin.'
  },
  {
    id: 'T-9102-LL',
    name: 'Globex International',
    shortLetter: 'G',
    status: 'syncing',
    secureScore: 62,
    securePtsDelta: -18,
    secureSparkline: [12, 9, 7, 4],
    complianceScore: 74,
    compliancePtsDelta: 0,
    complianceSparkline: [10, 10, 10],
    baselineAlignment: 59,
    gdap: {
      text: '12d 18h left',
      daysLeft: 12,
      percent: 30,
    },
    automation: {
      text: 'Syncing Policy...',
      isSyncing: true,
    },
    incidentsCount: 5,
    hasWarning: true,
    hasLockReset: false,
    hasSyncIssue: false,
    region: 'eu-west-1',
    licenseCount: 2100,
    usersCount: 1950,
    mfaEnforcedPercent: 65,
    conditionalAccessRules: 15,
    primaryDomain: 'globex.corp',
    failedWorkflowsDetails: [
      'Global Admin Account Audit in progress'
    ],
    notes: 'Automated drift engine currently syncing Microsoft Defender for Endpoint policy baseline.'
  },
  {
    id: 'T-3042-CY',
    name: 'Cyberdyne Systems',
    shortLetter: 'C',
    status: 'warning',
    secureScore: 73,
    securePtsDelta: -2,
    secureSparkline: [8, 7, 9, 6],
    complianceScore: 81,
    compliancePtsDelta: 4,
    complianceSparkline: [7, 8, 10],
    baselineAlignment: 76,
    gdap: {
      text: '8d 12h left',
      daysLeft: 8,
      percent: 25,
      isCritical: false,
    },
    automation: {
      text: '1 Failed Workflow',
      count: 1,
      isFailed: true,
    },
    incidentsCount: 3,
    hasWarning: true,
    hasLockReset: false,
    hasSyncIssue: true,
    region: 'us-west-1',
    licenseCount: 1100,
    usersCount: 950,
    mfaEnforcedPercent: 78,
    conditionalAccessRules: 20,
    primaryDomain: 'cyberdyne.ai',
    failedWorkflowsDetails: [
      'Entra ID Application Registration Expiration Notice'
    ],
    notes: 'Secondary GDAP role needs extension prior to next automated deployment run.'
  },
  {
    id: 'T-5511-WE',
    name: 'Wayne Enterprises',
    shortLetter: 'W',
    status: 'healthy',
    secureScore: 96,
    securePtsDelta: 5,
    secureSparkline: [10, 12, 14, 15],
    complianceScore: 95,
    compliancePtsDelta: 2,
    complianceSparkline: [11, 12, 13],
    baselineAlignment: 99,
    gdap: {
      text: '210d left',
      daysLeft: 210,
      percent: 92,
    },
    automation: {
      text: '184 Healthy',
      count: 184,
    },
    incidentsCount: 0,
    hasWarning: false,
    hasLockReset: true,
    hasSyncIssue: true,
    region: 'us-east-2',
    licenseCount: 5400,
    usersCount: 5120,
    mfaEnforcedPercent: 100,
    conditionalAccessRules: 34,
    primaryDomain: 'wayneenterprises.com',
    failedWorkflowsDetails: [],
    notes: 'Zero incident posture across all M365 workloads. Automated remediation active.'
  }
];

export const INITIAL_INTENT_FEED: IntentFeedItem[] = [
  {
    id: 'feed-1',
    timestamp: '14:22:01',
    type: 'AUTO-FIX',
    tenantName: 'Stark Industries',
    message: "Policy drift detected in 'Stark Industries'. Reverting Conditional Access to baseline."
  },
  {
    id: 'feed-2',
    timestamp: '14:21:45',
    type: 'ALERT',
    tenantName: 'Globex International',
    message: "GDAP session for 'Globex' entering critical window (<72h). Notification dispatched."
  },
  {
    id: 'feed-3',
    timestamp: '14:18:30',
    type: 'SIGNAL',
    tenantName: 'Contoso Corp',
    message: "New upsell signal: 'Contoso' usage of Entra ID P2 features increased by 40%."
  },
  {
    id: 'feed-4',
    timestamp: '14:12:10',
    type: 'AUTO-FIX',
    tenantName: 'Wayne Enterprises',
    message: "Orchestration engine verified zero-trust device compliance policy. No drift."
  },
  {
    id: 'feed-5',
    timestamp: '14:05:22',
    type: 'ALERT',
    tenantName: 'Hooli Data Systems',
    message: "Expired GDAP relationship prevented automated tenant health check."
  }
];
