// PLACEHOLDER DATA — not real product/pricing data. Structural placeholder only,
// carried over from the original AI-Studio mock (fabricated products, prices,
// team members). Wiring this to the real services catalog is a separate,
// later task — do not treat any price or product here as real.
import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'predictive-risk-engine',
    title: 'Predictive Risk Engine',
    description: 'Leverage neural networks to forecast tenant delinquency and asset volatility with 94% accuracy.',
    category: 'Intelligence',
    badge: 'PREMIUM',
    priceMonthly: 499,
    priceYearly: 399,
    iconName: 'analytics',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#a0c9ff]',
      border: 'border-[#a0c9ff]/20',
      badgeBg: 'bg-[#a0c9ff]/10',
      badgeText: 'text-[#a0c9ff]',
      badgeBorder: 'border-[#a0c9ff]/20',
    },
    accuracy: '94% Prediction Precision',
    features: [
      'Tenant credit delinquency forecaster',
      'Real-time asset volatility scoring',
      'Loss mitigation action triggers',
      'Automated lease probability modeling',
    ],
    rating: 4.9,
    reviewsCount: 128,
    activeTeams: 42,
    provider: 'Tenant Intelligence Labs',
  },
  {
    id: 'global-compliance-shield',
    title: 'Global Compliance Shield',
    description: 'Automated multi-jurisdictional regulatory mapping and real-time auditing for global portfolios.',
    category: 'Compliance',
    badge: 'ENTERPRISE',
    priceMonthly: 850,
    priceYearly: 680,
    iconName: 'shield',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#dab9ff]',
      border: 'border-[#dab9ff]/20',
      badgeBg: 'bg-[#dab9ff]/10',
      badgeText: 'text-[#dab9ff]',
      badgeBorder: 'border-[#dab9ff]/20',
    },
    accuracy: '100% Jurisdictional Coverage',
    features: [
      '50+ State & Country Regulatory Checkers',
      'Fair Housing & ESG Audit Trail',
      'Automated Legal Brief Generation',
      'Whistleblower & Compliance Portal',
    ],
    rating: 4.8,
    reviewsCount: 95,
    activeTeams: 38,
    provider: 'SecureProperty Global',
  },
  {
    id: 'auto-remediation-pro',
    title: 'Auto-Remediation Pro',
    description: 'Self-healing maintenance workflows that trigger contractors before a service failure occurs.',
    category: 'Automation',
    badge: 'CORE',
    priceMonthly: 299,
    priceYearly: 239,
    iconName: 'sparkles',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#a0c9ff]',
      border: 'border-[#a0c9ff]/20',
      badgeBg: 'bg-[#a0c9ff]/10',
      badgeText: 'text-[#a0c9ff]',
      badgeBorder: 'border-[#a0c9ff]/20',
    },
    accuracy: '89% Downtime Reduction',
    features: [
      'IoT Sensor Predictive Diagnostic',
      'Automated Contractor Dispatching',
      'Tenant Mobile Self-Service Portal',
      'Emergency Cost Cap Guardrails',
    ],
    rating: 4.95,
    reviewsCount: 210,
    activeTeams: 64,
    provider: 'AutoOps Systems',
  },
  {
    id: 'sentiment-analysis-hub',
    title: 'Sentiment Analysis Hub',
    description: 'Monitor tenant communications across all channels to detect churn signals and brand loyalty.',
    category: 'Intelligence',
    badge: 'ADD-ON',
    priceMonthly: 120,
    priceYearly: 96,
    iconName: 'message',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#a0c9ff]',
      border: 'border-[#a0c9ff]/20',
      badgeBg: 'bg-[#a0c9ff]/10',
      badgeText: 'text-[#a0c9ff]',
      badgeBorder: 'border-[#a0c9ff]/20',
    },
    accuracy: '91% Churn Signal Detection',
    features: [
      'Omnichannel NLP Sentiment Parser',
      'Tenant NPS Real-Time Heatmaps',
      'Priority Escalation Router',
      'AI Response Suggestion Engine',
    ],
    rating: 4.7,
    reviewsCount: 84,
    activeTeams: 29,
    provider: 'Tenant Voice AI',
  },
  {
    id: 'dark-fiber-security',
    title: 'Dark Fiber Security',
    description: 'Military-grade encryption for property IoT networks and critical data transmissions.',
    category: 'Security',
    badge: 'PROTECT',
    priceMonthly: 550,
    priceYearly: 440,
    iconName: 'lock',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#ffb4ab]',
      border: 'border-[#ffb4ab]/20',
      badgeBg: 'bg-[#ffb4ab]/10',
      badgeText: 'text-[#ffb4ab]',
      badgeBorder: 'border-[#ffb4ab]/20',
    },
    accuracy: 'Zero-Trust Protocol',
    features: [
      'Hardware-Enforced Encryption',
      'Intrusion Prevention System (IPS)',
      'Air-gapped Key Rotations',
      'Access Log Anomaly Detection',
    ],
    rating: 5.0,
    reviewsCount: 62,
    activeTeams: 19,
    provider: 'Aegis Cyber Defense',
  },
  {
    id: 'esg-performance-monitor',
    title: 'ESG Performance Monitor',
    description: 'Automated environmental, social, and governance reporting for institutional investors.',
    category: 'Compliance',
    badge: 'ESG',
    priceMonthly: 420,
    priceYearly: 336,
    iconName: 'leaf',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#dab9ff]',
      border: 'border-[#dab9ff]/20',
      badgeBg: 'bg-[#dab9ff]/10',
      badgeText: 'text-[#dab9ff]',
      badgeBorder: 'border-[#dab9ff]/20',
    },
    accuracy: 'GRESB & LEED Compliant',
    features: [
      'Utility Meter IoT Ingestion',
      'Carbon Emissions Calculator',
      'Institutional Investor Export',
      'Green Building Certification Sync',
    ],
    rating: 4.85,
    reviewsCount: 114,
    activeTeams: 31,
    provider: 'EcoMetric Analytics',
  },
];

