import { Product, TeamMember, DashboardMetric } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'predictive-risk-engine',
    title: 'Predictive Risk Engine',
    description: 'Leverage neural networks to forecast tenant delinquency and asset volatility with 94% accuracy.',
    category: 'Intelligence',
    badge: 'PREMIUM',
    priceMonthly: 499,
    priceYearly: 399,
    iconName: 'analytics',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#a0c9ff]',
      border: 'border-[#a0c9ff]/20',
      badgeBg: 'bg-[#a0c9ff]/10',
      badgeText: 'text-[#a0c9ff]',
      badgeBorder: 'border-[#a0c9ff]/20',
    },
    accuracy: '94% Prediction Precision',
    features: [
      'Tenant credit delinquency forecaster',
      'Real-time asset volatility scoring',
      'Loss mitigation action triggers',
      'Automated lease probability modeling',
    ],
    rating: 4.9,
    reviewsCount: 128,
    activeTeams: 42,
    provider: 'Tenant Intelligence Labs',
  },
  {
    id: 'global-compliance-shield',
    title: 'Global Compliance Shield',
    description: 'Automated multi-jurisdictional regulatory mapping and real-time auditing for global portfolios.',
    category: 'Compliance',
    badge: 'ENTERPRISE',
    priceMonthly: 850,
    priceYearly: 680,
    iconName: 'shield',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#dab9ff]',
      border: 'border-[#dab9ff]/20',
      badgeBg: 'bg-[#dab9ff]/10',
      badgeText: 'text-[#dab9ff]',
      badgeBorder: 'border-[#dab9ff]/20',
    },
    accuracy: '100% Jurisdictional Coverage',
    features: [
      '50+ State & Country Regulatory Checkers',
      'Fair Housing & ESG Audit Trail',
      'Automated Legal Brief Generation',
      'Whistleblower & Compliance Portal',
    ],
    rating: 4.8,
    reviewsCount: 95,
    activeTeams: 38,
    provider: 'SecureProperty Global',
  },
  {
    id: 'auto-remediation-pro',
    title: 'Auto-Remediation Pro',
    description: 'Self-healing maintenance workflows that trigger contractors before a service failure occurs.',
    category: 'Automation',
    badge: 'CORE',
    priceMonthly: 299,
    priceYearly: 239,
    iconName: 'sparkles',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#a0c9ff]',
      border: 'border-[#a0c9ff]/20',
      badgeBg: 'bg-[#a0c9ff]/10',
      badgeText: 'text-[#a0c9ff]',
      badgeBorder: 'border-[#a0c9ff]/20',
    },
    accuracy: '89% Downtime Reduction',
    features: [
      'IoT Sensor Predictive Diagnostic',
      'Automated Contractor Dispatching',
      'Tenant Mobile Self-Service Portal',
      'Emergency Cost Cap Guardrails',
    ],
    rating: 4.95,
    reviewsCount: 210,
    activeTeams: 64,
    provider: 'AutoOps Systems',
  },
  {
    id: 'sentiment-analysis-hub',
    title: 'Sentiment Analysis Hub',
    description: 'Monitor tenant communications across all channels to detect churn signals and brand loyalty.',
    category: 'Intelligence',
    badge: 'ADD-ON',
    priceMonthly: 120,
    priceYearly: 96,
    iconName: 'message',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#a0c9ff]',
      border: 'border-[#a0c9ff]/20',
      badgeBg: 'bg-[#a0c9ff]/10',
      badgeText: 'text-[#a0c9ff]',
      badgeBorder: 'border-[#a0c9ff]/20',
    },
    accuracy: '91% Churn Signal Detection',
    features: [
      'Omnichannel NLP Sentiment Parser',
      'Tenant NPS Real-Time Heatmaps',
      'Priority Escalation Router',
      'AI Response Suggestion Engine',
    ],
    rating: 4.7,
    reviewsCount: 84,
    activeTeams: 29,
    provider: 'Tenant Voice AI',
  },
  {
    id: 'dark-fiber-security',
    title: 'Dark Fiber Security',
    description: 'Military-grade encryption for property IoT networks and critical data transmissions.',
    category: 'Security',
    badge: 'PROTECT',
    priceMonthly: 550,
    priceYearly: 440,
    iconName: 'lock',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#ffb4ab]',
      border: 'border-[#ffb4ab]/20',
      badgeBg: 'bg-[#ffb4ab]/10',
      badgeText: 'text-[#ffb4ab]',
      badgeBorder: 'border-[#ffb4ab]/20',
    },
    accuracy: 'Zero-Trust Protocol',
    features: [
      'Hardware-Enforced Encryption',
      'Intrusion Prevention System (IPS)',
      'Air-gapped Key Rotations',
      'Access Log Anomaly Detection',
    ],
    rating: 5.0,
    reviewsCount: 62,
    activeTeams: 19,
    provider: 'Aegis Cyber Defense',
  },
  {
    id: 'esg-performance-monitor',
    title: 'ESG Performance Monitor',
    description: 'Automated environmental, social, and governance reporting for institutional investors.',
    category: 'Compliance',
    badge: 'ESG',
    priceMonthly: 420,
    priceYearly: 336,
    iconName: 'leaf',
    colorTheme: {
      bg: 'bg-[#121414]',
      text: 'text-[#dab9ff]',
      border: 'border-[#dab9ff]/20',
      badgeBg: 'bg-[#dab9ff]/10',
      badgeText: 'text-[#dab9ff]',
      badgeBorder: 'border-[#dab9ff]/20',
    },
    accuracy: 'GRESB & LEED Compliant',
    features: [
      'Utility Meter IoT Ingestion',
      'Carbon Emissions Calculator',
      'Institutional Investor Export',
      'Green Building Certification Sync',
    ],
    rating: 4.85,
    reviewsCount: 114,
    activeTeams: 31,
    provider: 'EcoMetric Analytics',
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  { id: '1', name: 'John Doe', initials: 'JD', bgColor: 'bg-[#479ef5]', textColor: 'text-[#001c37]', role: 'Portfolio Manager' },
  { id: '2', name: 'Alex Smith', initials: 'AS', bgColor: 'bg-[#5a3289]', textColor: 'text-[#cda3ff]', role: 'Risk Analyst' },
  { id: '3', name: 'Elena Rostova', initials: 'ER', bgColor: 'bg-[#333535]', textColor: 'text-[#e2e2e2]', role: 'Compliance Officer' },
  { id: '4', name: 'Michael Chen', initials: 'MC', bgColor: 'bg-[#00497f]', textColor: 'text-[#a0c9ff]', role: 'Property Director' },
  { id: '5', name: 'Sarah Jenkins', initials: 'SJ', bgColor: 'bg-[#2a0053]', textColor: 'text-[#dab9ff]', role: 'Operations Lead' },
];

export const MOCK_DASHBOARD_METRICS: DashboardMetric[] = [
  { id: 'delinquency-rate', title: 'Tenant Delinquency Rate', value: '1.8%', change: '-0.4%', isPositive: true, chartData: [3.2, 2.8, 2.4, 2.1, 1.9, 1.8] },
  { id: 'occupancy-score', title: 'Portfolio Occupancy', value: '96.4%', change: '+1.2%', isPositive: true, chartData: [92, 93.5, 94.1, 95.2, 95.8, 96.4] },
  { id: 'risk-exposure', title: 'Asset Volatility Score', value: 'Low (12)', change: '-3 pts', isPositive: true, chartData: [24, 20, 18, 15, 14, 12] },
  { id: 'compliance-audit', title: 'Compliance Coverage', value: '99.2%', change: '+0.5%', isPositive: true, chartData: [95, 96.8, 97.4, 98.1, 98.9, 99.2] },
];
