/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConsentInviteLinkInput,
  ConsentInviteLinkResponse,
  CreateMspCustomerInput,
  ListMspCustomersParams,
  MspAuthLogout200,
  MspAuthResponse,
  MspCustomer,
  MspCustomerList,
  MspDashboard,
  MspErrorResponse,
  MspLoginInput,
  MspSettings,
  MspTenant,
  MspTierList,
  MspUserProfile,
  UpdateMspCustomerInput,
  UpdateMspSettingsInput
} from './mspApi.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getMspAuthLoginUrl = () => {




  return `/api/msp/auth/login`
}

/**
 * @summary Log in to the MSP portal
 */
export const mspAuthLogin = async (mspLoginInput: MspLoginInput, options?: RequestInit): Promise<MspAuthResponse> => {

  return customFetch<MspAuthResponse>(getMspAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      mspLoginInput,)
  }
);}




export const getMspAuthLoginMutationOptions = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mspAuthLogin>>, TError,{data: BodyType<MspLoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof mspAuthLogin>>, TError,{data: BodyType<MspLoginInput>}, TContext> => {

const mutationKey = ['mspAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mspAuthLogin>>, {data: BodyType<MspLoginInput>}> = (props) => {
          const {data} = props ?? {};

          return  mspAuthLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MspAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof mspAuthLogin>>>
    export type MspAuthLoginMutationBody = BodyType<MspLoginInput>
    export type MspAuthLoginMutationError = ErrorType<MspErrorResponse>

    /**
 * @summary Log in to the MSP portal
 */
export const useMspAuthLogin = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mspAuthLogin>>, TError,{data: BodyType<MspLoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof mspAuthLogin>>,
        TError,
        {data: BodyType<MspLoginInput>},
        TContext
      > => {
      return useMutation(getMspAuthLoginMutationOptions(options));
    }

export const getMspAuthRefreshUrl = () => {




  return `/api/msp/auth/refresh`
}

/**
 * @summary Refresh MSP access token using httpOnly cookie
 */
export const mspAuthRefresh = async ( options?: RequestInit): Promise<MspAuthResponse> => {

  return customFetch<MspAuthResponse>(getMspAuthRefreshUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getMspAuthRefreshMutationOptions = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mspAuthRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof mspAuthRefresh>>, TError,void, TContext> => {

const mutationKey = ['mspAuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mspAuthRefresh>>, void> = () => {


          return  mspAuthRefresh(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MspAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof mspAuthRefresh>>>

    export type MspAuthRefreshMutationError = ErrorType<MspErrorResponse>

    /**
 * @summary Refresh MSP access token using httpOnly cookie
 */
export const useMspAuthRefresh = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mspAuthRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof mspAuthRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getMspAuthRefreshMutationOptions(options));
    }

export const getMspAuthLogoutUrl = () => {




  return `/api/msp/auth/logout`
}

/**
 * @summary Log out and clear the refresh token cookie
 */
export const mspAuthLogout = async ( options?: RequestInit): Promise<MspAuthLogout200> => {

  return customFetch<MspAuthLogout200>(getMspAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getMspAuthLogoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mspAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof mspAuthLogout>>, TError,void, TContext> => {

const mutationKey = ['mspAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mspAuthLogout>>, void> = () => {


          return  mspAuthLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MspAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof mspAuthLogout>>>

    export type MspAuthLogoutMutationError = ErrorType<unknown>

    /**
 * @summary Log out and clear the refresh token cookie
 */
export const useMspAuthLogout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mspAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof mspAuthLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getMspAuthLogoutMutationOptions(options));
    }

export const getMspAuthMeUrl = () => {




  return `/api/msp/auth/me`
}

/**
 * @summary Return the currently authenticated user's profile
 */
export const mspAuthMe = async ( options?: RequestInit): Promise<MspUserProfile> => {

  return customFetch<MspUserProfile>(getMspAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getMspAuthMeQueryKey = () => {
    return [
    `/api/msp/auth/me`
    ] as const;
    }


export const getMspAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof mspAuthMe>>, TError = ErrorType<MspErrorResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof mspAuthMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMspAuthMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof mspAuthMe>>> = ({ signal }) => mspAuthMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof mspAuthMe>>, TError, TData> & { queryKey: QueryKey }
}

export type MspAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof mspAuthMe>>>
export type MspAuthMeQueryError = ErrorType<MspErrorResponse>


/**
 * @summary Return the currently authenticated user's profile
 */

export function useMspAuthMe<TData = Awaited<ReturnType<typeof mspAuthMe>>, TError = ErrorType<MspErrorResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof mspAuthMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getMspAuthMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetPortalTenantUrl = (slug: string,) => {




  return `/api/portal/tenant/${slug}`
}

/**
 * @summary Resolve a tenant slug to its MSP record (used for portal branding)
 */
export const getPortalTenant = async (slug: string, options?: RequestInit): Promise<MspTenant> => {

  return customFetch<MspTenant>(getGetPortalTenantUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPortalTenantQueryKey = (slug: string,) => {
    return [
    `/api/portal/tenant/${slug}`
    ] as const;
    }


export const getGetPortalTenantQueryOptions = <TData = Awaited<ReturnType<typeof getPortalTenant>>, TError = ErrorType<MspErrorResponse>>(slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPortalTenant>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPortalTenantQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPortalTenant>>> = ({ signal }) => getPortalTenant(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPortalTenant>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPortalTenantQueryResult = NonNullable<Awaited<ReturnType<typeof getPortalTenant>>>
export type GetPortalTenantQueryError = ErrorType<MspErrorResponse>


/**
 * @summary Resolve a tenant slug to its MSP record (used for portal branding)
 */

export function useGetPortalTenant<TData = Awaited<ReturnType<typeof getPortalTenant>>, TError = ErrorType<MspErrorResponse>>(
 slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPortalTenant>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPortalTenantQueryOptions(slug,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetMspDashboardUrl = () => {




  return `/api/msp/dashboard`
}

/**
 * @summary Return MSP KPI dashboard metrics
 */
export const getMspDashboard = async ( options?: RequestInit): Promise<MspDashboard> => {

  return customFetch<MspDashboard>(getGetMspDashboardUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMspDashboardQueryKey = () => {
    return [
    `/api/msp/dashboard`
    ] as const;
    }


export const getGetMspDashboardQueryOptions = <TData = Awaited<ReturnType<typeof getMspDashboard>>, TError = ErrorType<MspErrorResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMspDashboard>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMspDashboardQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMspDashboard>>> = ({ signal }) => getMspDashboard({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMspDashboard>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMspDashboardQueryResult = NonNullable<Awaited<ReturnType<typeof getMspDashboard>>>
export type GetMspDashboardQueryError = ErrorType<MspErrorResponse>


/**
 * @summary Return MSP KPI dashboard metrics
 */

export function useGetMspDashboard<TData = Awaited<ReturnType<typeof getMspDashboard>>, TError = ErrorType<MspErrorResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMspDashboard>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMspDashboardQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListMspCustomersUrl = (params?: ListMspCustomersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/msp/customers?${stringifiedParams}` : `/api/msp/customers`
}

/**
 * @summary List customers for the authenticated MSP
 */
export const listMspCustomers = async (params?: ListMspCustomersParams, options?: RequestInit): Promise<MspCustomerList> => {

  return customFetch<MspCustomerList>(getListMspCustomersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMspCustomersQueryKey = (params?: ListMspCustomersParams,) => {
    return [
    `/api/msp/customers`, ...(params ? [params] : [])
    ] as const;
    }


export const getListMspCustomersQueryOptions = <TData = Awaited<ReturnType<typeof listMspCustomers>>, TError = ErrorType<MspErrorResponse>>(params?: ListMspCustomersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMspCustomers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMspCustomersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMspCustomers>>> = ({ signal }) => listMspCustomers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMspCustomers>>, TError, TData> & { queryKey: QueryKey }
}

export type ListMspCustomersQueryResult = NonNullable<Awaited<ReturnType<typeof listMspCustomers>>>
export type ListMspCustomersQueryError = ErrorType<MspErrorResponse>


/**
 * @summary List customers for the authenticated MSP
 */

export function useListMspCustomers<TData = Awaited<ReturnType<typeof listMspCustomers>>, TError = ErrorType<MspErrorResponse>>(
 params?: ListMspCustomersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMspCustomers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListMspCustomersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateMspCustomerUrl = () => {




  return `/api/msp/customers`
}

/**
 * @summary Create a new customer under the authenticated MSP
 */
export const createMspCustomer = async (createMspCustomerInput: CreateMspCustomerInput, options?: RequestInit): Promise<MspCustomer> => {

  return customFetch<MspCustomer>(getCreateMspCustomerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createMspCustomerInput,)
  }
);}




export const getCreateMspCustomerMutationOptions = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMspCustomer>>, TError,{data: BodyType<CreateMspCustomerInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createMspCustomer>>, TError,{data: BodyType<CreateMspCustomerInput>}, TContext> => {

const mutationKey = ['createMspCustomer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMspCustomer>>, {data: BodyType<CreateMspCustomerInput>}> = (props) => {
          const {data} = props ?? {};

          return  createMspCustomer(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMspCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof createMspCustomer>>>
    export type CreateMspCustomerMutationBody = BodyType<CreateMspCustomerInput>
    export type CreateMspCustomerMutationError = ErrorType<MspErrorResponse>

    /**
 * @summary Create a new customer under the authenticated MSP
 */
export const useCreateMspCustomer = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMspCustomer>>, TError,{data: BodyType<CreateMspCustomerInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createMspCustomer>>,
        TError,
        {data: BodyType<CreateMspCustomerInput>},
        TContext
      > => {
      return useMutation(getCreateMspCustomerMutationOptions(options));
    }

export const getGetMspCustomerUrl = (id: number,) => {




  return `/api/msp/customers/${id}`
}

/**
 * @summary Get a single customer record
 */
export const getMspCustomer = async (id: number, options?: RequestInit): Promise<MspCustomer> => {

  return customFetch<MspCustomer>(getGetMspCustomerUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMspCustomerQueryKey = (id: number,) => {
    return [
    `/api/msp/customers/${id}`
    ] as const;
    }


export const getGetMspCustomerQueryOptions = <TData = Awaited<ReturnType<typeof getMspCustomer>>, TError = ErrorType<MspErrorResponse>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMspCustomer>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMspCustomerQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMspCustomer>>> = ({ signal }) => getMspCustomer(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMspCustomer>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMspCustomerQueryResult = NonNullable<Awaited<ReturnType<typeof getMspCustomer>>>
export type GetMspCustomerQueryError = ErrorType<MspErrorResponse>


/**
 * @summary Get a single customer record
 */

export function useGetMspCustomer<TData = Awaited<ReturnType<typeof getMspCustomer>>, TError = ErrorType<MspErrorResponse>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMspCustomer>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMspCustomerQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateMspCustomerUrl = (id: number,) => {




  return `/api/msp/customers/${id}`
}

/**
 * @summary Update a customer record
 */
export const updateMspCustomer = async (id: number,
    updateMspCustomerInput: UpdateMspCustomerInput, options?: RequestInit): Promise<MspCustomer> => {

  return customFetch<MspCustomer>(getUpdateMspCustomerUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateMspCustomerInput,)
  }
);}




export const getUpdateMspCustomerMutationOptions = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMspCustomer>>, TError,{id: number;data: BodyType<UpdateMspCustomerInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMspCustomer>>, TError,{id: number;data: BodyType<UpdateMspCustomerInput>}, TContext> => {

const mutationKey = ['updateMspCustomer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMspCustomer>>, {id: number;data: BodyType<UpdateMspCustomerInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateMspCustomer(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMspCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof updateMspCustomer>>>
    export type UpdateMspCustomerMutationBody = BodyType<UpdateMspCustomerInput>
    export type UpdateMspCustomerMutationError = ErrorType<MspErrorResponse>

    /**
 * @summary Update a customer record
 */
export const useUpdateMspCustomer = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMspCustomer>>, TError,{id: number;data: BodyType<UpdateMspCustomerInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateMspCustomer>>,
        TError,
        {id: number;data: BodyType<UpdateMspCustomerInput>},
        TContext
      > => {
      return useMutation(getUpdateMspCustomerMutationOptions(options));
    }

export const getListMspSignupTiersUrl = () => {




  return `/api/msp/signup/tiers`
}

/**
 * @summary List available MSP subscription tiers
 */
export const listMspSignupTiers = async ( options?: RequestInit): Promise<MspTierList> => {

  return customFetch<MspTierList>(getListMspSignupTiersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMspSignupTiersQueryKey = () => {
    return [
    `/api/msp/signup/tiers`
    ] as const;
    }


export const getListMspSignupTiersQueryOptions = <TData = Awaited<ReturnType<typeof listMspSignupTiers>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMspSignupTiers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMspSignupTiersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMspSignupTiers>>> = ({ signal }) => listMspSignupTiers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMspSignupTiers>>, TError, TData> & { queryKey: QueryKey }
}

export type ListMspSignupTiersQueryResult = NonNullable<Awaited<ReturnType<typeof listMspSignupTiers>>>
export type ListMspSignupTiersQueryError = ErrorType<unknown>


/**
 * @summary List available MSP subscription tiers
 */

export function useListMspSignupTiers<TData = Awaited<ReturnType<typeof listMspSignupTiers>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMspSignupTiers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListMspSignupTiersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetMspSettingsUrl = () => {




  return `/api/msp/settings`
}

/**
 * @summary Return MSP organisation settings
 */
export const getMspSettings = async ( options?: RequestInit): Promise<MspSettings> => {

  return customFetch<MspSettings>(getGetMspSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMspSettingsQueryKey = () => {
    return [
    `/api/msp/settings`
    ] as const;
    }


export const getGetMspSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getMspSettings>>, TError = ErrorType<MspErrorResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMspSettings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMspSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMspSettings>>> = ({ signal }) => getMspSettings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMspSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMspSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getMspSettings>>>
export type GetMspSettingsQueryError = ErrorType<MspErrorResponse>


/**
 * @summary Return MSP organisation settings
 */

export function useGetMspSettings<TData = Awaited<ReturnType<typeof getMspSettings>>, TError = ErrorType<MspErrorResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMspSettings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMspSettingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateMspSettingsUrl = () => {




  return `/api/msp/settings`
}

/**
 * @summary Update MSP organisation settings
 */
export const updateMspSettings = async (updateMspSettingsInput: UpdateMspSettingsInput, options?: RequestInit): Promise<MspSettings> => {

  return customFetch<MspSettings>(getUpdateMspSettingsUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateMspSettingsInput,)
  }
);}




export const getUpdateMspSettingsMutationOptions = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMspSettings>>, TError,{data: BodyType<UpdateMspSettingsInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMspSettings>>, TError,{data: BodyType<UpdateMspSettingsInput>}, TContext> => {

const mutationKey = ['updateMspSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMspSettings>>, {data: BodyType<UpdateMspSettingsInput>}> = (props) => {
          const {data} = props ?? {};

          return  updateMspSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMspSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof updateMspSettings>>>
    export type UpdateMspSettingsMutationBody = BodyType<UpdateMspSettingsInput>
    export type UpdateMspSettingsMutationError = ErrorType<MspErrorResponse>

    /**
 * @summary Update MSP organisation settings
 */
export const useUpdateMspSettings = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMspSettings>>, TError,{data: BodyType<UpdateMspSettingsInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateMspSettings>>,
        TError,
        {data: BodyType<UpdateMspSettingsInput>},
        TContext
      > => {
      return useMutation(getUpdateMspSettingsMutationOptions(options));
    }

export const getCreateConsentInviteLinkUrl = () => {




  return `/api/consent/invite-link`
}

/**
 * @summary Generate a single-use Microsoft admin-consent invite link
 */
export const createConsentInviteLink = async (consentInviteLinkInput: ConsentInviteLinkInput, options?: RequestInit): Promise<ConsentInviteLinkResponse> => {

  return customFetch<ConsentInviteLinkResponse>(getCreateConsentInviteLinkUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      consentInviteLinkInput,)
  }
);}




export const getCreateConsentInviteLinkMutationOptions = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConsentInviteLink>>, TError,{data: BodyType<ConsentInviteLinkInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createConsentInviteLink>>, TError,{data: BodyType<ConsentInviteLinkInput>}, TContext> => {

const mutationKey = ['createConsentInviteLink'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createConsentInviteLink>>, {data: BodyType<ConsentInviteLinkInput>}> = (props) => {
          const {data} = props ?? {};

          return  createConsentInviteLink(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateConsentInviteLinkMutationResult = NonNullable<Awaited<ReturnType<typeof createConsentInviteLink>>>
    export type CreateConsentInviteLinkMutationBody = BodyType<ConsentInviteLinkInput>
    export type CreateConsentInviteLinkMutationError = ErrorType<MspErrorResponse>

    /**
 * @summary Generate a single-use Microsoft admin-consent invite link
 */
export const useCreateConsentInviteLink = <TError = ErrorType<MspErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConsentInviteLink>>, TError,{data: BodyType<ConsentInviteLinkInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createConsentInviteLink>>,
        TError,
        {data: BodyType<ConsentInviteLinkInput>},
        TContext
      > => {
      return useMutation(getCreateConsentInviteLinkMutationOptions(options));
    }

