/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
export interface MspLoginInput {
  email: string;
  /** @minLength 1 */
  password: string;
  /** The MSP's portal slug */
  slug: string;
  /** TOTP code for MFA-enabled accounts */
  totpCode?: string;
}

export type MspUserProfileRole = typeof MspUserProfileRole[keyof typeof MspUserProfileRole];


export const MspUserProfileRole = {
  admin: 'admin',
  user: 'user',
} as const;

export type MspUserProfileMspRole = typeof MspUserProfileMspRole[keyof typeof MspUserProfileMspRole] | null;


export const MspUserProfileMspRole = {
  PlatformAdmin: 'PlatformAdmin',
  MSPAdmin: 'MSPAdmin',
  MSPOperator: 'MSPOperator',
  Customer: 'Customer',
  ServiceAccount: 'ServiceAccount',
  Free: 'Free',
} as const;

export interface MspUserProfile {
  id: number;
  email: string;
  name?: string | null;
  role: MspUserProfileRole;
  mspRole?: MspUserProfileMspRole;
  mspId?: number | null;
  mspSlug?: string | null;
  customerId?: number | null;
}

export interface MspAuthResponse {
  accessToken: string;
  user: MspUserProfile;
}

export interface MspTenant {
  id: number;
  slug: string;
  name: string;
  logoUrl?: string | null;
  primaryColor?: string | null;
  status?: string;
}

export type MspDashboardMsp = {
  id?: number;
  name?: string;
  status?: string;
  offboardingState?: string | null;
} | null;

export type MspDashboardCustomers = {
  total?: number;
  active?: number;
  inactive?: number;
  suspended?: number;
};

export type MspDashboardSignals = {
  firedThisMonth?: number;
};

export type MspDashboardOffers = {
  sentThisMonth?: number;
  acceptedThisMonth?: number;
  acceptanceRate?: number;
  unacceptedCount?: number;
};

export type MspDashboardRevenue = {
  totalThisMonthCents?: number;
};

export type MspDashboardAi = {
  creditsRemaining?: number | null;
  creditLimit?: number | null;
};

export interface MspDashboard {
  msp?: MspDashboardMsp;
  customers?: MspDashboardCustomers;
  signals?: MspDashboardSignals;
  offers?: MspDashboardOffers;
  revenue?: MspDashboardRevenue;
  ai?: MspDashboardAi;
}

export type MspCustomerStatus = typeof MspCustomerStatus[keyof typeof MspCustomerStatus];


export const MspCustomerStatus = {
  active: 'active',
  inactive: 'inactive',
  onboarding: 'onboarding',
  archived: 'archived',
  suspended: 'suspended',
  offboarding: 'offboarding',
} as const;

export interface MspCustomer {
  id: number;
  mspId?: number;
  name: string;
  domain?: string | null;
  industry?: string | null;
  status: MspCustomerStatus;
  tenantId?: string | null;
  tenantUrl?: string | null;
  isTestbed?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export type MspCustomerListItemStatus = typeof MspCustomerListItemStatus[keyof typeof MspCustomerListItemStatus];


export const MspCustomerListItemStatus = {
  active: 'active',
  inactive: 'inactive',
  onboarding: 'onboarding',
  archived: 'archived',
} as const;

export interface MspCustomerListItem {
  id: number;
  name: string;
  domain?: string | null;
  status: MspCustomerListItemStatus;
  tenantId?: string | null;
  mspId: number;
  createdAt: string;
  seats?: number | null;
  people?: number | null;
  lastScanAt?: string | null;
  openSignals: number;
  /** The subset of `openSignals` whose signal definition is severity "critical" (Git */
  criticalSignals: number;
}

export interface MspCustomerList {
  customers: MspCustomerListItem[];
  total: number;
  page: number;
  pageSize: number;
}

export type CreateMspCustomerInputStatus = typeof CreateMspCustomerInputStatus[keyof typeof CreateMspCustomerInputStatus];


export const CreateMspCustomerInputStatus = {
  active: 'active',
  onboarding: 'onboarding',
  inactive: 'inactive',
} as const;

export interface CreateMspCustomerInput {
  /**
     * @minLength 2
     * @maxLength 200
     */
  name: string;
  domain?: string;
  industry?: string;
  /**
     * @minLength 1
     * @maxLength 36
     */
  tenantId: string;
  status?: CreateMspCustomerInputStatus;
}

export type UpdateMspCustomerInputStatus = typeof UpdateMspCustomerInputStatus[keyof typeof UpdateMspCustomerInputStatus];


export const UpdateMspCustomerInputStatus = {
  active: 'active',
  inactive: 'inactive',
  onboarding: 'onboarding',
  archived: 'archived',
} as const;

export interface UpdateMspCustomerInput {
  /**
     * @minLength 2
     * @maxLength 200
     */
  name?: string;
  domain?: string | null;
  industry?: string | null;
  status?: UpdateMspCustomerInputStatus;
}

export interface MspTier {
  id: number;
  slug?: string | null;
  name: string;
  description?: string | null;
  tagline?: string | null;
  price?: string | null;
  tenantAllowance?: number | null;
  aiCreditAllowance?: number | null;
  overageRateCents?: number | null;
  features?: string[] | null;
  badge?: string | null;
  highlighted?: boolean;
}

export interface MspTierList {
  tiers: MspTier[];
}

export interface MspSettings {
  companyName?: string | null;
  domain?: string | null;
  logoUrl?: string | null;
  primaryColor?: string | null;
  supportEmail?: string | null;
  timezone?: string | null;
}

export interface UpdateMspSettingsInput {
  companyName?: string;
  domain?: string;
  logoUrl?: string;
  primaryColor?: string;
  supportEmail?: string;
  timezone?: string;
}

export interface ConsentInviteLinkInput {
  /** Azure AD tenant ID hint (use "common" to allow any tenant) */
  tenantId?: string;
  customerId?: number;
  clientUserId?: number;
  /**
     * @minimum 1
     * @maximum 168
     */
  ttlHours?: number;
}

export interface ConsentInviteLinkResponse {
  consentUrl: string;
  token: string;
  expiresAt: string;
  scopes: string[];
}

export type MspErrorResponseDetails = { [key: string]: unknown };

export interface MspErrorResponse {
  error: string;
  details?: MspErrorResponseDetails;
}

export type MspAuthLogout200 = {
  ok?: boolean;
};

export type ListMspCustomersParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Filter by customer name or domain
 */
search?: string;
status?: ListMspCustomersStatus;
};

export type ListMspCustomersStatus = typeof ListMspCustomersStatus[keyof typeof ListMspCustomersStatus];


export const ListMspCustomersStatus = {
  active: 'active',
  inactive: 'inactive',
  onboarding: 'onboarding',
  all: 'all',
} as const;

