/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
export interface MspLoginInput {
  email: string;
  /** @minLength 1 */
  password: string;
  /** The MSP's portal slug */
  slug: string;
  /** TOTP code for MFA-enabled accounts */
  totpCode?: string;
}

export type MspUserProfileRole = typeof MspUserProfileRole[keyof typeof MspUserProfileRole];


export const MspUserProfileRole = {
  admin: 'admin',
  user: 'user',
} as const;

export type MspUserProfileMspRole = typeof MspUserProfileMspRole[keyof typeof MspUserProfileMspRole] | null;


export const MspUserProfileMspRole = {
  PlatformAdmin: 'PlatformAdmin',
  MSPAdmin: 'MSPAdmin',
  MSPOperator: 'MSPOperator',
  CustomerUser: 'CustomerUser',
  ServiceAccount: 'ServiceAccount',
  Free: 'Free',
} as const;

export interface MspUserProfile {
  id: number;
  email: string;
  name?: string | null;
  role: MspUserProfileRole;
  mspRole?: MspUserProfileMspRole;
  mspId?: number | null;
  mspSlug?: string | null;
  customerId?: number | null;
}

export interface MspAuthResponse {
  accessToken: string;
  user: MspUserProfile;
}

export interface MspTenant {
  id: number;
  slug: string;
  name: string;
  logoUrl?: string | null;
  primaryColor?: string | null;
  status?: string;
}

export type MspDashboardMsp = {
  id?: number;
  name?: string;
  status?: string;
  offboardingState?: string | null;
} | null;

export type MspDashboardCustomers = {
  total?: number;
  active?: number;
  inactive?: number;
  suspended?: number;
};

export type MspDashboardSignals = {
  firedThisMonth?: number;
};

export type MspDashboardOffers = {
  sentThisMonth?: number;
  acceptedThisMonth?: number;
  acceptanceRate?: number;
  unacceptedCount?: number;
};

export type MspDashboardRevenue = {
  totalThisMonthCents?: number;
};

export type MspDashboardAi = {
  creditsRemaining?: number | null;
  creditLimit?: number | null;
};

export interface MspDashboard {
  msp?: MspDashboardMsp;
  customers?: MspDashboardCustomers;
  signals?: MspDashboardSignals;
  offers?: MspDashboardOffers;
  revenue?: MspDashboardRevenue;
  ai?: MspDashboardAi;
}

export type MspCustomerStatus = typeof MspCustomerStatus[keyof typeof MspCustomerStatus];


export const MspCustomerStatus = {
  active: 'active',
  inactive: 'inactive',
  suspended: 'suspended',
  offboarding: 'offboarding',
} as const;

export interface MspCustomer {
  id: number;
  mspId?: number;
  companyName: string;
  domain?: string | null;
  status: MspCustomerStatus;
  contactName?: string | null;
  contactEmail?: string | null;
  tenantId?: string | null;
  createdAt?: string;
}

export interface MspCustomerList {
  customers: MspCustomer[];
  total: number;
  page: number;
  limit: number;
}

export interface CreateMspCustomerInput {
  /** @minLength 1 */
  companyName: string;
  domain?: string;
  contactName?: string;
  contactEmail?: string;
  tenantId?: string;
}

export type UpdateMspCustomerInputStatus = typeof UpdateMspCustomerInputStatus[keyof typeof UpdateMspCustomerInputStatus];


export const UpdateMspCustomerInputStatus = {
  active: 'active',
  inactive: 'inactive',
  suspended: 'suspended',
} as const;

export interface UpdateMspCustomerInput {
  /** @minLength 1 */
  companyName?: string;
  domain?: string;
  contactName?: string;
  contactEmail?: string;
  status?: UpdateMspCustomerInputStatus;
}

export interface MspTier {
  id: number;
  slug?: string | null;
  name: string;
  description?: string | null;
  tagline?: string | null;
  price?: string | null;
  tenantAllowance?: number | null;
  aiCreditAllowance?: number | null;
  overageRateCents?: number | null;
  features?: string[] | null;
  badge?: string | null;
  highlighted?: boolean;
}

export interface MspTierList {
  tiers: MspTier[];
}

export interface MspSettings {
  companyName?: string | null;
  domain?: string | null;
  logoUrl?: string | null;
  primaryColor?: string | null;
  supportEmail?: string | null;
  timezone?: string | null;
}

export interface UpdateMspSettingsInput {
  companyName?: string;
  domain?: string;
  logoUrl?: string;
  primaryColor?: string;
  supportEmail?: string;
  timezone?: string;
}

export interface ConsentInviteLinkInput {
  /** Azure AD tenant ID hint (use "common" to allow any tenant) */
  tenantId?: string;
  customerId?: number;
  clientUserId?: number;
  /**
     * @minimum 1
     * @maximum 168
     */
  ttlHours?: number;
}

export interface ConsentInviteLinkResponse {
  consentUrl: string;
  token: string;
  expiresAt: string;
  scopes: string[];
}

export type MspErrorResponseDetails = { [key: string]: unknown };

export interface MspErrorResponse {
  error: string;
  details?: MspErrorResponseDetails;
}

export type MspAuthLogout200 = {
  ok?: boolean;
};

export type ListMspCustomersParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * Filter by company name or domain
 */
search?: string;
status?: ListMspCustomersStatus;
};

export type ListMspCustomersStatus = typeof ListMspCustomersStatus[keyof typeof ListMspCustomersStatus];


export const ListMspCustomersStatus = {
  active: 'active',
  inactive: 'inactive',
  all: 'all',
} as const;

