-- 2026-07-23-simulator-check-runs.sql
--
-- Simulator Studio — M365 Endpoints node, Phase 3 (Run History + Bulk Run).
--
-- Creates the durable home for ad-hoc Simulator Studio check runs. Until now
-- run tracking lived entirely in an in-memory Map inside
-- artifacts/api-server/src/routes/admin-monitor-check-runs.ts, so every run was
-- lost on api-server restart and "run history" / "diff two runs" could not mean
-- anything. This table is that missing storage.
--
-- WHY A NEW TABLE RATHER THAN EXTENDING tenant_monitor_profiles
-- -------------------------------------------------------------
-- tenant_monitor_profiles is the production monitoring record: every row is read
-- back by mergeMonitorProfileRows()/buildTenantProfile() to compute a tenant's
-- real signal profile and pillar scores, and it is keyed on idempotency_key
-- precisely to prevent duplicate collection. Simulator runs are the opposite
-- kind of data — they deliberately pass skipIdempotency and re-run the same
-- check repeatedly against a testbed tenant. Putting operator-workflow state
-- (progress, status_text, batch grouping, a saved engine trace) and large
-- untruncated response payloads onto that table would (a) place ad-hoc test
-- metadata directly on the live signal path, (b) make "is this row real
-- monitoring data?" unanswerable from the row itself, and (c) grow the hottest
-- monitoring table with payloads nothing in production reads.
-- They also disagree on payload semantics: tenant_monitor_profiles.raw_response
-- deliberately holds only the FIRST page (and only five rows of a CSV usage
-- report), while a simulator run must keep the untruncated item list so the
-- engine trace can re-apply the real mapping without re-fetching.
--
-- executeMonitorCheck() still writes its normal tenant_monitor_profiles row on
-- every simulator run, so nothing that existed before is lost or moved — this
-- table is purely additive.
--
-- Safe to re-run (IF NOT EXISTS throughout).

CREATE TABLE IF NOT EXISTS simulator_check_runs (
  id                   SERIAL PRIMARY KEY,

  -- The runId the API returns and the UI polls. Generated by the route (the
  -- same uuid is passed to executeMonitorCheck as its triggerId, so a simulator
  -- run is traceable straight through to the tenant_monitor_profiles row it
  -- produced) — hence NOT defaulted here.
  run_id               UUID        NOT NULL UNIQUE,

  -- Set when this run was started as part of a bulk "run every check under this
  -- domain prefix" batch. NULL for a single run.
  batch_id             UUID,

  check_key            TEXT        NOT NULL,
  check_label          TEXT        NOT NULL,
  customer_id          INTEGER     NOT NULL,
  tenant_id            TEXT        NOT NULL,

  -- pending | running | completed | failed  (the existing status model, unchanged)
  status               TEXT        NOT NULL DEFAULT 'pending',
  status_text          TEXT        NOT NULL DEFAULT '',
  progress             INTEGER     NOT NULL DEFAULT 0,

  -- Denormalised from result, so the history list and bulk-run summary can
  -- aggregate ok/error/license_gap counts without loading every result payload.
  -- ok | error | consent_revoked | requires_script | license_gap
  result_status        TEXT,
  item_count           INTEGER,
  page_count           INTEGER,
  severity_matched     TEXT,
  license_feature      TEXT,
  error_message        TEXT,

  -- The real resolved request the executor was asked to run.
  request              JSONB       NOT NULL,
  -- The real CheckResult, minus items (which gets its own column below).
  result               JSONB,

  -- The FULL captured item list — never a truncated prefix. When a response is
  -- too large to persist, this stays NULL and items_omitted is set to TRUE, so
  -- the trace/diff routes refuse explicitly instead of computing a confident
  -- wrong number off a partial list.
  items                JSONB,
  items_omitted        BOOLEAN     NOT NULL DEFAULT FALSE,
  items_omitted_reason TEXT,

  -- Snapshotted at run time so a later catalog edit cannot retroactively change
  -- what this run's trace claims the response produced.
  mapping              JSONB       NOT NULL DEFAULT '[]'::jsonb,
  properties           JSONB       NOT NULL DEFAULT '[]'::jsonb,

  -- The last engine trace run against this run, if any.
  trace                JSONB,
  traced_at            TIMESTAMPTZ,

  started_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at         TIMESTAMPTZ,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS simulator_check_runs_run_id_idx
  ON simulator_check_runs (run_id);

-- The history list: most recent runs for one check.
CREATE INDEX IF NOT EXISTS simulator_check_runs_check_key_started_idx
  ON simulator_check_runs (check_key, started_at);

-- The bulk-run summary: every run in one batch.
CREATE INDEX IF NOT EXISTS simulator_check_runs_batch_id_idx
  ON simulator_check_runs (batch_id);

CREATE INDEX IF NOT EXISTS simulator_check_runs_customer_id_idx
  ON simulator_check_runs (customer_id);

-- Note on retention: the api-server prunes to the most recent
-- SIMULATOR_RUN_RETENTION_PER_CHECK runs per check_key on each insert
-- (simulator-run-store.ts), which is the durable replacement for the old
-- in-memory MAX_TRACKED_RUNS eviction. No scheduled job is required.
