-- ─────────────────────────────────────────────────────────────────────────────
-- Git #3466 — local Postgres persistence for BuildConsole's Test Pad notes
-- ─────────────────────────────────────────────────────────────────────────────
-- Real, live report: Test Pad notes were never surviving a BuildConsole restart.
-- Root cause (confirmed): `TestPadService` (desktop/BuildConsole/Services/TestPad/
-- TestPadService.cs) was a purely in-memory `static List<TestPadNote>` — no
-- load-on-startup, no save-on-change, no backing store at all. On process exit
-- every note was gone.
--
-- This is a NEW BuildConsole-local table, following the same direct-Npgsql,
-- DATABASE_URL-resolved convention as the other `bt_*` BuildConsole tables
-- (bt_build_queue, bt_issue_mirror, ...). One row per note; the C# store
-- (TestPadPersistence) load-on-startup seeds TestPadService and every mutation
-- funnel (Add/Update/Remove/MarkSent/selection) writes through to here.
--
-- Additive only (CREATE TABLE IF NOT EXISTS + indexes) — safe to run in-session
-- against the local dev DB per the project's manual-migration rule.

CREATE TABLE IF NOT EXISTS bt_test_pad_notes (
  -- TestPadNote.Id — a Guid formatted "N" (32 hex chars), generated client-side.
  id             TEXT PRIMARY KEY,
  text           TEXT NOT NULL DEFAULT '',
  -- NoteType enum NAME ('Note' | 'Bug' | 'Question' | 'Idea' | 'Works'). Stored as
  -- its real vocabulary string, not an ordinal, so a future enum reorder can't
  -- silently remap persisted rows.
  note_type      TEXT NOT NULL DEFAULT 'Note',
  -- Auto-stamped context captured by NoteContextStamper at file time. Nullable —
  -- a note filed before any context was resolvable keeps NULLs.
  screen         TEXT,
  feature        TEXT,
  build_number   INTEGER,
  created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  is_sent        BOOLEAN NOT NULL DEFAULT false,
  is_edited      BOOLEAN NOT NULL DEFAULT false,
  is_selected    BOOLEAN NOT NULL DEFAULT false,
  -- "Attach shot" arms a droppable thumbnail slot on the note. The BitmapSource
  -- image itself is NOT persisted (the attach-shot / PasteTray path isn't ported
  -- into BuildConsole — see TestPadWindow's class doc), only whether the slot was
  -- armed, so the row round-trips its layout intent without a binary blob.
  has_shot_slot  BOOLEAN NOT NULL DEFAULT false,
  -- Monotonic insertion order. The in-memory list inserts new notes at index 0
  -- (newest-first); this sequence lets load reconstruct that exact order
  -- (ORDER BY sort_seq DESC) regardless of created_at tick collisions during a
  -- bulk import.
  sort_seq       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS bt_test_pad_notes_sort_seq_idx
  ON bt_test_pad_notes (sort_seq DESC);

-- Self-marking run record so Simulator Studio's Migrations tree (Git #497)
-- reflects DB reality regardless of which console ran the file.
INSERT INTO simulator_migration_runs (filename, ran_at)
VALUES ('2026-09-10-bt-test-pad-notes-3466.sql', now())
ON CONFLICT (filename) DO UPDATE SET ran_at = now();
