-- Real Emergency MFA Bypass Code
-- Manual migration — review and run by hand (do not run drizzle-kit push/push --force).
--
-- Backs the "Generate Emergency Bypass Code" action in customer-team.tsx, which
-- previously produced a Math.random() fake code that nothing at login honored.
--
-- mfa_bypass_codes holds a transient, single-use emergency credential an MSP
-- admin issues for a team member locked out of their MFA device. Only the bcrypt
-- hash of the code is stored (the plaintext is shown to the admin exactly once);
-- the code carries a real 24h expiry and is single-use (used_at flips on
-- consumption). At most one active code per user is enforced in application code
-- at generation time (delete-then-insert). The code is:
--   * generated by  POST /portal/team/:userId/emergency-bypass  (portal.ts)
--   * consumed by    POST /auth/mfa/bypass                        (mfa.ts)
-- Both generation and use are recorded via createAuditLog (audit_logs).

CREATE TABLE IF NOT EXISTS "mfa_bypass_codes" (
  "id" serial PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "code_hash" text NOT NULL,
  "created_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "customer_id" integer,
  "expires_at" timestamp NOT NULL,
  "used_at" timestamp,
  "used_ip" text,
  "used_user_agent" text,
  "created_at" timestamp NOT NULL DEFAULT now()
);

-- Login-side consumption looks up the (single) active code by user_id.
CREATE INDEX IF NOT EXISTS "mfa_bypass_codes_user_id_idx" ON "mfa_bypass_codes" ("user_id");

-- user_sessions.login_method carries a DB-level CHECK constraint (see
-- 2026-07-19-user-sessions.sql). A bypass sign-in records a session with
-- login_method = 'bypass', so the constraint must admit that value — otherwise
-- the (best-effort) session-tracking insert would be rejected and bypass logins
-- would silently vanish from Active Sessions / Login History. Widen it.
ALTER TABLE "user_sessions" DROP CONSTRAINT IF EXISTS "user_sessions_login_method_check";
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_login_method_check"
  CHECK ("login_method" IN ('password', 'totp', 'sms', 'passkey', 'impersonation', 'bypass'));
