-- Decommission Legacy CRM — Phase B (#136, parent #77).
--
-- Run manually (per repo convention: no drizzle-kit push). Idempotent.
--
-- Prerequisite: the Phase A backfill
-- (2026-07-29-decommission-legacy-crm-phase-a.sql, PART 1) must already have
-- been run. Phase B re-points crm-pipeline.ts, lead-intent.ts and
-- workflow-executor.ts's find_object node at `lead_staging`; without that
-- backfill every one of those surfaces reads an empty table and honestly
-- reports nothing.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- opportunities.lead_id — NOT NULL → NULLABLE
-- ─────────────────────────────────────────────────────────────────────────────
-- `crm-pipeline.ts`'s ensureOpportunityForSow was the last writer keeping the
-- `opportunities` table pinned to the legacy `leads` id space (see #136's
-- cross-reference from #135). It now writes `lead_staging_id` — the pointer
-- #83 already added — and populates the legacy `lead_id` only when the staged
-- row still carries a `legacy_lead_id`.
--
-- A lead captured after this cutover has no `leads` row at all, so an
-- opportunity scored from it can only carry `lead_staging_id`. That is
-- impossible while `lead_id` is NOT NULL: the insert would fail and the
-- non-fatal catch in ensureOpportunityForSow would swallow it, so a SOW
-- delivery would silently stop producing an opportunity.
--
-- The FK to `leads(id)` is intentionally KEPT. Pre-cutover rows still point at
-- real `leads` rows, and the not-yet-re-pointed readers (routes/opportunities.ts,
-- routes/inbox.ts, routes/admin-marketing.ts, routes/ai-next-best-actions.ts)
-- still join on it. It goes away with the `leads` table itself, in the
-- follow-up issue that re-keys the satellite FK columns.

ALTER TABLE opportunities ALTER COLUMN lead_id DROP NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- NOT DROPPED IN THIS PHASE — deliberately.
-- ─────────────────────────────────────────────────────────────────────────────
-- #136 asked whether `opportunities` / `lead_qualifications` can finally be
-- dropped once crm-pipeline.ts stops writing `opportunities` directly. Audited
-- on 2026-07-29 against main: no. crm-pipeline.ts was not the only writer, and
-- both tables still have live readers and writers outside this phase's three
-- files:
--
--   opportunities        — routes/opportunities.ts (insert + 3 updates),
--                          routes/inbox.ts (insert), routes/leads.ts,
--                          routes/admin-marketing.ts, routes/admin-overview.ts,
--                          routes/analytics-forecast.ts,
--                          routes/ai-next-best-actions.ts
--   lead_qualifications  — routes/inbox.ts (insert + update),
--                          routes/leads.ts (insert + reads),
--                          routes/opportunities.ts (reads + 4 updates)
--
-- Six of those eight files are the ones #135 deliberately deferred, and
-- admin-overview.ts / analytics-forecast.ts are new to this audit. Both tables
-- stay live until that follow-up lands.
--
-- The legacy `leads` table likewise stays: `lead_intent_events.lead_id` and the
-- other nine satellite FK columns still store `leads.id`, and #114's scoring
-- engine (recomputeAndPersistHotScore, in lead-intent.ts) still reads `leads`
-- directly — explicitly out of this phase's scope.
