// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/orbital-sphere/OrbitalCommandSphere.tsx": () => import("../components/mockups/orbital-sphere/OrbitalCommandSphere.tsx"),
  "./components/mockups/sow-scope/SowScopeRedesign.tsx": () => import("../components/mockups/sow-scope/SowScopeRedesign.tsx")
};
