/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */

export interface ConsentInviteLinkInput {
  /** Azure AD tenant ID hint (use "common" to allow any tenant) */
  tenantId?: string;
  customerId?: number;
  clientUserId?: number;
  /**
     * @minimum 1
     * @maximum 168
     */
  ttlHours?: number;
}
