/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateMspCustomerInputStatus } from './createMspCustomerInputStatus';

export interface CreateMspCustomerInput {
  /**
     * @minLength 2
     * @maxLength 200
     */
  name: string;
  domain?: string;
  industry?: string;
  /**
     * @minLength 1
     * @maxLength 36
     */
  tenantId: string;
  status?: CreateMspCustomerInputStatus;
}
