/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */

export interface CreateMspCustomerInput {
  /** @minLength 1 */
  companyName: string;
  domain?: string;
  contactName?: string;
  contactEmail?: string;
  tenantId?: string;
}
