/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
import type { ListMspCustomersStatus } from './listMspCustomersStatus';

export type ListMspCustomersParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * Filter by company name or domain
 */
search?: string;
status?: ListMspCustomersStatus;
};
