/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
import type { MspCustomerStatus } from './mspCustomerStatus';

export interface MspCustomer {
  id: number;
  mspId?: number;
  companyName: string;
  domain?: string | null;
  status: MspCustomerStatus;
  contactName?: string | null;
  contactEmail?: string | null;
  tenantId?: string | null;
  createdAt?: Date;
}
