/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */

export type MspCustomerStatus = typeof MspCustomerStatus[keyof typeof MspCustomerStatus];


export const MspCustomerStatus = {
  active: 'active',
  inactive: 'inactive',
  suspended: 'suspended',
  offboarding: 'offboarding',
} as const;
