/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
import type { MspCustomerListItemStatus } from './mspCustomerListItemStatus';

export interface MspCustomerListItem {
  id: number;
  name: string;
  domain?: string | null;
  status: MspCustomerListItemStatus;
  tenantId?: string | null;
  mspId: number;
  createdAt: Date;
  seats?: number | null;
  people?: number | null;
  lastScanAt?: Date | null;
  openSignals: number;
  /** The subset of `openSignals` whose signal definition is severity "critical" (Git */
  criticalSignals: number;
}
