/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
import type { MspCustomerStatus } from './mspCustomerStatus';

export interface MspCustomer {
  id: number;
  mspId?: number;
  name: string;
  domain?: string | null;
  industry?: string | null;
  status: MspCustomerStatus;
  tenantId?: string | null;
  tenantUrl?: string | null;
  isTestbed?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}
