/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
import type { MspDashboardAi } from './mspDashboardAi.ts';
import type { MspDashboardCustomers } from './mspDashboardCustomers.ts';
import type { MspDashboardMsp } from './mspDashboardMsp.ts';
import type { MspDashboardOffers } from './mspDashboardOffers.ts';
import type { MspDashboardRevenue } from './mspDashboardRevenue.ts';
import type { MspDashboardSignals } from './mspDashboardSignals.ts';

export interface MspDashboard {
  msp?: MspDashboardMsp;
  customers?: MspDashboardCustomers;
  signals?: MspDashboardSignals;
  offers?: MspDashboardOffers;
  revenue?: MspDashboardRevenue;
  ai?: MspDashboardAi;
}
