/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */

export interface MspLoginInput {
  email: string;
  /** @minLength 1 */
  password: string;
  /** The MSP's portal slug */
  slug: string;
  /** TOTP code for MFA-enabled accounts */
  totpCode?: string;
}
