/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */

export interface MspTenant {
  id: number;
  slug: string;
  name: string;
  logoUrl?: string | null;
  primaryColor?: string | null;
  status?: string;
}
