/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */

export interface MspTier {
  id: number;
  slug?: string | null;
  name: string;
  description?: string | null;
  tagline?: string | null;
  price?: string | null;
  tenantAllowance?: number | null;
  aiCreditAllowance?: number | null;
  overageRateCents?: number | null;
  features?: string[] | null;
  badge?: string | null;
  highlighted?: boolean;
}
