/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
import type { MspUserProfileMspRole } from './mspUserProfileMspRole';
import type { MspUserProfileRole } from './mspUserProfileRole';

export interface MspUserProfile {
  id: number;
  email: string;
  name?: string | null;
  role: MspUserProfileRole;
  mspRole?: MspUserProfileMspRole;
  mspId?: number | null;
  mspSlug?: string | null;
  customerId?: number | null;
}
