/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */

export type MspUserProfileMspRole = typeof MspUserProfileMspRole[keyof typeof MspUserProfileMspRole] | null;


export const MspUserProfileMspRole = {
  PlatformAdmin: 'PlatformAdmin',
  MSPAdmin: 'MSPAdmin',
  MSPOperator: 'MSPOperator',
  CustomerUser: 'CustomerUser',
  ServiceAccount: 'ServiceAccount',
  Free: 'Free',
} as const;
