/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MspApi
 * MSP Portal API specification — covers authentication, MSP CRUD, customer management, and portal-facing endpoints.
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateMspCustomerInputStatus } from './updateMspCustomerInputStatus';

export interface UpdateMspCustomerInput {
  /** @minLength 1 */
  companyName?: string;
  domain?: string;
  contactName?: string;
  contactEmail?: string;
  status?: UpdateMspCustomerInputStatus;
}
