/**
 * ⚠️ TEMPORARY DEBUG CODE — DELETE BEFORE PRODUCTION ⚠️
 * This file renders a testbed-only debug scan trigger button (see the
 * "generating" case in StepPanel, guarded by `status.isTestbed`) that exists
 * only so scan progress can be watched live during development. It calls
 * POST /portal/assessment/debug-trigger-scan, which is hard-gated server-side to
 * isTestbed=true customers — this client-side check is only a second layer, not
 * the real safeguard. Must be fully removed before this flow reaches real
 * customers. See backlog: [Shane to add ticket].
 *
 * AssessmentWizard.tsx
 *
 * The Assessment flow container — the locked, sequential step experience that
 * mounts inside the Assessment shell. This is the *flow-control* surface only
 * (task 2): it moves the customer from "assessment ordered" through "all reports
 * finished generating", gating each step on its predecessor. It renders
 * placeholders where later tasks own the real content (document views, OMG
 * cards, the SOW selector, payment) — it never renders that content itself.
 *
 * What it wires together, all reusing existing platform mechanisms:
 *   - Live scan progress via the existing diagnostics SSE stream
 *     (/api/msp/customers/:id/diagnostics/runs/:runId/sse) — the same stream the
 *     CustomerUser Mission Control scan strip uses.
 *   - Document-generation wait state via polling GET /api/portal/assessment/status
 *     (insights documents expose no per-document SSE channel; their status column
 *     flipping generating → approved/delivered is the platform's completion signal).
 *   - The mandatory first-login MFA gate (AssessmentMfaEnrollment).
 *   - The first-login provisioning trigger (POST /portal/first-login/provision).
 */
import { useCallback, useEffect, useRef, useState } from "react";
import { useAuth } from "@/lib/auth-context";
import { useTheme } from "@/lib/theme-context";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ScoreRing, type ScoreRingColor } from "@/components/ui/score-ring";
import { AssessmentMfaEnrollment } from "./AssessmentMfaEnrollment";
import { AssessmentDocumentViewer } from "./AssessmentDocumentViewer";
import { AssessmentSowSelector } from "./AssessmentSowSelector";
import { AssessmentPaymentPlan } from "./AssessmentPaymentPlan";
// Real radar/spider chart renderer from the platform's dashboard web-part
// system — the same component real dashboards use for pillar-snapshot
// widgets (engine.pillarSnapshot). Aliased to avoid colliding with the
// lucide-react "Radar" icon already used as this step's PanelShell icon.
import { Radar as RadarChart, type DistributionWidgetData } from "@workspace/dashboard-canvas";
import {
  CheckCircle2,
  ChevronRight,
  Coins,
  FileText,
  FileSignature,
  CreditCard,
  ListChecks,
  Loader2,
  Lock,
  Quote,
  Radar,
  ScrollText,
  ShieldCheck,
  AlertTriangle,
  XCircle,
} from "lucide-react";

// ⚠️ TEMPORARY TESTING BYPASS — REMOVE BEFORE PRODUCTION ⚠️
// Mandatory MFA enrollment is a real security requirement — this flag only
// skips it for active testing. Must be removed/set to false before any real
// customer reaches this flow. See backlog: [Shane to add ticket].
const SKIP_MFA_GATE_FOR_TESTING = true;

// ── Status payload (mirrors GET /api/portal/assessment/status) ────────────────

interface AssessmentDocument {
  id: number;
  docType: string;
  category: string;
  title: string;
  status: string;
}

interface AssessmentStatus {
  scan: {
    active: boolean;
    runId: string | null;
    status: string | null;
    startedAt: string | null;
    checksTotal: number | null;
    checksOk: number | null;
    checksError: number | null;
    checksLicenseGap: number | null;
    licenseGapFeatures: string[];
    lastScanAt: string | null;
    everScanned: boolean;
  };
  documents: {
    items: AssessmentDocument[];
    // Real titles of every document the assessment service will generate (from
    // the service's associated-documents mapping), present from the moment the
    // customer lands here — before any `items` row exists — so the generation
    // checklist can be rendered by real name up front, not only as rows appear.
    expected: { docType: string; title: string }[];
    total: number;
    generating: number;
    ready: number;
    failed: number;
    allReady: boolean;
    // Live doc-generation workflow run: run ID for the progress SSE stream, and
    // its status as the reliable terminal signal (failed/cancelled → failure UI).
    workflowRunId: number | null;
    workflowStatus: string | null;
  };
  mfa: { enrolled: boolean };
  // CIO-Report Narrative — the "senior M365 Architect" narrative of this scan's
  // real, already-classified findings + real peer-benchmark data, generated by
  // cio-narrative-generator.ts as soon as the scan completes (independent of how
  // long document generation still has left). "not_started" until a completed
  // scan exists to narrate.
  narrative: {
    status: "not_started" | "generating" | "ready" | "failed";
    html: string | null;
    generatedAt: string | null;
  };
  // Real tenant-health radar — only pillars this customer's actual scanned
  // package genuinely covers (pillar-coverage.ts on the backend). Empty until
  // the package has real monitoring_package_checks rows curated for it.
  radar: {
    packageKey: string | null;
    pillars: { pillar: string; label: string; score: number }[];
  };
  // Real stat cards — every number traces to this run's own persisted summary
  // or a live cost-engine query; null means "no real data yet", never a
  // placeholder.
  stats: {
    genuineFindings: number | null;
    licenseWasteMonthlyCents: number | null;
  };
  // ⚠️ TEMPORARY DEBUG CODE — DELETE BEFORE PRODUCTION ⚠️ (see file header note)
  isTestbed: boolean;
}

// Live diagnostics SSE events (same discriminated union as Mission Control).
type DiagnosticsSSEEvent =
  | { type: "diagnostics_progress"; checkKey: string; checkLabel: string; status: string; index: number; total: number }
  | { type: "diagnostics_complete"; status: string; checksTotal: number; checksOk: number; checksError: number; findings: number }
  | { type: "diagnostics_error"; message: string };

// Live document-generation workflow run SSE events (run-ID-scoped stream).
type DocWorkflowSSEEvent =
  | { type: "workflow_run_progress"; message: string; step?: number; total?: number; nodeId?: string }
  | { type: "workflow_run_complete"; presentationId?: number | string }
  | { type: "workflow_run_error"; message: string };

const POLL_INTERVAL_MS = 4000;

// ── Step model ────────────────────────────────────────────────────────────────

// "scan" and "reports" are deliberately ONE step ("generating"): the customer
// watches the deep scan, then every document, then the SOW complete on a single
// continuous screen with a live checklist — never a separate per-phase wait
// screen to click through.
type StepKey = "consent" | "generating" | "review" | "sow" | "payment";

interface StepDef {
  key: StepKey;
  title: string;
  subtitle: string;
  icon: typeof Radar;
}

const STEPS: StepDef[] = [
  { key: "consent", title: "Consent granted", subtitle: "Access authorized", icon: ShieldCheck },
  { key: "generating", title: "Generating your assessment", subtitle: "Scan, reports & SOW", icon: Radar },
  { key: "review", title: "Review findings", subtitle: "Your results", icon: ScrollText },
  { key: "sow", title: "Statement of work", subtitle: "Tailor your scope", icon: FileSignature },
  { key: "payment", title: "Choose a plan", subtitle: "Sign & pay", icon: CreditCard },
];

type StepState = "complete" | "current" | "locked";

export function AssessmentWizard() {
  const { user, accessToken, fetchWithAuth } = useAuth();
  const customerId = user?.customerId ?? null;

  const [status, setStatus] = useState<AssessmentStatus | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [mfaJustEnrolled, setMfaJustEnrolled] = useState(false);
  const [selected, setSelected] = useState<number>(1); // default to the generating step
  const [scanProgress, setScanProgress] = useState<{ index: number; total: number; label: string } | null>(null);
  const [scanLog, setScanLog] = useState<{ checkKey: string; label: string; status: string }[]>([]);
  const [scanJustFinished, setScanJustFinished] = useState(false);
  const [docProgress, setDocProgress] = useState<{ message: string; step?: number; total?: number } | null>(null);

  const prevCurrentRef = useRef<number | null>(null);
  const provisionFiredRef = useRef(false);

  // ── Load status (polled) ───────────────────────────────────────────────────
  const loadStatus = useCallback(async () => {
    try {
      const res = await fetchWithAuth("/api/portal/assessment/status", undefined, { silent: true });
      if (res.ok) {
        const data = (await res.json()) as AssessmentStatus;
        // `documents.expected` was added to this endpoint alongside this wizard's
        // continuous-generation checklist (both landed together). api-server runs
        // as its own long-lived process here and isn't guaranteed to have already
        // restarted onto the code that added this field by the moment this bundle
        // is served — the wire response is a genuine external boundary, not
        // something the TS return type actually enforces at runtime. Normalize
        // once here (not scattered at each read site) so a response from an
        // older-but-still-live process degrades to "no expected documents known
        // yet" instead of throwing.
        if (data.documents && !Array.isArray(data.documents.expected)) {
          data.documents.expected = [];
        }
        // Same "older-but-still-live backend process" boundary as `expected`
        // above — `narrative` was added alongside this feature, so a response
        // from a not-yet-restarted process degrades to "nothing to show yet"
        // instead of throwing.
        if (!data.narrative || typeof data.narrative !== "object") {
          data.narrative = { status: "not_started", html: null, generatedAt: null };
        }
        // Same "older-but-still-live backend process" boundary as `expected` and
        // `narrative` above — `stats` was added alongside the richer stat-card
        // visual pass, so a response from a not-yet-restarted process degrades to
        // "no real stat data yet" (StatCards' existing `!= null` guards mean it
        // simply renders no cards) instead of throwing.
        if (!data.stats || typeof data.stats !== "object") {
          data.stats = { genuineFindings: null, licenseWasteMonthlyCents: null };
        }
        setStatus(data);
      }
    } catch {
      // best-effort; the next poll retries
    } finally {
      setLoaded(true);
    }
  }, [fetchWithAuth]);

  // ⚠️ TEMPORARY DEBUG CODE — DELETE BEFORE PRODUCTION ⚠️ (see file header note)
  const [debugTriggering, setDebugTriggering] = useState(false);
  const debugTriggerScan = useCallback(async () => {
    setDebugTriggering(true);
    try {
      await fetchWithAuth("/api/portal/assessment/debug-trigger-scan", { method: "POST" });
      await loadStatus();
    } finally {
      setDebugTriggering(false);
    }
  }, [fetchWithAuth, loadStatus]);

  useEffect(() => {
    void loadStatus();
    const t = setInterval(() => void loadStatus(), POLL_INTERVAL_MS);
    return () => clearInterval(t);
  }, [loadStatus]);

  // ── First-login provisioning trigger (fire once on mount) ──────────────────
  useEffect(() => {
    if (provisionFiredRef.current) return;
    provisionFiredRef.current = true;
    void fetchWithAuth("/api/portal/first-login/provision", { method: "POST" }, { silent: true }).catch(
      () => {
        /* provisioning is best-effort and idempotent server-side */
      },
    );
  }, [fetchWithAuth]);

  // ── Derived step completion ────────────────────────────────────────────────
  // A "failed" run is neither active nor a real completion — without this
  // exclusion it would render as "scan complete" with a hollow 0-of-0 result
  // and silently never unlock reports (which need real check data to generate
  // from), leaving the customer stuck with no honest explanation why.
  const scanFailed = Boolean(
    status?.scan.everScanned && !status.scan.active && status.scan.status === "failed",
  );
  const scanComplete = Boolean(
    status?.scan.everScanned && !status.scan.active && status.scan.status !== "failed",
  );
  const reportsComplete = Boolean(status?.documents.allReady);
  // The interactive SOW step unlocks once the consolidated SOW has finished
  // generating (it's the last document produced by the same generation run).
  const sowReady = Boolean(
    status?.documents.items.some(
      (d) => d.docType === "consolidated_sow" && (d.status === "approved" || d.status === "delivered"),
    ),
  );

  // Document generation failed if the workflow run terminated unsuccessfully or a
  // document row is marked failed. Poll-derived (reliable) — the SSE stream only
  // makes it feel instant. A failed run must never leave the wizard spinning.
  const reportsFailed =
    !reportsComplete &&
    ((status?.documents.failed ?? 0) > 0 ||
      status?.documents.workflowStatus === "failed" ||
      status?.documents.workflowStatus === "cancelled");

  // The first incomplete, unlocked step — the flow's "current" position. Scan
  // and document generation are one continuous "generating" step (index 1), so
  // there is no separate wait screen to auto-advance through between them —
  // only once everything (scan + every document + the SOW) is genuinely done
  // does the customer move on to review.
  const currentIndex = !reportsComplete ? 1 : 2;

  // Follow the flow forward when a milestone advances it, but leave the user on
  // whatever step they clicked to between milestones.
  useEffect(() => {
    if (prevCurrentRef.current !== currentIndex) {
      setSelected(currentIndex);
      prevCurrentRef.current = currentIndex;
    }
  }, [currentIndex]);

  // ── Live scan progress via the existing diagnostics SSE endpoint ───────────
  const scanActive = status?.scan.active ?? false;
  const scanRunId = status?.scan.runId ?? null;
  useEffect(() => {
    if (!scanActive || !scanRunId || customerId == null || !accessToken) return;
    const es = new EventSource(
      `/api/msp/customers/${customerId}/diagnostics/runs/${scanRunId}/sse?jwt=${encodeURIComponent(accessToken)}`,
    );
    setScanLog([]);
    setScanJustFinished(false);
    es.onmessage = (event) => {
      const parsed = JSON.parse(event.data) as DiagnosticsSSEEvent;
      if (parsed.type === "diagnostics_progress") {
        setScanProgress({ index: parsed.index, total: parsed.total, label: parsed.checkLabel });
        setScanLog((prev) => [...prev, { checkKey: parsed.checkKey, label: parsed.checkLabel, status: parsed.status }]);
      } else if (parsed.type === "diagnostics_complete") {
        es.close();
        setScanProgress(null);
        // The completion landing needs the poll's authoritative status before it
        // can render (real checksOk/checksTotal, real document state) — this flag
        // only bridges the ~800ms gap so the UI reads as "wrapping up" instead of
        // falling back to a stale "scan in progress" message right after finishing.
        setScanJustFinished(true);
        setTimeout(() => void loadStatus(), 800);
      } else if (parsed.type === "diagnostics_error") {
        es.close();
        setScanProgress(null);
        setTimeout(() => void loadStatus(), 800);
      }
    };
    es.onerror = () => es.close();
    return () => {
      es.close();
      setScanProgress(null);
    };
  }, [scanActive, scanRunId, customerId, accessToken, loadStatus]);

  // ── Live document-generation progress via the workflow run-ID SSE stream ────
  // Keyed on the workflow run ID (the only stable handle before the presentation
  // exists). Live progress only — completion/failure are authoritatively detected
  // by the status poll (workflowStatus / allReady / failed), so a dropped stream
  // never strands the wizard. Subscribes only while docs are still generating.
  const docWorkflowRunId = status?.documents.workflowRunId ?? null;
  const docGenActive = docWorkflowRunId != null && !reportsComplete && !reportsFailed;
  useEffect(() => {
    if (!docGenActive || docWorkflowRunId == null || !accessToken) return;
    const es = new EventSource(
      `/api/portal/assessment/doc-workflow/${docWorkflowRunId}/sse?jwt=${encodeURIComponent(accessToken)}`,
    );
    es.onmessage = (event) => {
      const parsed = JSON.parse(event.data) as DocWorkflowSSEEvent;
      if (parsed.type === "workflow_run_progress") {
        setDocProgress({ message: parsed.message, step: parsed.step, total: parsed.total });
      } else if (parsed.type === "workflow_run_complete") {
        es.close();
        setDocProgress(null);
        setTimeout(() => void loadStatus(), 600);
      } else if (parsed.type === "workflow_run_error") {
        es.close();
        setDocProgress(null);
        setTimeout(() => void loadStatus(), 600);
      }
    };
    es.onerror = () => es.close();
    return () => {
      es.close();
      setDocProgress(null);
    };
  }, [docGenActive, docWorkflowRunId, accessToken, loadStatus]);

  // ── Mandatory MFA gate ─────────────────────────────────────────────────────
  // Block the entire flow until the customer enrolls a portal-login second factor.
  if (!SKIP_MFA_GATE_FOR_TESTING && loaded && status && !status.mfa.enrolled && !mfaJustEnrolled) {
    return (
      <AssessmentMfaEnrollment
        onEnrolled={() => {
          setMfaJustEnrolled(true);
          void loadStatus();
        }}
      />
    );
  }

  if (!loaded && !status) {
    return (
      <div className="mx-auto w-full max-w-4xl px-6 py-10">
        <Skeleton className="h-72 w-full rounded-2xl" />
      </div>
    );
  }

  const stepState = (index: number): StepState => {
    if (index === 0) return "complete"; // consent
    // "generating" — one continuous step spanning scan + every document + SOW.
    if (index === 1) return reportsComplete ? "complete" : "current";
    if (index === 2) return reportsComplete ? "current" : "locked"; // review
    if (index === 3) return reportsComplete && sowReady ? "current" : "locked"; // sow
    // Payment unlocks alongside the SOW step — the customer settles their scope
    // there, then chooses a plan and signs here.
    if (index === 4) return reportsComplete && sowReady ? "current" : "locked"; // payment
    return "locked";
  };

  const isUnlocked = (index: number): boolean => stepState(index) !== "locked";

  return (
    <div className="mx-auto flex w-full max-w-5xl flex-col gap-6 px-4 py-8 md:flex-row md:px-6">
      {/* ── Locked, sequential step sidebar ── */}
      <nav className="md:w-64 md:shrink-0" aria-label="Assessment steps">
        <ol className="flex gap-2 overflow-x-auto pb-2 md:flex-col md:gap-1 md:overflow-visible md:pb-0">
          {STEPS.map((step, i) => {
            const state = stepState(i);
            const unlocked = state !== "locked";
            const active = i === selected;
            const Icon = step.icon;
            return (
              <li key={step.key} className="shrink-0 md:shrink">
                <button
                  type="button"
                  disabled={!unlocked}
                  onClick={() => unlocked && setSelected(i)}
                  aria-current={active ? "step" : undefined}
                  className={[
                    "flex w-full items-center gap-3 rounded-xl border px-3 py-2.5 text-left transition-colors",
                    active
                      ? "border-primary/40 bg-primary/5"
                      : "border-transparent hover:bg-muted/60",
                    !unlocked ? "cursor-not-allowed opacity-50" : "cursor-pointer",
                  ].join(" ")}
                >
                  <span
                    className={[
                      "flex size-8 shrink-0 items-center justify-center rounded-full",
                      state === "complete"
                        ? "bg-status-green/15 text-status-green"
                        : state === "current"
                          ? "bg-primary/15 text-primary"
                          : "bg-muted text-muted-foreground",
                    ].join(" ")}
                  >
                    {state === "complete" ? (
                      <CheckCircle2 className="size-4" />
                    ) : state === "locked" ? (
                      <Lock className="size-3.5" />
                    ) : (
                      <Icon className="size-4" />
                    )}
                  </span>
                  <span className="min-w-0">
                    <span className="block truncate text-sm font-medium text-foreground">
                      {step.title}
                    </span>
                    <span className="block truncate text-[11px] text-muted-foreground">
                      {step.subtitle}
                    </span>
                  </span>
                </button>
              </li>
            );
          })}
        </ol>
      </nav>

      {/* ── Step content panel ── */}
      <section className="min-w-0 flex-1">
        <StepPanel
          stepKey={STEPS[selected].key}
          status={status}
          scanProgress={scanProgress}
          scanLog={scanLog}
          scanJustFinished={scanJustFinished}
          docProgress={docProgress}
          scanComplete={scanComplete}
          scanFailed={scanFailed}
          reportsComplete={reportsComplete}
          reportsFailed={reportsFailed}
          sowReady={sowReady}
          fetchWithAuth={fetchWithAuth}
          onGoToReview={() => isUnlocked(2) && setSelected(2)}
          onGoToSow={() => isUnlocked(3) && setSelected(3)}
          onGoToPayment={() => isUnlocked(4) && setSelected(4)}
          debugTriggerScan={debugTriggerScan}
          debugTriggering={debugTriggering}
        />
      </section>
    </div>
  );
}

// ── Per-step content ───────────────────────────────────────────────────────────

function PanelShell({
  icon: Icon,
  tone = "primary",
  title,
  children,
}: {
  icon: typeof Radar;
  tone?: "primary" | "emerald" | "muted";
  title: string;
  children: React.ReactNode;
}) {
  const toneCls =
    tone === "emerald"
      ? "bg-status-green/10 text-status-green"
      : tone === "muted"
        ? "bg-muted text-muted-foreground"
        : "bg-primary/10 text-primary";
  return (
    <div className="rounded-2xl border border-border bg-card p-6 md:p-8">
      <div className="flex items-center gap-3">
        <div className={`flex size-11 items-center justify-center rounded-2xl ${toneCls}`}>
          <Icon className="size-5" />
        </div>
        <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      </div>
      <div className="mt-5">{children}</div>
    </div>
  );
}

// ── Generating-step shell ────────────────────────────────────────────────────
// A richer stage for the one screen a paying customer stares at the longest:
// the same card language as PanelShell, plus an ambient accent glow, an
// eyebrow line, and a larger title. Purely presentational — `tone` tracks the
// same derived states (in progress / complete / failed) the step already
// computes, it never derives anything of its own.
function GeneratingShell({
  icon: Icon,
  tone,
  eyebrow,
  title,
  children,
}: {
  icon: typeof Radar;
  tone: "progress" | "complete" | "failed";
  eyebrow: string;
  title: string;
  children: React.ReactNode;
}) {
  const chipCls =
    tone === "complete"
      ? "bg-status-green/15 text-status-green"
      : tone === "failed"
        ? "bg-status-red/15 text-status-red"
        : "bg-primary/15 text-primary";
  const orbCls =
    tone === "complete" ? "bg-status-green/10" : tone === "failed" ? "bg-status-red/10" : "bg-primary/10";
  return (
    <div className="relative overflow-hidden rounded-2xl border border-border bg-card p-6 md:p-8">
      <div
        aria-hidden
        className={`pointer-events-none absolute -right-24 -top-24 size-64 rounded-full blur-3xl ${orbCls}`}
      />
      <div className="relative flex items-center gap-4">
        <div className={`flex size-12 shrink-0 items-center justify-center rounded-2xl ${chipCls}`}>
          <Icon className="size-5" />
        </div>
        <div className="min-w-0">
          <p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-foreground/65">{eyebrow}</p>
          <h2 className="mt-0.5 text-xl font-semibold tracking-tight text-foreground md:text-2xl">{title}</h2>
        </div>
      </div>
      <div className="relative mt-6">{children}</div>
    </div>
  );
}

// ── Generation checklist item status ────────────────────────────────────────
// Real, not simulated: derived straight from the live scan/document state the
// wizard already polls + subscribes to via SSE.
type ChecklistStatus = "complete" | "active" | "failed" | "pending";

/** Resolve a real document row's live status for a given expected docType. */
function checklistDocStatus(docType: string, items: AssessmentDocument[]): ChecklistStatus {
  const row = items.find((d) => d.docType === docType);
  if (!row) return "pending";
  if (row.status === "approved" || row.status === "delivered") return "complete";
  if (row.status === "failed") return "failed";
  return "active"; // "generating" or any other in-flight status
}

// ── Path to remediation — connected phase timeline ──────────────────────────
// The generation journey as three connected phases — deep scan, report
// generation (each real expected document as a live chip), Statement of Work —
// with glow states, status badges, and a progress connector between phases.
// Purely a richer presentation of the same real statuses derived by
// checklistDocStatus; the underlying data and derivation are untouched.
function phaseStatusLabel(status: ChecklistStatus): string {
  switch (status) {
    case "complete":
      return "Complete";
    case "active":
      return "In Progress";
    case "failed":
      return "Failed";
    default:
      return "Planned";
  }
}

interface PhaseDocItem {
  key: string;
  label: string;
  status: ChecklistStatus;
}

interface PhaseItem {
  key: string;
  title: string;
  blurb: string;
  status: ChecklistStatus;
  icon: typeof Radar;
  /** Per-document live chips (report-generation phase only). */
  docs?: PhaseDocItem[];
  /** Optional live-progress slot rendered under the phase body (e.g. the doc workflow's SSE ticker). */
  live?: React.ReactNode;
}

function PhaseBadge({ status }: { status: ChecklistStatus }) {
  const toneCls =
    status === "complete"
      ? "border-status-green/30 bg-status-green/10 text-status-green"
      : status === "failed"
        ? "border-status-red/30 bg-status-red/10 text-status-red"
        : status === "active"
          ? "border-primary/30 bg-primary/10 text-primary"
          : "border-border bg-muted/40 text-muted-foreground";
  return (
    <span
      className={`inline-flex shrink-0 items-center gap-1.5 rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${toneCls}`}
    >
      {status === "active" && (
        <span aria-hidden className="relative flex size-1.5">
          <span className="absolute inline-flex size-full animate-ping rounded-full bg-primary opacity-75 motion-reduce:hidden" />
          <span className="relative inline-flex size-1.5 rounded-full bg-primary" />
        </span>
      )}
      {phaseStatusLabel(status)}
    </span>
  );
}

function PhaseNode({ status, icon: Icon }: { status: ChecklistStatus; icon: typeof Radar }) {
  if (status === "complete") {
    return (
      <span className="relative z-10 flex size-10 shrink-0 items-center justify-center rounded-full border border-status-green/30 bg-status-green/10 text-status-green">
        <CheckCircle2 className="size-4" />
      </span>
    );
  }
  if (status === "failed") {
    return (
      <span className="relative z-10 flex size-10 shrink-0 items-center justify-center rounded-full border border-status-red/30 bg-status-red/10 text-status-red">
        <XCircle className="size-4" />
      </span>
    );
  }
  if (status === "active") {
    return (
      <span className="relative z-10 flex size-10 shrink-0 items-center justify-center rounded-full border border-primary/40 bg-primary/10 text-primary shadow-[0_0_18px_-4px_hsl(var(--primary)/0.6)]">
        <span
          aria-hidden
          className="absolute inset-0 animate-ping rounded-full border border-primary/40 [animation-duration:2.6s] motion-reduce:hidden"
        />
        <Icon className="size-4" />
      </span>
    );
  }
  return (
    <span className="relative z-10 flex size-10 shrink-0 items-center justify-center rounded-full border border-border bg-muted/40 text-muted-foreground">
      <Icon className="size-4" />
    </span>
  );
}

/** Connector segment between two phases — colored by both endpoints so the
 *  line reads as progress flowing down the timeline. */
function connectorCls(from: ChecklistStatus, to: ChecklistStatus): string {
  if (from === "complete") {
    if (to === "complete") return "bg-status-green/40";
    if (to === "active") return "bg-gradient-to-b from-status-green/40 to-primary/40";
    if (to === "failed") return "bg-gradient-to-b from-status-green/40 to-status-red/40";
    return "bg-gradient-to-b from-status-green/40 to-border";
  }
  if (from === "active") return "bg-gradient-to-b from-primary/40 to-border";
  if (from === "failed") return "bg-gradient-to-b from-status-red/40 to-border";
  return "bg-border";
}

function DocChip({ label, status }: { label: string; status: ChecklistStatus }) {
  const toneCls =
    status === "complete"
      ? "border-status-green/25 bg-status-green/5 text-foreground"
      : status === "failed"
        ? "border-status-red/30 bg-status-red/5 text-foreground"
        : status === "active"
          ? "border-primary/30 bg-primary/5 text-foreground"
          : "border-border bg-muted/30 text-muted-foreground";
  return (
    <span className={`flex min-w-0 items-center gap-2 rounded-lg border px-2.5 py-1.5 transition-colors duration-500 ${toneCls}`}>
      {status === "complete" ? (
        <CheckCircle2 className="size-3.5 shrink-0 text-status-green" />
      ) : status === "failed" ? (
        <XCircle className="size-3.5 shrink-0 text-status-red" />
      ) : status === "active" ? (
        <Loader2 className="size-3.5 shrink-0 animate-spin text-primary" />
      ) : (
        <span aria-hidden className="flex size-3.5 shrink-0 items-center justify-center">
          <span className="size-1 rounded-full bg-current opacity-60" />
        </span>
      )}
      <span className="truncate text-xs">{label}</span>
      {/* The per-document status the old flat checklist showed as visible text —
          kept in the accessibility tree; sighted users read it from the icon. */}
      <span className="sr-only">{phaseStatusLabel(status)}</span>
    </span>
  );
}

function PhaseTimeline({ phases }: { phases: PhaseItem[] }) {
  return (
    <ol>
      {phases.map((phase, i) => (
        <li key={phase.key} className={`relative flex gap-4 ${i < phases.length - 1 ? "pb-7" : ""}`}>
          {i < phases.length - 1 && (
            <span
              aria-hidden
              className={`absolute bottom-0 left-5 top-10 w-px -translate-x-1/2 ${connectorCls(phase.status, phases[i + 1].status)}`}
            />
          )}
          <PhaseNode status={phase.status} icon={phase.icon} />
          <div className="min-w-0 flex-1 pt-0.5">
            <div className="flex flex-wrap items-center gap-x-2.5 gap-y-1">
              <p className={`text-sm font-semibold ${phase.status === "pending" ? "text-muted-foreground" : "text-foreground"}`}>
                {phase.title}
              </p>
              <PhaseBadge status={phase.status} />
            </div>
            <p className="mt-1 text-xs leading-relaxed text-muted-foreground">{phase.blurb}</p>
            {phase.docs && phase.docs.length > 0 && (
              <div className="mt-3 grid grid-cols-1 gap-1.5 sm:grid-cols-2">
                {phase.docs.map((d) => (
                  <DocChip key={d.key} label={d.label} status={d.status} />
                ))}
              </div>
            )}
            {phase.live && <div className="mt-3">{phase.live}</div>}
          </div>
        </li>
      ))}
    </ol>
  );
}

// ── Live-progress primitives ────────────────────────────────────────────────

/** The shared Progress bar with a shimmer sweep while work is in flight. */
function ShimmerProgress({ value }: { value: number }) {
  return (
    <div className="relative overflow-hidden rounded-full">
      <Progress value={value} className="h-1.5" />
      <span
        aria-hidden
        className="pointer-events-none absolute inset-y-0 left-0 w-1/3 animate-shimmer-sweep bg-gradient-to-r from-transparent via-primary/25 to-transparent motion-reduce:hidden dark:via-white/25"
      />
    </div>
  );
}

/** The live per-check feed from the diagnostics SSE stream, styled as a
 *  telemetry readout: mono type, entrance per row, pinned to the newest entry. */
function ScanLogFeed({ log }: { log: { checkKey: string; label: string; status: string }[] }) {
  const boxRef = useRef<HTMLDivElement>(null);
  // Keep the newest check in view as entries stream in — but only while the
  // user is already at (or near) the bottom. Never yank the scroll position
  // away from someone reading earlier entries; scrolls only this box, never
  // the page. The threshold absorbs the row(s) just appended, since this runs
  // after the DOM update.
  useEffect(() => {
    const el = boxRef.current;
    if (!el) return;
    const nearBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 64;
    if (nearBottom) el.scrollTop = el.scrollHeight;
  }, [log.length]);

  return (
    <div className="overflow-hidden rounded-xl border border-border bg-background/50">
      <div className="border-b border-border px-3 py-2">
        <p className="text-[10px] font-semibold uppercase tracking-wider text-foreground/65">Live check feed</p>
      </div>
      <div ref={boxRef} className="max-h-44 space-y-1 overflow-y-auto p-3">
        {log.map((entry, i) => (
          <div
            key={`${entry.checkKey}-${i}`}
            className="flex items-center gap-2 animate-in fade-in slide-in-from-bottom-1 duration-300 motion-reduce:animate-none"
          >
            {entry.status === "ok" ? (
              <CheckCircle2 className="size-3.5 shrink-0 text-status-green" />
            ) : (
              <XCircle className="size-3.5 shrink-0 text-status-red" />
            )}
            <span className="min-w-0 truncate font-mono text-[11px] text-muted-foreground">{entry.label}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Real stat cards ──────────────────────────────────────────────────────────
// Every number here traces to a real, already-computed source (this run's own
// persisted summary counts, or a live cost-engine query against real pricing
// data) — never a placeholder. A stat with no real data behind it (null) is
// simply omitted, not shown as zero or "—".
function StatCards({ stats }: { stats: AssessmentStatus["stats"] | null | undefined }) {
  // Defense-in-depth against the same "older-but-still-live backend process" /
  // deploy-skew boundary `loadStatus` already normalizes for (see its `stats`
  // guard above) — this component must never assume its caller's normalization
  // ran, so it degrades to "no real stat data yet" instead of throwing.
  if (!stats) return null;
  const cards: { label: string; value: string; icon: typeof Radar; iconCls: string }[] = [];
  if (stats.genuineFindings != null) {
    cards.push({
      label: stats.genuineFindings === 1 ? "Finding to review" : "Findings to review",
      value: String(stats.genuineFindings),
      icon: ListChecks,
      // Zero genuine findings is good news — let the icon say so.
      iconCls:
        stats.genuineFindings > 0
          ? "bg-status-amber/15 text-status-amber"
          : "bg-status-green/15 text-status-green",
    });
  }
  if (stats.licenseWasteMonthlyCents != null) {
    cards.push({
      label: "License waste, per month",
      value: `$${Math.round(stats.licenseWasteMonthlyCents / 100).toLocaleString()}`,
      icon: Coins,
      iconCls: "bg-status-violet/15 text-status-violet",
    });
  }
  if (cards.length === 0) return null;

  return (
    <div className="grid grid-cols-1 gap-3 min-[420px]:grid-cols-2 animate-in fade-in slide-in-from-bottom-2 duration-500 delay-100 fill-mode-backwards motion-reduce:animate-none">
      {cards.map((c) => {
        const CardIcon = c.icon;
        return (
          <div key={c.label} className="rounded-xl border border-border bg-background/50 p-4">
            <div className="flex items-start justify-between gap-2">
              <p className="min-w-0 break-words text-2xl font-semibold tabular-nums tracking-tight text-foreground">{c.value}</p>
              <span className={`flex size-7 shrink-0 items-center justify-center rounded-lg ${c.iconCls}`}>
                <CardIcon className="size-3.5" />
              </span>
            </div>
            <p className="mt-1.5 text-xs text-muted-foreground">{c.label}</p>
          </div>
        );
      })}
    </div>
  );
}

// ── Tenant health axes — real radar, real coverage only ─────────────────────
// The same "Package-Aware Pillar Rings" concept, built as a radar instead of
// individual rings: only pillars this customer's actual scanned package
// genuinely covers (traced server-side through monitoring_package_checks →
// signal_derivation_rules pillar weights — see pillar-coverage.ts) ever appear
// as an axis. A package with real coverage for only 3 of 7 pillars renders 3
// axes, never 7 with fabricated "perfect" scores on the rest. Nivo's own Radar
// renderer already refuses to render below 3 dimensions, but we hide the
// panel entirely rather than show a near-empty/broken-looking chart.
function PillarRadarPanel({ radar }: { radar: AssessmentStatus["radar"] }) {
  // This app's --border/--muted-foreground CSS vars hold raw HSL triples the
  // Nivo theme can't consume as colors, and light/dark want different resolved
  // values — so the chart's grid/tick/series colors are resolved here,
  // theme-aware, and passed to the shared renderer explicitly.
  const { theme } = useTheme();
  const isDark = theme === "dark";

  if (radar.pillars.length < 3) return null;

  const data: DistributionWidgetData = {
    shape: "distribution",
    label: "This tenant",
    slices: radar.pillars.map((p) => ({ name: p.label, value: p.score })),
  };

  return (
    <div className="rounded-2xl border border-border bg-background/50 p-5 animate-in fade-in zoom-in-95 duration-700 delay-200 fill-mode-backwards motion-reduce:animate-none">
      <p className="text-sm font-medium text-foreground">Tenant health axes</p>
      <p className="mt-1 text-xs text-muted-foreground">
        Real coverage from this scan's package — only pillars with real signal data are plotted.
      </p>
      <div className="mt-2 flex h-60 min-h-0">
        <RadarChart
          data={data}
          color={isDark ? "#479ef5" : "#1a7eef"}
          gridStroke={isDark ? "rgba(255,255,255,0.10)" : "rgba(0,0,0,0.10)"}
          tickFill={isDark ? "rgba(255,255,255,0.55)" : "rgba(0,0,0,0.55)"}
        />
      </div>
    </div>
  );
}

// ── CIO-Report Narrative ────────────────────────────────────────────────────
// The architect-voice narrative leads the "generating" step once the scan is
// done — real findings + real peer-benchmark data, written up by
// cio-narrative-generator.ts. The checklist below it becomes supporting
// evidence, not the main event. Renders nothing until a completed scan has
// actually started producing (or finished) a narrative.
function CioNarrativePanel({ narrative }: { narrative: AssessmentStatus["narrative"] }) {
  if (narrative.status === "not_started") return null;

  return (
    <div className="relative overflow-hidden rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/10 via-primary/[0.04] to-transparent p-5 animate-in fade-in slide-in-from-bottom-2 duration-500 motion-reduce:animate-none md:p-6">
      <span
        aria-hidden
        className="absolute inset-y-0 left-0 w-[3px] bg-gradient-to-b from-primary via-primary/40 to-transparent"
      />
      <div className="mb-4 flex items-center gap-2.5">
        <span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/15 text-primary">
          <Quote className="size-3.5" />
        </span>
        <div className="min-w-0">
          {/* Light primary (#1a7eef) is below AA at this size on the tinted
              panel — deepen the same hue in light mode only. */}
          <p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[hsl(212_87%_42%)] dark:text-primary">
            Architect's perspective
          </p>
          <p className="text-xs text-muted-foreground">From Shane McCaw, your M365 architect</p>
        </div>
      </div>
      {narrative.status === "ready" && narrative.html ? (
        <div
          className="prose prose-sm max-w-none text-foreground prose-headings:text-foreground prose-strong:text-foreground prose-p:text-muted-foreground prose-li:text-muted-foreground animate-in fade-in duration-500 motion-reduce:animate-none"
          dangerouslySetInnerHTML={{ __html: narrative.html }}
        />
      ) : narrative.status === "failed" ? (
        <p className="text-sm text-muted-foreground">
          We couldn't put together your narrative summary this time — your real findings and documents below are unaffected.
        </p>
      ) : (
        <div className="space-y-2.5">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Loader2 className="size-4 animate-spin text-primary" />
            Shane is reviewing your results and writing up what matters most…
          </div>
          <Skeleton className="h-3.5 w-full" />
          <Skeleton className="h-3.5 w-5/6" />
          <Skeleton className="h-3.5 w-4/6" />
        </div>
      )}
    </div>
  );
}

function StepPanel({
  stepKey,
  status,
  scanProgress,
  scanLog,
  scanJustFinished,
  docProgress,
  scanComplete,
  scanFailed,
  reportsComplete,
  reportsFailed,
  sowReady,
  fetchWithAuth,
  onGoToReview,
  onGoToSow,
  onGoToPayment,
  debugTriggerScan,
  debugTriggering,
}: {
  stepKey: StepKey;
  status: AssessmentStatus | null;
  scanProgress: { index: number; total: number; label: string } | null;
  scanLog: { checkKey: string; label: string; status: string }[];
  scanJustFinished: boolean;
  docProgress: { message: string; step?: number; total?: number } | null;
  scanComplete: boolean;
  scanFailed: boolean;
  reportsComplete: boolean;
  reportsFailed: boolean;
  sowReady: boolean;
  fetchWithAuth: ReturnType<typeof useAuth>["fetchWithAuth"];
  onGoToReview: () => void;
  onGoToSow: () => void;
  onGoToPayment: () => void;
  // ⚠️ TEMPORARY DEBUG CODE — DELETE BEFORE PRODUCTION ⚠️ (see file header note)
  debugTriggerScan: () => Promise<void>;
  debugTriggering: boolean;
}) {
  if (!status) return null;

  switch (stepKey) {
    case "consent":
      return (
        <PanelShell icon={ShieldCheck} tone="emerald" title="Consent granted">
          <p className="text-sm text-muted-foreground">
            Thanks — you authorized read access to your Microsoft&nbsp;365 tenant. That's
            everything we need to begin. Your deep scan runs next; you don't have to do
            anything else.
          </p>
        </PanelShell>
      );

    // One continuous screen for the entire generation phase — scan, then every
    // real document, then the SOW — with a live checklist. The customer never
    // clicks through a separate per-phase wait screen; this step only ever
    // hands off (auto-advances to "review") once genuinely everything is done.
    case "generating": {
      const anyFailed = scanFailed || reportsFailed;

      // The same real per-item statuses the flat checklist used, grouped for
      // presentation into three connected phases: deep scan → report generation
      // (one live chip per real expected document) → Statement of Work. The
      // underlying derivation (checklistDocStatus) is untouched — only how
      // those statuses are laid out changed.
      const docItems: PhaseDocItem[] = status.documents.expected.map((d) => ({
        key: `doc:${d.docType}`,
        label: d.title,
        status: !scanComplete ? ("pending" as ChecklistStatus) : checklistDocStatus(d.docType, status.documents.items),
      }));
      const scanPhaseStatus: ChecklistStatus = scanFailed ? "failed" : scanComplete ? "complete" : "active";
      // Phase-level rollup of those same per-document statuses (presentation
      // only), ordered so a contradiction can never render: a failed document
      // always wins over "complete" (the server's allReady deliberately
      // tolerates a failed row among ready ones, so "every ready" and "one
      // failed" can be true at once), and a run whose workflow died can't sit
      // "in progress" forever.
      const workflowDead =
        status.documents.workflowStatus === "failed" || status.documents.workflowStatus === "cancelled";
      const docsPhaseStatus: ChecklistStatus = !scanComplete
        ? "pending"
        : docItems.some((d) => d.status === "failed")
          ? "failed"
          : docItems.length > 0
            ? docItems.every((d) => d.status === "complete")
              ? "complete"
              : workflowDead
                ? "failed"
                : "active"
            : reportsComplete
              ? "complete"
              : workflowDead
                ? "failed"
                : "active";
      // The SOW phase reads its own real row status. A missing row is "failed"
      // only when the workflow genuinely died before producing it — never just
      // because some other document failed (reportsFailed can latch on a stale
      // failed row while the run is still alive and the SOW still on its way).
      // Once every report is done and the run is alive, the missing-row window
      // reads "active": the SOW is generated last, so that window is its turn.
      const sowDocStatus: ChecklistStatus = !scanComplete
        ? "pending"
        : checklistDocStatus("consolidated_sow", status.documents.items);
      const sowPhaseStatus: ChecklistStatus =
        sowDocStatus !== "pending"
          ? sowDocStatus
          : !scanComplete
            ? "pending"
            : workflowDead
              ? "failed"
              : docsPhaseStatus === "complete" && !reportsComplete
                ? "active"
                : "pending";

      // Live doc-generation ticker (the workflow SSE stream + poll fallback,
      // exactly the same message logic as before) — attached to whichever
      // phase is actually in progress, so it can never sit under a phase
      // badged "Complete" (in every successful run's final window the ticker's
      // "Generating 1 document…" is the SOW itself).
      const liveTicker =
        scanComplete && !anyFailed && !reportsComplete ? (
          <div className="space-y-2">
            <div className="flex items-start gap-2 font-mono text-[11px] text-muted-foreground">
              <Loader2 className="mt-px size-3.5 shrink-0 animate-spin text-primary" />
              <span className="min-w-0">
                {docProgress?.message
                  ? docProgress.message
                  : status.documents.generating > 0
                    ? `Generating ${status.documents.generating} document${status.documents.generating === 1 ? "" : "s"}…`
                    : "Preparing your documents…"}
              </span>
            </div>
            {docProgress?.total != null && docProgress.total > 0 && (
              <ShimmerProgress
                value={Math.min(100, Math.round(((docProgress.step ?? 0) / docProgress.total) * 100))}
              />
            )}
          </div>
        ) : null;

      const phases: PhaseItem[] = [
        {
          key: "scan",
          title: "Deep scan of your tenant",
          blurb: "Reading your tenant's real configuration, security posture, and licensing.",
          status: scanPhaseStatus,
          icon: Radar,
        },
        {
          key: "docs",
          title: "Report generation",
          blurb: "Each report is written from your scan's real findings.",
          status: docsPhaseStatus,
          icon: FileText,
          docs: docItems,
          live: docsPhaseStatus === "active" ? liveTicker : null,
        },
        {
          key: "sow",
          title: "Statement of Work",
          blurb: "Tailored to your results — you'll fine-tune the scope before anything is signed.",
          status: sowPhaseStatus,
          icon: FileSignature,
          live: docsPhaseStatus !== "active" && sowPhaseStatus === "active" ? liveTicker : null,
        },
      ];

      // Once reports finish, this step reads as "complete" (the customer may
      // have navigated back to it) — a settled recap instead of a live checklist.
      if (reportsComplete) {
        const readyCount = status.documents.ready;
        return (
          <GeneratingShell
            icon={FileText}
            tone="complete"
            eyebrow="Your Microsoft 365 assessment"
            title="Your assessment is ready"
          >
            {status.narrative.status === "ready" && status.narrative.html && (
              <div className="mb-5">
                <CioNarrativePanel narrative={status.narrative} />
              </div>
            )}
            <div className="mb-5 space-y-4">
              <StatCards stats={status.stats} />
              <PillarRadarPanel radar={status.radar} />
            </div>
            <p className="text-sm leading-relaxed text-muted-foreground">
              We've finished generating your assessment{" "}
              {readyCount > 0 ? (
                <>
                  — <span className="font-medium text-foreground">{readyCount} document{readyCount === 1 ? "" : "s"}</span>{" "}
                  including your tailored Statement of Work.
                </>
              ) : (
                "documents, including your tailored Statement of Work."
              )}{" "}
              Review the findings that matter most, then tailor your scope and choose a plan.
            </p>
            <div className="mt-6">
              <p className="mb-5 text-[10px] font-semibold uppercase tracking-[0.16em] text-foreground/65">
                Path to remediation
              </p>
              <PhaseTimeline phases={phases} />
            </div>
            <div className="mt-6 flex flex-wrap gap-3">
              <Button onClick={onGoToReview}>
                Review findings <ChevronRight className="ml-1 size-4" />
              </Button>
              {sowReady && (
                <Button variant="outline" onClick={onGoToSow}>
                  View statement of work
                </Button>
              )}
            </div>
          </GeneratingShell>
        );
      }

      const total = status.scan.checksTotal ?? 0;
      const ok = status.scan.checksOk ?? 0;
      const licenseGap = status.scan.checksLicenseGap ?? 0;
      const genuineError = status.scan.checksError ?? 0;
      const licenseGapFeatures = status.scan.licenseGapFeatures ?? [];
      // Score over checks we could actually evaluate. License gaps are
      // "unavailable" (the tenant lacks the add-on), NOT failures, so they don't
      // drag the passed-rate down — a tenant without Defender/Entra Premium
      // shouldn't read as "31% healthy" when everything checkable passed.
      const evaluable = ok + genuineError;
      const pct = evaluable > 0 ? Math.round((ok / evaluable) * 100) : total > 0 ? 100 : 0;
      const ringColor: ScoreRingColor = evaluable === 0 ? "blue" : pct >= 85 ? "green" : pct >= 60 ? "amber" : "red";
      // Honest one-line summary: what passed, what genuinely needs a look, and
      // what we simply couldn't check because the licensing isn't there (named).
      const scanSummary = (() => {
        const parts: string[] = [];
        if (ok > 0) parts.push(`${ok} check${ok === 1 ? "" : "s"} passed`);
        if (genuineError > 0) parts.push(`${genuineError} couldn't complete`);
        const lead = parts.length > 0 ? parts.join(" · ") : "Scan complete";
        const gap =
          licenseGap > 0
            ? ` ${licenseGap} check${licenseGap === 1 ? "" : "s"} couldn't run because your tenant doesn't have ${
                licenseGapFeatures.length > 0 ? licenseGapFeatures.join(" or ") : "certain Microsoft 365 add-ons"
              } — that's a licensing gap, not a security issue.`
            : "";
        return `${lead}. Now writing up your findings and Statement of Work.${gap}`;
      })();

      return (
        <GeneratingShell
          icon={anyFailed ? AlertTriangle : Radar}
          tone={anyFailed ? "failed" : "progress"}
          eyebrow="Your Microsoft 365 assessment"
          title={anyFailed ? "We hit a snag" : "Generating your assessment"}
        >
          {/* Honest failure — a failed scan or doc run is never silently hung or
              treated as success; the timeline below still shows exactly what did
              and didn't finish. */}
          {anyFailed ? (
            <>
              <p className="text-sm leading-relaxed text-muted-foreground">
                Something went wrong while {scanFailed ? "reading your Microsoft 365 environment" : "preparing your assessment documents"}, and we couldn't finish automatically. This is on us — nothing you did caused it{scanFailed ? "" : ", and your scan data is safe"}.
              </p>
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                Our team has been notified automatically and will get this sorted. This page keeps
                checking, so you can leave it open — it'll update the moment things are ready.
              </p>
            </>
          ) : scanComplete ? (
            // The narrative leads once the scan is done — it's the value-delivery
            // moment while documents are still generating, not a second wait
            // screen. The stat cards, radar, and scan-result ring stagger in
            // underneath it as supporting evidence, not the headline.
            <div className="space-y-4">
              <CioNarrativePanel narrative={status.narrative} />
              <StatCards stats={status.stats} />
              <PillarRadarPanel radar={status.radar} />
              <div className="flex items-center gap-4 rounded-xl border border-border bg-background/50 p-4 animate-in fade-in slide-in-from-bottom-2 duration-500 delay-300 fill-mode-backwards motion-reduce:animate-none">
                <ScoreRing value={pct} color={ringColor} size={56} strokeWidth={5} className="shrink-0" />
                <div className="min-w-0 space-y-0.5">
                  <p className="text-sm font-medium text-foreground">Your scan results</p>
                  <p className="text-xs leading-relaxed text-muted-foreground">
                    {total > 0 ? scanSummary : "Now writing up your findings and Statement of Work."}
                  </p>
                </div>
              </div>
            </div>
          ) : (
            // Scan still running — a quiet sonar motif carries the "actively
            // reading your tenant" feeling; the live bar + check feed below it
            // are the real telemetry.
            <div className="flex items-center gap-4">
              <div aria-hidden className="relative flex size-14 shrink-0 items-center justify-center">
                <span className="absolute inset-0 animate-ping rounded-full border border-primary/30 [animation-duration:2.8s] motion-reduce:hidden" />
                <span className="absolute inset-1.5 animate-ping rounded-full border border-primary/20 [animation-duration:2.8s] [animation-delay:0.9s] motion-reduce:hidden" />
                <span className="flex size-9 items-center justify-center rounded-full bg-primary/15 text-primary">
                  <Radar className="size-4.5" />
                </span>
              </div>
              <div className="min-w-0">
                <p className="text-sm font-medium text-foreground">
                  {scanJustFinished ? "Your scan just finished" : "Reading your Microsoft 365 environment"}
                </p>
                <p className="mt-0.5 text-xs leading-relaxed text-muted-foreground">
                  {scanJustFinished
                    ? "We're finalizing your results now."
                    : "Configuration and security posture first, then your findings and a tailored Statement of Work — all on this page."}
                </p>
              </div>
            </div>
          )}

          {/* ── Live scan progress — the bar + per-check telemetry feed ── */}
          {!anyFailed && !scanComplete && (
            <div className="mt-6 space-y-3">
              {scanProgress ? (
                <div className="space-y-2">
                  <div className="flex items-baseline justify-between gap-3">
                    <p className="min-w-0 truncate font-mono text-[11px] text-muted-foreground">
                      {scanProgress.label}
                    </p>
                    <p className="shrink-0 font-mono text-[11px] font-medium tabular-nums text-foreground">
                      {scanProgress.index}/{scanProgress.total}
                    </p>
                  </div>
                  <ShimmerProgress
                    value={scanProgress.total > 0 ? Math.round((scanProgress.index / scanProgress.total) * 100) : 0}
                  />
                </div>
              ) : (
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Loader2 className="size-4 animate-spin" />
                  {scanJustFinished
                    ? "Finalizing…"
                    : status.scan.everScanned
                      ? "Scan in progress…"
                      : "Starting your scan…"}
                </div>
              )}
              {scanLog.length > 0 && <ScanLogFeed log={scanLog} />}
            </div>
          )}

          {/* ── Path to remediation — the same real items and statuses, as a
              connected phase timeline. During document generation the reports
              phase carries the live chips + workflow ticker, so the timeline
              doubles as the live progress display. ── */}
          <div className="mt-7">
            <p className="mb-5 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">
              Path to remediation
            </p>
            <PhaseTimeline phases={phases} />
          </div>

          {/* ⚠️ TEMPORARY DEBUG CODE — DELETE BEFORE PRODUCTION ⚠️ testbed-only trigger button, see file header note */}
          {status.isTestbed && !status.scan.active ? (
            <Button
              className="mt-5"
              variant="outline"
              onClick={() => void debugTriggerScan()}
              disabled={debugTriggering}
            >
              {debugTriggering ? <Loader2 className="mr-1 size-4 animate-spin" /> : null}
              [DEBUG] {status.scan.everScanned ? "Re-trigger scan" : "Trigger scan"}
            </Button>
          ) : null}
        </GeneratingShell>
      );
    }

    case "review": {
      if (!reportsComplete) {
        return (
          <PanelShell icon={ScrollText} tone="muted" title="Review findings">
            <p className="text-sm text-muted-foreground">
              This unlocks once your reports have finished generating.
            </p>
          </PanelShell>
        );
      }
      // The SOW is surfaced interactively in its own dedicated step below — keep it
      // out of the read-only findings viewer so it isn't shown twice.
      const findingsDocs = status.documents.items.filter((d) => d.docType !== "consolidated_sow");
      return (
        <PanelShell icon={ScrollText} tone="emerald" title="Review findings">
          <p className="text-sm text-muted-foreground">
            Your reports are ready. Each opens with the findings that matter most, followed
            by the full report.
          </p>
          <div className="mt-5">
            <AssessmentDocumentViewer documents={findingsDocs} fetchWithAuth={fetchWithAuth} />
          </div>
          {sowReady && (
            <Button className="mt-6" onClick={onGoToSow}>
              Continue to your statement of work <ChevronRight className="ml-1 size-4" />
            </Button>
          )}
        </PanelShell>
      );
    }

    case "sow": {
      if (!(reportsComplete && sowReady)) {
        return (
          <PanelShell icon={FileSignature} tone="muted" title="Statement of work">
            <p className="text-sm text-muted-foreground">
              Once your reports finish generating, you'll see a tailored statement of work
              here — with the flexibility to adjust its scope before you proceed.
            </p>
          </PanelShell>
        );
      }
      return (
        <PanelShell icon={FileSignature} tone="primary" title="Your statement of work">
          <p className="text-sm text-muted-foreground">
            Here's the plan we recommend, tailored to what we found. Fine-tune the scope to fit
            your priorities — the price updates as you go.
          </p>
          <div className="mt-5">
            <AssessmentSowSelector fetchWithAuth={fetchWithAuth} />
          </div>
          <a
            href="/assessment/compare"
            className="mt-3 inline-block text-xs font-medium text-primary underline-offset-2 hover:underline"
          >
            Compare this scope with a previous version
          </a>
          <Button className="mt-6" onClick={onGoToPayment}>
            Continue to choose a plan <ChevronRight className="ml-1 size-4" />
          </Button>
        </PanelShell>
      );
    }

    case "payment": {
      if (!(reportsComplete && sowReady)) {
        return (
          <PanelShell icon={CreditCard} tone="muted" title="Choose a plan">
            <p className="text-sm text-muted-foreground">
              Once your statement of work is ready, you'll choose how to pay — in full or phase by
              phase — and sign here.
            </p>
          </PanelShell>
        );
      }
      return (
        <PanelShell icon={CreditCard} tone="primary" title="Choose a plan">
          <p className="text-sm text-muted-foreground">
            You've settled your scope — now choose how you'd like to proceed and sign to confirm.
          </p>
          <div className="mt-5">
            <AssessmentPaymentPlan fetchWithAuth={fetchWithAuth} />
          </div>
        </PanelShell>
      );
    }

    default:
      return null;
  }
}
